[HTTP 서버 구현하기 - 1단계] 제리(박재성) 미션 제출합니다.
woowacourse/jwp-dashboard-http pull request #10
Opened 2021-08-28 02:51 UTC by jaeseongDev

안녕하세요 영이~! 제리입니다🐭🐭
리팩토링을 안정적으로 하기 위해 테스트 코드를 같이 작성하면서 기능을 구현하려고 했어요! 
기능은 1단계까지 수행한 상태입니다:)

크루들끼리는 또 코드 리뷰가 처음이라 어떻게 코드 리뷰를 받고 성장할 수 있을 지 궁금하네요~~~
시간 편하실 때 리뷰 부탁드려요😄😄

2021-08-29 08:17 UTC, choijy1705 commented on app/src/main/java/nextstep/jwp/http/HttpRequestStreamReader.java
> +            .split(": ");
두번에 걸쳐 진행하였는데 한번에 진행할 수 있을 것 같아요.

2021-08-29 09:16 UTC, choijy1705 requested changes
안녕하세요 제리.
미션 잘 구현하셨네요. 모의면접도 있었는데 미션 진행하느라 고생하셨습니다👍
리뷰 남긴 것 중에 이해가 안되거나 다른 의견이 있으면 언제든지 DM주세요.

2021-08-29 09:16 UTC, choijy1705 commented on app/src/main/java/nextstep/jwp/controller/RegisterController.java
> +    }
get, post요청시 둘다 response를 생성하고 있는데 requestHandler에서 response를 생성하여 파라미터로 넘겨주고 get, post 에서는 response를 반환하지 않고 처리하는 방법은 어떤가요?

2021-08-30 08:16 UTC, jaeseongDev commented on app/src/main/java/nextstep/jwp/http/HttpRequestStreamReader.java
> +            .split(": ");
오오! 한 번에 진행할 수 있도록 고칠게요~!😄

2021-08-30 08:25 UTC, jaeseongDev commented on app/src/main/java/nextstep/jwp/controller/FrontControllerServlet.java
> +    }
enum을 활용해서 if문을 없애볼게요~!! 좋은 피드백 감사합니다🙏

2021-08-30 09:01 UTC, jaeseongDev commented on app/src/main/java/nextstep/jwp/controller/FrontControllerServlet.java
> +    }
enum을 활용해서 수정했습니다~!

2021-08-30 09:03 UTC, jaeseongDev commented on app/src/main/java/nextstep/jwp/http/StaticFileReader.java
> +        return read(fileName);
`read(String fileName)`은 `read(HttpRequest httpRequest)`와 달리 경로를 파라미터로 받지 않고, fileName을 파라미터로 입력받아서 사용하기 위해 만들어놓은 메서드 용도로 만들어놨어요~! 그래서 `String filePath = "static/" + fileName;` 형태로 코드를 작성했었어요!

2021-08-30 09:05 UTC, jaeseongDev commented on app/src/main/java/nextstep/jwp/controller/LoginController.java
> +        return new HttpResponse(HttpStatus.BAD_REQUEST);
아하! 값이 없는 경우와 있는 경우를 다시 분리해서 indent를 줄여서 다시 수정했습니다~~

2021-08-30 09:07 UTC, jaeseongDev commented on app/src/main/java/nextstep/jwp/controller/NoController.java
> +    }
정적 폴더인 resources/static 폴더를 의미하기 위해서 static을 쓴건데, 메서드에 붙여서 사용하는 static과 혼동을 준 것 같네요😭😭
혼동 없게 클래스 이름을 다른 이름으로 수정해볼게요~!!

2021-08-30 09:09 UTC, jaeseongDev commented on app/src/main/java/nextstep/jwp/http/HttpRequest.java
> +    private static final String KEY_AND_VALUE_DELIMITER = "=";
제가 너무 문자로 하드코딩 된 것에 대해서는 전부 상수로 치환해야 된다는 원칙에 잘못 사로 잡혀있었던 것 같애요! 
영이 말대로 특수만자는 그대로 바로 사용하는 것이 훨씬 가독서에 좋다고 느껴지네요~!

2021-08-30 09:11 UTC, jaeseongDev commented on app/src/main/java/nextstep/jwp/http/HttpRequest.java
> +                String value = splitParam[1];
하드코딩 된 부분 상수로 치환했어요~!~!

2021-08-30 09:50 UTC, jaeseongDev commented on app/src/main/java/nextstep/jwp/controller/RegisterController.java
> +    }
requestHandler에서 response를 생성해서 파라미터로 넘겨주는 방식으로 리팩토링 해봤습니다!
Spring을 까봐도 이런 형태로 구성이 되어 있는데, 이런 형태로 구성하려면 setter를 써야 한다는 단점이 있는 것 같네요ㅠㅠ
setter를 쓰면서까지도 이런 형태의 구조로 가져가면 어떤 점이 좋은걸까요 ?

2021-08-30 15:17 UTC, choijy1705 commented on app/src/main/java/nextstep/jwp/http/RequestHandler.java
> +    }
getHttpResponse라는 메소드 명이 어색한거 같아요. 그리고 viewResolver랑 컨트롤러를 진행하는 로직이 서로 연관이 없는것 같아요

2021-08-30 15:17 UTC, choijy1705 commented on app/src/main/java/nextstep/jwp/controller/RegisterController.java
> +    }
흠 저도 이부분을 고민해봐야겠네요 기존의 스프링에서 이렇게 넘겨주는 것이 좋다고 생각해서 그렇게 말씀드렸는데 고민을 좀 해보겠습니다.

2021-08-30 15:32 UTC, choijy1705 commented on app/src/main/java/nextstep/jwp/controller/AbstractController.java
> +        }
request 내에서 method를 확인하는 로직을 처리하는 건 어떤가요? `reqeust.isGet()` 이런식으로요

2021-08-30 15:36 UTC, choijy1705 approved these changes
안녕하세요 제리.
리뷰 반영 확인했습니다.
간단한 피드백 남겼습니다. 2,3단계 진행하면서 같이 고민해보면 좋을 것 같습니다.
1단계는 이만 머지하겠습니다.

2021-08-30 15:36 UTC, merged