[톰캣 구현하기 - 1단계] 포키(권예진) 미션 제출합니다.
woowacourse/jwp-dashboard-http pull request #113
Opened 2022-09-01 11:07 UTC by YJGwon

안녕하세요 제로! 포키입니다. 1단계 미션에서는 클래스 분리 등의 리팩토링은 거의 하지 않고 구현해서 코드가 많이 더럽네요;;
가차없이 리뷰 주시면 열심히 반영해볼게요! 💦

2022-09-01 11:41 UTC, YJGwon commented
Test 추가 해두긴 했는데,  Class 분리 거의 없이 private method로 대부분의 기능을 구현했더니 test가 많이 없네요... DM으로 말씀드렸듯 제가 지금 2단계 구현 중이던 와중에 1단계까지만 branch를 분리해서 PR요청을 보낸거라 지금 코드에서 refactoring을 많이 진행하기 보다는 의견 주시면 다음 단계에서 반영해도 될까요 ㅠㅠ

2022-09-02 05:04 UTC, kang-hyungu requested changes
포키 몇 가지 피드백 남겼어요
수정해보시고 리뷰 재요청주세요.

2022-09-02 05:04 UTC, kang-hyungu commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +            final Map<String, String> header = parseHeader(reader);
header를 일급 컬렉션으로 만들면 어떨까요?

2022-09-02 05:04 UTC, kang-hyungu commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +                .getOrDefault("Accept", "text/html")
문자열을 enum으로 관리해보시기 바랍니다.

2022-09-02 05:04 UTC, kang-hyungu commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +            return new Response(ContentType.HTML, StatusCode.OK, "Hello world!");
HTML, OK를 매번 클라이언트가 결정해줘야하는 불편함이 있네요.
정적 팩터리 메서드를 만들어서 response body만 전달 받도록 만들면 클라이언트가 좀더 사용하기 쉬운 코드가 나올거에요.

2022-09-02 05:04 UTC, kang-hyungu commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +                    if (user.checkPassword(password)) {
filter를 추가하고 ifPresent는 로그만 찍으면 좀더 깔끔하지 않을까요

2022-09-02 05:04 UTC, kang-hyungu commented on tomcat/src/main/java/org/apache/coyote/response/Response.java
> +        this.headers.put("Content-Type", contentType.toString());
문자열을 enum으로 관리하면 어떨까요

2022-09-03 09:57 UTC, asebn1 requested changes
포키, 안녕하세요! 제로입니다. 😄 
코드를 보고 몇 가지 피드백을 남겨봤습니다!!
제 개인적인 코드 스타일과 의견들이 들어간 피드백이기 때문에 편히 보시고
납득이 가는 피드백들이 있다면 수정 후 리뷰 재 요청 부탁드립니다 :)
수고하셨습니다!

2022-09-03 09:57 UTC, asebn1 commented on README.md
> +    - [X] account와 password를 확인하여 유저 정보를 조회한 후 콘솔에 로깅한다.
체크리스트를 꼼꼼히 잘 짜셨네요 👍 👍

2022-09-03 09:57 UTC, asebn1 commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +        }
```suggestion
        while (!"".equals(line)) {
            final String[] splitLine = line.split(": ", 2);
            header.put(splitLine[KEY], splitLine[VALUE]);
            line = reader.readLine();
        }
```

상수로 만들어두면 코드를 이해하기 쉬울 것 같아요!

2022-09-03 09:57 UTC, asebn1 commented on tomcat/src/main/java/org/apache/coyote/header/ContentType.java
> +    }
```suggestion
                .orElse(HTML);
    }

    @Override
    public String toString() {
        return this.value;
    }
```

공백이 두 개 있네요!

2022-09-03 09:57 UTC, asebn1 commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
변수를 생성할 때 어떤 것은 var, 어떤 것은 명시를 해주는데 기준이 무엇인가요?
통일하면 좋을 것 같아요.

2022-09-03 09:57 UTC, asebn1 commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +            final String response = getResponse(requestUri, header).toText();
Objects.requireNonNull를 사용해볼 수도 있을 것 같아요. 개인적인 의견입니다!

2022-09-03 09:57 UTC, asebn1 commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +    }
? & = 키워드도 상수화할 수도 있을 것 같아요.
```
 param -> param[0],
param -> param[1]
```
이 부분은 
```
 param -> param[KEY],
param -> param[VALUE]
```
가 이해하기 편할 것 같아요!

2022-09-03 09:57 UTC, asebn1 commented on tomcat/src/test/java/nextstep/org/apache/coyote/http11/Http11ProcessorTest.java
> +    }
테스트도 구현해 주셨네요! 👍 👍

2022-09-03 09:57 UTC, asebn1 commented on tomcat/src/main/java/org/apache/coyote/header/ContentType.java
> +
궁금해서 질문 드립니다!
제가 미션할 때 js, ico 파일들도 같이 읽어와서 필요했는데 (없으면 화면이 이상하게 출력되더라구요)
포키처럼 기본 값을 HTML로 반환해주면 js, ico에 대해서도 정상동작하는 걸까요?
저는 enum에 JS, ICO 정보도 추가해서 진행했어요!

2022-09-03 10:19 UTC, asebn1 commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +
저도 아직 해결못한 부분인데, login이라는 서비스 로직이 웹 구동(Http11Processor)에 들어가는 것이 좋지 않은 것 같아요.
현재 회원 로직이 존재하지만 여러기능이 추가될 때마다 Http11Processor 클래스에 계속 추가할 수 없다고 생각하기에 책임을 분리하는 것이 좋다고 생각합니다.
다음 미션 때 기회가 된다면 해결하는 것도 좋은 시도라고 생각됩니다..! 👍

2022-09-04 11:28 UTC, YJGwon commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
기준이 있다기보다 기존에 var로 선언된 것을 수정하지 않았었는데, 리팩토링하면서 제 원래 코드 스타일 대로 var 키워드를 사용하지 않고 type을 명시해주었습니다!

2022-09-04 11:34 UTC, YJGwon commented on tomcat/src/main/java/org/apache/coyote/header/ContentType.java
> +
js는 괜찮았는데, ico 같은 경우에는 resource directory내에 `favicon.ico` 파일이 없어서 예외처리만 해주고 응답이 나가지 않아서 신경쓰지 못했네요..! `404.html`에서 svg파일을 읽지 못하는 것을 보고 저도 JS, ICO, SVG를 추가해주었습니다.

2022-09-04 12:10 UTC, YJGwon commented
안녕하세요 제로!! DM으로 말씀드렸던 것과 같이 2단계 첫번째 요구사항 구현 코드(로그인 성공 후 302 응답)를 포함하여 리팩토링 진행 후 다시 리뷰요청 드립니다! 2단계 구현은 다음 PR에서 리뷰해주셔도 괜찮을 것 같아요 😅 코드가 좀 많이 바뀌게 되었는데, 보기 힘드시거나 궁금하신 부분은 DM 또는 리뷰로 편하게 말씀해주세요!!

2022-09-05 05:19 UTC, asebn1 approved these changes
포키 고생하셨습니다! 
다음미션도 화이팅! 👍 👍

2022-09-05 05:19 UTC, merged