[톰캣 구현하기 - 1단계] 레오(남궁현) 미션 제출합니다.
woowacourse/jwp-dashboard-http pull request #121
Opened 2022-09-01 15:23 UTC by DWL21

디우 안녕하세요. 오랜만에 미션이라 재미있었습니다. ㅎㅎ
1단계 기능 구현을 완료하였습니다.
리팩터링과 예외 처리 관련하여 자유롭게 의견 주셔도 됩니다!

구현한 기능 목록
- [x] GET /index.html 응답하기
- [x] CSS 지원하기
- [x] Query String 파싱

2022-09-02 08:21 UTC, tco0427 requested changes
안녕하세요 레오!! 디우입니다😃

레오 코드를 보면서 QueryParam 같은 부분들은 제 미션에서도 적용해보면 좋겠다는 생각이 들었어요!!
404 예외처리등 저는 고려하지 못한 부분에 대해서도 꼼꼼하게 진행해주신 것 같아요!!

최대한 디테일하게 보면서 실수하신 것 같은 부분들 위주로 몇가지 코멘트 남겨보았습니다!!😃

2022-09-02 08:21 UTC, tco0427 commented on tomcat/src/main/java/nextstep/jwp/http/HttpRequest.java
> +        final int URI_INDEX = 1;
상수로 빼주시면 좋을 것 같습니다!!

2022-09-02 08:21 UTC, tco0427 commented on tomcat/src/main/java/nextstep/jwp/http/HttpRequest.java
> +        List<String> request = of(requestLine.split(REQUEST_LINE_SEPARATOR));
이런 경우에는 저는 static import 하는 것이 아닌 `List.of()` 와 같이 명시적으로 표현해주는 것이 보다 가독성 있다고 생각하는데요 (처음 코드를 보는 사람은 무엇의 of 인지 모르므로) 레오는 어떻게 생각하시나요??ㅇㅅㅇ

2022-09-02 08:21 UTC, tco0427 commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +    private String handler(HttpRequest httpRequest) throws IOException {
엇..!! 메소드명이 `명사` 네요!!

2022-09-02 08:21 UTC, tco0427 commented on tomcat/src/test/java/nextstep/jwp/http/ContentTypeTest.java
> +class ContentTypeTest {
저희 요구사항 중 하나인 `CSS 지원하기` 에 대한 직접적인 테스트는 없는 것 같네요..ㅠ.ㅠ
ContentTypeTest 에서 혹은 전체적인 흐름에 대해서 테스트하겠다고 하면 Http11ProcessorTest 에서 테스트해주면 어떨까요??ㅇㅅㅇ

2022-09-03 03:51 UTC, DWL21 commented on tomcat/src/test/java/study/FileTest.java
>          assertThat(actual).containsOnly("nextstep");
uri 대신 url 클래스를 사용하면 URISyntaxException을 던지지 않아도 되는 차이점이 있네요..! 감사합니다

2022-09-03 04:06 UTC, DWL21 commented on tomcat/src/test/java/nextstep/jwp/utils/FileUtilsTest.java
> +    void extractFileExtension_success_default() {
FileUtils의 확장자 반환하는 유틸은 파일을 불러올때는 `localhost:8080/` 로 요청해도 사용하지 않고 있어요.

2022-09-03 04:07 UTC, DWL21 commented on tomcat/src/test/java/nextstep/jwp/utils/FileUtilsTest.java
> +    void extractFileExtension_success_default() {
<img width="1433" alt="스크린샷 2022-09-03 13 03 50" src="https://user-images.githubusercontent.com/76774809/188255191-833bd01f-71c6-4c7e-9880-3de6bf2fa0e9.png">

response headers에 text/html이 있지만 /index 경로는 /index.html로 변환하는 것을 말씀하신건가요??

2022-09-03 04:09 UTC, DWL21 commented on tomcat/src/main/java/nextstep/jwp/handler/LoginHandler.java
> +
좋습니다!

2022-09-03 04:10 UTC, DWL21 commented on tomcat/src/test/java/study/FileTest.java
>          assertThat(actual).containsOnly("nextstep");
[67a4e14](https://github.com/woowacourse/jwp-dashboard-http/pull/121/commits/67a4e14447fa687c00c0a954bb538d5580952981)

2022-09-03 04:12 UTC, DWL21 commented on tomcat/src/main/java/nextstep/jwp/handler/LoginHandler.java
> +
[70c96b2](https://github.com/woowacourse/jwp-dashboard-http/pull/121/commits/70c96b28d2d06ac61daf3abefcd0840345c0056a)

2022-09-03 04:15 UTC, DWL21 commented on tomcat/src/test/java/nextstep/jwp/http/HttpRequestTest.java
> +public class HttpRequestTest {
평소에 클래스에서 인텔리제이의 테스트 만들기 기능을 주로 사용해서 직접 만들 때 신경을 안쓰고 있었네요.ㅎㅎ 알려주셔서 고맙습니다.

2022-09-03 04:16 UTC, DWL21 commented on tomcat/src/test/java/nextstep/jwp/http/HttpRequestTest.java
> +public class HttpRequestTest {
[34f7196](https://github.com/woowacourse/jwp-dashboard-http/pull/121/commits/34f7196e1332aa323edce45d87839b6b9d2a9680)

2022-09-03 04:18 UTC, DWL21 commented on tomcat/src/main/java/nextstep/jwp/http/HttpRequest.java
> +    }
다음단계에서 사용할 것 같아 다 만들어 놓았네요. 당장 사용하지 않으니 지우겠습니다.

2022-09-03 04:19 UTC, DWL21 commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +    private String handler(HttpRequest httpRequest) throws IOException {
commit 전에 컨벤션을 확인한다^^

2022-09-03 04:21 UTC, DWL21 commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +        return FileUtils.readFile(getResource(path));
핸들러 내부 메서드에 bufferedReader.readLine() 이 있었어서 추가했는데 리팩터링 하면서 없어진 걸 놓쳤네요. 원래 회색으로 사용하지 않는다고 뜨는 걸로 알고 있는데 뜨지 않네요?

2022-09-03 04:24 UTC, DWL21 commented on tomcat/src/main/java/nextstep/jwp/utils/FileUtils.java
> +        String EMPTY_FILE = "";
[refactor: 빈 파일 상수 처리](https://github.com/woowacourse/jwp-dashboard-http/pull/121/commits/cdcd1ed90a122f853a3fdd30ffb803805e7c5dca)
상수 처리 하겠습니다!

2022-09-03 04:24 UTC, DWL21 commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +        }
넵 추가하겠습니다.

2022-09-03 04:32 UTC, DWL21 commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +        String line;
gc가 작동할 것이라 생각해 close를 하지 않았네요. 디우 말대로 try-with-rosources 사용하는게 좋을 듯 합니다.

2022-09-03 04:34 UTC, DWL21 commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +        String line;
[refactor: 자원 관리, 불 필요 예외 처리 제거](https://github.com/woowacourse/jwp-dashboard-http/pull/121/commits/b8a3244b1bb3f080bcd4bda705cca2cc22ad2d72)

2022-09-03 04:37 UTC, DWL21 commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +        final int REQUEST_LINE_INDEX = 0;
해당 경우 메서드 내에서 한번만 사용되는 인덱스는 다시 사용될 일이 없어 클래스 맨 위의 상수처리 대신 위와 같이 메서드 내 설명으로 충분하다 생각했어요.

2022-09-03 04:42 UTC, DWL21 commented on tomcat/src/main/java/nextstep/jwp/http/HttpRequest.java
> +        final int URI_INDEX = 1;
[refactor: 리스트 인덱스 상수처리](https://github.com/woowacourse/jwp-dashboard-http/pull/121/commits/c8813d77e60daca3dfe148c3862f3a354a74a832)
넵 상수 처리 하겠습니다.

2022-09-03 04:45 UTC, DWL21 commented on tomcat/src/main/java/nextstep/jwp/http/HttpRequest.java
> +        List<String> request = of(requestLine.split(REQUEST_LINE_SEPARATOR));
저도 of의 경우 명시하는게 좋다고 생각합니다. 의도하지 않았는데 바뀌어있네요? 감사합니다!

2022-09-03 04:49 UTC, DWL21 commented on tomcat/src/test/java/nextstep/jwp/http/ContentTypeTest.java
> +class ContentTypeTest {
Http11ProcessorTest에서 테스트 하는게 좋을 것 같습니다!

2022-09-03 04:50 UTC, DWL21 commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +        return FileUtils.readFile(getResource(path));
[refactor: 자원 관리, 불 필요 예외 처리 제거](https://github.com/woowacourse/jwp-dashboard-http/pull/121/commits/b8a3244b1bb3f080bcd4bda705cca2cc22ad2d72)
변경했습니다! 감사합니다.

2022-09-03 04:52 UTC, DWL21 commented
안녕하세요. 디우 양질의 리뷰 주셔서 정말 고맙습니다! 테스트 관련 코멘트도 반영하여 다시 리뷰요청 드리겠습니다.
(https://github.com/woowacourse/jwp-dashboard-http/pull/121#discussion_r961401476)
(https://github.com/woowacourse/jwp-dashboard-http/pull/121#discussion_r961378573)

2022-09-04 04:20 UTC, DWL21 commented on tomcat/src/test/java/nextstep/jwp/http/ContentTypeTest.java
> +class ContentTypeTest {
[test: QueryParams 클래스 contains 메서드 성공 테스트 작성](https://github.com/woowacourse/jwp-dashboard-http/pull/121/commits/2a3842f27c0866447f928cf43e83588269b602f1)

2022-09-04 04:20 UTC, DWL21 commented on tomcat/src/test/java/nextstep/jwp/handler/LoginHandlerTest.java
> +        Assertions.assertDoesNotThrow(() -> LoginHandler.login(queryParams));
[test: 로그인 성공시 회원 정보에 대한 로그 출력 테스트 작성](https://github.com/woowacourse/jwp-dashboard-http/pull/121/commits/69c611ea6ac0b11f6211840c5733ec3ee4c550bc)

2022-09-04 04:21 UTC, DWL21 commented
[test: QueryParams 클래스 contains 메서드 성공 테스트 작성](https://github.com/woowacourse/jwp-dashboard-http/pull/121/commits/2a3842f27c0866447f928cf43e83588269b602f1)
[test: 로그인 성공시 회원 정보에 대한 로그 출력 테스트 작성](https://github.com/woowacourse/jwp-dashboard-http/pull/121/commits/69c611ea6ac0b11f6211840c5733ec3ee4c550bc)

테스트 코드 수정도 완료하였습니다!

2022-09-04 09:45 UTC, tco0427 commented on tomcat/src/test/java/nextstep/jwp/utils/FileUtilsTest.java
> +    void extractFileExtension_success_default() {
넵!! 테스트만 봤을 때 `abc` 로 오면 기본 파일 확장자로 `abc.html` 을 반환해주는데, 이 때 abc.html 이 없는 경우에만 404 페이지를 보여주는게 맞는 것 같아서요..!!

2022-09-04 09:49 UTC, tco0427 commented
레오 주말인데도 불구하고 열심히 피드백 반영해주셨네요!! 고생하셨습니다! 1단계 머지할게요~_~

2022-09-04 09:49 UTC, tco0427 approved these changes
레오 주말인데도 불구하고 열심히 피드백 반영해주셨네요!! 고생하셨습니다! 1단계 머지할게요~_~

2022-09-04 09:49 UTC, merged