[톰캣 구현하기 - 1단계] 렉스(오성원) 미션 제출합니다.
woowacourse/jwp-dashboard-http pull request #130
Opened 2022-09-02 03:47 UTC by Seongwon97

안녕하세요 토닉!
리뷰어로 만나게되어 영광입니다~

`🚀 1단계 - HTTP 서버 구현하기`만 구현하여 제출합니다!
리펙터링을 하려고 많은 노력을 하였으나 아직 부족함이 많은 것 같네요😭

코드에 이해가 안가는 부분이 있다면 언제든지 디엠주세요!!
잘 부탁드립니다!!

2022-09-02 05:49 UTC, tonic523 reviewed
렉스 1단계 리뷰하면서 제가 보고 배운 점이 더 많았네요 👍
특히 HttpRequest랑 HttpResonse는 제 미션에도 적용해봐야겠어요 ㅎㅎ
추가로 고민해보면 좋을 부분들을 작성해두었으니 참고하시면 좋을 것 같아요!

### 예외 처리
아래의 예외가 발생했을 때 클라이언트에게 응답을 해주고 있지 않습니다.
- 정적 리소스가 존재하지 않을 때
- `/login` 로그인 요청을 할 때 쿼리 스트링이 없을 경우
- 로그인을 실패했을 때

2022-09-02 05:49 UTC, tonic523 commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +        String requestLine = bufferedReader.readLine();
Request에서 첫 번째 라인을 start line이라고 부르더라구요. 네이밍을 바꿔주면 좋을 것 같습니다 ㅎㅎ

2022-09-02 05:49 UTC, tonic523 commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +        }
depth가 2개네요 수정할 방법이 없을까요? 🤔

2022-09-02 05:49 UTC, tonic523 commented on tomcat/src/main/java/org/apache/coyote/http11/HttpRequest.java
> +public class HttpRequest {
HttpRequest 파싱하는 로직을 읽기 좋게 잘 작성해주셨네요!

2022-09-02 07:40 UTC, Seongwon97 commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +        String requestLine = bufferedReader.readLine();
![image](https://user-images.githubusercontent.com/57744251/188084119-b58b1dde-16c2-40cb-acfb-2c8ceed959de.png)

그림으로 배우는 HTTP 책에서는 해당 라인을 `request line`이라고 불러서 오늘 강의에서 구구가 언급해주신 [RFC2616](https://www.rfc-editor.org/rfc/rfc2616#section-3.7.2)을 참고해보니 `start line`을 Request에 대해서는 `request line`으로 response에 대해서는 `status line`이라고 부르는 것 같습니다.
새로 알게 되었네요📚

2022-09-02 11:02 UTC, tonic523 commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +        String requestLine = bufferedReader.readLine();
오 그렇군요! 역시 공식문서를 제대로 읽어봐야겠네요

2022-09-03 08:23 UTC, Seongwon97 commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +        }
메서드 분리를 통해 수정했습니다!!

2022-09-03 08:27 UTC, Seongwon97 commented
안녕하세요 토닉 보내주신 리뷰를 반영하여 코드를 수정해봤습니다!! 

예외 처리의 경우 아래의 3가지 상황을 지적해주셨는데 3번째인 `로그인을 실패하였을 때`에 대한 예외 처리는 2단계 요구사항이라 미뤄두고 남은 2가지 상황에 대한 예외 처리는 추가했습니다!!
- 정적 리소스가 존재하지 않을 때
- /login 로그인 요청을 할 때 쿼리 스트링이 없을 경우
- 로그인을 실패했을 때

그 외에도 사전에 작성하지 않았던 테스트 코드의 추가와 중복 로직 제거를 하는 리펙터링을 진행해봤습니다!

아직 `HttpResponse` 객체의 경우 어떻게 만드는게 좋을지 방법이 떠오르지 않아 그대로 두었으나 2단계를 진행하며 `HttpResponse`객체도 수정해보도록 하겠습니다!

감사합니다😁

2022-09-03 10:37 UTC, tonic523 requested changes
렉스! 리뷰 너무 잘 반영해주시고 테스트까지 깔끔하게 작성해주셨네요 👍👍

로그인 관련한 요구사항이 2단계 때 있었네요!
저도 관련해서 로직을 어떻게 해야할 지 고민해봤는데 방법이 확실히 떠오르진 않네요 ㅠㅠ
같이 고민해보아요! ㅎㅎ 1단계 요구사항은 충분히 충족했다고 생각해서 이만 머지할게요!
리뷰 반영하시느라 고생많았습니다~ 다음 단계도 화이팅!!

2022-09-03 10:38 UTC, merged