[톰캣 구현하기 - 1단계] 차리(이찬주) 미션 제출합니다.
woowacourse/jwp-dashboard-http pull request #148
Opened 2022-09-02 06:33 UTC by cjlee38

안녕하세요 케이~ 리뷰 잘 부탁드립니다.

현재 아직 제대로 구현하지 못한 부분이 두 가지 있는데요.

1. Exception은 우선 TempException으로 전부 처리하고 있습니다. 발생하는 예외를 확인해서 다시 정리해보겠습니다~
2. Content Type을 지정하는 부분이 하드코딩 되어있습니다. 이 부분은 request의 view resolving 부분을 클래스로 분리하면서 리팩토링할 계획입니다.

이 점 참고바랍니다. 감사합니다 ~

2022-09-03 16:50 UTC, cjlee38 commented
`Content Type을 지정하는 부분이 하드코딩 되어있습니다. 이 부분은 request의 view resolving 부분을 클래스로 분리하면서 리팩토링할 계획입니다.`

이 부분 반영되었으니 참고바랍니다 ~

2022-09-04 03:03 UTC, kth990303 requested changes
설계가 되게 이쁘네요.
코드를 굉장히 잘 짜주셔서 보기에 편했습니다 ㅎㅎ
현재 `css`, `js` 파일을 못 받아들이는 것 같아서 해당 부분이 처리되면 바로 approve로 하겠습니다.
의문점이 있다면 DM이나 댓글로 부탁드려요!

2022-09-04 03:03 UTC, kth990303 commented on tomcat/src/test/java/org/apache/mvc/RequestHandlerMethodTest.java
> +class RequestHandlerMethodTest {
꼼꼼한 테스트가 인상깊네요! 👍

2022-09-04 03:05 UTC, kth990303 commented on tomcat/src/main/java/nextstep/Application.java
>      }
`StaticFileRequestHandlerChain`을 조금 고치면 될 것 같아요. 밑으로 내리면 해당 클래스 부분에 리뷰 남겼으니 참고하시면 될 것 같습니다~!

2022-09-04 03:14 UTC, kth990303 commented on tomcat/src/main/java/org/apache/mvc/RequestHandlerMethod.java
> +    }
```suggestion
    private void validateReturnType(Class<?> clazz) {
        if (!clazz.equals(ResponseEntity.class)) {
            throw new TempException();
        }
    }
```

2022-09-04 06:24 UTC, cjlee38 commented on tomcat/src/main/java/nextstep/Application.java
>      }
`UrlUtil`의 `urlJoin` 메소드가 잘못되었네요 ㅎㅎ; 수정하였습니다.

2022-09-04 06:24 UTC, cjlee38 commented on tomcat/src/main/java/nextstep/jwp/ui/DashboardController.java
> +        System.out.println(user.getAccount() + "의 패스워드가 일치하지 않습니다");
패스워드 일치여부를 확인한 뒤 어떤 동작을 하라고 딱히 명시된 바가 없어서 그냥 적었던거라서 크게 상관없을듯하네요 !

2022-09-04 06:25 UTC, cjlee38 commented on tomcat/src/main/java/org/apache/exception/TempException.java
> +}
그냥 표준예외로 처리할까 싶기도하네요 .. ㅎㅎ

2022-09-04 06:25 UTC, cjlee38 commented on tomcat/src/main/java/org/apache/mvc/ControllerParser.java
> +}
☺️

2022-09-04 06:26 UTC, cjlee38 commented on tomcat/src/main/java/org/apache/coyote/http11/response/headers/ContentType.java
> +    TEXT_PLAIN("text/plain", "");
root 로 요청을 보냈을 때 `Hello world!` 가 text plain으로 나가야할 것 같아서 이렇게 했었는데, 기존에 작성된 테스트 코드가 text/html 을 받아야 하더라구요.. 그래서 테스트를 고칠까 하다가 우선은 이대로 진행하였습니다!

2022-09-04 06:26 UTC, cjlee38 commented on tomcat/src/main/java/org/apache/mvc/handlerchain/StaticFileRequestHandlerChain.java
> +        }
이 부분은 위애서 언급한대로, url을 잘못 join하느라 발생한 에러였습니다. 수정하였습니다 :)

2022-09-04 06:26 UTC, cjlee38 commented on tomcat/src/test/java/org/apache/mvc/RequestHandlerMethodTest.java
> +class RequestHandlerMethodTest {
☺️

2022-09-04 06:27 UTC, cjlee38 commented on tomcat/src/main/java/org/apache/mvc/RequestHandlerMethod.java
> +    }
이게뭐죠.. 자동완성이 좀 이상하게 됐나보네요 ㅋㅋ; 감사합니다.

2022-09-04 08:04 UTC, kth990303 approved these changes
수고하셨습니다! 1, 3단계를 미리 끝내버리신 것 같을 정도로 설계가 이뻐서 approve하고 이만 머지할게요! 다음 단계에서 봐요~

2022-09-04 08:04 UTC, merged