[톰캣 구현하기 - 1단계] 이브(이유정) 미션 제출합니다.
woowacourse/jwp-dashboard-http pull request #157
Opened 2022-09-02 07:31 UTC by 2yujeong

안녕하세요 쿤!
로직이 많이 정리 되지 않은 느낌인데 리뷰 반영하면서 리팩토링 진행하고 테스트 추가하겠습니다.

2022-09-04 05:47 UTC, Hongdonggeon requested changes
이브 안녕하세요!! 메서드 네이밍이랑 코드를 너무 깔끔하고 분리도 잘되어있어서 코드를 정말 이해하기 쉬웠던 것 같아요!!👍👍
간단한 리뷰 남겨놓았는데요! 생각이 다른 점 있으면 같이 이야기해보아요!! 수고하셨습니다

2022-09-04 05:47 UTC, Hongdonggeon commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +        String mimeType = Files.probeContentType(path);
이렇게도 content type 을 알아낼 수 있군요 👍

2022-09-04 18:25 UTC, 2yujeong commented on tomcat/src/test/java/nextstep/org/apache/coyote/http11/Http11ProcessorTest.java
> +    }
테스트 추가했습니다!

2022-09-04 18:25 UTC, 2yujeong commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +                );
Processor에서 HttpRequest, HttpResponse와 비즈니스 로직을 수행하는 Handler 클래스를 분리했어요!
적절하게 책임 분리를 하려고 열심히 리팩토링 해봤는데 너무 어렵네요ㅜㅜ 계속해서 리팩토링 진행해가야 할 것 같습니다!

2022-09-05 06:31 UTC, Hongdonggeon approved these changes
httpRequest나 httpResponse 뿐만 아니라  프론트 컨트롤러 패턴을 적용한 핸들러와 핸들러 매핑도 추가 되었네요!! 
뿐만 아니라 http 메서드나 상태코드들도 enum으로 관리하면서 추후에 계속 추가될 것 같고요!! 
어렵다고 하셨는데 충분히 역할 분리가 잘되고 있다는 생각이 듭니다!! 많이 배워갑니다!! 
1단계는 merge 할게요 수고하셨습니다 😀

2022-09-05 06:34 UTC, merged