[톰캣 구현하기 - 1단계] 레넌(조형래) 미션 제출합니다.
woowacourse/jwp-dashboard-http pull request #168
Opened 2022-09-02 08:36 UTC by brorae

안녕하세요. 찬!
코드가 좀 지저분하지만 잘 부탁드립니다!
추후에 리팩토링할 예정입니다.

2022-09-04 13:28 UTC, kimchan123 requested changes
레넌! 체크리스트와 학습테스트 모두 정상적으로 잘 작동하는 것 확인했습니다 ㅎㅎ
메서드 분리가 잘 이루어져있어 코드 이해하기가 굉장히 쉬웠습니다.
일단 궁금한 것 몇가지 리뷰 남겼어요. 남긴 리뷰중에 의아하신 부분 있으시면 언제든 DM 주세요!!

2022-09-04 13:28 UTC, kimchan123 commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +            StartLine startLine = StartLine.from(bufferedReader.readLine());
HttpRequest이 StartLine을 가지고 있도록 하는거 어떨까요? 44~48번째 라인을 HttpRequest에 넣을 수 있을 것 같아요!

2022-09-04 13:28 UTC, kimchan123 commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +             BufferedReader bufferedReader = new BufferedReader(
BufferedReader도 사용을 완료하면 자원을 닫아주는 것이 좋을 것 같아요!

2022-09-04 13:28 UTC, kimchan123 commented on tomcat/src/main/java/org/apache/coyote/http11/QueryParams.java
> +public class QueryParams {
책임 분리 좋네요!!

2022-09-04 13:28 UTC, kimchan123 commented on tomcat/src/main/java/org/apache/coyote/http11/HttpRequest.java
> +            String key = item[0];
상수로 분리 하는게 어떨까요?!

2022-09-04 13:28 UTC, kimchan123 commented on tomcat/src/main/java/org/apache/coyote/http11/QueryParams.java
> +    public boolean isLoginPath() {
Path를 확인하는 부분이 StartLine에 있는 것 같은데 Login의 경우 QueryParam에 있는 것 같아요! 어떻게 생각하시나용?

2022-09-04 13:28 UTC, kimchan123 commented on tomcat/src/main/java/org/apache/coyote/http11/StartLine.java
> +    private String requestURL;
requestUrl은 final을 안붙이신 이유가 있으신가요?!

2022-09-04 13:28 UTC, kimchan123 commented on tomcat/src/main/java/org/apache/coyote/http11/StartLine.java
> +        return "/".equals(requestURL);
상수로 분리하면 좋을 것 같아요 ㅎㅎ

2022-09-04 13:28 UTC, kimchan123 commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +        Path path = Paths.get(this.getClass().getClassLoader().getResource("static" + httpRequest.getRequestURL()).getFile());
한 줄에 하나의 점만 찍도록 변경하면 어떨까요?

2022-09-05 05:11 UTC, brorae commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +             BufferedReader bufferedReader = new BufferedReader(
현재 BufferedReader도 try-with-resource로 사용되고 있어요!

2022-09-05 06:10 UTC, brorae commented on tomcat/src/main/java/org/apache/coyote/http11/QueryParams.java
> +    public boolean isLoginPath() {
startLine에서 처리하도록 변경했습니다!

2022-09-05 06:12 UTC, brorae commented on tomcat/src/main/java/org/apache/coyote/http11/StartLine.java
> +    private String requestURL;
`/login`요청의 경우 requestURL을 변경해주기 위함이었습니다.

2022-09-05 07:17 UTC, kimchan123 approved these changes
레넌! 1단계 고생하셨습니다 ㅎㅎ
머지 할게요~! 2단계도 화이팅입니다!

2022-09-05 07:17 UTC, merged