[톰캣 구현하기 - 1단계] 쿤(홍동건) 미션 제출합니다.
woowacourse/jwp-dashboard-http pull request #169
Opened 2022-09-02 08:37 UTC by Hongdonggeon

안녕하세요 포키! 
이렇게 또 만나게 되서 반갑습니다!!
미션 진행하는데 오래 걸려서 설계에 신경을 쓰지 못했네요..
현재로서는 1단계 요구사항만 완료한 상황입니다! 
리팩토링을 하면서 리뷰 기다리고 있겠습니다!

2022-09-04 15:23 UTC, YJGwon requested changes
안녕하세요 쿤! 리뷰어 포키입니다.
학습 테스트와 체크리스트 모두 확인했어요. 수고하셨습니다 👏👏
몇 가지 궁금한 점과 개선해보면 좋을 부분 의견 남겨두었으니 확인 부탁드립니다.

(+) login 했을 때 로그는 잘 찍히지만 페이지가 출력되지 않고 있는데요!
체크리스트에 포함된 내용은 아니지만, 미션 페이지의 출력 예시 화면을 보면 login.html도 함께 출력되고 있어서, 페이지가 보이게 해보면 어떨까 싶어요. (필수 요구사항은 아닌 것으로 파악했기 때문에 고려만 해봐주세요!)

2022-09-04 15:23 UTC, YJGwon commented on tomcat/src/main/java/org/apache/coyote/http11/HttpResponse.java
> +        final String contentType = Files.probeContentType(path);
java의 api로 ContentType을 구할 수 있는건 처음 알았네요...!
그런데 browser에서 보니 `.js`의 type이 null로 반환되고 있어요. 동작은 잘 되지만, 확인해보시면 좋을 듯 합니다!

2022-09-04 15:23 UTC, YJGwon commented on tomcat/src/main/java/org/apache/coyote/http11/ViewResolver.java
> +            return null;
null을 반환하지 않을 방법은 없을까요?

2022-09-05 06:38 UTC, Hongdonggeon commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +            final HttpRequest requestValue = readHttpRequest(inputStream);
리팩토링하기전에 inputStream에서 읽은 값들을 requestValue라고 하고 httpRequest객체로 바인딩후에는 httpRequest로 네이밍을 바꾸려고 했는데 바뀌지 않았던 것 같아요.. httpRequest로 변경하였습니다!!

2022-09-05 06:44 UTC, Hongdonggeon commented on tomcat/src/main/java/org/apache/coyote/http11/QueryStringParser.java
> +        final Map<String, String> map = new HashMap<>();
좋습니다! 자료형을 사용하게 되면 의미도 불분명하고 자료형을 바꾸게 되면 변수명도 바꿔야되겠네요!!  리뷰 반영했습니다 :)

2022-09-05 06:57 UTC, Hongdonggeon commented on tomcat/src/main/java/org/apache/coyote/http11/ViewResolver.java
> +            return null;
Optional을 이용해서 null을 사용하지 않게 변경했습니다

2022-09-05 07:02 UTC, Hongdonggeon commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +        final List<String> headerLines = new ArrayList<>();
지금 쓰이진 않지만 원래 사용하려고 하였는데 BufferedReader에 담긴 문자열을 모두 읽으면 IndexoutOfBoundException이 발생하더라고요.. 
에러 파악 후 해결까지하고 리뷰 요청을 하면 너무 늦어질 것 같아서, 먼저 리뷰요청을 드렸는데 사용하지 않는 부분이 지워지지 않았던 것 같네요,,

2022-09-05 07:03 UTC, Hongdonggeon commented on tomcat/src/main/java/org/apache/coyote/http11/HttpResponse.java
> +                "Content-Type: " + contentType + ";charset=utf-8 ",
좋은 생각인 것 같아요!! header 뿐만 아니라 상태코드, http 메서드, 파일 확장자도 enum으로 관리하면 좋을 것 같네요~

2022-09-05 07:33 UTC, Hongdonggeon commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +        final List<String> headerLines = new ArrayList<>();
에러 발생한 곳을 찾아서 header 값들도 바인딩하게 했습니다

2022-09-05 08:11 UTC, Hongdonggeon commented on tomcat/src/main/java/org/apache/coyote/http11/HttpResponse.java
> +        final String contentType = Files.probeContentType(path);
넵 확인해보겠습니다!

2022-09-05 10:43 UTC, YJGwon approved these changes
안녕하세요 쿤~! 포키입니당. 리뷰 반영하시느라 수고많으셨습니다.

현재는 요청에 따라 보여줄 결과 page의 경로를 항상 uri에서 찾고 root path만 따로 처리하고 있는데, view page의 경로가 요청 uri와 일치하지 않을 경우가 많을 것이라 생각해요.
root path 외에 요청 경로와 다른 경로를 가진 view를 응답해야 할 경우가 더 늘어난다면 `ViewResolver`의 분기 처리가 어떻게 바뀌게 될 지, 해당 분기 처리의 책임을 나눌 수는 없을 지 생각해볼 수 있을 것 같습니다.

1단계에서 요구하는 기능 모두 잘 구현된 것 같아 이번 단계는 머지할게욥 🚀 
몇 가지 comment 남겨두었으니 2단계 진행하면서 함께 고민해봅시다! 화이팅 💪

2022-09-05 10:43 UTC, YJGwon commented on tomcat/src/main/java/org/apache/coyote/http11/HttpHeader.java
> +public enum HttpHeader {
👍

2022-09-05 10:43 UTC, YJGwon commented on tomcat/src/main/java/org/apache/coyote/http11/HttpRequest.java
> +                        final Map<String , String> headers) {
불필요한 공백이 추가되어있네요 👀

2022-09-05 10:43 UTC, YJGwon commented on tomcat/src/main/java/org/apache/coyote/http11/HttpResponse.java
> +    public static HttpResponse of(final Optional<URI> uri) throws URISyntaxException, IOException {
Optional을 parameter type으로 사용하게 되면 어떤 문제들이 발생할 수 있을까요? [reference](https://johngrib.github.io/wiki/java-optional/)

2022-09-05 10:43 UTC, YJGwon commented on tomcat/src/main/java/org/apache/coyote/http11/ViewResolver.java
> +            return Optional.empty();
root일 경우에 `Optional.empty()`를 반환하는 것이 이 method를 호출하는 곳에서 보았을때 충분한 의미 전달이 될까 하는 우려가 들어요! root인 경우에 대한 분기 처리가 이 곳에서 이루어지는게 맞을지 한 번 더 고민해볼 수 있을 것 같아요.

2022-09-05 10:43 UTC, merged