[톰캣 구현하기 - 2, 3단계] 루키(최지훈) 미션 제출합니다.
woowacourse/jwp-dashboard-http pull request #211
Opened 2022-09-06 12:55 UTC by Wishoon

안녕하세요 후니 💪 

지난 PR에서 3단계 조금씩 진행했어서 2, 3단계를 같이 제출합니다. 아직 단위 테스트가 작성되어 있지 않는데요.. 계속해서 HttpXXX 구조를 변경하다보니 시간이 많이 지체되어서 일단 통합테스트만 작성했습니다 😅

이번에도 피드백 잘 부탁드릴게요~~

2022-09-07 01:43 UTC, jayjaehunchoi requested changes
루키!! 테스트도 꼼꼼하게 짜고, 코드도 굉장히 좋아진 것 같아요!!
몇가지 내용만 rc 드리니 한 번 확인해보시고 다시 리뷰 요청주세요!!

2022-09-07 01:43 UTC, jayjaehunchoi commented on tomcat/src/main/java/nextstep/jwp/db/InMemoryUserRepository.java
> +    public static boolean existByAccount(final String account) {
오 좋은데요?

2022-09-07 01:43 UTC, jayjaehunchoi commented on tomcat/src/main/java/nextstep/jwp/handler/RequestHandler.java
> +            "/login", LoginController.getInstance(),
상수는 따로 관리해줘도 좋을 것 같아요

2022-09-07 01:43 UTC, jayjaehunchoi commented on tomcat/src/main/java/nextstep/jwp/http/response/HttpResponse.java
> +        if (httpHeaders.isExistSetCookie()) {
루키도 잘 알겠지만 toString은 로그 목적으로 override하는 메서드입니다! 다른 메서드를 사용해주세용

2022-09-07 01:43 UTC, jayjaehunchoi commented on tomcat/src/main/java/nextstep/jwp/presentation/AbstractController.java
> +        throw new UnsupportedOperationException();
저도 이걸 썼긴했지만 Servlet어쩌구로 custom exception이 만들어져있더라구요

2022-09-07 01:43 UTC, jayjaehunchoi commented on tomcat/src/main/java/nextstep/jwp/presentation/LoginController.java
> +            File file = new File(Thread.currentThread().getContextClassLoader().getResource(PREFIX + "/index.html").getFile());
파일을 읽어오는 것이 컨트롤러의 책임인가요?

2022-09-07 01:43 UTC, jayjaehunchoi commented on tomcat/src/main/java/nextstep/jwp/presentation/RegisterController.java
> +            File file = new File(Thread.currentThread().getContextClassLoader().getResource(PREFIX + "/index.html").getFile());
책임 분리

2022-09-07 01:43 UTC, jayjaehunchoi commented on tomcat/src/main/java/nextstep/jwp/presentation/RegisterController.java
> +            httpResponse.addRedirect(file, "/register.html");
예외를 보내는 클래스를 만들거나, 있는 클래스에 넣어보세요!

Servlet 라이브러리의 httpServletRequest를 참고해보세용

2022-09-07 16:58 UTC, Wishoon commented on tomcat/src/main/java/nextstep/jwp/handler/RequestHandler.java
> +            "/login", LoginController.getInstance(),
각 Controller에서 Path를 상수로 관리하도록 반영했습니다~~

2022-09-07 16:59 UTC, Wishoon commented on tomcat/src/main/java/nextstep/jwp/http/response/HttpResponse.java
> +        if (httpHeaders.isExistSetCookie()) {
😅 하하.. 그냥 재정의해서 사용해버렸네요 ㅎㅎ.. 수정했습니다!

2022-09-07 17:01 UTC, Wishoon commented on tomcat/src/main/java/nextstep/jwp/presentation/LoginController.java
> +            File file = new File(Thread.currentThread().getContextClassLoader().getResource(PREFIX + "/index.html").getFile());
File을 읽어오는 Util 클래스를 만들고 이를 Header에서 넣어주도록 수정했습니다!

2022-09-07 17:01 UTC, Wishoon commented on tomcat/src/main/java/nextstep/jwp/presentation/RegisterController.java
> +            File file = new File(Thread.currentThread().getContextClassLoader().getResource(PREFIX + "/index.html").getFile());
위와 동일한 방식으로 진행했습니다!!

2022-09-07 17:03 UTC, Wishoon commented on tomcat/src/main/java/nextstep/jwp/presentation/RegisterController.java
> +            httpResponse.addRedirect(file, "/register.html");
음 HttpHeader에 sendError라는 메서드를 만들어서 처리하도록 변경했는데, 혹시 후니가 생각했던 부분과 동일할까요??

2022-09-08 01:26 UTC, jayjaehunchoi commented on tomcat/src/main/java/nextstep/jwp/presentation/RegisterController.java
> +            httpResponse.addRedirect(file, "/register.html");
맞습니다 ㅎㅎ

2022-09-08 01:29 UTC, jayjaehunchoi approved these changes
루키 ! 코드가 많이 깔끔해졌네요 ㅎㅎ. 저도 배울점이 많은 리뷰였고, 리뷰를 하면서 이런저런 고민들을 추가적으로 해볼 수 있어 좋았어요.

피알은 이만 머지하겠습니다! 마지막 미션도 화이팅해주세용

2022-09-08 01:29 UTC, merged