[톰캣 구현하기 - 2단계] 라라(박세은) 미션 제출합니다.
woowacourse/jwp-dashboard-http pull request #218
Opened 2022-09-07 04:46 UTC by sure-why-not

오리 안녕하세요!
일단 2단계 구현 완료하여 PR 날립니다~
아직 구조가 잘 나눠지지 않았다고 생각합니다 ㅠ_ㅠ
테스트 코드도 미흡해서 추가해보겠습니다!!
구조는 3단계 리팩토링에서 더 고민해보고 적용해보겠습니다!!
잘 부탁드립니당 오선생 😎

2022-09-07 13:12 UTC, jinyoungchoi95 requested changes
안녕하세요 라라 :)

미션 요구 사항 다 구현된것 확인했습니다 😄 
세세한 구조는 말씀해주신대로 3단계에서 진행하시면 될 것 같아요. 몇가지 코멘트 남겨두었으니 확인 부탁드려요! 
(테스트가 터지는데 확인 부탁드려요 🙇‍♂️)

2022-09-09 14:03 UTC, sure-why-not commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +            return getLoginResponseWithRequestBody(httpRequest);
맞습니다!! 수정했어요 👍🏻

2022-09-09 14:04 UTC, sure-why-not commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +            }
```
    protected HttpResponse doGet(HttpRequest request) {
        if (isAlreadyLogin(request)) {
            return HttpResponse.redirect()
                    .addLocation(View.INDEX.getViewFileName());
        }
        return HttpResponse.ok()
                .addResponseBody(View.LOGIN.getContents(), ContentType.TEXT_HTML_CHARSET_UTF_8);
    }

    private boolean isAlreadyLogin(HttpRequest request) {
        return request.getSession()
                .map(SessionManager::findSession)
                .isPresent();
    }
```
오리 의견 반영해서 이렇게 변경해보았어요!! 감사합니다 😆

2022-09-09 14:06 UTC, sure-why-not commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +            }
QueryParam으로 로그인하는 방법은 삭제했습니다~~

2022-09-09 19:28 UTC, sure-why-not commented on tomcat/src/main/java/org/apache/coyote/http11/response/HttpResponse.java
> +    private String protocol = null;
빌더 패턴 적용을 예상하고 만들어둔 것이었는데 역시 예리하시네요 !👍🏻

2022-09-09 19:35 UTC, sure-why-not commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +        InMemoryUserRepository.save(new User(account, password, email));
맞는 말씀이십니다 😱 추가했습니다!

2022-09-09 19:36 UTC, sure-why-not commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +                .addResponseBody("페이지를 찾을 수 없습니다.", ContentType.TEXT_HTML_CHARSET_UTF_8);
오리의 피드백을 반영하여 isPresent()의 if문 분기는 없애도록 했습니다! 좋은 피드백 감사해용 🥰

2022-09-09 19:37 UTC, sure-why-not commented on tomcat/src/main/java/org/apache/coyote/http11/session/Cookies.java
> +    }
요구사항을 그대로 반영하다보니 이런 구조가 되었네요 😭
저도 Cookie가 해도 되는 책임이라고 생각하여 수정했습니다~

2022-09-12 01:44 UTC, kang-hyungu requested changes
라라 몇 가지 피드백 남겼어요
수정해보시고 리뷰 재요청주세요.

2022-09-12 01:44 UTC, kang-hyungu commented on tomcat/src/main/java/nextstep/jwp/controller/LoginController.java
> +            Session session = new Session(uuid.toString());
세션키를 컨트롤러에서 만들어서 넣어주는 것보다 세션에서 직접 만들면 어떨까요

2022-09-12 01:44 UTC, kang-hyungu commented on tomcat/src/main/java/nextstep/jwp/controller/MainController.java
> +        return null;
리턴값으로 null은 피하는게 좋습니다.
npe 발생 원인이 됩니다.

2022-09-12 01:44 UTC, kang-hyungu commented on tomcat/src/main/java/org/apache/catalina/connector/Connector.java
> +        threadPool.submit(() -> processor.process(connection));
```suggestion
        threadPool.submit(processor);
```

Http11Processor 클래스의 run 메서드를 참고하세요.

2022-09-12 01:44 UTC, kang-hyungu commented on tomcat/src/main/java/org/apache/coyote/http11/request/HttpRequest.java
> +    private Optional<String> extractSessionValue(String cookieValue) {
쿠키 객체를 따로 추출해보는건 어떨까요?

2022-09-12 01:44 UTC, kang-hyungu commented on tomcat/src/main/java/org/apache/coyote/http11/request/RequestBody.java
> +    public RequestBody(Map<String, String> bodies) {
클라이언트가 분해해서 map 형태로 전달하는 구조가 되면 클라이언트의 코드가 복잡해집니다.
중복 코드도 생길 여지가 있구요.
RequestBody 문자열을 그대로 받아와서 객체 내부에서 파싱하도록 만들어보세요.

2022-09-12 01:44 UTC, kang-hyungu commented on tomcat/src/main/java/org/apache/coyote/http11/request/HttpRequest.java
> +    private Optional<String> extractSessionValue(String cookieValue) {
쿠키가 있네요? 하지만 쿠키가 거의 활용되지 않고 있네요.
쿠키 문자열에 대한 처리를 쿠키 객체에게 넘기는게 어떨까요

2022-09-12 21:49 UTC, sure-why-not commented on tomcat/src/main/java/nextstep/jwp/controller/LoginController.java
> +            Session session = new Session(uuid.toString());
세션키는 세션이 만드는게 더 적절한 책임인 것 같네요. 수정했습니다

2022-09-12 21:50 UTC, sure-why-not commented on tomcat/src/main/java/nextstep/jwp/controller/MainController.java
> +        return null;
앗 이 부분을 놓쳤네요. notFound 응답을 반환하도록 변경했습니다~

2022-09-12 21:52 UTC, sure-why-not commented on tomcat/src/main/java/org/apache/coyote/http11/request/HttpRequest.java
> +    private Optional<String> extractSessionValue(String cookieValue) {
Request에 대해서는 쿠키를 사용하지 않고 있었네요.😅
```java
   private Optional<String> extractSessionValue(String cookieValue) {
        Cookie cookie = Cookie.of(cookieValue);
        return cookie.getJSessionValue();
    }
```
이와 같이 수정했습니다 😀

2022-09-12 21:52 UTC, sure-why-not commented on tomcat/src/main/java/org/apache/coyote/http11/request/RequestBody.java
> +    public RequestBody(Map<String, String> bodies) {
미처 생각하지 못했던 부분이네요. 감사합니다 🥺☺️

2022-09-13 00:36 UTC, jinyoungchoi95 requested changes
안녕하세요 라라 :)

추석연휴동안 미션하느라 고생하셨습니다!
몇가지 같이 고민해보면 좋을만한 부분들 코맨트 남겨두었어요. 궁금하신 부분은 코맨트 혹은 dm으로 편하게 부탁드립니다 🙇‍♂️

2022-09-13 00:36 UTC, jinyoungchoi95 commented on tomcat/src/main/java/nextstep/jwp/controller/LoginController.java
> +        return doNotFoundRequest();
요 부분이 반복되고 있는 것 같지 않나요?
`MainController`도 Post만 구현되어있지 않을 뿐이지 해당 부분이 계속해서 반복되고 있어요

`AbstractController`를 사용하고 있는 상황이라면 이 부분이 적절하게 해소될 것 같은데 어떻게 생각하세요?
`AbstractController`에서 `doPost`와 `doGet`은 throws를 던지게끔 두고, 지금 메소드라인을 `AbstractController`에서 구현하는거죠. 만약 각각의 Controller에서 overriding을 하지 않으면 throws가 나오는 구조가 될 것 같아요.

2022-09-13 00:36 UTC, jinyoungchoi95 commented on tomcat/src/main/java/nextstep/jwp/controller/LoginController.java
> +                    .build();
이부분도 `getLoginRedirectResponse()`으로 뺀다면 `getLoginResponse`를 읽기 더 수월하다라는 생각이 드네요 :)

2022-09-13 00:36 UTC, jinyoungchoi95 commented on tomcat/src/main/java/nextstep/jwp/controller/LoginController.java
> +        return SessionManager.isExist(session.get());
```java
return request.getSession()
                .stream()
                .anyMatch(SessionManager::isExist);
```
와 같은 방법을 사용할 수도 있고
```java
return request.getSession()
                .map(SessionManager::isExist)
                .orElse(false);
```
와 같은 방법도 있으니 나중에 한번 고려해주세요 :)

2022-09-13 00:36 UTC, jinyoungchoi95 commented on tomcat/src/main/java/nextstep/jwp/view/View.java
> +public enum View {
view 객체 좋네요 :)

2022-09-13 00:36 UTC, jinyoungchoi95 commented on tomcat/src/main/java/org/apache/catalina/connector/Connector.java
> +    private final ExecutorService threadPool;
thread pool 👍

2022-09-13 00:36 UTC, jinyoungchoi95 commented on tomcat/src/main/java/org/apache/catalina/connector/Connector.java
> +    public Connector(final int port, final int acceptCount) {
매개변수에 final이 달린곳과 안달린곳이 있어요 :) ide 설정을 나중에 한번 살펴보시는 것도 좋을 것 같네요 😄

2022-09-13 00:36 UTC, jinyoungchoi95 commented on tomcat/src/main/java/org/apache/catalina/connector/Connector.java
> +}
eol
https://velog.io/@d-h-k/intellij-%ED%8C%8C%EC%9D%BC%EB%81%9D%EC%97%90-%EA%B0%9C%ED%96%89%EC%9D%84-%EC%9E%90%EB%8F%99%EC%9C%BC%EB%A1%9C-%EC%B6%94%EA%B0%80%ED%95%98%EB%8A%94-%EB%B0%A9%EB%B2%95

2022-09-13 00:36 UTC, jinyoungchoi95 commented on tomcat/src/main/java/org/apache/catalina/connector/Connector.java
> +        threadPool.submit(processor);
`ExecutorService`의 `submit()`과 `execute()`의 차이는 무엇인가요? 둘 중 `submit()`을 사용한 이유가 무엇인가요?

2022-09-13 00:36 UTC, jinyoungchoi95 commented on tomcat/src/main/java/org/apache/coyote/http11/request/RequestBody.java
> +    public static RequestBody ofEmptyValue() {
취향차이라고 생각하는데요, 개인적으로는 빈 값을 나타낸다면 `empty()`로도 충분하다라는 생각이 드네요 🤔

2022-09-13 00:36 UTC, jinyoungchoi95 commented on tomcat/src/main/java/org/apache/coyote/http11/response/HttpResponse.java
> +    public static HttpResponseBuilder ok() {
👍

2022-09-13 00:36 UTC, jinyoungchoi95 commented on tomcat/src/main/java/org/apache/coyote/http11/response/HttpResponse.java
> +            sb.append("Content-Type: ").append(contentType.getType()).append(" ").append("\r\n");
```suggestion
            sb.append("Content-Type: ").append(contentType.getType()).append(" \r\n");
```
소소하지만 이렇게 변경되어도 될 것 같네요

2022-09-13 00:36 UTC, jinyoungchoi95 commented on tomcat/src/main/java/org/apache/coyote/http11/session/Session.java
> +    private final Map<String, Object> values = new HashMap<>();
Session도 Concurrency 문제가 발생하지 않을까요?

2022-09-13 06:28 UTC, sure-why-not commented on tomcat/src/main/java/nextstep/jwp/controller/ControllerMapping.java
> +    private final static Map<String, Controller> controllers = new HashMap<>();
헉 ㅎ 많이 졸렸던 것 같네요...

2022-09-13 08:34 UTC, sure-why-not commented on tomcat/src/main/java/nextstep/jwp/controller/LoginController.java
> +        return SessionManager.isExist(session.get());
대박 ! 꿀팁 감사합니다 👍🏻

2022-09-13 12:22 UTC, sure-why-not commented on tomcat/src/main/java/org/apache/coyote/http11/session/Session.java
> +    private final Map<String, Object> values = new HashMap<>();
한 세션에서도 발생할 수 있겠네요!1 좋은 피드백 감사합니다. 👍🏻

2022-09-14 05:45 UTC, jinyoungchoi95 approved these changes
테스트가 많이 추가되어서 더 안정적으로 리팩터링 기간을 가질 수 있게 된 것 같네요
리뷰량이 많았을텐데 긴 기간동안 고생하셨습니다 🙇‍♂️
다음 미션도 화이팅 하세요! :)

2022-09-14 05:46 UTC, merged