[톰캣 구현하기 - 2단계] 코린(유현지) 미션 제출합니다.
woowacourse/jwp-dashboard-http pull request #219
Opened 2022-09-07 04:51 UTC by hamcheeseburger

스컬 안녕하세요!
톰캣 2,3단계 구현해서 PR 제출합니다.

많은 지적 부탁드립니다 🙇🏻‍♀️

2022-09-09 06:34 UTC, skullkim requested changes

2022-09-09 06:34 UTC, skullkim commented on tomcat/src/main/java/nextstep/jwp/http/HttpCookie.java
> +    public static HttpCookie create(final String raw) {
변수명이 raw네요. 올바른 네이밍 일까요?

2022-09-09 06:34 UTC, skullkim commented on tomcat/src/main/java/nextstep/jwp/http/HttpCookie.java
> +    private static void validateKeyValueSize(final String[] split) {
split이 무슨 의미죠? 개발자는 저자입니다. 그리고 저자는 읽기 좋은 글을 써야할 책임이 있죠. 좋은 글을 읽기 수월하고요. split 이라는 변수 이름을 통해 해당 변수가 어떤 것인지 알 수 있을까요?
클린코드 1장을 읽어보는 것을 추천드릴게요.
[클린코드 1장. 깨끗한 코드](https://iskull-dev.tistory.com/218)

2022-09-09 06:34 UTC, skullkim commented on tomcat/src/main/java/nextstep/jwp/http/InvalidCookieException.java
> +    public InvalidCookieException() {
유효하지 않은 쿠키 에러에 다른 에러 메시지를 남겨야 할 경우 다른 에러를 만들어야 하나요? 이 예외를 어떻게 수정해야 할까요?

2022-09-09 06:34 UTC, skullkim commented on tomcat/src/main/java/nextstep/jwp/http/RequestParser.java
> +        final String url = line.split(" ")[1];
매직넘버!

2022-09-10 09:41 UTC, hamcheeseburger commented
스컬 안녕하세요! 코멘트 달아주신 부분 반영하여 구현해보았습니다.

### 웹서버 패키지의 사용자 패키지 의존성 분리

제일 중요하게 짚어주신 범용 웹서버를 만들기 위해서 웹서버 패키지가 사용자 패키지를 의존하지 않도록 하였습니다.

어떻게 분리를 해야 할까 생각해보니 웹서버에서 사용자가 원하는 대로 구현할 수 있도록 추상화된 레이어를 제공해 주면 되겠다고 생각했습니다. 그렇게 만들게 된 것이 `org.apache.catalina.core.Servlet` 입니다. 

또한 uri별로 동작할 Servlet을 관리하기 위해서 `org.apache.catalina.core.ServletContainer`을 생성하게 되었습니다. 솔직히 지금 시점에서는 그렇게 필요한 객체는 아니라는 생각이 드는데요, 말씀 주신대로 범용 웹서버를 만들기 위해서는 사용자가 원하는대로 조작할 수 있게끔 제공해주는 것이 맞다는 생각이 들어 만들게 되었습니다.

### AbstractController 적용

말씀 주신대로 HttpMethod 별로 Controller를 생성하는 것은 관리 포인트가 늘어 날 것 같아, LMS에 명시된 AbstractController를 적용하였습니다.

### 응답 객체를 미리 생성하여 전달하기

이전 코드의 Controller에서는 요청 객체를 전달 받아 응답 객체를 반환하는 형태이었는데요. 이런 구조를 갖게 되면 Response 객체를 미리 Wrapping해야 하거나 스컬이 말씀하신대로 사용자의 의도와 관계 없이 세팅되어야 하는 부분이 있을 때 구현이 어렵겠다고 생각했어요. 그래서 요청 객체와 응답 객체를 미리 생성하고 필요한 부분에 전달하는 방식으로 변경하였습니다.

이번에 리팩터링 하면서 패키지 구조가 많이 바뀌다 보니 FileChanges가 너무 많네요..😭 다시 한번 살펴보시고 리뷰 부탁드리겠습니다!!

정말 꼼꼼하고 정성스러운 리뷰 매번 감사드립니다👍🏻🙇🏻‍♀️

2022-09-10 09:42 UTC, hamcheeseburger commented on tomcat/src/main/java/nextstep/jwp/http/InvalidCookieException.java
> +    public InvalidCookieException() {
InvalidException으로 변경하고 메시지를 외부에서 전달할 수 있게끔 변경하였습니다!

2022-09-10 13:06 UTC, skullkim requested changes
안녕하세요 코린🤚. 피드백 반영해주신 코드 잘 봤습니다. 이전보다 훨씬 구조가 깔끔해진거 같아요👍🏻. 추가적인 피드백을 남겼으니 확인해주세요😁

2022-09-10 13:06 UTC, skullkim commented on tomcat/src/main/java/org/apache/coyote/Headers.java
> +        values.forEach((key, value) ->
Map에 구현된 forEach를 보면 인자로 BiConsumer 타입을 받고 있죠. BiConsumer는 java8에서 함수형 인터페이스를 정의한 java.util.function 패키지에 존재하고요. 함수형인터페이스는 자바에서 함수를 일급 시민으로 사용하기 위해 만들어졌고, 이는 함수형 프로그래밍을 자바에 도입했다고 볼 수 있죠. 이 떄, 함수형 프로그래밍에서 중요한 것이 함수 외부의 상태를 변경하지 않는 것이에요. 그런데 이 코드에서는 자바에서 함수형 프로그래밍을 염두한 람다를 사용하면서도 함수 외부의 상태인 builder를 변경하고 있죠. 코드가 올바르게 동작하는 것은 맞지만 의도가 잘못되었다는 생각이 드네요.

이 방식 대신 for-each loop를 사용하는 것은 어떤가요?
```
for (Entry<HttpHeader, String> entry : value.entrySet()) {...}
```

2022-09-10 13:06 UTC, skullkim commented on tomcat/src/test/java/nextstep/jwp/http/ControllerMappingTest.java
> +class ControllerMappingTest {
테스트가 비어있네요😃.

2022-09-10 17:33 UTC, hamcheeseburger commented on tomcat/src/main/java/nextstep/jwp/controller/Controller.java
> +    void service(Request request, Response response);
결론적으로 말하자면 Controller와 Servlet의 역할이 다르기 때문인데요,

제가 프로젝트에서 사용한 Controller와 Servlet의 역할에 대해 설명드리겠습니다.

- Controller : 구체적인 uri별 요청 처리를 위한 객체
- Servlet : 특정 uri 규칙을 가지는 요청들을 전달받고 구체적인 uri별 요청 처리를 위한 Controller를 관리함. 또한 Controller 실행 전 후로 이루어져야 할 context를 구현하고 있음.

Servlet의 행위를 Http11Processor 에서 맡을 수 있을 것 같긴 하다만, Controller 전후로 포함될 로직도 사용자에게 맡길 수 있는 것이 더 좋다고 생각했습니다. 해당 로직을 사용자에게 구현할 수 있게끔 하기 위해서는 웹서버 측에서 interface를 제공해야 한다고 생각했으며 이를 Servlet으로 칭한 것 입니다. 사실 명칭의 문제일 수도 있을 것 같아요. Servlet으로 칭하지 않고 Context 라든지 다른 네이밍을 활용 했었다면 코멘트를 받지 않았을 수도 있겠다는 생각이 드네요.

다만 아래 명시된 jakarta Servlet에 대한 설명을 읽어보면 제가 생성한 Servlet과 그리 상충한다고 생각하지 않아요. 그렇기 때문에 현재로써는 계속 이 네이밍을 써도 괜찮다는 생각입니다.

> A servlet is a small Java program that runs within a Web server. **Servlets receive and respond to requests from Web clients**, usually across HTTP, the HyperText Transfer Protocol.
> **This interface defines methods to initialize a servlet, to service requests, and to remove a servlet from the server.** 

이견 있으시면 코멘트 주시면 감사하겠습니다!

2022-09-12 08:33 UTC, hamcheeseburger commented on tomcat/src/main/java/nextstep/jwp/http/HttpCookie.java
> +public class HttpCookie {
apache 패키지로 이동하였습니다!

2022-09-12 08:34 UTC, hamcheeseburger commented on tomcat/src/main/java/org/apache/coyote/Headers.java
> +        values.forEach((key, value) ->
자세한 설명 감사합니다! 적용하였습니다.

2022-09-12 08:34 UTC, hamcheeseburger commented on tomcat/src/test/java/nextstep/jwp/http/ControllerMappingTest.java
> +class ControllerMappingTest {
추가하였습니다😅

2022-09-14 04:44 UTC, merged