[톰캣 구현하기 - 3단계] 릭(나일성) 미션 제출합니다.
woowacourse/jwp-dashboard-http pull request #232
Opened 2022-09-07 12:34 UTC by nailseong

안녕하세요 아스피~! 
지난 1, 2단계 리뷰 주신 부분 반영 & 3단계 구현해봤어요. 리뷰 잘 부탁드려요 (_ _)

혹시 코드 읽으시다가 궁금한 부분이 생긴다면 언제든지 DM 주셔도 됩니다~!

2022-09-09 07:34 UTC, shindong96 requested changes
안녕하세요 릭! 아스핍니다 :)
추석 첫 날 잘 보내고 계신가요ㅎㅎ

우선 릭 코드의 전반적인 구조에 대한 저의 감동을 표현하고 싶네요...💯 
정말 코드를 보면서 책임 분리가 잘 되어 있고 읽기 쉬운 코드라는 생각이 들었어요.
특히 jwp 패키지만 보면 저희가 이전 레벨들에서 구현하던 부분들이 여기구나라는 생각을 하게 되더라구요. 
다른 패키지를 다 닫고 보면 비즈니스 로직만 딱 볼 수 있는! 그 만큼 패키지 간의 책임 분리도 잘 되어있다는 것 같아요!

개인적인 생각으로 코드 자체에 피드백할 점은 크게 없었던 거 같아요. 다만, 상황에 따른 처리가 하나 더 되면 좋겠다는 생각이 들었습니다.

```
1. 로그인을 한다.
2. localhost:8080/register 로 간다.
3. 회원가입을 한다.
```
이 순서로 실행하게 되면 JSESSIONID가 하나 더 발급되는 부분을 볼 수 있어요!
요구사항에는 따로 적힌게 없으나 처리해둔다면 더 좋을거 같아요ㅎㅎ

풍성한 한가위 되세요 릭 :)
고생하셨습니당

2022-09-09 07:34 UTC, shindong96 commented on tomcat/src/main/java/org/apache/coyote/http/request/RequestHeader.java
> +            if (splitHeader[KEY].equals(COOKIE.getValue())) {
이 분기는 Header에서 Cookie에 대한 정보가 있을 때, Cookie를 따로 저장해주기 위한 처리 인 것 같아요!
그렇다면 method 분리를 통해 indent depth를 줄여보는 것은 어떨까요? 메서드 책임 분리도 이루어질 거 같아서 좋을 것 같은데 릭의 생각은 어떠세요?

2022-09-09 07:34 UTC, shindong96 commented on tomcat/src/main/java/org/apache/coyote/http/request/RequestHeader.java
> +        while (!"".equals((header = bufferedReader.readLine()))) {
이건 제 개인적인 생각이니 참고만 해주세요!
저는 헤더를 읽을 때마다 이 헤더가 Cookie에 관한 부분인지 확인하는 로직이 실행되는  것 보다는 다른 헤더들처럼 String으로 저장하고 while문이 끝난 이후에 Cookie가 있었는지 확인한 후 있었다면 RequestCookie를 만들어 value를 바꾸는 방식은 어떨까라는 생각이 들었어요!

```
while (!"".equals((header = bufferedReader.readLine()))) {
            final String[] splitHeader = header.split(HEADER_DELIMITER);
            values.put(splitHeader[KEY], splitHeader[VALUE].trim());
}

if(values.containsKey(COOKIE.getValue())){
            final String cookies = (String) values.get(COOKIE.getValue());
            values.put(COOKIE.getValue(), RequestCookie.from(cookies.trim()));
}
```

이런 식으로 변경하면 if문 조건 비교가 헤더의 개수만큼 실행되지 않고 1번만 실행되니 더 좋지 않을까...?라는 사견이였습니다!

2022-09-09 07:34 UTC, shindong96 commented on tomcat/src/main/java/org/apache/coyote/http/response/HttpResponse.java
> +public class HttpResponse {
체이닝을 이용한 방식덕에 Controller에서 이해가 수월했어요! 마치 Builder...
릭...천재신가요? 🥇

2022-09-09 07:34 UTC, shindong96 commented on tomcat/src/test/java/nextstep/jwp/service/AuthServiceTest.java
> +        final UserDto request = new UserDto(account, "1234", "아스피@levellog.app");
전 이미 levellog.app에 가입한 상태라 중복된 회원입니다! :wink:

2022-09-09 07:34 UTC, shindong96 commented on tomcat/src/main/java/org/apache/coyote/util/StringParser.java
> +    public static Map<String, String> split(final String source, final String fieldDelimiter,
저번 피드백에서 릭의 의견을 봤어요!! Delimeter를 인자로 넘기면서 훨씬 util에 맞는 메서드가 된 것 같아요!!ㅎㅎ

2022-09-12 02:57 UTC, nailseong commented on tomcat/src/main/java/org/apache/coyote/http/HttpStatusCode.java
> +    INTERNAL_SERVER_ERROR(500, "Internal Server Error"),
좋은 피드백 감사해요!! 완전 동의 합니다. 500 보다는 405를 응답하는게 좋겠어요!!

실제 Spring MVC는 어떻게 처리할까 궁금해서 테스트를 해봤어요. 
- 요청 경로가 매핑된 컨트롤러가 존재하지 않으면 `500`
- 요청 경로에 매핑된 컨트롤러가 있지만 http method까지 일치하지 않는 경우 아래와 같이 `405`
![image](https://user-images.githubusercontent.com/68512686/189565612-355b8563-9897-4e46-998b-efa773ff5b01.png)

2022-09-12 03:32 UTC, nailseong commented on tomcat/src/main/java/org/apache/coyote/http/HttpStatusCode.java
> +        return "HTTP/1.1 " + statusCode + " " + message;
그렇네요!! 반영해볼께요~!! 😋

2022-09-12 03:58 UTC, nailseong commented on tomcat/src/main/java/org/apache/coyote/http/request/HttpRequest.java
> +        final String queryString = uri.substring(prefixIndex + PATH);
`1`을 상수 추출하면서 같이 `PATH`로 변경된 것 같아요! 😱😱😱😱😱
수정하겠습니다~!!

2022-09-12 04:20 UTC, nailseong commented on tomcat/src/main/java/org/apache/coyote/http/request/RequestHeader.java
> +            if (splitHeader[KEY].equals(COOKIE.getValue())) {
좋습니다!! 👍👍👍👍

2022-09-12 04:56 UTC, nailseong commented on tomcat/src/main/java/org/apache/coyote/http/request/RequestHeader.java
> +        while (!"".equals((header = bufferedReader.readLine()))) {
오!!!! 좋네요!! `Cookie` 분기처리를 어떻게 해야하나 고민이었는데 좋아요!! 아스피 짱 👍👍👍

2022-09-12 04:58 UTC, nailseong commented
안녕하세요 아스피~!! 추석 연휴 잘 쉬고계신가요?!
아스피의 좋은 피드백 덕분에 코드가 많이 개선되었어요. 감사합니다 😋😋😋
이번에 남겨주신 코멘트 반영했습니다. 확인 부탁드려요~!!

2022-09-13 06:42 UTC, shindong96 approved these changes
안녕하세요 릭!! 아스핍니당 :)
이번 미션 너무 고생하셨습니다. 릭의 코드를 리뷰하면서 재밌고 신기했네요ㅎㅎ

제 피드백이 도움이 되셨다니 다행이에요ㅎㅎ 사실 릭의 코드를 보고 또 리팩토링 해나가는 걸 보면서 저에게도 더 큰 도움이 되었습니다! 👍 
이번 미션에서 피드백을 받으면서도 피드백을 하면서도 느끼는 바가 많네요...덕분이에요ㅎㅎ

너무 고생하셨고 다음에 뵐게요! 감사했습니당 🥇

2022-09-13 06:42 UTC, shindong96 commented on tomcat/src/main/java/org/apache/coyote/http/HttpStatusCode.java
> +        return statusCode + " " + message;
[톰캣 응답 HTTP 버젼 정보](https://tomcat.apache.org/tomcat-5.5-doc/config/http.html#HTTP/1.1_and_HTTP/1.0_Support)
릭! 제가 받은 피드백 중에 공유해드릴게 있네요! 
```
위의 글을 읽어보면, 응답은 항상 요청과 같은 HTTP 버전을 사용하지 않아도 됩니다. 서버가 처리할 수 있는 HTTP 버전 중 가장 높은 버전을 보낸다고 하네요. 아스피가 만들고 있는 톰캣 서버는 HTTP/1.1을 처리할 수 있는 것 같습니다. (RFC-2616을 참고 하고 있으니깐요)
그렇다면 응답 버전을 보낼 때 request의 프로토콜 버전이 아닌 서버에서 처리할 수 있는 HTTP/1.1을 보내는 것이 좋겠네요.
```
릭이 제 피드백을 반영해주셨는데ㅜㅜ오히려 혼란을 드렸네요
글 한번 읽어보시고 다시 생각해보시면 좋을거 같아요!!

2022-09-13 06:42 UTC, shindong96 commented on tomcat/src/main/java/org/apache/coyote/http/request/HttpRequest.java
> +    private static final int METHOD = 0;
개인적으로 `METHOD`보다 인덱스임을 나타내주면 더 좋을 거 같아요! `METHOD_INDEX`같은 식의 상수명은 어떨까요?
릭이 한번 생각해보시고 반영여부 정해주시면 좋을 거 같아요!!

2022-09-13 06:43 UTC, merged