[톰캣 구현하기 - 2, 3단계] 토닉(최우석) 미션 제출합니다.
woowacourse/jwp-dashboard-http pull request #238
Opened 2022-09-07 16:10 UTC by tonic523

안녕하세요 티키!
2, 3단계 미션 리뷰도 잘 부탁드립니다 😄

생각보다 구현이 늦어져서 뒤늦게 PR 보내게 됐네요 ㅠㅠ
시간에 쫓기게 되어 하다보니 테스트도 구현하지 못한 부분이 있고 신경쓰지 못한 부분이 있습니다.. 다음 구현 때 보다 깔끔하게 수정하도록 하겠습니다!

2022-09-11 12:51 UTC, yh20studio requested changes
안녕하세요 토닉!
추석 잘 보내고 계신가요 ㅎㅎ 시간이 부족했지만, 단계를 거쳐가면서 좋은 코드가 되고 있는 거 같아 좋아보이네요! 이번엔 화요일까지 최종 머지로 아직 시간이 남아서,, 혹시 급하게 처리했던 부분 있으셨다면 해결하시고 더불어 제가 남긴 리뷰도 한번 생각해보셨으면 좋겠습니다!!

추가적으로 남겨주신 코멘트에 대한 답드립니다!

`현재 모든 응답을 리다이렉트 또는 정적페이지를 반환하도록 구현
요구사항에 리다이렉트 하도록 작성되어 있어 이렇게 구현했는데 상태코드와 함께 정적페이지를 반환하는 방법과 아직 고민 중 입니다. 티키는 어떤 방법으로 구현하셨나요?`
- 저는 정적 페이지를 반환하도록 구현했습니다! 그 이유는 리다이렉트되면, 브라우저에서 해당 요청을 인지하고 다시 요청을 해야한다고 생각합니다. 그리고 에러페이지는 리다이렉트에 대한 요청으로 날라가게 되겠죠... 그렇기 보다는 현재의 요청에서 직접 에러 사항이 나가는 것이 맞다고 생각했습니다!

2022-09-11 12:51 UTC, yh20studio commented on tomcat/src/main/java/nextstep/jwp/controller/Controller.java
> +}
해당 메서드들이 전부 오버라이딩 되어있어서 내부에 로직이 필요한가 싶습니다..!
그렇게되면 `Controller`를 굳이 추상 클래스가 아닌 인터페이스로 선언하는 건 어떨까요?

2022-09-11 12:51 UTC, yh20studio commented on tomcat/src/main/java/org/apache/coyote/http11/HandlerMapping.java
> +    STATIC("static", new StaticController());
현재 `http://localhost:8080` 루트로 접속하면 404가 나오네요.. 해당 경로도 hello world로 응답이 되어야 할 거 같아요!

2022-09-11 12:51 UTC, yh20studio commented on tomcat/src/main/java/nextstep/jwp/controller/LoginController.java
> +    }
redirect 하는 로직이 LoginController 에서도 사용되고, RegisterController에서도 사용되는 것으로 보입니다!
해당 로직을 이렇게 controller 마다 따로 두기보다는 httpResponse 내부에 두는 것은 어떨까요?

2022-09-11 12:51 UTC, yh20studio commented on tomcat/src/main/java/org/apache/coyote/http11/request/Body.java
> +        HashMap<String, String> applicationForm = new HashMap<>();
선언에서는 HashMap보다는 Map을 사용하는 것이 어떨까요?

2022-09-11 12:51 UTC, yh20studio commented on tomcat/src/main/java/nextstep/jwp/controller/RegisterController.java
> +            response.setHeader("Location", "/400.html");
토닉은 에러페이지를 클라이언트에게 전달할 때
400 코드와 400.html 바디를 보내는 것이아닌, 302로 리다이렉션 한 이유가 있을까요?

2022-09-11 12:51 UTC, yh20studio commented on tomcat/src/main/java/org/apache/catalina/connector/Connector.java
> +        executorService.execute(() -> new Http11Processor(connection).run());
쓰레드 풀을 잘 처리해주셨네요!

2022-09-11 12:51 UTC, yh20studio commented on tomcat/src/main/java/nextstep/jwp/controller/StaticController.java
> +        response.setHeader("Content-Length", body.getBytes().length);
Header들도 Enum으로 선언해서 관리해보는 건 어떨까요??

2022-09-11 12:51 UTC, yh20studio commented on tomcat/src/main/java/org/apache/coyote/http11/ContentType.java
>      JAVASCRIPT("application/js", ".js"),
js의 content type을 한번 더 확인해보면 좋을 거 같아요!
https://developer.mozilla.org/ko/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types

2022-09-11 12:51 UTC, yh20studio commented on tomcat/src/main/java/org/apache/coyote/http11/MethodMapping.java
> +        HttpResponse response = HttpResponse.ok();
여기 부분에서 빈 값을 생성하는 의미가 더 좋을 거 같아요..!
status code를 OK로 선언하고 그 뒷 로직에서 사용되지 않은 거 같네요

2022-09-11 12:51 UTC, yh20studio commented on tomcat/src/main/java/org/apache/coyote/http11/request/HttpCookie.java
> +        HashMap<String, String> values = new HashMap<>();
여기도 마찬가지 입니다! 선언에서는 HashMap보다는 Map을 사용하는 것이 어떨까요?

2022-09-11 12:51 UTC, yh20studio commented on tomcat/src/main/java/org/apache/coyote/http11/request/HttpRequest.java
> +        }
👍 👍 👍 👍 👍 👍

2022-09-11 12:51 UTC, yh20studio commented on tomcat/src/main/java/org/apache/coyote/http11/request/HttpMethod.java
> +}
Enum으로 관리하여 훨씬 더 좋아졌네요! 👍

2022-09-11 12:51 UTC, yh20studio commented on tomcat/src/main/java/org/apache/coyote/http11/request/HttpRequest.java
> +        int contentLength = Integer.parseInt(header.get("Content-Length").trim());
Java 11 에서 문자열에서 공백을 제거할 때 trim을 사용하는데 혹시 strip도 알아보시면 좋을 것 같습니다!
https://stackoverflow.com/questions/51266582/difference-between-string-trim-and-strip-methods-in-java-11

2022-09-11 12:51 UTC, yh20studio commented on tomcat/src/main/java/org/apache/coyote/http11/response/HttpResponse.java
> +        return HTTP_VERSION + SPACE + status.code() + SPACE + status + SPACE;
현재 HttpStatus Enum 값으로 사용하고 있는 것으로 보입니다! 이때 출력형식을 설정할 때 status의 기본 정의된 toString()을 사용해서 Enum의 name() 값을 이용하는 것으로 보입니다

하지만, 개인적으로는 Enum의 name() 값을 그대로 사용해서, 현재 Enum의 name으로 사용되는 컨벤션인 대문자에 의존하지 않고,  필드를 한개 만들어서 사용하는 건 어떨까? 싶습니다

2022-09-11 12:51 UTC, yh20studio commented on tomcat/src/test/java/study/ExecutorsTest.java
> +}
꼼꼼한 테스트 좋네요!

2022-09-11 12:59 UTC, yh20studio commented on tomcat/src/main/java/nextstep/jwp/controller/LoginController.java
>      }
현재 `http://localhost:8080/login`로 접근하면 NPE가 발생합니다!

2022-09-12 08:22 UTC, tonic523 commented on tomcat/src/main/java/nextstep/jwp/controller/Controller.java
> +}
현재는 전부 오버라이딩이 되있어서 인터페이스로 선언해도 괜찮을 것 같네요
두 방법의 차이점은 `구현체에서 직접 예외처리를 한다` 와` 추상 클래스에서 예외처리를 통일화 시키고 사용하는 메서드인 경우 오버라이딩을 한다` 인 것 같네요. 이런 차이점이라면 저는 추상 클래스로 통일화 시키는게 좋다고 생각이 드는데 다른 이유나 의견이 있을까요?

2022-09-12 08:27 UTC, tonic523 commented on tomcat/src/main/java/org/apache/coyote/http11/HandlerMapping.java
> +    STATIC("static", new StaticController());
넵 hello world를 body에 응답하도록 수정하겠습니다!

2022-09-12 09:33 UTC, tonic523 commented on tomcat/src/main/java/nextstep/jwp/controller/LoginController.java
> +    }
네 컨트롤러에서 로직을 수행하면서 Response를 어떻게 만들어서 응답을 할까 고민을 많이 하다보니 따로 빌더 클래스를 구현해봤습니다. 구현하다보니 이 구조가 특별하게 좋다고 느껴지진 않네요.. redirect를 만들 때 중복 로직은 없앨 수 있었는데 response를 다루는 로직은 좀 더 고민이 필요할 것 같아요 ㅠㅠ 현재 구조에서 안좋은 점들이 보인다면 피드백 부탁드립니다!

2022-09-12 09:34 UTC, tonic523 commented on tomcat/src/main/java/org/apache/coyote/http11/request/Body.java
> +        HashMap<String, String> applicationForm = new HashMap<>();
네 반영하겠습니다!

2022-09-12 09:43 UTC, tonic523 commented on tomcat/src/main/java/nextstep/jwp/controller/RegisterController.java
> +            response.setHeader("Location", "/400.html");
현재 미션의 구조 상 응답 코드만 반환할 수 없는 구조이고 WAS에서 요청마다 직접 정적 페이지를 응답해주어야 해요. 정적 페이지에 상태 코드에 맞는 페이지가 구현되어 있기 때문에 redirect와 정적 리소스로 응답 코드를 대체하는 느낌으로 구현했어요. 결국 클라이언트에게 서버가 어떤 응답을 알려줘야 하는건 페이지라고 생각했습니다.
그래도 redirect 후에 무조건 200 상태코드를 응답하는 부분이 어색해보이네요 혹시 다른 이유나 의견있을까요?

2022-09-12 10:10 UTC, tonic523 commented on tomcat/src/main/java/nextstep/jwp/controller/LoginController.java
>      }
sessionManager에서 session을 찾지 못했을 때 null을 반환해서 에러가 발생했네요
수정하겠습니다!

2022-09-12 15:37 UTC, yh20studio commented
피드백 반영하느라 고생하셨습니다!
HttpResponseBuilder로 response를 만드는 객체를 따로 분리해서 인자로 전달하는 구조가 괜찮을까?
모든 요청에 redirect로 응답하는게 맞나?
method 분기 처리를 AbstractController에 구현 vs 각 컨트롤러마다의 service() 메서드를 오버라이딩하여 구현

2022-09-12 15:42 UTC, yh20studio commented on tomcat/src/main/java/nextstep/jwp/controller/Controller.java
> +}
구현상 큰 차이는 없다라고 느낍니다.
그런데 단 개인적으로 느끼기에는 예외처리를 하는 부분과 역할이, 
`구현체에서 오버라이딩 되지 않은 메서드들은 추상 클래스에서 보아야하는 가?` vs `각 구현체 클래스에서 직접 볼 수 있는가?`
의 차이라고 생각이 듭니다.

그럼에도 불구하고 정말 똑같은 로직들이 반복이 되고, 각 구현체 클래스마다 따로 구현해야할 필요가 없다면, 추상 클래스에서 모두 다 구현을 하고 final 키워드를 붙여서 하위 클래스에서 오버라이딩하지 못하도록 막을 수도 있겠네요

개인적으로는 이렇게 이용하는 편이라서 토닉의 의견이 궁금했었습니다!

2022-09-12 15:52 UTC, yh20studio commented
피드백 반영하느라 고생많으셨습니다!!
물어봐주신 부분에서 제 의견을 남겨볼까합니다 ㅎㅎ

`HttpResponseBuilder로 response를 만드는 객체를 따로 분리해서 인자로 전달하는 구조가 괜찮을까?`
- 저도 처음에는 Builder를 만들어서 response를 구현했었습니다...! 그런데 중간에 마음이 변해서 빌더 패턴을 걷어내고 set을 이용해서 값을 채워 넣어주는 방식을 선택했습니다. 
- set을 이용해서 값을 채워넣어주면, redirect에 대한 반복을 줄일 수 가 없게되는데... 이러한 경우는 response에 redirect("리다이렉트할 url") 과 같은 방식을 사용해서 이용했습니다.
    ``` java
    private void redirect(HttpResponse response, String value) {
            response.setStatus(HttpStatus.FOUND);
            response.setHeader("Location", value);
        }
    ```
    이 코드와 같은 로직을 각 controller의 private 메서드로 두는 것이 아닌 response의 public 메서드로 놓고 다양한 컨트롤러에서 사용할 수 있도록 했습니다
- 해당 이유는 다음 링크의 제 답변을 살펴보시면 좋을 거 같습니다 [링크](https://github.com/woowacourse/jwp-dashboard-http/pull/290#discussion_r968000963)

`모든 요청에 redirect로 응답하는게 맞나?`
- 저는 에러가 나면, 정적 페이지를 반환하도록 구현했습니다! 그 이유는 리다이렉트되면, 브라우저에서 해당 요청을 인지하고 다시 요청을 해야한다고 생각합니다. 그리고 에러페이지는 리다이렉트에 대한 요청으로 날라가게 되겠죠... 그렇기 보다는 현재의 요청에서 직접 에러 사항이 나가는 것이 맞다고 생각했습니다!

`method 분기 처리를 AbstractController에 구현 vs 각 컨트롤러마다의 service() 메서드를 오버라이딩하여 구현`
- [코멘트 링크](https://github.com/woowacourse/jwp-dashboard-http/pull/238#discussion_r968578551) 여기 코멘트한 부분과 이야기가 비슷한 거 같습니다. 여기서 service()에 대한 구현은 모든 컨트롤러마다 겹칠것으로 개인적으로는 AbstractController에서 구현을 모두 할 것 같습니다. 이후에 doGet(), doPost()의 경우에는 모두 각 컨트롤러마다 오버라이딩을 할 것 같네요

추가적으로 중간에 가려진 코멘트에 대해서는 따로 답글이 없어서 확인을 못하셨는지 확인차 물어봅니다...!
더 궁굼하거나 의견나누고 싶으신 점 있으시다면 DM 주시고, 화요일에 추가적인 변경사항 없다면 머지하겠습니다!

2022-09-13 06:58 UTC, merged