[톰캣 구현하기 - 2, 3, 4단계] 이프(송인봉) 미션 제출합니다.
woowacourse/jwp-dashboard-http pull request #246
Opened 2022-09-08 04:21 UTC by sinb57

안녕하세요 알린!! 저번에 말씀드린대로 시간상 2,3,4단계를 한번에 진행했어요.

Controller 분기 처리를 리팩토링하는 과정에서 RequestMapping과 RequestParams 어노테이션을 구현했었는데 (001fa5d9fcac14770a8420251d9528e2b98fe8e8)
다음 미션 MVC를 보니까 해당 내용을 미리 구현하면 미션이 꼬이게 되더라고요ㅠ
그래서 3단계 요구사항에 맞춰 Controller 추상화작업으로 변경했습니다,,

- [x] 로그인/회원가입 기능 구현
- [x] Controller 추상화
- [x] 세션 구현
- [x] 스레드풀 적용

2022-09-11 10:24 UTC, OzRagwort requested changes
안녕하세요 이프 전체적으로 잘 구현해주셨고 많이 배우게되네요 !

요구사항은 전체적으로 만족하는 것 같은데 버그가 하나 있는 것 같아요!

서버에 저장되지 않은 JSESSIONID을 브라우저가 가진 상태로 로그인 시도를 하면 페이지가 제대로 로딩되지 않는 것 같아요!

버그 재현할 때 참고하시라구 상황 남겨볼게요!
1. 로그인을 한다.
2. 브라우저에 JSESSIONID이 저장된다. 
3. 로그인이 잘 된다.
4. 서버를 껐다 켠다. 
5. 저장된 세션이 초기화된다.
6. 새로 로그인 페이지로 간다.
7. 브라우저는 가진 JSESSIONID을 헤더에 담아 보낸다
8. 서버는 제대로 페이지를 반환하지 못한다.

없는 JSESSIONID가 왔을 때 여러가지 대응방법이 있을 것 같은데 이프가 생각하는대로 수정해주시면 좋을 것 같아요!

2022-09-11 10:24 UTC, OzRagwort commented on tomcat/src/main/java/org/apache/coyote/http11/request/RequestReader.java
> +        final RequestCookie cookies = RequestCookie.parse(header);
혹시 이렇게 `HttpRequest` 에 따로 cookie를 가지고 있는 이유가 있을까요?

헤더는 필요할 때 호출해서 사용하면 될텐데 쿠키만 따로 빼서 미리 저장해두는 이유가 궁금해요!

쿠키를 따로 저장하는 기준이 있다면 그 기준에 맞는 다른 헤더가 더 생긴다면 또 `HttpRequest`의 멤버로 추가해야 할 것 같아서요

2022-09-11 10:24 UTC, OzRagwort commented on tomcat/src/main/java/org/apache/coyote/http11/response/ContentType.java
> +    SVG("image/svg+xml", "svg"),
어떤 데이터냐에 따라 보낼 content-type이 달라져야할텐데 잘 구현해주셨네요! 저는 if문 지옥에 빠져버렸었는데 말이죠 ㅠㅠ

직접 바퀴를 재창조해보는 시도를 해보신 것 같아서 좋았어요! 

지금 구현해주신 것과 비슷한 동작을 하는 이미 있는 바퀴도 있더라구요! 혹시 관심있으면 찾아보셔도 좋을 것 같아요! 

힌트는 MIME 형식 입니다!

<img width="563" alt="image" src="https://user-images.githubusercontent.com/32123302/189522414-0d61ff35-ac76-4ee7-9080-5defaf43eb70.png">

2022-09-11 13:53 UTC, sinb57 commented on tomcat/src/main/java/org/apache/coyote/http11/request/HttpRequest.java
> +        SessionManager.add( session);
앜ㅋㅋㅋㅋㅋ 집나간 스페이스 되찾아주었습니다~

2022-09-11 13:59 UTC, sinb57 commented on tomcat/src/main/java/org/apache/coyote/http11/response/ContentType.java
> +    SVG("image/svg+xml", "svg"),
오호 좋습니다~!! Files.probeContentType 를 쓰면 되는군요!!

2022-09-11 14:39 UTC, sinb57 commented on tomcat/src/main/java/nextstep/jwp/controller/LoginController.java
> +            return fail(HttpStatus.UNAUTHORIZED, Page.UNAUTHORIZED);
AbstractController의 `success` `redirect` `fail`은 자식 클래스에서 공통적으로 사용되는 형태를 중복 제거하기 위해 선언된 메서드들이에요!! 따라서 setCookie와 같이 커스텀의 필요가 있다면 `LoginController`와 같이 해당 위치에서 별도의 작업을 취하는 형태를 취할 듯해요! 다만 이러한 행위 또한 중복을 일으킨다면 AbstractController와 같이 최상위 부모 클래스에서, 혹은 AbstractController와 자식 클래스 사이에 또다른 부모 클래스를 두어 중복을 제거할 수도 있겠네요. 그게 아니라면 HttpResponse를 조합하는 행위를 따로 모아둔 클래스를 만들 수도 있어 보여요.(해당 클래스에는 HttpResponse#ok와 같은 메소드도 위치하겠네요)

2022-09-11 14:43 UTC, sinb57 commented on tomcat/src/main/java/org/apache/coyote/http11/request/HttpRequest.java
> +        SessionManager.add( session);
앜ㅋㅋㅋㅋㅋ 집나간 스페이스 찾아줘서 고마워요~

2022-09-11 14:46 UTC, sinb57 commented on tomcat/src/main/java/org/apache/coyote/http11/request/HttpRequest.java
> +    public Session generateSession() {
동의합니다!! 부메서드를 주메서드 아래에 배치하는 편인데, 해당 메서드는 리팩토링과정에서 미스했네요!! 놓치기 쉬운데 지적해주셔서 감사해요!! 단순히 스타일 견해더라도 코드를 읽기 힘든 부분이 있으면 적극적으로 지적해주세요~!! 최대한 가독성 좋은 코드를 만들고 싶거든요ㅎㅎ

2022-09-11 14:54 UTC, sinb57 commented on tomcat/src/main/java/org/apache/coyote/http11/request/HttpRequest.java
> +    public Session generateSession(final Map<String, Object> attributes) {
미션의 힌트에 적혀있는 코드를 기반으로 작성하다보니 현재의 구조를 어거지로 작성되었네요ㅎ!!
고민해보고 수정하겠습니다!!

2022-09-11 15:00 UTC, sinb57 commented on tomcat/src/main/java/org/apache/coyote/http11/request/RequestReader.java
> +        final RequestCookie cookies = RequestCookie.parse(header);
`RequestCookie`가 지닌 `JSESSIONID` `Cookie`와 같은 매직넘버와 더불어 세션ID를 추출하는 로직 등 이러한 행위를 하나로 응집시키고자 `RequestHeader` 내부가 아닌 별도의 클래스를 생성했고, 그러다보니 `RequestHeader`와 `RequestCookie`가 양립하는 상황이 이뤄졌는데요. 위의 코멘트와 더불어 세션기능에 대한 구조가 명확히 확립되지 않았네요ㅠ 구조 파악이 어려운 것도 사실이구요,, 고치도록 하겠습니다~

2022-09-11 15:27 UTC, sinb57 commented on tomcat/src/main/java/org/apache/coyote/http11/response/ContentType.java
> +    SVG("image/svg+xml", "svg"),
어라라.. `Files.probeContentType`은 js파일에 대한 확장자를 못읽어오고, `URLConnection.guessContentTypeFromName`는 js를 비롯한 css파일에 대해서 또한 확장자를 읽어오지 못하네요ㅠㅜ 슬프지만 기존의 ContentType을 활용할게요ㅠㅠ

2022-09-13 01:40 UTC, OzRagwort requested changes
안녕하세요 이프 ! 

꼼꼼하게 잘 수정해주셔서 사실 머지해도 될 것 같았는데 시간이 조금 남아서 간단한 것들 조금 남겨봤어요! 

필수 요구사항은 아니지만 시간이 남으신다면 없는 페이지를 요청할 때 404페이지를 반환해보면 어떨까요? 
리소스에 404.html이 이미 있어서 한번 시도해볼만 할 것 같아요!

이프 짱 이프 짱짱이에요 파이팅! 👍

2022-09-13 01:58 UTC, sinb57 commented on tomcat/src/test/java/org/apache/coyote/http11/request/UriTest.java
> +class UriTest {
아 그렇네요 (GET 방식) Uri로부터 파라미터를 가져오는 로직에서 (POST 방식) 바디로부터 파라미터를 가져오는 로직으로 수정하면서 해당 부분을 제거하지 않았네요!! 지적 감사합니다~ 사용하지 않으니 제거할게요!!

2022-09-13 02:50 UTC, sinb57 commented on tomcat/src/main/java/org/apache/coyote/http11/request/RequestCookie.java
> +        }
`Params` 내부에서 처리되는 예외처리를 유지한채 로직을 작성하다보니 `RequestCookie#existSession` 로직이 난잡해졌네요!! 가장 Low한 단계인 `Params` 내부에서 예외처리하는 것이 오히려 중복을 제거하는 방향이라 생각했는데, 오히려 이러한 판단 때문에 `RequestCookie#existSession` 로직이 복잡한 것에 더불어 `LoginController`와 `RegisterController`에서 디미터법칙을 어기고 있었네요!! 현재는 `Params#find`가 Optional을 반환하도록 함으로써 세션 조회 로직을 전반적으로 리팩토링했습니다!!

2022-09-13 02:51 UTC, sinb57 commented
404 의견 반영!! 코멘트 의견 반영!! 알린~ 좋은 지적 감사합니다!!

2022-09-13 03:10 UTC, OzRagwort approved these changes
이프 미션 수고하셨습니다. 👍 

많이 배워가요!

2022-09-13 03:10 UTC, merged