[톰캣 구현하기 - 2, 3,4단계] 쿤(홍동건) 미션 제출합니다.
woowacourse/jwp-dashboard-http pull request #251
Opened 2022-09-08 05:47 UTC by Hongdonggeon

인녕하세요 포키!!
포키가 1단계 때 주신 피드백 반영하고 전반적으로 구조에 대해 다시 생각해보았어요!
구조를 다시 설계하고 미션을 진행하니 회원가입이나, 쿠키, 세션 같은 새로운 요구사항이 추가되어도 변경이 frontServlet이나 connector 까지 일어나지 않았던 것 같습니다!!
전반적인 구조에 대한 그림은 그려서 첨부해놓겠습니다
감사합니다!!

2022-09-09 14:59 UTC, YJGwon requested changes
쿤 안녕하세요~! 4단계까지 진행하시느라 수고 많으셨습니다. 구조를 diagram과 함께 설명해주셔서 흐름을 이해하기가 편했네요 👍

전반적으로 요구사항 잘 구현해주셨는데요, 코멘트에도 남겼듯 두 가지만 확인 부탁드릴게요.
- 로그인 실패 시 401.html이 아닌 404.html로 redirect 되고 있는 점
- 서버에선 삭제되었는데, 브라우저에만 저장되어있는 존재하지 않는 session id를 가진 요청이 올 수 있는 점

추석 연휴 잘 보내시구요, 의논하고 싶거나 이해되지 않는 comment가 있다면 언제든지 편한 방법으로 연락 주세요 😸

2022-09-09 14:59 UTC, YJGwon commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +            final FrontServlet servlet = new FrontServlet();
매 요청이 들어올 때 마다 `FrontServlet`의 instance를 새로 만들고 있네요 👀

2022-09-09 14:59 UTC, YJGwon commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +        return HttpRequest.from(line, values, bufferedReader);
`line`과 `values`라는 변수명은 다소 모호하게 느껴질 수 있을 것 같아요..! [Http Request Message를 구성하는 각 요소의 명칭](https://datatracker.ietf.org/doc/html/rfc7230#section-3)을 따라 변수명을 바꾸는건 어떠신가요?

2022-09-09 14:59 UTC, YJGwon commented on tomcat/src/main/java/org/apache/coyote/http11/request/HttpHeaders.java
> +        StringBuilder sb = new StringBuilder();
`final` 키워드를 추가하면 좋을 것 같아요 👀

2022-09-09 14:59 UTC, YJGwon commented on tomcat/src/main/java/org/apache/coyote/http11/request/HttpRequest.java
> +    public static HttpRequest from(final String firstLine, final List<String> values, final BufferedReader reader)
이 method의 parameter들도 rename하면 좋을 것 같네요!

2022-09-09 14:59 UTC, YJGwon commented on tomcat/src/main/java/org/apache/coyote/http11/request/HttpRequest.java
> +        final HttpHeaders httpHeaders = toHttpHeaders(values);
`RequestLine`처럼, `HttpHeaders`도 정적 팩토리 메서드에서 헤더 문자열 parsing하는건 어떠신가요?

2022-09-09 14:59 UTC, YJGwon commented on tomcat/src/main/java/org/apache/coyote/http11/request/HttpRequest.java
> +        final Map<String, String> body = new HashMap<>(Collections.EMPTY_MAP);
지금 요구사항에선 body가 항상 query string이지만, 사실 실제로는 그렇지 않을 경우도 있을 것 같아요. 요구사항 구현에 포함되는 내용은 아니니 고려만 해봐주세요 ㅎㅎ

2022-09-09 14:59 UTC, YJGwon commented on tomcat/src/main/java/org/apache/coyote/http11/request/HttpRequest.java
> +    public Session getSession() {
`getSession()`에서 매번 새로운 session을 생성하는데, 호출하는 쪽에서 이를 모르고 이미 session id를 발급받은 client의 request에 대해서도 `getSession()`을 호출해버릴 수 있지 않을까 하는 우려가 드네요 😟

2022-09-09 14:59 UTC, YJGwon commented on tomcat/src/main/java/org/apache/coyote/http11/servlet/FrontServlet.java
> +public class FrontServlet {
이건 그냥 궁금해서 여쭤보는건데요, 미션 페이지에서는 요청과 controller를 mapping해주는 역할을 하는 class를 `RequestMapping`으로 만들라고 나와있었는데 `FrontServlet`이라는 네이밍을 하신 이유가 궁금합니다.

2022-09-09 14:59 UTC, YJGwon commented on tomcat/src/main/java/org/apache/coyote/http11/response/HttpResponse.java
> +        body += value;
body를 할당하지 않고 `+=`으로 더해주시는 이유가 있을까요? `setBody()`라는 이름만 보면 할당해준다고 생각하게 될 것 같아요.

2022-09-09 14:59 UTC, YJGwon commented on tomcat/src/test/java/nextstep/jwp/controller/LoginControllerTest.java
> +    @DisplayName("로그인 기능을 실패하는 경우에 상태코드 302와 404.html 경로를 헤더로 보낸다.")
```suggestion
    @DisplayName("로그인 기능을 실패하는 경우에 상태코드 302와 401.html 경로를 헤더로 보낸다.")
```

2022-09-09 14:59 UTC, YJGwon commented on tomcat/src/test/java/nextstep/org/apache/coyote/http11/Http11ProcessorTest.java
> +    private static MockedStatic<UUID> uuid;
mockito 활용 👍 배워갑니다!!

2022-09-09 14:59 UTC, YJGwon commented on tomcat/src/test/java/nextstep/org/apache/coyote/http11/Http11ProcessorTest.java
> +    @DisplayName("/register 경로로 get요청을 하면 login.html 페이지를 반환받는다.")
다른 test들도 display name을 추가해주면 좋을 것 같네요 😄

2022-09-09 14:59 UTC, YJGwon commented on tomcat/src/main/java/nextstep/jwp/controller/RegisterController.java
> +        InMemoryUserRepository.save(user);
요구사항에 포함된 부분은 아니지만, 지금은 이미 존재하는 account로도 가입이 되고 있어요. 이에 대해 예외처리가 필요하지 않을까요?
이 부분과 함께 프로그램에서 전반적으로 일어날 수 있는 예외와 그 처리에 대해서도 고민해보면 더 좋을 것 같아요. (optional하다고 생각되는 부분이긴 합니다.)

2022-09-13 03:44 UTC, Hongdonggeon commented on tomcat/src/main/java/nextstep/jwp/controller/LoginController.java
> +        httpResponse.sendRedirect("/404.html");
아 그렇네요.. 401.html 페이지로 리다이렉트하게 변경해주었습니다!

2022-09-13 03:50 UTC, Hongdonggeon commented on tomcat/src/main/java/org/apache/catalina/connector/Connector.java
> +        this(DEFAULT_PORT, DEFAULT_ACCEPT_COUNT, 200);
좋아요 리뷰 반영했습니다!

2022-09-13 03:55 UTC, Hongdonggeon commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +            final FrontServlet servlet = new FrontServlet();
싱글톤 패턴을 이용해서 객체 생성이 한번만 되게 변경했습니다!

2022-09-13 03:56 UTC, Hongdonggeon commented on tomcat/src/main/java/org/apache/coyote/http11/request/HttpHeaders.java
> +        StringBuilder sb = new StringBuilder();
리뷰 반영했습니다! 꼼꼼한 리뷰 감사합니다 :)

2022-09-13 04:18 UTC, Hongdonggeon commented on tomcat/src/main/java/org/apache/coyote/http11/servlet/FrontServlet.java
> +public class FrontServlet {
RequestMapping은 요청을 처리할 컨트롤러 객체를 맵핑하는 것 이외에도 정적 파일의 정보를 body에 써주는 일도 하고 있고 컨트롤러로 등록되지 않은 `/`경로 처리도 해주고 있기 때문에 스프링에서 DispatcherServlet과 같은 역할을 하고 있다고 생각했어요! DispatcherServlet이 Spring에서 FrontController이기 때문에 FrontServlet이라고 네이밍했습니다

2022-09-13 04:26 UTC, Hongdonggeon commented on tomcat/src/main/java/org/apache/coyote/http11/response/HttpResponse.java
> +        body += value;
http 응답에 body에 빈문자열이 들어갈 수 있으니 body에 빈문자열을 생성자에서 초기화해주었어요. 메서드명이 setBody여서 할당한다고 생각할 수 있을 것 같아서 메서드명 변경했습니다!

2022-09-13 04:35 UTC, Hongdonggeon commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +        return HttpRequest.from(line, values, bufferedReader);
좋아요! 첫줄은 startLine으로 변경하였고 header 부분은 headerLines로 변경하였습니다

2022-09-13 04:49 UTC, Hongdonggeon commented on tomcat/src/main/java/org/apache/coyote/http11/request/HttpRequest.java
> +        final HttpHeaders httpHeaders = toHttpHeaders(values);
좋은 것 같아요! 비어있는 httpHeaders도 만들어야하는 경우가 있어서 정적팩토리메서드로 이름을 다르게 주었습니다!

2022-09-13 08:28 UTC, Hongdonggeon commented on tomcat/src/main/java/nextstep/jwp/controller/LoginController.java
> +        if (session.isPresent()) {
브라우저에는 JSessionId가 남아있고 서버에서는 그 SessionId에 해당하는 세션이 존재하지 않는 경우에 새로 로그인 페이지를 조회할 수 있게 했습니다!

2022-09-13 08:29 UTC, Hongdonggeon commented on tomcat/src/main/java/org/apache/coyote/http11/request/HttpRequest.java
> +    public Session getSession() {
getSession 메서드 과정에 대해 변경했습니다. 해당하는 쿠키의 값에 해당하는 세션이 존재하는 경우에는 세션을 반환해주고, 세션이 존재하지 않으면 새롭게 세션을 생성하는 방식으로 변경했습니다!

2022-09-13 09:12 UTC, YJGwon approved these changes
이제 요구사항은 모두 충족된 것 같네요. 쿤과 함께 이번 미션에 대해 고민해볼 수 있어서 즐거웠어요! 많이 배웠습니다 👍 추가적으로 이야기해보고 싶은 부분에 대해 comment 몇개 남겼어요. 미션은 이만 머지하도록 하겠습니다. 이번 코멘트에 대해서는 편하게 생각해주세요~ 수고많으셨어요! 다음미션도 화이팅 💪

2022-09-13 09:12 UTC, YJGwon commented on tomcat/src/main/java/org/apache/coyote/http11/response/HttpResponse.java
> +        body += value;
body가 없을 경우를 생각하신거라고 이해하면 될까요?? 만약 text message 형태로 변환하는 과정에서 생기는 문제를 우려하신 거라면 변환이 이루어지는 시점에 해당 부분에 대한 처리가 이루어질 수 있을 것 같아요. 실제로 `addBody()` 로직이 쓰이는 모습을 보면  body를 append해주는 경우는 없고 set해주는 용도로 쓰이고 있으니, 해당 메서드가 용도에 맞게 적절하게 만들어진 method일지 고려해보면 좋을 듯 합니다!

2022-09-13 09:12 UTC, YJGwon commented on tomcat/src/main/java/org/apache/coyote/http11/servlet/FrontServlet.java
> +public class FrontServlet {
오홍 재밌네요..! 역시 spring박사 쿤박사

2022-09-13 09:12 UTC, YJGwon commented on tomcat/src/main/java/nextstep/jwp/controller/Controller.java
> +        processPost(httpRequest, httpResponse);
(optional) 저희가 요구사항에서 사용하는 api는 method가 get, post로 한정되어있지만 사실 요청 자체는 다른 method로 들어올 수 있잖아요!  preflight에 대한 처리를 통해 적절한 options 헤더를 주거나 또는 controller쪽에서 지원하지 않는 method에 대해 예외 처리 추가해보면 더 좋을 것 같아요.

2022-09-13 09:12 UTC, YJGwon commented on tomcat/src/main/java/org/apache/catalina/connector/Connector.java
> +        executorService.submit(this);
(optional)`submit()`과 `execute()`의 차이는 뭘까요?

2022-09-13 09:12 UTC, YJGwon commented on tomcat/src/main/java/org/apache/coyote/http11/request/HttpHeaders.java
> +            final String[] header = value.split(": ");
(optional) 이런 연결자들은 http 규약으로 정해져있는 값들이니 Enum을 통해 선언적으로 표현해주는 것도 좋을 듯 합니다.

2022-09-13 09:12 UTC, merged