[톰캣 구현하기 - 2, 3,4단계] 승팡(김승래) 미션 제출합니다.
woowacourse/jwp-dashboard-http pull request #253
Opened 2022-09-08 06:01 UTC by Seungpang

안녕하세요! 후디
저번 미션에 대한 코멘트에 대한 답변도 달아놨습니다. [이전 미션](https://github.com/woowacourse/jwp-dashboard-http/pull/184)
감기 몸살로 컨디션이 제대로 돌아오지 못해서 미션이 많이 힘들었습니다.
패키지 구조를 설정하는 것도 어렵고 겨우겨우 요구사항에 부합한 코드를 작성한 것 같습니다 ㅠㅠ
테스트 코드를 전혀 신경쓰지 못했네요! 추석기간때 리팩토링을 열심히 해보겠습니다.

리뷰 잘 부탁드리고 즐거운 추석 연휴 보내세요!

2022-09-09 02:27 UTC, devHudi requested changes
안녕하세요, 승팡! 몸이 안좋으신데도 불구하고 미션 잘 해주신 것 같아요 🥹
몇 가지 수정하면 좋아보이는 부분에 코멘트를 남겨두었어요.

또한, 기능 요구사항 중 하나가 구현이 안된 것 같아요.

> 그리고 로그인된 상태에서 /login 페이지에 HTTP GET method로 접근하면 이미 로그인한 상태니 index.html 페이지로 리다이렉트 처리한다.

요구사항 중 로그인 된 상태에서 `/login` 페이지에 접근하면, `/index.html` 으로 리다이렉션 해야하는데, 이 기능이 구현되어 있지 않아요.

나머지 내용은 코멘트 참고해주세요. 즐거운 한가위 보내세요 🌕

2022-09-09 02:27 UTC, devHudi commented on tomcat/src/main/java/nextstep/jwp/controller/UserController.java
> +
오타가 있네요! 😄

2022-09-09 02:27 UTC, devHudi commented on tomcat/src/main/java/nextstep/jwp/util/PathUtils.java
> +        if (resource == null) {
쓰레드를 사용하신 이유가 있을까요?

2022-09-09 02:27 UTC, devHudi commented on tomcat/src/main/java/org/apache/coyote/http/HttpHeader.java
> +        headers.put(CONTENT_LENGTH, String.valueOf(responseBody.getBytes(StandardCharsets.UTF_8).length));
`CONTENT_LENGTH` 와 마찬가지로 `"Content-Type"` 도 상수 처리할 수 있을 것 같아요!

2022-09-09 02:27 UTC, devHudi commented on tomcat/src/main/java/org/apache/coyote/http/HttpHeader.java
> +    }
나머지 헤더들도 상수처리 하는 것은 어떨까요? 🙂

2022-09-09 02:27 UTC, devHudi commented on tomcat/src/main/java/org/apache/coyote/http/request/HttpRequest.java
> +        return RequestBody.empty();
Content-Length 를 사용한 Body 추출 👍👍

2022-09-09 02:27 UTC, devHudi commented on tomcat/src/main/java/org/apache/coyote/http/session/Session.java
> +}
세션 객체에 로거를 두신 이유가 있을까요?

2022-09-11 09:40 UTC, Seungpang commented on tomcat/src/main/java/org/apache/coyote/http/response/HttpResponse.java
>      }
그 부분은 고려하지 못했는데 정적팩토리 메서드로 이름을 부여해서 좀더 명확하게 수정할 수 있겠네요!

2022-09-11 09:41 UTC, Seungpang commented on tomcat/src/main/java/nextstep/jwp/controller/UserController.java
> +
마음이 너무 급했나보네요 ㅠ

2022-09-11 09:45 UTC, Seungpang commented on tomcat/src/main/java/nextstep/jwp/util/PathUtils.java
> +        if (resource == null) {
static을 사용하기 위해 스레드를 사용했는데 여러 글들을 참고하다보니 ClassLoader와 ContextClassLoader의 차이점을 명확하게 모르는 이상 사용하기에는 많은 무리가 있는 것 같네요!
일단은 ContextClassLoader를 사용하지 않는걸 권장해서 수정했습니다.

+ 참고 글 (공부하고 있는데 아직 이해못했습니다 ㅠㅠ)
[Find a way out of the ClassLoader maze](https://www.infoworld.com/article/2077344/find-a-way-out-of-the-classloader-maze.html)
[Difference between thread's context class loader and normal classloader](https://stackoverflow.com/questions/1771679/difference-between-threads-context-class-loader-and-normal-classloader)

2022-09-11 10:00 UTC, Seungpang commented on tomcat/src/main/java/org/apache/coyote/http/HttpHeader.java
> +        headers.put(CONTENT_LENGTH, String.valueOf(responseBody.getBytes(StandardCharsets.UTF_8).length));
상수처리 했습니다!

2022-09-11 10:00 UTC, Seungpang commented on tomcat/src/main/java/org/apache/coyote/http/session/Session.java
> +}
개발하는 과정에서 확인차 log를 사용했는데 사용자 정보를 log로 찍는게 위험한거 같아서 제거했습니다.

2022-09-11 10:02 UTC, Seungpang commented
안녕하세요 후디!
승팡입니다 😄 

분명히 개발할때 /login 페이지에 접근하면, /index.html 으로 리다이렉션을 구현했는데
다시보니까 정상적으로 동작하지 않는걸 확인했습니다. JSESSIONID=value 이렇게 들어가야 하는 부분이 JSESSIONID부분에 공백이 하나
추가되는걸 확인했습니다... 그래서 일단 trim으로 처리하긴 했는데 좀더 살펴봐야겠네요!

2022-09-11 12:29 UTC, devHudi approved these changes
안녕하세요, 승팡 😄
수정해주신 추가 커밋 잘 봤어요!
제가 남긴 코멘트 외에는 수정할만한 사항은 보이지 않아서 이만 머지하겠습니다!
Thread와 class loader 에 대한 내용은 알게되시면 저도 알려주세요 ㅎㅎ ㅋㅋㅋ 
추석 연휴인데 고생 많으셨습니다 👍👍👍

2022-09-11 12:29 UTC, merged