[톰캣 구현하기 - 2단계] 알린(장원영) 미션 제출합니다.
woowacourse/jwp-dashboard-http pull request #264
Opened 2022-09-08 07:47 UTC by OzRagwort

안녕하세요 라라. 알린입니다.

시간이 다 되어서 우선 제출을 올리고 부족한 리팩과 3, 4 단계를 해서 push 하겠습니다

제가봐도 아직 부족하고 고칠곳이 많아서 리뷰가 많을 것 같습니다 ㅠㅠ

꾸준하게 수정하고 푸쉬하겠습니다 !..!

2022-09-10 09:37 UTC, sure-why-not requested changes
알린 안녕하세요! 🫡
추석 연휴 잘 보내고 계신가요. ㅎㅎ🍡

미션 진행하시느라 수고 많으셨어요 ㅜㅜ
요구사항 기능 잘 동작하는 것 확인했습니다!
리뷰 몇가지 달아두었으니 확인해주시면 감사하겠습니다 💌
화이팅 ~~~~~~~~ 💪🏻

2022-09-10 09:37 UTC, sure-why-not commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
>      private User getUser(final String account) {
해당 메서드는 파일체인지가 없어서 여기에 리뷰 달게요ㅜ
```
if (account == null || account.isBlank()) {
      return EMPTY_USER;
}
```
여기서 null 체크는 requestBody에서 꺼내온 account가 null 일 수 있기 때문에 체크하는 것일까요??
`isBlank` 든 `null` 이든 InMemoryUserRepository.findByAccount(account) 에서 찾지 못할테니 null을 담은 `Optional`을 반환할 것 같아요!
그래서 제거돼도 되는 로직이라고 생각이 드네요!

2022-09-10 09:37 UTC, sure-why-not commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
>      private User getUser(final String account) {
```
        try {
            return InMemoryUserRepository.findByAccount(account)
                    .orElseThrow(() -> new IllegalArgumentException(account + "가 없습니다."));
        } catch (final IllegalArgumentException e) {
            log.info(e.getMessage());
            return EMPTY_USER;
        }
```
이 부분에서 예외를 던지고 바로 catch 하는데, 예외를 던진 이유가 무엇인가요? 
로그를 찍기 위함이었나요?! (그리고 에러 로그는 `log.error()` 로 남기는건 어떨까요?)
예외를 던지지 않아도 조건문으로도 충분히 해결될 것 같아요.

그리고 예외처리를 제거한다면
```
return InMemoryUserRepository.findByAccount(account)
                    .orElse(EMPTY_USER);
```
이처럼 수정할 수도 있을 것 같아요!

2022-09-10 09:37 UTC, sure-why-not commented on tomcat/src/main/java/nextstep/jwp/model/Path.java
> +    private static final String REGISTER_PATH = "/register";
path에 대해 static으로 미리 생성해두셨네요!
만약 요청 uri 가 다양해진다면 이 부분이 굉장히 많아질 것 같다는 생각이 들어요.
사용되는 `fromUri()` 를 보면 `.html`을 붙여줄 때 사용하는데, 확장자가 있는 경우와 없는 경우만 확인하고 없는경우 해당 path 에 `.html`을 붙여주도록 변경하면 해당 상수와 객체들을 미리 만들어둘 필요가 없어질 것 같은데 어떠신가요? 😀

2022-09-10 09:37 UTC, sure-why-not commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +    private HttpResponse post(final HttpRequest httpRequest) throws IOException {
`post` 메서드가 많은 책임을 갖고 있는 것 같네요!
책임을 분리해볼까요? ㅎㅎ😎

2022-09-10 09:37 UTC, sure-why-not commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +    private HttpResponse get(final HttpRequest httpRequest) throws IOException {
`get` 메서드도 책임을 분리해볼까요? 😎

2022-09-10 09:37 UTC, sure-why-not commented on tomcat/src/main/java/nextstep/jwp/model/LoginResult.java
> +public class LoginResult {
사용되지 않고 있네요😱

2022-09-10 09:37 UTC, sure-why-not commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
>      private String readFile(final String url) throws IOException {
url 이라는 네이밍을 계속 사용하고 계신데요!
`URL` 과 `URI` 의 차이가 무엇일까요? 😎

2022-09-11 20:29 UTC, OzRagwort commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
>      private String readFile(final String url) throws IOException {
초반에 용어 정리가 안되었을 때 작성한 코드였던 것 같습니다

아래와 같이 기준을 잡고 사용했습니다
- uri => /login?account=gugu&password=password
- path => /login
- parameter => account=gugu&password=password

2022-09-11 20:32 UTC, OzRagwort commented on tomcat/src/main/java/nextstep/jwp/model/Path.java
> +    private static final String REGISTER_PATH = "/register";
Path 클래스를 enum으로 변경하면서 조금 수정해봤습니다. 

뒤에 .html을 추가하는 식으로 해서 여러가지 상수들을 만들지 않을 수도 있을 것 같긴한데 혹시라도 /login으로 들어왔을 때 /user_login.html 과 같은식으로 파일이름이 있을수도 있지 않을까? 하는 생각에 둘다 가지고 있도록 수정했습니다.

2022-09-11 20:33 UTC, OzRagwort commented on tomcat/src/main/java/nextstep/jwp/model/HttpRequest.java
> +        headers.put("Content-Length", "0");
저도 비슷한 기준으로 분리하려고 하는데 이번에는 신경쓰지 못한 것 같아요 ㅠㅠ

헤더나 상태 코드/메시지 등을 상수로 수정해봤고 이곳 저곳에서 사용될 수 있을 것 같아서 따로 클래스를 만들어서 분리해봤습니다

2022-09-11 20:36 UTC, OzRagwort commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +        response.addContentType("charset=utf-8");
이 부분도 인지하고 있었는데 수정을 하지 못했네요 ㅠㅠ

response body를 상황에 따라 받을 수 있도록 수정했습니다. 

예를들어 200 ok를 설정하면서 함께 body를 받고 302로 설정한다면 Location 헤더의 값을 함께 받는 등으로 수정해봤습니다

2022-09-11 20:42 UTC, OzRagwort commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +        final String method = httpRequest.getRequestLine().getMethod();
수정했습니다!

2022-09-11 20:42 UTC, OzRagwort commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +        final String path = httpRequest.getRequestLine().getPath();
수정했습니다!

2022-09-11 20:46 UTC, OzRagwort commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +        response.sendOk(httpVersion);
이 부분은 빌더를 이용해봐야겠다고 생각했는데 더 복잡해지고 어려운 것 같아서 적용하지는 않았습니다.

지금은 4개의 메서드를 이용해 HttpResponse를 만들고 있습니다.
- `ok(String body)` - `200 OK`
- `found(String location)` - `302 Found`
- `notFound()` - `404 Not found`
- `methodNotAllowed()` - `405 Method Not Allowed`

2022-09-11 20:47 UTC, OzRagwort commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
>      private User getUser(final String account) {
제가 괜히 너무 어렵게 생각했던 것 같아요 ! 감사합니당

2022-09-11 20:49 UTC, OzRagwort commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +        return !user.equals(EMPTY_USER);
해당 코드는 리뷰주신 느낌으로 수정했습니다! 

그런데 지금은 EMPTY_USER를 없애고 문제가 발생했을 때 예외를 던지는 식으로 수정했습니다

찾았는데 없으면 없는건데 왜 EMPTY_USER를 주어서 또 비교를 해야할까 EMPTY_USER는 왜 있어야할까? 등을 고민하다보니 필요가 없다고 생각하게 되었습니다.

2022-09-12 17:43 UTC, sure-why-not requested changes
알린 안녕하세요!! 👋🏻👋🏻👋🏻
4단계까지 잘 구현해주셨네요 😎
이전보다 객체들의 역할과 책임분리가 잘 이루어져 훨씬 읽기 수월해졌네요!!!
특히 `Http11Processor`의 엄청난 다이어트 👍🏻
연휴인데도 고생 많으셨어요 ㅜㅜ
몇가지 피드백 남겼으니 확인해주시면 감사하겠습니다 💌
화이팅팅 ~~~~~~~~~ 💪🏻

2022-09-12 17:43 UTC, sure-why-not commented on tomcat/src/main/java/org/apache/coyote/http11/controller/RegisterController.java
> +    @Override
전체적으로 클래스 첫줄은 개행을 추가하거나 추가하지 않는 컨벤션이 맞춰지면 좋을 것 같아요 ☺️

2022-09-12 17:43 UTC, sure-why-not commented on tomcat/src/main/java/org/apache/coyote/http11/controller/RegisterController.java
> +        }
이미 등록된 회원의 예외처리 좋네요 👍🏻
하지만 사용자 입장에선 이런 화면에 마주하게 되네요🥲
<img width="522" alt="스크린샷 2022-09-13 오전 2 10 10" src="https://user-images.githubusercontent.com/94965944/189714925-83058a40-966c-4d60-baae-2b2469e458d5.png">
특정 페이지로 리다이렉트시키는 response를 보내보는건 어떨까요??😆

2022-09-12 17:43 UTC, sure-why-not commented on tomcat/src/main/java/org/apache/coyote/http11/controller/AbstractController.java
> +public abstract class AbstractController implements Controller {
**Controller들이 Controller 의 구현체가 아닌 AbstractController를 상속받고 있네요!
AbstractController 를 추가한 이유가 무엇인가요?? 😎

2022-09-12 17:43 UTC, sure-why-not commented on tomcat/src/main/java/org/apache/coyote/http11/controller/Controller.java
> +public interface Controller {
Controller와 Sevice를 톰캣과 동일한 패키지에 두셨네요!

톰캣은 클라이언트와의 커넥션을 처리하고 클라이언트의 request를 http 규약에 맞게 변환하고 그에 맞는 response를 보내주는 역할로 알고있어요.

따라서 요청에 대한 비즈니스로직, DB 등의 처리를 하는 Controller 나 Sevice는 jwp 패키지가 더 적절하다는 생각이 들어요! 알린 생각은 어떠신가요?☺️

2022-09-12 17:43 UTC, sure-why-not commented on tomcat/src/main/java/org/apache/catalina/Session/SessionManager.java
> +    private static final Map<String, Session> SESSIONS = new ConcurrentHashMap<>();
동시성 컬렉션을 활용한 스레드 안전성 보장까지👍🏻

2022-09-12 17:43 UTC, sure-why-not commented on README.md
> +## 3단계 요구사항
요구사항 정리 빼놓을 수 없죠 👍🏻

2022-09-13 06:49 UTC, OzRagwort commented on tomcat/src/main/java/org/apache/coyote/http11/controller/LoginController.java
> +            final User user = UserService.findUser(session);
아하 저는 2단계 요구사항에 Session 객체에서 User를 저장한다고 해서 당장 쓰이지는 않지만 저렇게 User객체로 만들어 두라는 의미인 줄 알았어요 ..!

<img width="538" alt="image" src="https://user-images.githubusercontent.com/32123302/189830204-8209a97d-24c8-410d-ad93-5de0f8fbfde8.png">

2022-09-13 07:00 UTC, OzRagwort commented on tomcat/src/main/java/org/apache/coyote/http11/controller/AbstractController.java
> +public abstract class AbstractController implements Controller {
가장 큰 이유는 코드의 중복을 제거하기 위해서입니다. 

모든 Controller 같은 동작을 하는 service()를 가지고 그에따른 `doPost()`, `doGet()`메서드가 필수적으로 필요하게됩니다. 그렇기 때문에 중복되는 service 메서드를 AbstractController에 추가하고 doPost(), doGet()을 추상 메서드로 만들었고, controller들이 AbstractController를 상속받도록 하여 모든 컨트롤러들이 doPost(), doGet()을 가지도록 했습니다.

2022-09-13 07:02 UTC, OzRagwort commented on tomcat/src/main/java/org/apache/coyote/http11/controller/Controller.java
> +public interface Controller {
저도 다시한번 보니 UserService와 같은게 톰캣 패키지에 있는게 적절하지 않는 것 같다고 느꼈습니다! 수정했습니다.

2022-09-13 07:06 UTC, OzRagwort commented on tomcat/src/main/java/org/apache/coyote/http11/controller/RegisterController.java
> +    @Override
수정했습니다!

2022-09-13 07:07 UTC, OzRagwort commented on tomcat/src/main/java/org/apache/coyote/http11/model/Parameters.java
> +        return parseParameters(queryString, "&");
전체적으로 쓰지 않거나 불필요한 메서드를 제거했습니다.

2022-09-13 07:07 UTC, OzRagwort commented on tomcat/src/main/java/org/apache/coyote/http11/Request/HttpRequest.java
> +
예전부터 습관적으로 만들던 것 같습니다. 다른 곳들도 이런 경우가 많아서 수정했습니다!

2022-09-13 07:08 UTC, OzRagwort commented on tomcat/src/main/java/org/apache/coyote/http11/controller/LoginController.java
> +                        .cookie("JSESSIONID=" + session.getId());
HttpCookie에 있는 상수를 쓰는 것으로 수정했습니다.

2022-09-13 07:13 UTC, OzRagwort commented on tomcat/src/main/java/org/apache/coyote/http11/model/Headers.java
> +public class Headers {
enum으로 수정해봤습니다!

2022-09-13 07:26 UTC, OzRagwort commented on tomcat/src/main/java/org/apache/coyote/http11/controller/LoginController.java
> +                return HttpResponse.found("/index.html")
좋은 것 같아요 Path에서도 같은 값을 쓰고있어서 한곳에서 관리할 수 있도록 수정해야겠다고 생각이 드네요! 감사합니다 !

2022-09-13 07:54 UTC, OzRagwort commented on tomcat/src/main/java/org/apache/coyote/http11/controller/AbstractController.java
> +        if (method.equals("GET")) {
좋아요! 매직넘버를 없애면서도 더 깔끔해질 것 같아요!

2022-09-13 08:14 UTC, OzRagwort commented on tomcat/src/main/java/org/apache/coyote/http11/controller/RegisterController.java
> +        }
맞네요! 원래 의도한 동작이 그 동작이었는데 잘못구현한 것 같습니다. 수정했습니다!

2022-09-13 08:30 UTC, sure-why-not approved these changes
알린 안녕하세요👋🏻
피드백 반영한 부분 잘 확인했습니다 😃
첫 PR 보다 훨씬 코드가 읽고 이해하기 편해졌네요. 👍🏻
바쁘신 와중에 미션하시느라 수고 많으셨어요 🚀
남은 레벨4 기간도 화이팅이에요 ~~~ 💪🏻

2022-09-13 08:31 UTC, merged