[톰캣 구현하기 - 2, 3단계] 슬로(이한울) 미션 제출합니다.
woowacourse/jwp-dashboard-http pull request #291
Opened 2022-09-08 08:54 UTC by hanull

2022-09-12 15:36 UTC, dongho108 requested changes
안녕하세요 슬로~ 👋
코드 잘 봤습니다 ㅎㅎ
리뷰하면서 전반적으로 책임분리, 패키지분리가 잘 되어있다고 생각이 들었습니다!
몇가지 코멘트 남겼으니 읽어보시고 리뷰요청 다시 주시면 감사하겠습니다!

그런데 4단계는 언제쯤 요청하실까요~?
다음 리뷰요청 주실때 반영해주시면 좋을 것 같습니다 ㅎ

그리고 acr 리뷰법을 사용했습니다! 아래를 참고해주세용
### acr 리뷰방법
a : 반영하지 않아도 상관없다.
c : 고려해주었으면 좋겠다.
r : 반영해주었으면 좋겠다.

2022-09-12 15:36 UTC, dongho108 commented on tomcat/src/main/java/nextstep/jwp/controller/LoginController.java
> +        }
a : password를 변수로 빼는편이 더 가독성이 좋아보여요 ㅎㅎ

```suggestion
        final String password = request.getRequestBodyValue("password");
        if (user.checkPassword(password)) {
            throw new InvalidPasswordException();
        }
```

2022-09-12 15:36 UTC, dongho108 commented on tomcat/src/main/java/org/apache/coyote/http11/handler/Controller.java
> +    HttpResponse service(final HttpRequest request) throws IOException;
r : 요구사항에 맞게 반환타입을 void로 구현해보는 것이 어떨까요 ㅎㅎ
실제 서블릿 동작과정을 이해하기에 더 도움이 될 것 같습니다!

2022-09-12 15:36 UTC, dongho108 commented on tomcat/src/main/java/org/apache/coyote/http11/handler/RequestMapping.java
> +    }
어플리케이션이 띄워질때 컨트롤러가 생성되어서 계속 재사용하겠네요
요청마다 새로 컨트롤러를 생성하지 않게 만든 부분 아주 좋습니다!!! 굿!

2022-09-12 15:36 UTC, dongho108 commented on tomcat/src/main/java/org/apache/coyote/http11/header/HttpCookie.java
> +    }
`HttpCookie` 는 `JSESSIONID` 라는 것이 존재한다는 것을 알 수 있을까요?
c : `JSESSIONID` 라는 것은 누가 알면 좋을지 고민해보면 좋을 것 같아요!

2022-09-12 15:36 UTC, dongho108 commented on tomcat/src/main/java/org/apache/coyote/http11/request/HttpRequest.java
> +    }
`httpCookie.hasCookie()` 가 조금 어색하다고 느껴집니다.
a : 여기서는 `!httpCookie.isEmpty()`를 return하는 것이 어떨까요?

2022-09-13 07:59 UTC, hanull commented on tomcat/src/main/java/nextstep/jwp/controller/LoginController.java
> +        }
변수로 빼는게 더 가독성 좋아보이네요! 변경했습니다👍

2022-09-13 08:09 UTC, hanull commented on tomcat/src/main/java/org/apache/coyote/http11/request/HttpRequest.java
> +    }
!을 붙이지 않고 긍정문 형태로 작성하는게 더 가독성이 좋다고 생각해서 이렇게 작성했는데, cookie가 연속적으로 들어가니까 조금은 어색하게 느껴지네요. 
아래와 같이 변경해봤어요

```java
httpCookie.isExist()
```

2022-09-13 12:06 UTC, hanull commented on tomcat/src/main/java/org/apache/coyote/http11/header/HttpCookie.java
> +    }
`DEFAULT_SESSION_KEY` 로 변경해봤어요

2022-09-13 12:21 UTC, hanull commented on tomcat/src/main/java/org/apache/coyote/http11/handler/Controller.java
> +    HttpResponse service(final HttpRequest request) throws IOException;
조금 많은 부분을 고쳐야할 것 같아서 추후에 해볼게요!

2022-09-13 13:16 UTC, dongho108 commented on tomcat/src/main/java/org/apache/coyote/http11/request/HttpRequest.java
> +    }
너무좋네요 ㅎ

2022-09-14 01:52 UTC, dongho108 commented on tomcat/src/main/java/org/apache/coyote/http11/handler/Controller.java
> +    HttpResponse service(final HttpRequest request) throws IOException;
추후에 해보신다는건 이번 미션에서 적용하신다는 것인가요? 아니면 혼자 해보신다는 것인가요? 🤔
이번 미션에서 적용하지 않으시는거면 동작 요구사항은 만족하니 머지하려구요 ㅎ

2022-09-15 04:13 UTC, hanull commented on tomcat/src/main/java/org/apache/coyote/http11/header/HttpCookie.java
> +    }
의도 파악을 잘못했네요 🥲
SessionManager 역할을 다시 생각해봤는데 단순히 세션을 저장, 조회 역할만 수행 storage라고 느꼈어요. 
그래서 세션 id를 담고 있는 쿠키에서 JSESSIONID를 조회해야 하는게 더 자연스럽지 않나? 생각해요

2022-09-15 04:14 UTC, hanull commented on tomcat/src/main/java/org/apache/coyote/http11/handler/Controller.java
> +    HttpResponse service(final HttpRequest request) throws IOException;
이번 미션에서는 적용하지 않고 개인적으로 해보려구요!

2022-09-15 04:15 UTC, dongho108 approved these changes
동작 요구사항은 만족하니 이만 머지하겠습니다~ 😊
어려운 미션 구현하시느라 고생 많으셨어요!
다음에 뵈어용

2022-09-15 04:15 UTC, merged