[톰캣 구현하기 - 2, 3, 4단계] 스컬(김윤기) 미션 제출합니다.
woowacourse/jwp-dashboard-http pull request #294
Opened 2022-09-08 09:06 UTC by skullkim

로마! 이번 리뷰도 잘부탁해요😁

2022-09-10 09:21 UTC, kbsat requested changes
안녕하세요 스컬! 추석 연휴 잘 보내시고 계신가요?? 🙂
그동안 미션 수행하시느라 고생했어요. 2, 3, 4단계 잘 구현해주셨네요! 👍
체크리스트 모두 잘 돌아가는 것 확인했습니다!
코드 단에서 궁금한 점이나 개선할 사항 리뷰 남겼으니 한번 확인해보세요 ~!😊

2022-09-10 13:24 UTC, skullkim commented on tomcat/src/main/java/nextstep/jwp/view/IndexController.java
> +    }
삭제할게요~

2022-09-10 13:25 UTC, skullkim commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +    public synchronized void process(final Socket connection) {
버그 해결하려다가 동시성 이슈인줄 알고 붙였었는데요. 해결하고 지우는걸 깜빡했네요. 지울게요!

2022-09-10 13:27 UTC, skullkim commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +            e.printStackTrace();
stackTrace가 출력되냐 안되냐의 차이가 있겠네요. 추가적으로 printStackTrace는 내부에서 synchronized를 사용하고 있고요. 로그를 남기는 쪽으로 합칠게요!

2022-09-10 13:28 UTC, skullkim commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
>              char a = (char) bufferedReader.read();
네!

2022-09-10 13:33 UTC, skullkim commented on tomcat/src/main/java/org/apache/coyote/http11/HandlerMapper.java
> +                Map.entry("GET /register", new RegisterController())
AbstractController가 구현되고 매핑 방식이 바뀌었음에서 HandlerMapper는 여전히 이전의 매핑 방식을 사용하고 있었네요. 집어주셔서 감사합니다! HandlerMapper가 path만으로 컨트롤러를 매핑할 수 있게 수정할게요😁

2022-09-11 02:49 UTC, skullkim commented on tomcat/src/main/java/nextstep/jwp/view/LoginController.java
> +            responseBody = ResourceGenerator.getStaticResource("/401");
그러네요, 분리할게요~

2022-09-11 03:11 UTC, skullkim commented on tomcat/src/main/java/org/apache/coyote/common/request/Request.java
>          final String[] parsedRequest = rawRequest.split("\r\n");
URI에 그런 기능이 있는 줄 몰랐네요. URI를 사용하는 방식으로 수정할게요😁

2022-09-11 03:17 UTC, skullkim commented on tomcat/src/main/java/org/apache/coyote/common/response/Status.java
> +    UNAUTHORIZED("401 UNAUTHORIZED ");
뭔가 이유가 있었던거 같은대 기억이 안나네요. RFC2616을 찾아보니 응답 시작줄에서 status message 뒤에는 공백이 없네요. 삭제할게요!

2022-09-11 03:32 UTC, skullkim commented on tomcat/src/main/java/org/apache/coyote/common/response/Response.java
> +    private final OutputStream outputStream;
Controller에 존재하는 service가 반환값이 void여서 고민하다 OutpuStream을 Response 내부로 넣게 되었는데요. 생각해 보니까 Http11Processor의 process() 메서드 내에서 호출해도 되네요. 수정할게요~

2022-09-11 03:33 UTC, skullkim commented on tomcat/src/main/java/org/apache/coyote/common/response/Response.java
> +            log.info(e.getMessage(), e);
OutputStream을 외부로 빼면서 삭제했어요!

2022-09-11 03:39 UTC, skullkim commented on tomcat/src/main/java/org/apache/catalina/connector/Connector.java
> +        executor.submit(processor);
https://stackoverflow.com/questions/18730290/what-is-the-difference-between-executorservice-submit-and-executorservice-execut

submit은 Future를 반환하고 execute는 단순히 실행만 한다네요. 현 상황에서는 단순히 실행을 하는게 목적이니 execute로 바꾸는게 더 좋겠어요

2022-09-12 10:39 UTC, kbsat approved these changes
스컬 그동안 톰캣 구현하기 미션하시느라 고생하셨습니다~! 😃
요구했던 사항들 모두 잘 수정해주셨군요!
저도 스컬 코드 보고 많이 배웠습니다~ 이번 미션은 이만 머지하겠습니다! 고생하셨어요 ^>^

2022-09-12 10:39 UTC, kbsat commented on tomcat/src/main/java/nextstep/jwp/view/LoginController.java
> +        new SessionManager().add("userId", session);
세션을 더하는 메서드가 인스턴스 메서드로 정의되어있어서 매번 인스턴스를 만들고 add를 해주어야하네요!
싱글톤 패턴을 이용하면 이 문제를 해결할 수 있을 것 같아요! 🙂

2022-09-12 10:39 UTC, merged