[톰캣 구현하기 - 2,3단계] 짱구(신승철) 미션 제출합니다.
woowacourse/jwp-dashboard-http pull request #296
Opened 2022-09-08 09:16 UTC by sc0116

안녕하셍요 엘리
저 짱군데요!

혹시 4단계는 2,3단계 머지하고 새로 해야할까요 여기다가 추가하는게 좋을까요?

2022-09-12 07:26 UTC, RIANAEH requested changes
안녕하세요👋 짱구!
연휴 동안 쉬기만하느라 리뷰를 늦게 남겨드려 너무 죄송합니다🥲

1차적으로 체크 리스트 확인하고, 개선해보면 좋을 부분들 코멘트로 남겨놨어요!!
개선해보면 좋을 부분들은 참고만 해주시고 반영은 짱구의 선택입니다!!
그런데 아직 체크 리스트 중 구현되지 않은 부분들이 있더라구요. 
아래 체크 리스트를 첨부했으니 이 부분은 꼭 반영해주셨으면 좋겠습니다:)

### 체크 리스트
`2단계`
- [ ] HTTP Reponse의 상태 응답 코드를 302로 반환한다.
- [X] POST로 들어온 요청의 Request Body를 파싱할 수 있다.
- [ ] 로그인에 성공하면 HTTP Reponse의 헤더에 Set-Cookie가 존재한다.
- [ ] 서버에 세션을 관리하는 클래스가 있고, 쿠키로부터 전달 받은 JSESSIONID 값이 저장된다.

`3단계`
- [X] HTTP Request, HTTP Response 클래스로 나눠서 구현했다.
- [X] Controller 인터페이스와 RequestMapping 클래스를 활용하여 if절을 제거했다.

`4단계`
- [ ] Executors로 만든 ExecutorService 객체를 활용하여 스레드 처리를 하고 있다.

2022-09-12 07:26 UTC, RIANAEH commented on tomcat/src/main/java/nextstep/jwp/controller/AbstractController.java
> +    }
HTTP Method가 GET이 아니면 무조건 POST로 처리하는 것은 로직 상 알맞지 않은 것 같아요!!
조금 더 세부적으로 처리를 해보면 어떨까요?

2022-09-12 07:26 UTC, RIANAEH commented on tomcat/src/main/java/org/apache/coyote/request/HttpMethod.java
> +    ;
GET, POST 이외의 값이 들어왔을 때의 예외처리를 추가해주면 좋을 것 같아요!!

2022-09-12 07:26 UTC, RIANAEH commented on tomcat/src/main/java/nextstep/jwp/controller/CommonController.java
> +        response.ok(request.getPath());
만약 /gugu.html과 같이 없는 리소스를 요청하면 NPE가 발생하면서 응답을 못해주고 있어요. 
이에 대한 처리를 추가해보면 좋을 것 같아요!!

2022-09-12 07:26 UTC, RIANAEH commented on tomcat/src/main/java/org/apache/coyote/RequestMapping.java
> +    }
URL에 따라 Request를 처리할 Controller를 매핑해주는데 필드 이름이 key인게 의미상 어색한 것 같아요!

2022-09-12 07:26 UTC, RIANAEH commented on tomcat/src/main/java/org/apache/coyote/StatusCode.java
> +    UNAUTHORIZED("401", "UNAUTHORIZED"),
[RFC](https://www.rfc-editor.org/rfc/rfc2616#section-6.1.1)를 참고해 reason phrase의 형태를 변경해보면 좋을 것 같아요!

2022-09-13 05:24 UTC, sc0116 commented on tomcat/src/main/java/nextstep/jwp/handler/LoginHandler.java
> +                .orElseThrow();
앗 익셉션을 추가하지 않았네요..

2022-09-13 05:28 UTC, sc0116 commented on tomcat/src/main/java/nextstep/jwp/controller/AbstractController.java
> +    }
앗 지금은 GET, POST만 사용해서 현재 시점에서 처리를 했습ㄴ디ㅏ!

2022-09-13 05:28 UTC, sc0116 commented on tomcat/src/main/java/org/apache/coyote/request/HttpMethod.java
> +    ;
앗 좋아요!

2022-09-13 08:19 UTC, RIANAEH approved these changes
안녕하세요👋 짱구!
리뷰 빨리 반영해주셨네요💯
체크 리스트들도 모두 구현해주셔서 이만 머지해도 될 것 같아요!!

조금더 학습해보거나 고민해보면 좋을 포인트들을 코멘트로 달아놨어요. 
이 부분 확인해주시면 좋을 것 같아요:)

톰캣 구현하기 미션 멋지게 완료했으니 다음 미션도 파이팅해봅시다~~🎉

2022-09-13 08:19 UTC, RIANAEH commented on tomcat/src/main/java/org/apache/coyote/session/Session.java
> +    }
Optional을 이용해 null을 반환할 수 있음을 명시적이게 표현한게 너무 좋네요👍

2022-09-13 08:19 UTC, RIANAEH commented on tomcat/src/main/java/org/apache/coyote/request/HttpRequest.java
> +    }
저는 단순히 다음과 같이 getCookie()라는 메서드로 분리하기만 했는데, 생각해보니 HttpRequest의 Map<String, String>을 Map<String, Object>로 변경해 "Cookie"라는 키에 HttpCookie를 값으로 넣어 사용할 수도 있을 것 같네요. 이러한 구조에 대해 짱구는 어떻게 생각하시나요??

```java
public HttpCookie getCookie() {
    return HttpCookie.from(header.get("Cookie"));
}
```

2022-09-13 08:19 UTC, RIANAEH commented on tomcat/src/main/java/org/apache/catalina/connector/Connector.java
> +    private ExecutorService executor = Executors.newFixedThreadPool(10);
10이라는 값을 지정해서 넣은 이유가 있을까요?
지금 구조에서는 스레드 풀의 사이즈를 10말고는 지정할 수 없을 것 같아서요!

Executors를 이용해 스레드 풀을 만들 때 FixedThreadPool 말고도 다른 방법들이 있는 것으로 아는데 이것을 선택한 이유가 궁금합니다!!

2022-09-13 08:19 UTC, RIANAEH commented on tomcat/src/main/java/org/apache/catalina/connector/Connector.java
> +        executor.submit(processor);
submit() 말고도 execute(), invokeAll() 등 작업을 실행할 수 있는 방법들이 있는 것으로 알고 있는데 submit()을 선택한 이유가 궁금합니다!!

2022-09-13 08:19 UTC, merged