[HTTP 서버 구현하기 - 1단계] 알리(허진호) 미션 제출합니다.
woowacourse/jwp-dashboard-http pull request #30
Opened 2021-08-29 18:42 UTC by jh8579

안녕하세요 알리입니다!
이런저런 이슈를 겪다보니 시간이 너무 오래 걸렸네요 ㅜㅜ
너무 늦게 PR 보내드려서 죄송합니다
리뷰는 시간 제한이 풀렸으니 천천히 해주셔도 됩니다!
피드백 받으면서 많이 배우고 싶네요
감사합니다!

2021-08-30 15:24 UTC, jh8579 commented on app/src/main/java/nextstep/jwp/controller/AbstractController.java
> +        if (httpRequest.isGetRequest()) {
아 이부분 저도 고민을 했었는데 다시 생각해보니 다니 의견이 맞는 것 같네요!
수정했습니다!

2021-08-30 15:25 UTC, jh8579 commented on app/src/main/java/nextstep/jwp/handler/HttpStatus.java
> +public enum HttpStatus {
네 나중에 혹시나 필요하지 않을까 해서 자주 사용하던 것들만 넣어놨습니다

2021-08-30 15:27 UTC, jh8579 commented on README.md
> +* [ ] 서버를 실행시켜서 브라우저로 서버에 접속하면 index.html 페이지를 보여준다.
앗 깜빡했습니다ㅜㅜ

2021-08-30 15:29 UTC, jh8579 commented on app/src/main/java/nextstep/jwp/controller/ErrorController.java
> +        File file = FileReader.readErrorFile("/404.html");
좋은 것 같아요! 적용했습니다

2021-08-30 15:35 UTC, jh8579 commented on app/src/main/java/nextstep/jwp/controller/LoginController.java
> +        }
보기에도 더 깔끔하고 중복 코드도 줄어서 좋은 것 같아요!
적용했습니다!

2021-08-30 15:35 UTC, jh8579 commented on app/src/main/java/nextstep/jwp/controller/LoginController.java
> +        });
이 부분도 적용했습니다!

2021-08-30 15:38 UTC, jh8579 commented on app/src/main/java/nextstep/jwp/handler/HttpRequest.java
> +    private final HttpHeader httpHeader;
현재 할당은 하고 사용은 하고 있지 않지만 추후에 Request 헤더의 정보를 가져올 필요가 있을 때 사용할 수도 있지 않을까해서 남겨뒀습니다!

2021-08-30 15:41 UTC, jh8579 commented on app/src/main/java/nextstep/jwp/db/InMemoryUserRepository.java
> +        final User user = new User(currentId++, "gugu", "password", "hkkang@woowahan.com");
앗 그러네요 사용자를 추가할 때도 COUNT를 증가시켜야겠네요...
수정했습니다!

2021-08-30 15:46 UTC, jh8579 commented on app/src/main/java/nextstep/jwp/handler/HttpBody.java
> +        throw new IllegalArgumentException("body의 해당 키를 가지는 값이 존재하지 않습니다.");
이 부분 포함해서 전체적으로 HTTP 메세지 파싱이나 HTTP 메세지 객체에서 발생한 에러를 어떻게 처리할 지 한번 고민해봐야겠네요.
이부분은 미션 진행하면서 조금씩 적용해볼게요!

2021-08-30 15:48 UTC, jh8579 commented on app/src/main/java/nextstep/jwp/handler/HttpRequest.java
> +    public static HttpRequest fromRequest(BufferedReader reader) throws IOException {
앗 동의합니다 적용했습니다!

2021-08-30 15:50 UTC, jh8579 commented on app/src/main/java/nextstep/jwp/handler/HttpRequest.java
> +            if (headerLine.equals("")) {
아 이렇게 순서를 바꾸는 것 만으로 NPE를 막을 수 있겠네요!
꿀팁 감사합니다!

2021-08-30 15:59 UTC, jh8579 commented on app/src/main/java/nextstep/jwp/handler/HttpResponse.java
> +    private String httpVersion;
적용했습니다!

2021-08-30 15:59 UTC, jh8579 commented on app/src/main/java/nextstep/jwp/handler/HttpResponse.java
> +        addHttpHeader("Location", url);
적용했습니다!

2021-08-30 16:03 UTC, jh8579 commented on app/src/main/java/nextstep/jwp/util/FileReader.java
> +public class FileReader {
음 이부분도 고민을 했었는데

중복되는 부분이 있는 것 같아 추상화를 하려다가
나중에 파일마다 클래스를 만들기보다는 동적 파라미터를 사용해서 메소드 하나로 만들어보면 어떨까 생각해서 일단 남겨뒀습니다.
이 부분은 미션 진행하면서 다른 상황을 적용하면서 개선해나가도 괜찮을까요?

2021-08-30 16:04 UTC, jh8579 commented on app/src/main/java/nextstep/jwp/util/FileReader.java
> +    }
이 에러 처리 부분이 정말 고민을 많이 한 부분인데...

File이 존재하지 않을 때는 404로 반환을 해도 괜찮을 것 같은데
나머지 예외는 어떤 상황에서 발생하는지 정확이 학습을 안해서 한꺼번에 처리하기가 좀 애매했어요.
URISyntaxException은 인코딩 오류나 사용자의 잘못된 입력으로 발생할 것 같아 404가 맞을 것 같은데
IOException은 좀 애매하네요...

이 부분도 예외 상황을 좀 더 학습해보고 개선해도 괜찮을까요?

2021-08-30 16:06 UTC, jh8579 commented on app/src/main/java/nextstep/jwp/handler/HttpUri.java
> +            String[] querySplit = uri.split("\\?");
Split 메소드 인자로 들어가는 String이 정규식이어서 정규식에서 사용하는 문자들은 이스케이프 문자를 사용해야되더라구요

저도 최근에 코딩 테스트 하면서 저도 처음 알았습니다...

2021-08-30 16:20 UTC, jh8579 commented
제가 빼먹은 부분이나 실수한 부분들 꼼꼼하게 집어주셔서 감사합니다 ㅜㅜ
id가 증가하지 않는 버그는 생각도 못하고 있었네요 ㅋㅋ
대부분 피드백은 적용했습니다!
제가 이번에 좀 급하게 코드를 짜느라 공부를 하고 나서 짜고 싶은 부분들이 있었는데
그 부분들은 TODO로 남겨 미션 진행하면서 개선해보려고 합니다!
감사합니다!

2021-08-30 16:22 UTC, jh8579 commented on app/src/main/java/nextstep/jwp/handler/HttpBody.java
> +        throw new IllegalArgumentException("body의 해당 키를 가지는 값이 존재하지 않습니다.");
일단 HttpBodyException이란 예외를 만들었습니다!
HttpMessageException으로 통합적인 예외로 처리를 해야할지 
KEY에 대한 VALUE가 없는 상황이니 해당 상황에 맞는 예외를 사용해야할지 고민이 되네요

2021-08-30 16:54 UTC, da-nyee commented on app/src/main/java/nextstep/jwp/handler/HttpBody.java
> +        throw new IllegalArgumentException("body의 해당 키를 가지는 값이 존재하지 않습니다.");
저는 통합적인 예외로 처리해도 괜찮다고 생각은 해요!
예외 메시지 필드에 뭐 때문에 문제가 발생했는지 명시해주니까요!
다음 단계에서 알리가 어떤 결론을 내릴지 기대됩니다 ~! ㅎㅎ

2021-08-30 17:00 UTC, da-nyee commented on app/src/main/java/nextstep/jwp/handler/HttpUri.java
> +            String[] querySplit = uri.split("\\?");
오오 정규식에서 사용하는 문자들은 이스케이프 문자를 사용해야하는군요!!!
꿀팁 알아갑니다 👍

2021-08-30 17:03 UTC, da-nyee commented on app/src/main/java/nextstep/jwp/util/FileReader.java
> +public class FileReader {
좋습니다 ~~! 😁

2021-08-30 17:12 UTC, da-nyee commented on app/src/main/java/nextstep/jwp/util/FileReader.java
> +    }
오오 알리의 고민을 나눠주셔서 감사합니다 👍

저는 readErrorFile 부분은 생각하지 못했는데, 제가 예상한 것보다 더 다양한 예외 상황이 발생할 수도 있겠군요...!!!
좋아요!! 더 학습하고 다음 단계에서 반영해주세요 ㅎㅎㅎㅎ

2021-08-30 17:28 UTC, da-nyee requested changes
알리 ~!
빠른 피드백 반영 감사합니다 👏

코멘트 답글 달아주신 것들 전부 확인했어요!! 👍
알리가 말한대로 todo로 남긴 것들은 다음 단계에서 반영해주세요 ~!

피드백 하나만 더 남길게요!
지금 JaCoCo 리포트 생성 코드가 없어 SonarCloud Quality Gateway가 fail로 뜨는데요,
build.gradle에 JaCoCo 관련 내용들을 추가해야 할 것 같아요!

이 부분만 해결되면 바로 머지하겠습니다 !

2021-08-31 03:32 UTC, da-nyee approved these changes
JaCoCo까지 잘 적용해주셨네요!!!

이번 단계 수고하셨습니다 👏

2021-08-31 03:32 UTC, merged