[톰캣 구현하기 - 1, 2단계] 테오(최우성) 미션 제출합니다.
woowacourse/jwp-dashboard-http pull request #304
Opened 2023-09-02 18:31 UTC by woosung1223

안녕하세요 토리! 반갑습니다~

1, 2단계 구현 마치고 리뷰 요청드립니다!

아래는 큰 흐름을 도식화한 그림인데, 리뷰하실 때 참고하시면 좋을 것 같아요 🙇‍♂️

![image](https://github.com/woowacourse/jwp-dashboard-http/assets/78679830/657d2598-d8b0-4cfa-8827-02013cbfb4e4)

2023-09-04 10:36 UTC, ezzanzzan commented on tomcat/src/main/java/org/apache/coyote/http11/RequestExtractor.java
> +        }
body로 들어오는 값이 길어진다면 잘릴 위험이 있을 것 같아요 ! 또한 body값으로 &가 delimiter가 아닌 값이 들어올 수도 있지 않을까요 !?

2023-09-04 10:38 UTC, ezzanzzan commented on tomcat/src/main/java/org/apache/coyote/http11/message/Headers.java
> +    public Headers(Map<String, String> mappings) {
사용하지 않는 생성자인거 같아요 private로 닫아두는건 어떨까요?

2023-09-04 10:41 UTC, ezzanzzan commented on tomcat/src/main/java/org/apache/coyote/http11/message/request/RequestBody.java
> +    }
`RequestExtractor.class`에서 달았던 리뷰와 비슷한데, RequestBody는 '&', '=' 이 delimiter가 아닌 값이 올 수도 있지 않을까요 ?

2023-09-04 10:42 UTC, ezzanzzan commented on tomcat/src/main/java/org/apache/coyote/http11/message/HttpMethod.java
> +    }
👍

2023-09-04 10:49 UTC, ezzanzzan commented on tomcat/src/main/java/org/apache/coyote/http11/handler/Handlers.java
> +    }
오.. 멋져요 👍

2023-09-04 10:50 UTC, ezzanzzan commented on tomcat/src/main/java/org/apache/coyote/http11/message/request/RequestURI.java
> +    }
오... 좋은데요?👍

2023-09-04 10:57 UTC, ezzanzzan commented on tomcat/src/main/java/org/apache/coyote/http11/handler/Handler.java
> +        URL resourceUrl = Handler.class.getClassLoader().getResource("static/" + absolutePath);
`static/` 상수로 빼주는건 어떨까요 ?!

2023-09-04 10:58 UTC, ezzanzzan commented on tomcat/src/main/java/org/apache/coyote/http11/ContentTypeParser.java
> +    ICO("image/x-icon");
👍👍👍👍👍

2023-09-04 11:06 UTC, ezzanzzan commented on tomcat/src/main/java/org/apache/coyote/http11/message/HttpStatus.java
> +    UNAUTHORIZED("401 UNAUTHORIZED");
code와 message를 나누는건 어떨까요 ?

2023-09-04 11:07 UTC, ezzanzzan commented on tomcat/src/main/java/org/apache/coyote/http11/handler/IndexHandler.java
> +                "Content-Length", String.valueOf(resource.getBytes().length)
다른 Handler처럼 상수로 빼는건 어떨까요 ?
enum으로도 관리해볼 수 있을 거 같아요 !

2023-09-04 11:11 UTC, ezzanzzan commented on tomcat/src/main/java/org/apache/coyote/http11/handler/LoginHandler.java
> +        String absolutePath = "login.html";
이 부분도 상수로 빼줄 수 있을 거 같아요 ! 
아래 401.html 두요 !

2023-09-04 11:13 UTC, ezzanzzan commented on tomcat/src/main/java/org/apache/coyote/http11/handler/LoginHandler.java
> +        ));
`index.html`로 redirect가 안되고 있어요 !

2023-09-04 11:31 UTC, ezzanzzan commented on tomcat/src/main/java/org/apache/coyote/http11/handler/LoginHandler.java
> +        ));
여기도 redirect가 안되고 있는 거 같아요 !

2023-09-04 11:31 UTC, ezzanzzan commented on tomcat/src/main/java/org/apache/coyote/http11/handler/LoginHandler.java
> +        ));
여기도 redirect가 되어야겠네요 ~!

2023-09-04 11:36 UTC, ezzanzzan commented on tomcat/src/main/java/org/apache/coyote/http11/handler/RegisterHandler.java
> +        ResponseBody responseBody = new ResponseBody(resource);
`회원가입을 완료하면 index.html로 리다이렉트한다.` 라는 요구사항이 있어요 !
LoginHandler에 남긴 리뷰와 마찬가지로 "Location"을 추가해줘야 될 거 같네요 !

2023-09-04 12:02 UTC, ezzanzzan requested changes
안녕하세요 테오 ! 토리입니다 🙇‍♀️

전체적으로 코드 구조가 깔끔하고 도식화한 그림까지 주셔서 리뷰 하는데 큰 어려움이 없었습니다 !
코드가 술술 읽혀서 재밌었어요 👍

리뷰 남긴 부분 확인 후 다시 요청 부탁드려요 !
좋은 하루 되세요 🌈🙇‍♀️

2023-09-04 13:37 UTC, woosung1223 commented on tomcat/src/main/java/org/apache/coyote/http11/RequestExtractor.java
> +        }
말씀해주셔서 Request Body에 어떤 값들이 들어올 수 있는지 조사를 조금 해보았는데요!

현재는 HTML 파일의 form 태그를 통해 로그인 정보를 보내는 방식이다보니
기본으로 Content-Type을 `application/x-www-form-urlencoded` 로 사용합니다. 

이 경우 데이터가 `key=value&key=value` 형식으로 들어오게 되고, 그렇기 때문에 위의 코드가 정상적으로 작동하는 것 같습니다.

토리가 말씀주신대로 Content-Type에 따라 여러 Delimiter가 들어올 수 있더라구요.
Postman으로 form-data를 작성해 요청해보기도 했는데, 이 경우에는 multipart/form-data를 사용하고 delimiter를 클라이언트가 정의하기 때문에 파싱 자체가 불가능했었습니다 🥲

현재는 다양한 Content-Type을 수용할 필요는 없으나 추가적으로 JSON 정도까지만 파싱이 가능하게 구현해보려고 하는데, 어떻게 생각하시는지 궁금합니다!

2023-09-04 13:38 UTC, woosung1223 commented on tomcat/src/main/java/org/apache/coyote/http11/RequestExtractor.java
> +        }
body buffer 크기 부분은 `Content-Length` 를 사용하는 쪽으로 수정해보도록 하겠습니다!

2023-09-04 14:15 UTC, woosung1223 commented on tomcat/src/main/java/org/apache/coyote/http11/message/Headers.java
> +    }
저도 사용하지 않는 줄 알고 지웠더니 Handler들이 사용하고 있더라구요 🥲

생성자와 정팩메를 둘 다 열어두는 건 헷갈릴 거 같아서, 말씀해주신것처럼 private 생성자를 사용하고 정팩메를 하나 더 추가했습니다!

2023-09-04 14:17 UTC, woosung1223 commented on tomcat/src/main/java/org/apache/coyote/http11/message/request/RequestBody.java
> +    }
맞습니다! 요거는 위에서 답글을 달기는 했지만 Content-Type에 따라 바뀌어야 할 것 같아요!

수정해보도록 하겠습니다~

2023-09-04 14:47 UTC, woosung1223 commented on tomcat/src/main/java/org/apache/coyote/http11/handler/IndexHandler.java
> +                "Content-Length", String.valueOf(resource.getBytes().length)
enum으로 관리하게 변경했습니다!

2023-09-05 04:40 UTC, ezzanzzan approved these changes
안녕하세요 테오 ! 토리입니다 ˙ᵕ˙ 
리뷰 빠르게 반영해주셨네요 👍 
원래도 깔끔한 코드였는데 더 빛이 나고 있네요 .. 

이번 단계는 머지 하도록 하겠습니다 !! 
자그만 리뷰 몇 개 남겼는데 다음 단계 진행하면서 같이 생각해보시면 좋을 것 같아요 ~ 
다음 단계에서 봬요 👋

2023-09-05 04:40 UTC, ezzanzzan commented on tomcat/src/main/java/org/apache/coyote/http11/RequestExtractor.java
> +            char[] buffer = new char[contentLength];
👍

2023-09-05 04:40 UTC, ezzanzzan commented on tomcat/src/main/java/org/apache/coyote/http11/RequestExtractor.java
> +        }
얘기나눴던 부분인데 다시 정리해서 리뷰 남기자면 !
제가 의도한 방향은 "&"로 파싱하는 부분을 한 단계 밖이나, 실제로 body값에 대한 파싱이 필요한 부분에서 실행하는게 어떨까 였습니다 !
외부에서 하면 조금 더 content-type에 따라 분기를 나눠서 실행하기도 편하고 로직이 추가되기도 편할 것 같았습니다 ㅎㅎ

말씀해주신대로 현재는 다양한 Content-Type을 수용할 필요가 없으니 따로 파싱을 추가하지 않아도 괜찮을 것 같아요 👍

2023-09-05 04:40 UTC, ezzanzzan commented on tomcat/src/main/java/org/apache/coyote/http11/message/Headers.java
> +    }
헉 제가 제대로 확인하지 못했었군요.. 🥲 좋습니다 👍

2023-09-05 04:40 UTC, ezzanzzan commented on tomcat/src/main/java/org/apache/coyote/http11/message/Headers.java
> +    public static Headers fromLines(List<String> lines) {
네이밍 좋은데요 ? 👍

2023-09-05 04:40 UTC, ezzanzzan commented on tomcat/src/main/java/org/apache/coyote/http11/message/HttpHeaders.java
> +    LOCATION("Location");
:+1

2023-09-05 04:40 UTC, ezzanzzan commented on study/src/test/java/study/IOStreamTest.java
> +            }
try 안의 outputStream을 밖에서 선언해준 뒤 변수를 사용하면 확실하게 검증이 될 거 같네요 !!

2023-09-05 04:40 UTC, merged