[톰캣 구현하기 1,2단계] 호이(이건호) 미션 제출합니다.
woowacourse/jwp-dashboard-http pull request #313
Opened 2023-09-04 02:26 UTC by This2sho

안녕하세요. 엔델 🙇‍♂️

1,2 단계 리뷰 요청드립니다!

Http11Processor 에서 inputStream으로 HttpRequest를 생성하고
request에 해당하는 컨트롤러를 찾아서 해당 컨트롤러가 작업 후 HttpResponse를 반환하는 형식으로 구현하였습니다.

편하게 시간에 편하게 리뷰 부탁드립니다 ~! 🙇‍♂️

2023-09-04 08:24 UTC, SproutMJ requested changes
안녕하세요 호이 구현해주신 것 잘 봤습니다.
제가 남긴 의견은 필수적으로 하기보다는 개인적인 의견이 있으시면 코멘트 부탁드립니다.
추가로, 공통적인 코멘트를 여기에 남기자면 final 키워드가 전반적으로 빠져있는데요, 이를 보강하면 좋을 것 같습니다.
감사합니다.

2023-09-04 08:24 UTC, SproutMJ commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +            final Controller controller = controllerAdapter.findController(request);
Controller 로직을 잘 구현하신 것 같아요!

2023-09-04 08:24 UTC, SproutMJ commented on tomcat/src/main/java/org/apache/coyote/http11/HttpResponse.java
> +                "Content-Length: " + responseBody.getBytes().length + " ");
상수화는 어떠신지 궁금합니다!

2023-09-04 08:24 UTC, SproutMJ commented on tomcat/src/main/java/org/apache/coyote/http11/HttpRequest.java
> +
HttpMethod와 HttpCookie 구현해주신거 잘 봤습니다. 그런데 혹시 나머지 요소들을 객체화 하실건지 궁금한데요.
3단계 요구사항이긴 하지만, 일부분은 객체화 하셔서 질문드립니다.

2023-09-04 08:24 UTC, SproutMJ commented on tomcat/src/main/java/org/apache/coyote/http11/HttpRequest.java
> +            int contentLength = Integer.parseInt(headers.get("Content-Length"));
이 클래스에 매직넘버가 존재하는데 이를 상수화 하실지 의견을 듣고싶습니다!

2023-09-05 06:48 UTC, This2sho commented on tomcat/src/main/java/org/apache/coyote/http11/controller/LoginController.java
> +        return null;
분기가 너무 많긴하네요..! 
예외로 처리 후, 예외에 따른 페이지로 이동하는 쪽으로 해보겠습니다!

2023-09-08 08:57 UTC, This2sho commented on tomcat/src/main/java/org/apache/coyote/http11/controller/RegisterController.java
> +            e.getStackTrace();
1,2 단계에서 시간이 급해서 요구사항만 만족하도록 구현했습니다.

2023-09-10 13:46 UTC, This2sho commented on tomcat/src/main/java/org/apache/coyote/http11/HttpResponse.java
> +                "Content-Length: " + responseBody.getBytes().length + " ");
반영하였습니다!

2023-09-10 13:46 UTC, This2sho commented on tomcat/src/main/java/org/apache/coyote/http11/HttpRequest.java
> +
하다보니 객체하나가 부분적으로 무거워져서 하고 싶은 것만 일단 하였는데, 객체화할 생각입니다!

2023-09-10 14:14 UTC, This2sho commented on tomcat/src/main/java/org/apache/coyote/http11/HttpRequest.java
> +            int contentLength = Integer.parseInt(headers.get("Content-Length"));
상수화 하겠습니다~!

2023-09-11 06:18 UTC, SproutMJ approved these changes
요구사항 만족하신 것 같아서 1,2단계는 마무리 해도 될 것 같습니다. 3,4단계에서 다시 뵙겠습니다.

2023-09-11 06:18 UTC, SproutMJ commented on tomcat/src/main/java/org/apache/coyote/http11/request/HttpRequest.java
> +            int contentLength = Integer.parseInt(headers.get("Content-Length"));
Content-Length도 상수화할 수 있겠네요

2023-09-11 06:19 UTC, merged