[톰캣 구현하기 - 1단계] 디노(신종화) 미션 제출합니다.
woowacourse/jwp-dashboard-http pull request #319
Opened 2023-09-04 04:47 UTC by jjongwa

안녕하세요 성하~ 디노입니다!🦖

레벨 1에서 같이 블랙잭 하던게 엊그제 같은데.. 시간이 참 빠르네요 ㅎㅎ
따로 말씀드린대로 우선 step1 요구사항에 대한 구현 부분 리뷰 받고,
남겨주실 코멘트 반영해서 step2를 조금 더 가다듬은 뒤 다시 pr 요청 보내겠습니다!

2023-09-04 08:18 UTC, sh111-coder requested changes
안녕하세요 디노! 성하입니다!! ㅎㅎㅎㅎ
블랙잭 페어였는데 진짜.. 감회가 새롭네요,,

객체지향적으로 잘 짜주시고 도메인 테스트도 많은 것 같아서 인상 깊었습니다!
실력이 더 발전하신 것 같아요 짱짱 👍🏻👍🏻

몇 가지 개선 제안 부분 남겨서 디노가 보시고 반영해주시면 감사하겠습니다!
이해 안되시거나 안바꿔도 되겠다! 하는 부분들은 코멘트로 남겨주시면 감사하겠습니다 ㅎㅎ

수고하셨어요 디노 🦖🦕

2023-09-04 08:18 UTC, sh111-coder commented on tomcat/src/main/java/org/apache/coyote/http11/HttpPath.java
> +
HttpPath의 요소를 객체로 묶어서 더 객체지향적인 것 같아요! 👍🏻👍🏻

그런데 HttpExtensionType은 HttpPath가 가지지 않아도 되는 필드라고 느껴지네요!
'index.html'이 있으면 클라이언트에서 서버에게 요구하는 resource가 extension을 제외하지 않은
'index.html'이라고 생각합니다!

그래서 HttpExtensionType을 제거하고 resource을 extension을 제외하지 않고 가진 후에
다른 클래스가 resource의 Extesion에 따른 Content-Type을 찾도록 처리하는 건 어떨까요?!

2023-09-04 08:18 UTC, sh111-coder commented on tomcat/src/main/java/org/apache/coyote/http11/HttpRequest.java
> +    private final HttpPath httpPath;
HttpRequest에서 빠진 요소가 있는 것 같아요!

당장은 안 쓰이지만 2단계 구현 시에 body도 필드로 추가되면 좋을 것 같습니다!!

2023-09-04 08:18 UTC, sh111-coder commented on tomcat/src/main/java/org/apache/coyote/http11/HttpResponse.java
> +    private final String responseBody;
이 부분도 HttpRequest와 동일하게 Http Request Message의 요소대로 필드가 구성되어 있는 것 같지는 않습니다!!
2단계 때 바뀔 것 같아서 언급만 하고 넘어가도록 할게요!! 😃

2023-09-06 17:22 UTC, jjongwa commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +        }
성하의 의견에 동의합니다. 바아아로 변경했습니다.!

2023-09-06 17:24 UTC, jjongwa commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +        log.info(user.toString());
이 부분은 다음 스텝에서 조금 더 생각해 보겠습니다.! toString으로 처리하는 다른 클래스들이 생겨서 일관성을 맞춰주고 싶어서요.!
성하의 말대로 명시적으로 바로 파악할 수 있게 작성하는 것도 좋은 방식이라 생각합니다.

2023-09-06 17:24 UTC, jjongwa commented on tomcat/src/main/java/org/apache/coyote/http11/HttpMethodType.java
> +                .orElseThrow(() -> new UncheckedServletException("해당하는 HttpMethod가 존재하지 않습니다."));
댓츠 굿

2023-09-06 17:25 UTC, jjongwa commented on tomcat/src/main/java/org/apache/coyote/http11/HttpRequest.java
> +        return new HttpRequest(HttpMethodType.from(split[0]), HttpPath.from(split[1]));
적용했습니다!

2023-09-06 17:26 UTC, jjongwa commented on tomcat/src/main/java/org/apache/coyote/http11/HttpPath.java
> +
이 부분도 심히 동감하는 바입니다.. 구조 변경 중에 자연스럽게 ExtensionType은 없어지는 방향으로 진행됐습니다!

2023-09-07 03:50 UTC, sh111-coder approved these changes
안녕하세요 디노! 
1차 수정 제안 부분들 대부분이 반영되어서 Approve 하겠습니다!!
제안 드린 것 중에 반영 안하신 부분은 디노의 생각을 코멘트로 잘 남겨주셔서 이해하기 좋았어요! 👍🏻👍🏻👍🏻

2단계 구현하신 부분 중에서 몇 가지 수정 제안 부분이나 궁금한 부분 코멘트 남겼습니다!
해당 부분들은 다 리팩토링 부분이라서 이번 PR은 Merge하고,
이후에 3단계 구현하실 때 선택적으로 반영해주시면 될 것 같아요!!

2단계 구현 시에 Request 클래스, Response 클래스로 리팩토링하시면서
리팩토링하기 힘드셨을 것 같은데 너무 잘 해주신 것 같아서 코드 보면서 배웠습니다 ㅎㅎㅎ
추가로, 테스트 관련 부분은 저보다 양, 질 다 좋은 것 같아요,,, 반성합니다 😂

다음 단계도 화이팅합시다!!! 다이노~~~ 🦖🦕

2023-09-07 03:51 UTC, merged

2023-09-09 18:07 UTC, jjongwa commented on tomcat/src/main/resources/static/409.html
> +<!DOCTYPE html>
회원가입시 이미 존재하는 아이디 또는 이메일일 경우 다른 예외를 던져줘야 한다고 생각했습니다.! 그래서 409 html 페이지를 만들어 해당 페이지를 반환하도록 구성해 봤습니다..!