[톰캣 구현하기 1,2단계] 이레(이다형) 미션 제출합니다.
woowacourse/jwp-dashboard-http pull request #329
Opened 2023-09-04 05:51 UTC by zillionme

안녕하세요 오션! 리뷰 잘 부탁드립니다!
예외 처리는 모두 IllegalArgumentException으로 처리하였는데 후에 리팩토링 과정에서 커스텀 예외로 변경하도록 하겠습니다.
제 코드의 전체 흐름은 정리해서 곧 올리도록 하겠습니다.

2023-09-04 13:38 UTC, donghae-kim requested changes
안녕하세요 이레 ~! 오션입니다 🌊

전체적으로 코드 구조를 잘 작성해주셔서 읽기 좋았어요 ! 
테스트가 없었던 것이 조금 아쉽네요 😢

제 생각을 가볍게 남겨봤습니다! 확인 부탁드립니다 ~
고생하셨어요 ! ~

2023-09-04 13:38 UTC, donghae-kim commented on tomcat/src/main/java/org/apache/coyote/http11/handler/StaticFileHandler.java
> +        try (BufferedReader br = new BufferedReader(new FileReader(requestedFile.getFile(), Charset.forName("UTF-8")))) {
URL 파일을 스트링으로 변환하는 로직인 것 같은데 `Files.readAllBytes`를 참고해도 좋을 것 같아요 !

2023-09-04 13:38 UTC, donghae-kim commented on tomcat/src/main/java/org/apache/coyote/http11/handler/StaticFileHandler.java
> +                        .header("Content-Type: text/html;charset=utf-8 ")
contentType을 enum으로 관리하면 어떨까요 ?!
확장자 or accept에 맞는 타입만 넣어주면 되기 때문에 밑에 로직하고 분리 할 필요가 없어질 것 같아요!

2023-09-04 13:38 UTC, donghae-kim commented on tomcat/src/main/java/org/apache/coyote/http11/common/Cookie.java
> +        System.out.println("parts[0] = " + parts[0]);
놓치신 것 같아요 !!

2023-09-04 13:38 UTC, donghae-kim commented on tomcat/src/main/java/org/apache/coyote/http11/common/HttpStatus.java
> +    REDIRECTION(302, "Moved Temporarily ");
301 message가 Moved Temporarily
302 message가 Found 로 알고 있습니다!

2023-09-04 13:38 UTC, donghae-kim commented on tomcat/src/main/java/org/apache/coyote/http11/response/HttpResponseBuilder.java
> +public class HttpResponseBuilder {
빌더 패턴은 생각 못했었는데 좋은 것 같아요 ! 👍👍

2023-09-04 13:38 UTC, donghae-kim commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +        int contentLength = Integer.valueOf(requestHeader.getHeaderValue("Content-Length"));
int 값 반환으로는 praseInt가 좀 더 적절해보입니다~~

2023-09-04 13:38 UTC, donghae-kim commented on tomcat/src/main/java/org/apache/coyote/http11/request/RequestHeader.java
> +    final private Map<String, String> headers;
private final ...?

2023-09-04 13:38 UTC, donghae-kim commented on tomcat/src/main/java/org/apache/coyote/http11/handler/LoginHandler.java
> +            String account = requestBody.getContentValue("account");
account, password 같은 부분들은 상수화 하는게 좋을 것 같아요!

2023-09-04 13:38 UTC, donghae-kim commented on tomcat/src/main/java/org/apache/coyote/http11/request/RequestBody.java
> +        String[] body = input.split("&");
stream 을 활용하면 더 깔끔하게 작성할 수 있을 것 같아요 ~

2023-09-04 13:38 UTC, donghae-kim commented on tomcat/src/main/java/org/apache/coyote/http11/handler/StaticFileHandler.java
> +    private static final String EXTENSION = ".html";
이 상수는 사용하지 않는 것 같아요 !

2023-09-04 13:38 UTC, donghae-kim commented on tomcat/src/main/java/org/apache/coyote/http11/common/SessionManager.java
> +import java.util.UUID;
사용하지 않는 import문은 정리하면 좋을 것 같아요 !

2023-09-06 07:46 UTC, zillionme commented on tomcat/src/main/java/org/apache/coyote/http11/handler/StaticFileHandler.java
> +        try (BufferedReader br = new BufferedReader(new FileReader(requestedFile.getFile(), Charset.forName("UTF-8")))) {
```
URL requestedFile = ClassLoader.getSystemClassLoader().getResource("static" + requestURI);
            Path path = Paths.get(requestedFile.getPath());
            **return String.valueOf(Files.readAllBytes(path));**
```
와 같이 적용하라는 말씀이신가요?

2023-09-06 07:59 UTC, zillionme commented on tomcat/src/main/java/org/apache/coyote/http11/handler/StaticFileHandler.java
> +                        .header("Content-Type: text/html;charset=utf-8 ")
contentType를 enum으로 한다면,
HTML("text/html;charset=utf-8 ")
CSS("ccs/~")
JS
..
와 같을텐데, 클라이언트에서 요청하는 
1. 리소스의 content타입을 제가 모르기도하고, 
2. 리소스 타입이 추가될때마다 enum에 코드 변경이 일어나야 하는데, 좋은 방법인지 잘 모르겠습니다!

의견 부탁드립니다~

2023-09-06 08:01 UTC, zillionme commented on tomcat/src/main/java/org/apache/coyote/http11/common/HttpStatus.java
> +    REDIRECTION(302, "Moved Temporarily ");
넵 수정하도록 하겠습니다.

2023-09-06 08:01 UTC, zillionme commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +        int contentLength = Integer.valueOf(requestHeader.getHeaderValue("Content-Length"));
둘의 차이를 몰랐는데 valueOf는 Integer라는 래퍼 클래스를 반환하더라구요. 감사합니다

2023-09-06 08:20 UTC, zillionme commented on tomcat/src/main/java/org/apache/coyote/http11/handler/StaticFileHandler.java
> +    private static final String EXTENSION = ".html";
삭제 했습니다!

2023-09-06 08:25 UTC, zillionme commented on tomcat/src/main/java/org/apache/coyote/http11/handler/LoginHandler.java
> +            String account = requestBody.getContentValue("account");
상수화에 대한 생각이 갈리기는 하는데요
여러번이 아닌, 딱 한번 사용하는 ""문자열에 대해서 상수화를 하는 것이 가독성 측면에서 좋을까요?

2023-09-06 08:43 UTC, zillionme commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +        return RequestHeader.from(lines);
Optional의 스트림 기능을 이용해서
```
User user = InMemoryUserRepository.findByAccount(account)
        .filter(u -> u.checkPassword(password))
        .orElseThrow(() -> new IllegalArgumentException("해당하는 계정이 존재하지 않거나 비밀번호가 일치하지 않습니다"));
```
와 같이 바꾸고 싶었지만, 이렇게 되면 두개인 예외가 하나로 합쳐져야 해서 불가피하게 위와 같이 결정하게 되었습니다.
후에 서비스를 만드는 것을 가정할 때 해당 내용을 분리한 것이 좋을 것 같아서요
감사합니다!

2023-09-06 08:55 UTC, zillionme commented on tomcat/src/main/java/org/apache/coyote/http11/request/RequestLine.java
> +    private final String requestMethod;
해당 내용 적용해서 수정했습니다

2023-09-06 09:06 UTC, zillionme commented on tomcat/src/main/java/org/apache/coyote/http11/common/SessionManager.java
> +import java.util.UUID;
넵

2023-09-06 10:27 UTC, zillionme commented on tomcat/src/main/java/org/apache/coyote/http11/request/RequestBody.java
> +        String[] body = input.split("&");
수정했습니다

2023-09-06 10:52 UTC, zillionme commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +            RequestLine requestLine = readRequestLine(reader);
수정했습니다!

2023-09-07 13:57 UTC, donghae-kim commented on tomcat/src/main/java/org/apache/coyote/http11/handler/LoginHandler.java
> +            String account = requestBody.getContentValue("account");
한번 사용하는 문자열까지 상수화를 하면 지나치게 복잡해질 수 있을 수 있어서 이레 의견에는 어느정도 동의합니다!
저는 재사용가능성, 상수 자체의 가독성 등의 이유로 왠만하면 상수화 하려고 하는 편인데 사람마다 의견이 다를 수 있는 것 같스빈다.

이레가 그렇게 생각하신다면 그렇게 진행하는 것이 좋을 것 같아요 !!

2023-09-07 15:57 UTC, donghae-kim requested changes
안녕하세요 이레!
리뷰어 오션입니다!

객체지향적인 구조로 클래스 잘 나눠주시고 직관적으로 보이게 코드를 잘 작성해주셨는데 리팩토링을 하는 과정에서 몇가지 작동이 달라진 부분이 존재하더라고요!🥲

이 부분만 수정이 완료되면 바로 3&4단계를 진행해도 좋을 것 같아요!

2023-09-07 15:57 UTC, donghae-kim commented on tomcat/src/main/java/org/apache/coyote/http11/handler/StaticFileHandler.java
> +            throw new NotExistFileException();
이 예외가 발생했을 경우에는 404 html 로 리다이렉트 되도록 하는 것이 좋을 것 같아요 !
이 과정은 3단계에서 진행해도 좋을 것 같아요 !

2023-09-07 15:57 UTC, donghae-kim commented on tomcat/src/main/java/org/apache/coyote/http11/request/RequestMethod.java
> +                .anyMatch(requestMethod -> requestMethod.name().equals(value));
`requestLine.getRequestMethod().isSameRequestMethod("GET")` 이걸 통해서 GET 메소드인지 확인하려고 하는것 같아요!
다만 지금과 같은 로직으로 실행되면 무조건 true가 나오는 상황이 발생하여 리다이렉트가 불가합니다!

위의 로직 대신 이건 어떨까요 ?
```suggestion
                return this.name().equals(value);
```

2023-09-07 16:02 UTC, merged