[톰캣 구현하기 1, 2단계] 마코(이규성) 미션 제출합니다.
woowacourse/jwp-dashboard-http pull request #332
Opened 2023-09-04 06:58 UTC by aak2075

버스타고 사장님 반갑습니다~👋  
결국 리뷰어로 만나게 됐네요. 잘 부탁드립니다~~

전체적인 흐름은 다음과 같습니다.

1. HttpRequestReader 에서 request를 파싱하여 HttpRequest를 만든다.
2. Handler에서 파싱한 HttpRequest를 처리하여 응답을 HttpResponse를 만든다.
3. HttpResponseWriter에서 HttpResponse를 파싱하여 응답을 내려준다.

handler에서 핸들링하는 코드도 복잡할 뿐만 아니라 비즈니스 로직도 섞여있어서 리팩토링이 필요하나 고민이 더 필요할 것 같습니다.

부족한 점이나 궁금한 점, 피드백 얼마든지 환영합니다!😄

2023-09-04 07:50 UTC, xxeol2 commented on tomcat/src/main/java/org/apache/coyote/http11/util/HttpRequestReader.java
> +        final var bufferedReader = new BufferedReader(new InputStreamReader(inputStream));
자원을 사용하고 닫아주지 않으면 메모리 누수가 일어날지도 몰라요! (줄줄줄)

2023-09-04 08:57 UTC, xxeol2 requested changes
소소한 리뷰 남겼습니다!
오늘 밤이나 내일중으로 추가 리뷰 남길게요 ㅎㅎ

2023-09-04 08:57 UTC, xxeol2 commented on tomcat/src/main/java/org/apache/coyote/http11/util/HttpRequestReader.java
> +        final var bufferedReader = new BufferedReader(new InputStreamReader(inputStream));
InputStream은 try-with-resource 구문으로 닫아주고있지만, InputStreamReader와 BufferedReader는 그러지 않네요!
랩핑한 스트림을 닫을 때 내부 스트림은 함께 닫히지만, 그 반대는 아닌걸로 알고있어요!
이 친구들도 사용이 끝나면 닫아주는건 어떨까요?

2023-09-04 08:57 UTC, xxeol2 commented on tomcat/src/main/java/org/apache/coyote/http11/util/HttpRequestReader.java
> +        final var splitLine = requestLine.split(" ");
" ", ": "와 같은 구분자를 상수로 정의해보는건 어떨까요?

2023-09-04 08:57 UTC, xxeol2 commented on tomcat/src/main/java/org/apache/coyote/http11/util/HttpRequestReader.java
> +    }
이친구가 사용되는 메서드 바로 밑으로 이동하면 더 보기 좋을 것 같아요

2023-09-04 08:57 UTC, xxeol2 commented on tomcat/src/main/java/org/apache/coyote/http11/util/HttpRequestReader.java
> +    }
http://localhost:8080/login?account 이렇게 요청이 들어오면 어떻게 될까요?! 그리고 어떻게 처리하는게 좋을까요?

2023-09-04 08:57 UTC, xxeol2 commented on tomcat/src/main/java/org/apache/coyote/http11/util/HttpRequestReader.java
> +            }
올바르지 않은 세션정보가 넘어왔을 때 예외를 던지는 대신, 세션을 없는 친구처럼 여기는건 어떨까요?!
만료된 세션 정보로 요청을 보냈을 때, 접근자체가 불가능한 것 보다 로그아웃상태로 접근되는게 더 자연스러운 흐름일 것 같아요!

2023-09-04 08:57 UTC, xxeol2 commented on tomcat/src/main/java/nextstep/handler/Handler.java
> +            if (session != null) {
isAlreadyLogin 같은 느낌으로 메서드 추출하면 의미 전달이 더 명확해질 것 같아요!
(저도 메서드 추출 안했는데.. 하러가야겠네요)

2023-09-04 08:57 UTC, xxeol2 commented on tomcat/src/main/java/nextstep/handler/Handler.java
> +            httpResponse.addHeader(HttpHeaders.LOCATION, "/500.html");
400 페이지 하나 만드시죠 ㅎㅎ ㅋㅋㅋㅋ
상태코드는 왜 200인가요?!

2023-09-04 08:57 UTC, xxeol2 commented on tomcat/src/main/java/nextstep/handler/Handler.java
> +        }
login 페이지에서 빈 칸으로 요청하면 어떻게될까요 ?!

2023-09-04 08:57 UTC, xxeol2 commented on tomcat/src/main/java/nextstep/handler/Handler.java
> +        }
얘도 마찬가지로 회원가입 페이지에서 빈 칸으로 요청하면 어떻게될까요 ?!

2023-09-04 08:57 UTC, xxeol2 commented on tomcat/src/main/java/nextstep/handler/Handler.java
> +        InMemoryUserRepository.save(new User(account, password, email));
사소한건데 이미 존재하는 account로 가입하려할 때 예외처리해주는건 어떤가요?!

2023-09-04 08:57 UTC, xxeol2 commented on tomcat/src/main/java/nextstep/handler/Handler.java
> +    }
얘도 사용하는 메서드 밑으로 옮겨주시면 읽을 때 더 편할 것 같아요!

2023-09-04 13:21 UTC, xxeol2 requested changes
구조에 대한 리뷰를 드리고 싶었는데, 이미 구조를 깔끔하게 잘 잡아주셨네요 👍
아래 리뷰들은 변경을 요구하는 건 아니고 3단계때 반영해주셔도 좋을 것 같아요!
앞서 남긴 소소한 리뷰들 반영해주시고 재요청 보내주세요!

2023-09-04 13:21 UTC, xxeol2 commented on tomcat/src/main/java/org/apache/coyote/http11/HttpRequest.java
> +    }
Response에서는 응답을 담아주기 위해 setter가 필요했지만, Request는 클라이언트의 응답을 엔티티로 변환한것이니 도중에 변하는 것 보다 불변 객체로 만들어주는 게 좋을 것 같아요!
생성자도 빈 생성자를 열어두고 헤더/바디를 넣어주는 구조보단, 생성할 때 헤더/바디를 초기화시키는게 좋지 않을까?라는 생각이 드는데 어떻게 생각하시나요!

2023-09-05 10:42 UTC, aak2075 commented on tomcat/src/main/java/org/apache/coyote/http11/util/HttpRequestReader.java
> +        final var bufferedReader = new BufferedReader(new InputStreamReader(inputStream));
내부 코드를 확인해 보니 inputStream의 close()는 closed = true 처리를 해줄 뿐이고 다른 작업을 하지 않네요. BufferedReader의 close()는 생성할때 파라미터로 받은 Reader인 in을 in.close()를 호출하고 null처리를 해주는 식으로 처리해주고 있네요!😱 요 친구도 함께 닫아주도록 하겠습니다.

2023-09-05 10:42 UTC, aak2075 commented on tomcat/src/main/java/org/apache/coyote/http11/util/HttpRequestReader.java
> +        final var splitLine = requestLine.split(" ");
아주 좋은 생각입니다💡

2023-09-05 10:42 UTC, aak2075 commented on tomcat/src/main/java/org/apache/coyote/http11/util/HttpRequestReader.java
> +    }
![image](https://github.com/woowacourse/jwp-dashboard-http/assets/35948985/11a5c8af-6bee-4643-b9c2-1be4433cfdd3)
bfs로 되어있었네요 dfs로 변경했습니다ㅎㅎㅎ

2023-09-05 10:42 UTC, aak2075 commented on tomcat/src/main/java/org/apache/coyote/http11/util/HttpRequestReader.java
> +    }
`ArrayIndexOutOfBoundsException`이 발생하는군요! 
```java
    private static Map<String, String> parseParameters(String queryString) {
        return Arrays.stream(queryString.split(QUERY_STRING_DELIMITER))
                .map(parameter -> parameter.split(KEY_VALUE_DELIMITER))
                .filter(keyValuePair -> keyValuePair.length == 2)
                .collect(Collectors.toMap(keyValuePair -> keyValuePair[0],
                        keyValuePair -> keyValuePair[1]));
    }
```
위와 같이 keyValuePair의 length가 2인지 검증하도록 변경했습니다~
고민을 하다 보니 HttpRequest를 읽는 `HttpRequestReader`에서 **파싱**을 하는 작업도 하는 것이 책임 분리가 필요하다고 생각하여 `HttpParser`를 만들어서 파싱하는 책임을 이 친구한테 넘겼습니다.

2023-09-05 10:42 UTC, aak2075 commented on tomcat/src/main/java/org/apache/coyote/http11/util/HttpRequestReader.java
> +            }
이거 누가 짰죠???👀

2023-09-05 10:43 UTC, aak2075 commented on tomcat/src/main/java/nextstep/handler/Handler.java
> +            httpResponse.addHeader(HttpHeaders.LOCATION, "/500.html");
~~오케이도 나쁘지 않죠~~
뷰도 추가하고 400으로 바꿨습니다

2023-09-05 10:43 UTC, aak2075 commented on tomcat/src/main/java/nextstep/handler/Handler.java
> +        }
`account=&password=` 이런 식으로 요청이 들어와서 ArrayIndexOutOfBoundsException이 발생하네요!!
자주 사용되는 body부분의 파싱이라 검증 로직을 추가하여 `HttpParser` 에서 다음과 같이 공통으로 처리하도록 변경했습니다~
```java
public static Map<String, String> parseFormData(String formData) {
    return Arrays.stream(formData.split(PARAMETER_SEPARATOR))
            .map(parameter -> parameter.split(KEY_VALUE_DELIMITER))
            .filter(keyValuePair -> keyValuePair.length == 2)
            .collect(Collectors.toMap(keyValuePair -> keyValuePair[0],
                    keyValuePair -> keyValuePair[1]));
}
```

2023-09-05 10:43 UTC, aak2075 commented on tomcat/src/main/java/nextstep/handler/Handler.java
> +        }
위에서 정의한 `HttpParser` 재사용👍

2023-09-05 10:43 UTC, aak2075 commented on tomcat/src/main/java/nextstep/handler/Handler.java
> +        InMemoryUserRepository.save(new User(account, password, email));
반영했습니다~
서비스 분리가 하고싶어지네요....ㅋㅋㅋㅋㅋ

2023-09-05 10:45 UTC, aak2075 commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +            HttpResponseWriter.write(outputStream, httpResponse);
영광입니다👍

2023-09-05 11:49 UTC, aak2075 commented on tomcat/src/main/java/org/apache/coyote/http11/HttpRequest.java
> +    }
오! Request는 불변이 충분히 가능하네요!!
다만, 파라미터가 너무 많아서 Builder를 통해 생성하도록 수정했습니다!
Response도 래핑을 한다거나 객체를 분리하면 가능할 것 같은데 요건 다음 단계에서 리팩토링하면서 고민해보곘습니다!

2023-09-05 12:03 UTC, aak2075 commented
축제처럼 뻥뻥 터져서 저도 버스터콜 이용해야겠네요.
부족한 점이 많았는데 애쉬가 꼼꼼히 피드백 해주셔서 많이 좋아졌습니다!
피드백을 반영하면서 `Handler`의 책임이 너무 많고 중복으로 사용되거나 하는 코드가 많았는데요,
뷰를 찾거나 바디에 메시지를 쓰는 등의 책임을 `ViewResolver`로 분리했습니다.
점진적으로 리팩토링하면서 핸들링하는 부분도 나누면 깔끔해질 것 같습니다.

2023-09-05 23:51 UTC, xxeol2 approved these changes
하산하시죠!
깔끔한 코드 잘 봤습니다 🕶
3-4단계때 뵙겠습니다아

2023-09-05 23:51 UTC, xxeol2 commented on tomcat/src/main/java/common/FileReader.java
> +    private static final String EXTENSION_HTML = ".html";
DEFAULT_FILE_EXTENSION 은 어떤가요?!
기본 확장자가 .html인걸 더 잘 알려주는 것 같아요!

2023-09-05 23:51 UTC, xxeol2 commented on tomcat/src/main/java/nextstep/mvc/ModelAndView.java
> +    private final Map<String, String> model = new HashMap<>();
좋은데요?

2023-09-05 23:51 UTC, xxeol2 commented on tomcat/src/main/java/nextstep/mvc/View.java
> +        }
early return 👍

2023-09-05 23:51 UTC, xxeol2 commented on tomcat/src/main/java/org/apache/coyote/http11/HttpRequest.java
> +        private String body;
Builder 👍
빌더가 여러 클래스에서 생길수도있으니 HttpRequestBuilder로 정확하게 명시해주는것도 좋을 것 같아요!

2023-09-05 23:53 UTC, merged