[톰캣 구현하기 1, 2단계] 애쉬(정설희) 미션 제출합니다.
woowacourse/jwp-dashboard-http pull request #338
Opened 2023-09-04 07:41 UTC by xxeol2

2023-09-04 14:35 UTC, yoondgu requested changes
안녕하세요 애쉬 🏹

정말 감탄하면서 봤습니다 ... 덕분에 좋은 코드 보면서 많이 배운 것 같아 감사해요!!
전체적으로 일관성 있게, 잘 설계해주신 것 같아요.
과하지 않으면서도 섬세하게 HTTP 서버를 구현해주셨다는 인상을 받았습니다.

SornaCube가 남겨준 내용, 개행 및 컨벤션에 대해서는 잘 아시리라 생각하고,
리팩터링 진행 예정이니 별도 코멘트 남기지 않았습니다!

실행해보니 기능도 잘 동작하고, 테스트 코드만 추가되면 정말 완벽하겠는데요 🫢
좋았던 부분과 같이 이야기하고 싶은 부분 위주로 가볍게 남겨보았으니 확인해주세요!

2023-09-04 14:35 UTC, yoondgu commented on tomcat/src/main/java/org/apache/coyote/http11/handler/StaticContentRequestHandler.java
> +	}
이 Handler에서는 항상 true를 반환하는 이유가 뭘까요 ?
path가 파일명을 가리키지 않고 있는 경우 (ex. `/wooteco`, 다른 핸들러에 매핑되지 않음)에도 true를 반환하는 것이 자연스러울까요?!

2023-09-04 14:35 UTC, yoondgu commented on tomcat/src/main/java/org/apache/coyote/http11/request/RequestBody.java
> +	private final Map<String, String> fields = new HashMap<>();
RequestBody의 내용이 항상 key=value 일까요? 물론 지금 요구사항에서는 적절하다고 생각합니다!  
하지만 자료구조로만 보면 RequestUri의 QueryParameter와 동일시할 수 있겠네요 !

2023-09-04 14:35 UTC, yoondgu commented on tomcat/src/main/java/org/apache/coyote/http11/response/Response.java
> +	private static final String CRLF = "\r\n";
System.lineSeperator() 를 사용하는 건 어떻게 생각하시나요 ?!

2023-09-04 14:35 UTC, yoondgu commented on tomcat/src/main/java/org/apache/coyote/http11/MimeType.java
> +	}
Text 여부까지.. 👍👍👍

2023-09-04 14:35 UTC, yoondgu commented on tomcat/src/main/java/org/apache/coyote/http11/MimeType.java
> +	}
MimeType까지 잘 고려해주셔서 애쉬의 HTTP 지식이 느껴집니다 😀
그런데 Java 기본 라이브러리에도 생각보다 File, Path 관련 제공 메서드들이 많더라구요.
그 중 이 부분을 조금 더 간단하게 해줄 수 있는 게 있을 것 같아요!

2023-09-05 13:09 UTC, xxeol2 commented on tomcat/src/main/java/org/apache/coyote/http11/handler/HandlerMapping.java
> +	}
HandlerMapping 클래스는 핸들러들을 맵핑만 해주는 역할인데, 인스턴스화가 되어야하나? 라는 의문에 handle 메서드를 static 메서드로 두게되었습니다!

handlers, defaultHandler 필드를 초기화해주는걸 필드에서 바로 해줄 수도 있고 static 블럭에서 해줄수도 있었는데, 필드에서 해주면 handlers가 길어질 경우 어떤 필드가 있는지 한눈에 파악하기 어려울 것 같아 static 블럭을 활용해보았습니다!!

2023-09-05 13:13 UTC, xxeol2 commented on tomcat/src/main/java/org/apache/coyote/http11/handler/RequestHandler.java
> +	}
함수형 인터페이스를 활용한 방식을 말씀하시는걸까요 ?!
사실 저도 모르게 실제 HttpServlet의 service() 메서드 구조를 따라가게된 것 같아요..
3단계 리팩토링 적용하면서 도이가 말씀해주신 방식 한 번 적용해보겠습니다 !!

2023-09-05 13:16 UTC, xxeol2 commented on tomcat/src/main/java/org/apache/coyote/http11/handler/HandlerMapping.java
> +			}
> 또, Map에 저장하는 대신 이렇게 순회해서 조회하는 방법을 선택하신 이유도 궁금합니다 !!
Map으로 저장하게 된다면 HandlerMapping이 requestPath를 아는 구조인데, 각 Handler가 관리하는게 더 좋지않을까 싶어서 순회를 돌게되었습니다.
하지만 지금 제 구조에서는 Handler 개수가 늘어남에따라 순회하는 비용이 들겠네요 🥲

2023-09-06 00:11 UTC, xxeol2 commented on tomcat/src/main/java/org/apache/coyote/http11/handler/StaticContentRequestHandler.java
> +	}
항상 true를 return 함으로써 StaticContentRequestHandler는 Default 핸들러로, 다른 핸들러와 맵핑되지 않는 모든 요청이 해당 핸들러로 들어가도록 의도했습니다!
하지만 해당 핸들러가 Default 핸들러로 사용되지 않을 가능성이 있기에, path가 파일명을 가리키는 경우 canHandle을 반환하도록 하는것이 좋아보이네요!

2023-09-07 00:49 UTC, xxeol2 commented on tomcat/src/main/java/org/apache/coyote/http11/handler/HandlerMapping.java
> +			}
> 또, Map에 저장하는 대신 이렇게 순회해서 조회하는 방법을 선택하신 이유도 궁금합니다 !!

각 Handler들의 requestPath는 해당 인스턴스 내부에서 관리하는 것이 좋다고 생각했습니다!
Map으로 저장하게되면 HandlerMapping에서 requestPath를 관리하는 구조가 될 것 같아, List를 순회하는 구조로 만들어보았습니다.
다만, Handler 개수가 많아짐에 따라 순회 비용이 든다는 단점이 있겠네요 🥲

도이의 리뷰를 보고 아래와 같은 방식으로 requestPath를 getter로 꺼내와 Map에 저장하는 방식으로 리팩토링을 진행해보았어요!
```java
handlers = Stream.of(
	new BaseRequestHandler(),
	new LoginRequestHandler(),
	new RegisterRequestHandler()
	).collect(Collectors.toMap(
	RequestHandler::getRequestPath,
	handler -> handler
	));
```
그런데 이렇게 하니, Handler 초기화 과정에서 가독성이 다소 떨어지는 느낌을 받았는데, 혹시 생각나는 좋은 방법이 있으면 추천부탁드려요 !!

2023-09-07 00:50 UTC, xxeol2 commented on tomcat/src/main/java/org/apache/coyote/http11/handler/HandlerMapping.java
> +			}
> 그렇다면, 중복된 REQUEST_PATH 를 가진 Handler를 작성하지 않도록 코드 레벨에서 방지할 필요는 없을까요?

Map 형식으로 저장하는 구조로 바뀌면서 해당 문제도 해결이 된 것 같아요!

2023-09-07 00:54 UTC, xxeol2 commented on tomcat/src/main/java/org/apache/coyote/http11/handler/StaticContentRequestHandler.java
> +	}
+) canHandle 메소드가 사라지면서 해당 로직도 사라졌습니다!

2023-09-07 14:55 UTC, xxeol2 commented on tomcat/src/main/java/org/apache/coyote/http11/MimeType.java
> +	}
덕분에 File,Path 관련 제공 메서드들에 대해서 찾아보고 학습했습니다 감사해요!
하지만 지금은 몇가지 파일 확장자만 지원하고 있기 때문에, String.endsWith로 검사해도 충분할 것 같다는 생각이 들어요!
이 부분은 3-4단계 진행하며 확장성있는 프로그램을 만드는 과정에서 함께 고민해보겠습니다!

2023-09-07 14:59 UTC, xxeol2 commented on tomcat/src/main/java/org/apache/coyote/http11/request/RequestBody.java
> +	private final Map<String, String> fields = new HashMap<>();
json 형식이나 다른 형식의 ResponseBody가 들어오면 오류가 나오겠군요 ... 🥲
그래서 Request Body에도 Content-Type이 존재하는거군요 .. ! 깊은 깨달음을 얻고갑니다!!!
이 부분도 3-4단계 진행하며 Content-Type에 따라 확장성있게 받을 수 있는 방법이 있는지 함께 고민해보겠습니다!

2023-09-07 15:08 UTC, yoondgu commented on tomcat/src/main/java/org/apache/coyote/http11/handler/RequestHandler.java
> +	}
네 그렇게도 할 수 있겠다고 생각해서 언급헀는데요.
사실 Http Method의 개수는 한정적이어서 굳이 Map을 두지 않고 if문 분기로 명시하는 것도 괜찮아보이긴 해요!
취향대로 하셔도 될 것 같습니다 ㅎㅎ

2023-09-07 15:10 UTC, yoondgu commented on tomcat/src/main/java/org/apache/coyote/http11/response/Response.java
> +	private static final String CRLF = "\r\n";
> 하지만, HTTP/1.1 프로토콜은 개행 문자로 CRLF를 사용한다고 합니다! 
헉 ! 몰랐던 사실이네요 !! 배워갑니다 ,, 저도 상수로 사용해야겠어요!

2023-09-07 15:30 UTC, yoondgu commented on tomcat/src/main/java/org/apache/coyote/http11/handler/HandlerMapping.java
> +			}
오 이런 방식도 있네요! 좋은 접근인 것 같아요. 배워갑니다 .. 👍👍
Map vs List 중 고민중이었는데 저도 좀 따라하겠습니닿

> 그런데 이렇게 하니, Handler 초기화 과정에서 가독성이 다소 떨어지는 느낌을 받았는데, 혹시 생각나는 좋은 방법이 있으면 추천부탁드려요 !!

가독성 문제에 대해서는 현재 최신 커밋 대로도 좋다고 생각합니다!
그래도 제안을 해본다면 `handler -> handler` 대신 `Function::identity`를 쓰면 어떨까? 싶기도 하네요 ~
handler 변수명을 명시하는 게 더 이해하기 쉬울 수도 있겠지만요

```java
public HandlerMapping(final Set<RequestHandler> handlers, final RequestHandler defaultHandler) {
        this.handlers = handlers.stream()
	        .collect(Collectors.toMap(
		        RequestHandler::getRequestPath,
		        handler -> handler
	        ));
        this.defaultHandler = defaultHandler;
}
``

2023-09-07 16:08 UTC, yoondgu approved these changes
수고 많으셨습니다 애쉬!! 
사실상 3단계도 완료하신 것 같네요 ㅎㅎㅎ
코드 너무 잘 봤습니다. 적절한 패키지 분리, 핸들러를 주입하는 부분이 특히 인상적이었어요.

지난 Request change도 몇 가지 생각 공유를 위한 것이었기 때문에, 
이번에는 남겨주신 코멘트에 대한 답변으로 마무리하고, 바로 머지하도록 할게요 !
다음 단계 기대하겠습니다 😬

2023-09-07 16:09 UTC, merged

2023-09-07 16:17 UTC, yoondgu commented on tomcat/src/main/java/org/apache/coyote/MimeType.java
> +	}
빼먹고 올린 코멘트가 하나 있어서 추가합니다 ㅎ.ㅎ

```java
	public static MimeType fromPath(final String path) {
		validatePath(path);
		
		return Arrays.stream(values())
			.filter(mimeType -> path.endsWith(mimeType.fileExtension))
			.findAny()
			.orElseThrow(() -> new IllegalArgumentException("지원하지 않는 파일 확장자입니다."));
	}
```
이렇게 해줘도 될 것 같아요 !