[톰캣 구현하기 - 1,2단계] 오잉(이하늘) 미션 제출합니다.
woowacourse/jwp-dashboard-http pull request #341
Opened 2023-09-04 07:52 UTC by hanueleee

2023-09-05 07:18 UTC, jundonghyuk requested changes
안녕하세요 오잉 코드 정말 잘 봤습니다 !
객체의 책임에 따른 분리가 되게 깔끔하네요 !
특히 `Request` 클래스내의 책임분리가 돋보여요..!

코드를 보면서 많이 배웠습니다 ㅎㅎ

개별 코드에 관련된 커멘트는 각각 남겨놨습니다 !

다음 리퀘스트 때 머지 하겠습니다 ! 커멘트 보시고 각자 생각하는 중요도의 차이가 있으니 반영은 자유롭게 해주시면 도리 것 같아요 !

고생하셨습니다 ~~

2023-09-05 07:18 UTC, jundonghyuk commented on tomcat/src/main/java/org/apache/coyote/http11/handler/RegisterHandler.java
> +            User user = new User(params.getParam(ACCOUNT), params.getParam(PASSWORD), params.getParam(EMAIL));
만약 쿼리파마라미터의 `key`로 `account` or `password` or `email`이 없다면 null로 되어 잘못된`User`  데이터가 들어갈것같아요 !
`QueryParams`가 반환하는게 객체 그자체가 아니라 `Optional`로 객체를 감아버리면 그것을 반환받아 사용하는 입장에서 어떠한 추가적인 처리를 더 할 수 있을 것 같아요 !

예를 들면 `params.getParam(Account).isEmpty()`이면 잘못된 요청이니 예외페이지로 `redirect`시킬 수도 있구요 !

어떻게 생각하시는지 의견을 듣고 싶어요 ~

2023-09-05 07:18 UTC, jundonghyuk commented on tomcat/src/main/java/org/apache/coyote/http11/util/Parser.java
> +        Map<String, String> cookies = new LinkedHashMap<>();
쿠키를 관리하는 맵은 `LinkedHashMap`을 사용한 이유가 있을까요 ?

`HashMap`과의 차이가 무엇일까요 ?

2023-09-06 10:44 UTC, hanueleee commented on tomcat/src/main/java/org/apache/coyote/http11/util/Parser.java
> +        Map<String, String> cookies = new LinkedHashMap<>();
`HashMap`과 `LinkedHashMap`의 가장 큰 차이는 순서를 유지할 수 있는가 없는가라고 생각합니다.

`HttpHeaders`라는 객체에서 순서를 보장하기 위해 LinkedHashMap을 사용했는데,
`Cookies`를 만드는 과정에서 무의식적으로 동일하게 작성한 것 같네요..ㅎㅎ
현재 Cookie는 순서를 보장할 필요가 없기 때문에 HashMap으로 가도 될 것 같습니다!

2023-09-06 10:49 UTC, hanueleee commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +            final var bufferedReader = new BufferedReader(new InputStreamReader(inputStream));
`InputStreamReader`를 통해 byte기반의 입력 스트림을 문자 기반의 입력 스트림으로 바꿀 수 있습니다.
`BufferedReader`를 통해 입력에 버퍼링을 적용하여 readLine()등의 메소드를 사용해 효율적으로 처리할 수 있습니다.

2023-09-06 10:54 UTC, hanueleee commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
`BufferedReader`를 인자로 넘긴 이유는 다음과 같습니다.

1. Http11Processor의 로직을 깔끔하게 가져가고 싶다.
2. BufferedReader를 넘겨서 `HttpRequest` 객체에게 책임(입력받은 값을 스스로 파싱하여 구성)을 확실히 부여하고 싶다. 

하지만 `BufferedReader`를 인자로 넘기다보니 `HttpRequest` 객체에 대한 테스트가 어려워지더라구요..
그래서 다른 크루들과 이야기를 좀 나눠봤는데,
'HttpRequest를 일종의 DTO로 생각한다면 굳이 의미있는 책임을 부여하지 않아도 된다.'라는 말을 듣고 고민중입니다..ㅎㅎ

하디는 둘 중 어떤 방식을 선택하셨고 그 이유가 뭔가요?!

2023-09-06 10:55 UTC, hanueleee commented on tomcat/src/main/java/org/apache/coyote/http11/common/request/HttpRequest.java
> +        this.sessionManger = new SessionManger();
오우 날카로운 하디ㅎㅎㅎ
감사합니다 😋

2023-09-06 11:01 UTC, hanueleee commented on tomcat/src/main/java/org/apache/coyote/http11/handler/HandlerFinder.java
> +    }
검색을 해보니 static 블럭 외에
1. 정적 메소드를 통한 초기화
2. 레이지 초기화
이 두가지 방법을 접했는데, 혹시 다른 방법도 있나요??

하디는 `Map`을 어떤 방식으로 초기화 했고, 그 이유는 무엇인가용??

2023-09-06 11:16 UTC, hanueleee commented on tomcat/src/main/java/org/apache/coyote/http11/handler/HandlerFinder.java
> +    }
사실 예전에 잠깐 봤던 Servlet 사용 코드에서 urlPatterns로만 매핑해주길래
미션을 진행하면서 큰 고민 없이 `URI`를 키로 잡았는데요..ㅎㅎ
하디의 질문을 듣고 생각해봤습니다!

`RequestURI + RequestMethod`로 구분 하면
1. 해당 URI에 대한 Method가 추가될 때마다 Map에 새롭게 put을 해줘야한다.
2. 해당 URI+Method에 대한 key가 존재하지 않을 경우,
해당 리소스가 존재하지 않아서인지(404 Not Found), 해당 리소스가 해당 메소드를 지원하지 않아서인지 (405 Method Not Allowed)에 대한 핸들링이 어렵다.

라는 단점이 떠오르네요!

반면 `URI`로만 판단하면
장점은 Map관리가 깔끔해진다, 단점으로는 Servlet 내부에서 메소드로 구분해야한다
라는 생각이 듭니다!

하디가 `RequestURI + RequestMethod`를 선택하신 이유는 뭔가용??

2023-09-06 11:43 UTC, hanueleee commented on tomcat/src/main/java/org/apache/coyote/http11/common/request/HttpRequest.java
> +        this.sessionManger = new SessionManger();
`SessionManager`의 `add`, `findSession`, `remove`을 static 메소드로 만드는건 어떠냐는 말씀이실까요?!

Map은 Static이지만, 메소드는 Static으로 만들지 않은 이유는 다음과 같습니다.
1. SessionManager는 그자체로 의미있는 책임을 가지는 객체인데 모든 메소드를 static으로 만들어버리면, 객체라기보다 util성 클래스가 되어버리는 느낌이 들었습니다.
2. 현재 SessionManager는 Manager 인터페이스를 구현한 객체입니다. SessionManager의 메소드를 static으로 바꿔버리면 Manager implements가 불가능합니다. 현재는 session에 대한 관리를 메모리에서 하는 객체(SessionManager)만 존재하지만, 후에 외부 저장소 등에서 세션을 관리하는 객체가 추가되는 등 여러가지를 고려한다면 Manager 인터페이스를 통한 추상화가 유의미하다고 생각합니다.

2023-09-06 12:48 UTC, hanueleee commented on tomcat/src/main/java/org/apache/coyote/http11/handler/HandlerFinder.java
> +        return handlers.getOrDefault(path, DEFAULT_HANDLER);
헉 생각도 못헀습니다..

확장자가 있을 경우 STATIC_RESOURCE_SERVLET을 반환하고,
handlers에서 찾을 수 없을 경우 NOT_FOUND_SERVLET을 반환하도록 수정했습니다!
감사합니다!!

2023-09-07 01:44 UTC, hanueleee commented on tomcat/src/main/java/org/apache/coyote/http11/handler/RegisterHandler.java
> +            User user = new User(params.getParam(ACCOUNT), params.getParam(PASSWORD), params.getParam(EMAIL));
오 생각지 못했던 부분이네요!!
말씀하신대로 getParam의 반환값을 `Optional`로 감는 것이 좋을 것 같아요!
null 처리가 참 어럽네요..🤣

2023-09-07 01:45 UTC, hanueleee commented on tomcat/src/main/java/org/apache/coyote/http11/handler/RegisterHandler.java
> +            User user = new User(params.getParam(ACCOUNT), params.getParam(PASSWORD), params.getParam(EMAIL));
param 중 하나로 empty면 400.html을 띄우도록 수정했습니다!

2023-09-07 04:26 UTC, hanueleee commented on tomcat/src/main/java/org/apache/coyote/http11/handler/LoginHandler.java
> +                .isPresent();
와 이 리뷰 진짜 정말 너무너무 날카롭고 좋아요......
false를 반환한 경우에는 DB에 없거나 수정된 경우니까 Session을 remove해주는게 좋을 것 같네요!!
감사합니다!!!

2023-09-07 04:30 UTC, hanueleee commented on tomcat/src/main/java/org/apache/coyote/http11/common/request/HttpRequest.java
> +            String sessionId = headers.getCookies().getCookie(SESSIONID);
이번 미션을 진행하면서 null 처리에 대한 부분이 너무 힘들었는데요..
기존 제 코드처럼 == null로 확인하거나 try-catch 보다는
말씀하신 `Optional` 사용이 훨씬 나은 것 같아요!!

null이 발생할 수 있는 모든 부분에 대해 Optional을 사용하여 보완했습니당!! 감사합니다!!

2023-09-07 06:03 UTC, hanueleee commented on tomcat/src/main/java/org/apache/coyote/http11/common/request/HttpRequest.java
> +            String sessionId = headers.getCookies().getCookie(SESSIONID);
(수정)
Optional<String>을 반환하는 메소드의 경우 String을 반환하되 .getOrDefault(name, "");로 처리했습니다!
String은 ""의 경우 .isEmpty()에 true를 반환하더라구요!

2023-09-07 12:07 UTC, jundonghyuk commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
저는 `Inputstream`으로 부터 끝까지 읽어 `String`으로 구성하게 끔 하는 역할을 하는 친구를 만들어줬습니다.
`HttpRequestReader`라는 클래스인데요. 읽어온 내용을 `HttpRequest`에 넘겨 `Http`형식으로 만들었습니다.

이렇게 한 이유는 `inputStream으로 부터 읽는다` 와 `그 내용으로 HttpRequest를 만든다`를 나누고 싶었기 때문이에요.

`inputStream`은 데이터를 읽는 수단이라고 생각하고 이런 수단에 `HttpRequest`의 생성을 맡기고 싶지 않았습니다.

2023-09-07 12:18 UTC, jundonghyuk commented on tomcat/src/main/java/org/apache/coyote/http11/handler/HandlerFinder.java
> +    }
```java
private static final Map<String, Handler> handlers = new ConcurrentHashMap<>(
            Map.ofEntries(
                    new AbstractMap.SimpleEntry<String, Handler>("/", new HelloHandler()),
                    new AbstractMap.SimpleEntry<String, Handler>("/login", new LoginHandler()),
                    new AbstractMap.SimpleEntry<String, Handler>("/register", new RegisterHandler())
            )
    );
```

저는 이런방식으로 초기화를 했는데요. 
`enrty`를 이용하여 초기화 할 수 있더라구요..?

근데 가독성이 떨어지는 것같고..  `static`블럭이 깔끔하고 나을것같다는 생각이 듭니다.

처음에는 `Map.of`를 생각했지만 인자로 10개의 `key value`쌍 밖에 받지 못해 쓰지 않았었습니다..ㅋㅋ

2023-09-07 12:19 UTC, jundonghyuk commented on tomcat/src/main/java/org/apache/coyote/http11/handler/HandlerFinder.java
> +    }
저도 고민고민하다 오잉께서 말씀해주신 2번의 이유를 근거로 `URI`만 가지고 key를 잡았습니다....

생각해보니 key값이 다른 이유가 2개라 예외 분기처리가 힘들더라구요..!

2023-09-07 12:45 UTC, jundonghyuk approved these changes
오잉 코드 잘봤습니다..!

진짜 코드 너무너무 깔끔해서 읽으면서 박수쳤습니다.

몇개 커멘트 남겼으니 확인 부탁드려요 !

이번단계는 머지하겠씀다 고생하셨어요 ~

2023-09-07 12:45 UTC, jundonghyuk commented on tomcat/src/main/java/org/apache/coyote/http11/servlet/RegisterServlet.java
> +    private static HttpResponse doGet() throws IOException {
static method인 이유가 있을까요 ? 밑에도 마찬가지입니다 !

2023-09-07 12:45 UTC, merged