[톰캣 구현하기 - 1,2단계] 이오(이지우) 미션 제출합니다.
woowacourse/jwp-dashboard-http pull request #343
Opened 2023-09-04 07:54 UTC by LJW25

안녕하세요 지토 🙂
이번 리뷰 잘부탁드립니다.
기능 구현은 완료하였지만 전체적으로 부족한 부분이 많네요.🥲 
부족한 테스트코드는 리팩토링 과정에서 구현하도록 하겠습니다. 

---
### 고려한 부분
- **쿠키**
  미션에서 `Cookie`를 별도의 클래스를 분리해 구현하였지만, 저의 경우 `Header`와 `QueryString`을 `Map<String, String>`으로 두고 있었기 때문에 이와 비슷한 구조&역할인 `Cookie` 또한 `Map`으로 구현하였습니다. 분리에서 오는 장점보다 관리해야할 클래스를 늘린다는 단점이 더 크게 느껴졌고, 통일성을 유지하는 것이 더 낫다고 생각해서요.
- **Processor**
  현재 `Processor`가 하는 일이 과도하게 많다는 생각이 들어 고민중에 있습니다. 여러 Handler 메소드를 사용하여 리팩토링 하였지만 아직 부족한 것 같아서요. (다음 단계의 미션으로 Controller를 구현하면 좀 나아질 것으로 예상되긴 합니다.) 지토는 현재 단계의 `Processor`가 충분하다고 느끼시나요? 혹은 더 간결해 질 수 있도록 역할을 분리해야한다고 생각하시나요?

2023-09-04 10:47 UTC, apptie requested changes
안녕하세요 이오! 
미션 고생하셨습니다 👍 

(테스트가 없다는 것만 빼면) 훌륭하게 코드를 작성하신 것 같습니다 

일단 이오의 의견이 궁금한 부분이 있어서 Request changes로 설정하도록 하겠습니다
리뷰는 뭐 이것저것 제안 드리기는 했는데 별 내용 없어서...적용하고 싶으신 부분만 적용해주시면 좋을 것 같습니다

고려한 부분의 경우 제 생각이 궁금하신?것? 같아서, 그에 대한 제 생각은 밑에다가 추가적으로 적어두도록 하겠습니다!

---

1. 쿠키
저도 헤더나 쿠키나 쿼리 스트링이나 아무튼 Map 구조라는 것에 동의합니다! 
통일성을 유지하는 것도 중요한 관점이라고 생각하고요 ㅎㅎ
다만 저는 헤더나 쿠키나 쿼리 스트링을 모두 별도의 래핑 클래스로 감싸주기는 했습니다.
감쌀 경우 가독성은 좋아지더라고요! 시간이 없어서 테스트 코드 작성할 때 후회하기는 했지만요...
예를 들어 헤더같은 경우는 적어도 하나 이상의 데이터가 필요한데 쿠키는 아예 값이 없는 빈 쿠키도 허용하기는 해서 이런 차이점을 좀 명확하게 표현하기 위해서는 감싸는게 더 잘 보이겠다 싶더라고요 ㅎㅎ
꺼내오는 메서드도 이름을 조금 더 명확하게 할 수 있었고...
근데 이건 개인 차이라 아무튼 이오가 선택하신 근거가 충분히 납득이 되어서 좋았습니다? 네 

2. `Processor`
확실히 담당하고 있는 일이 많기는 한 것 같습니다 
근데 말씀해주신 대로 Step3에서 개선될 내용이라 굳이 신경쓸 필요가 있을까? 싶기는 하네요...
결론만 말씀드리면 Step2에서는 이오가 해주신 것처럼 메서드 분리만으로 충분하다고 생각합니다!
여기서 클래스로 분리하게 되면 Step3의 내용을 침범하는 것이라고 생각합니다
하면 좋지만 굳이? 느낌...

2023-09-04 10:47 UTC, apptie commented on tomcat/src/main/java/org/apache/coyote/http11/request/Http11Request.java
> +public class Http11Request {
이름에 어떠한 `Http Version`을 사용하는지 표현하는 것 보다는 필드로 `Http Version`을 갖는다거나 하는 방식은 어떠신가요?

2023-09-04 10:47 UTC, apptie commented on tomcat/src/main/java/org/apache/coyote/http11/response/Http11Response.java
> +    private static final String LINE_SEPARATOR = "\r\n";
자주 사용되는 상수(`\r\n`, ` `, `:`, `;` 등등)은 별도의 상수용 클래스로 분리하는 방법은 어떠실까요?

톰캣도 org.apache.coyote.http11.Constants에서와 같이 자주 사용되는 문자열 등등은 상수용 클래스로 쓰고 있습니다 ㅎㅎ

2023-09-04 10:47 UTC, apptie commented on tomcat/src/main/java/org/apache/coyote/http11/request/Http11Request.java
> +            headers.put(header[0], header[1]);
이러한 인덱스 관련된 내용도 어떠한 의미를 갖는지 상수로 표현해보시는 방법은 어떠신가요?

2023-09-04 10:47 UTC, apptie commented on tomcat/src/main/java/org/apache/coyote/http11/response/Http11Response.java
> +    }
이 로직을 `Status enum`에 위임해도 좋을 것 같습니다!

2023-09-04 10:47 UTC, apptie commented on tomcat/src/main/java/org/apache/coyote/http11/response/Http11Response.java
> +    }
`getResponse()`에서만 호출되는 `private method`로 보이는데, 정렬을 통일해주시면 좋을 것 같습니다!

다른 코드를 보니 호출되는 메서드 밑에 위치해주시는 식으로 정렬해주신 것 같더라고요 ㅎㅎ

2023-09-04 10:47 UTC, apptie commented on tomcat/src/main/java/org/apache/coyote/http11/response/Http11Response.java
> +    }
추가적으로 `h`가 아마도 `header`의 `key`인 것 같은데, 조금 더 명확한 네이밍을 사용해주시는 건 어떨까 건의드려봅니다!

2023-09-04 10:47 UTC, apptie commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +                input.append(LINE_SEPARATOR);
```suggestion
                input.append(s)
                     .append(LINE_SEPARATOR);
```

요런 식으로 체이닝도 가능합니다!

2023-09-04 10:47 UTC, apptie commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +            throw new RuntimeException(e);
`Unchekced Exception`을 던져주는 것을 의도하신걸까요?

2023-09-04 10:47 UTC, apptie commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +
개행..? 제거..?

2023-09-05 08:30 UTC, LJW25 commented on tomcat/src/main/java/org/apache/coyote/http11/request/Http11Request.java
> +public class Http11Request {
스켈레톤 코드의 processor가 Http11Processor이고, 그냥 HttpRepsonse을 사용할 경우 자바에서 기본으로 제공하는 HttpResponse와 혼동의 여지가 있어서 Http11Response라는 네이밍을 사용하였습니다!
하지만 확장성을 위해서라면 버전을 별도로 관리하는게 낫겠네요. 😀

2023-09-06 08:58 UTC, LJW25 commented on tomcat/src/main/java/nextstep/jwp/service/UserService.java
> +        }
[refactor(UserService): Optional 사용 방식 변경](https://github.com/woowacourse/jwp-dashboard-http/pull/343/commits/e3c9eced63beb0bf7812370da67e7ab09f8bc0d6)

Optional을 잘 활용하지 못하고 있었던것 같네요, 감사합니다! 😀

2023-09-06 08:58 UTC, LJW25 commented on tomcat/src/main/java/nextstep/jwp/service/UserService.java
> +        if (InMemoryUserRepository.findByAccount(account).isPresent()) {
[refactor(UserService): Optional 사용 방식 변경](https://github.com/woowacourse/jwp-dashboard-http/pull/343/commits/e3c9eced63beb0bf7812370da67e7ab09f8bc0d6)

동일하게 반영하였습니다~

2023-09-06 08:59 UTC, LJW25 commented on tomcat/src/main/java/nextstep/jwp/service/UserService.java
> +        log.info(user.toString());
[refactor(all): 코드 리팩토링](https://github.com/woowacourse/jwp-dashboard-http/pull/343/commits/90b384e570013661c69a679737bc0a1f230bd43b)
code smell 없는 코드 좋네요..👍

2023-09-06 09:00 UTC, LJW25 commented on tomcat/src/main/java/nextstep/jwp/service/UserService.java
> +    private String setSessionWithUUID(final User user) {
[refactor(UserService): 메소드 네이밍 변경](https://github.com/woowacourse/jwp-dashboard-http/pull/343/commits/a35bb6fd02832dbe5a6b2f471d3671c14dd7a15c)

그렇네요! 미처 놓쳤던 부분이었습니다. 수정했습니다 :)

2023-09-06 09:02 UTC, LJW25 commented on tomcat/src/main/java/org/apache/coyote/http11/response/Http11Response.java
> +    private static final String LINE_SEPARATOR = "\r\n";
[refactor(Constant): 상수처리](https://github.com/woowacourse/jwp-dashboard-http/pull/343/commits/702c0b795f77439b21fed02a173dc6e7193b6ad5)

저도 해당 상수가 반복적으로 사용되는 탓에 클래스로 분리 할까말까 고민했었어서, 지토 의견보고 바로 반영했습니다ㅎㅎ

2023-09-06 09:03 UTC, LJW25 commented on tomcat/src/main/java/org/apache/coyote/http11/request/Http11Request.java
> +            headers.put(header[0], header[1]);
[refactor(Constant): 상수처리](https://github.com/woowacourse/jwp-dashboard-http/pull/343/commits/702c0b795f77439b21fed02a173dc6e7193b6ad5)

적용해봤습니다! 직접 적용해보니 의미가 명확하다는 장점이 있지만, 한번만 사용되는 상수가 너무 많아진다는 단점도 있는 것 같네요. 어느쪽이 나을지는 더 고민해 봐야 할 것 같습니다ㅎㅎ

2023-09-06 09:05 UTC, LJW25 commented on tomcat/src/main/java/org/apache/coyote/http11/response/Http11Response.java
> +    }
[refactor(Status): status 메소드 위치 변경](https://github.com/woowacourse/jwp-dashboard-http/pull/343/commits/d62ae1128442339a39689e9a778480d29580b9b1)

formatHeader와 비슷한 역할이라서 고민을 했지만? 역시 status enum이 있는 상황에서 굳이 따로둘 이유가 없다는 생각이 들어서? 반영했습니다 ~~ 😄

2023-09-06 09:07 UTC, LJW25 commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +            response.addHeader("Content-Type", "text/css;charset=utf-8 ");
[feat(*Header): Header Enum 구현](https://github.com/woowacourse/jwp-dashboard-http/pull/343/commits/a0b819ca5713d9853810589bbf41142b4f94cd80)

Header를 enum으로 구현하였습니다. 구현 과정에서 ResponseHeader와 RequestHeader를 합쳐야하나 고민을 많이 했지만 각각 사용되는 헤더의 종류가 달라 구분을 주는 것이 명확하다고 생각하여 따로 두었습니다. 두 enum이 공통된 부분이 많아 상속으로 구현하고 싶었는데 enum은 상속을 적용할 수 없어 아쉽네요..🫠

2023-09-06 09:08 UTC, LJW25 commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +            throw new RuntimeException(e);
[refactor(Http11Processor): 예외 처리 방식 변경](https://github.com/woowacourse/jwp-dashboard-http/pull/343/commits/de9920224e9609ae6a18929e7742a9337ce5a8c5)

이 부분도 위의 메소드와 동일하게 로그를 남기도록 변경하였습니다!

2023-09-06 09:12 UTC, LJW25 commented on tomcat/src/main/java/org/apache/coyote/http11/SessionManager.java
> +public class SessionManager {
SessionManager가 가진 Session이 static이고, 포함된 메서드들이 내부 상태에 따라 동작이 달라지는 메소드는 아니라고 생각해서 static으로 관리하였습니다!
실제로 Tomcat이 Session을 어떻게 관리하는지는 미처 알아보지 못했는데, 학습해 보도록 하겠습니다. 감사합니다😁

2023-09-06 09:52 UTC, apptie approved these changes
고생하셨습니다!

테스트 코드도 추가되었고, 리펙토링한 내용도 충분히 좋게 작성해주신 것 같아서 approve를 하도록 하겠습니다

이오가 진행하실 3단계가 기대되네요 ㅎㅎ 
화이팅입니다!

2023-09-06 09:52 UTC, apptie commented on tomcat/src/test/java/nextstep/org/apache/coyote/http11/Http11ProcessorTest.java
> +            assertThat(socket.output()).contains("Location: /index.html");
<img width="1007" alt="스크린샷 2023-09-06 오후 6 40 25" src="https://github.com/woowacourse/jwp-dashboard-http/assets/57691173/941b257b-c0d1-4b83-8db0-2891184126f7">

`SoftAssertions`를 사용하신다면, `softly`와 체이닝을 하지 않으면 위 사진처럼 틀린 내용을 처음 하나밖에 알려주지 않습니다!

또한 assertThat()contains()는 체이닝이 가능해서, 다음과 같이 작성하실 수도 있을 것 같습니다!

<img width="751" alt="스크린샷 2023-09-06 오후 6 41 29" src="https://github.com/woowacourse/jwp-dashboard-http/assets/57691173/fc9f313d-d43e-4f36-bd38-779df1dbb3bf">

2023-09-06 09:53 UTC, merged