[톰캣 구현하기 1 & 2단계] 바론(이소민) 미션 제출합니다.
woowacourse/jwp-dashboard-http pull request #352
Opened 2023-09-04 08:08 UTC by somsom13

안녕하세요 홍고! 🍊 🟠 🧡 
바론입니다 🐈 😸 

톰캣 구현하기 1단계, 2단계 구현했는데요... 아직 리팩터링이 되지 않은 상태라 책임 분리가 잘 안 되어있습니다 ㅎㅎ (특히 Http11Processor에서 수많은 if문 분기를 처리하고 있습니다 하하...)
이 부분은 3단계 때 리팩터링 하면서 고쳐보겠습니다 🙇 

리뷰 잘 부탁드립니다~!!

2023-09-05 17:47 UTC, hgo641 reviewed
아앗... Comment로 남겨버렸다...

2023-09-05 17:47 UTC, hgo641 commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +            return httpResponse;
`login`메소드가 session객체를 반환하고 있군요! 그런데 session은 login메소드의 결과값이라고 던져주기에 조금 애매한 것 같아요. 
session에는 login과 관련된 값(user)외에도 다양한 데이터들을 저장하고 있어서 login메소드의 반환값으로 지정하는 것이 조금... 아쉬?워요!

session이라는 객체의 활용도가 커보여서, login메소드 이전에 session객체를 get해와 접근할 수도 있을 것 같아요. 이 때 login메소드의 반환값이 session이라면 login메소드 이전에 get해온 session과 login메소드의 반환값인 session을 합쳐야할 경우가 생길수도 있을 것 같아요.

`User`객체나 아예 `HttpResponse`를 던져주는 게 더 명확할 것 같아요. 물론 저만의 생각입니다...ㅎㅎ 바론의 생각이 궁금하네요! (이렇게 하면 try밖에서 먼저 Session을 선언하는 것도 지울 수 있을 것 같아요!)

2023-09-05 17:47 UTC, hgo641 commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +                return HttpResponse.ofFile(HttpStatus.CONFLICT, getFilePath("/login.html"), httpRequest);
오 CONFLICT status처음 알았어요....ㅋㅋ 배워갑니다 👍

2023-09-05 17:47 UTC, hgo641 commented on tomcat/src/main/java/org/apache/coyote/http11/message/HttpMethod.java
> +            .findAny()
ContentType에서는 findFirst()로 찾으셨는데, 여기서는 findAny()로 찾으신 이유가 있나요?

2023-09-05 17:47 UTC, hgo641 commented on tomcat/src/main/java/org/apache/coyote/http11/message/HttpHeaders.java
> +        final Map<String, String> headersWithValue = new LinkedHashMap<>();
LinkedHashMap으로 하신 이유가 궁금합니다! 테스트때문이신가요? (전 그렇습니다...ㅎㅎ)
근데 바꾸면서 현재 테스트를 통과시키기위해 LinkedHashMap으로 바꾸는 게 맞나... 싶었어요 ㅋㅋ 물론 시간이 없어서 저도 LinkedHashMap으로 할당하긴했습니다...ㅎㅎ

2023-09-05 17:47 UTC, hgo641 commented on tomcat/src/main/java/org/apache/coyote/http11/message/HttpHeaders.java
> +    }
👍

2023-09-05 17:47 UTC, hgo641 commented on tomcat/src/test/java/org/apache/coyote/http11/message/ContentTypeTest.java
> +    @DisplayName("일치하는 ContentType이 없다면 HTML 타입을 반환한다.")
ContentType이 text/html이면 어떤 파일이든 전부 처리할 수 있을까요?

2023-09-05 18:41 UTC, hgo641 requested changes
안녕하세요 바론:smile: 바론의 리뷰어가 되어서 굉장히 기쁩니다. ^^
코드 보면서 많이 배웠습니다. HttpRequest와 HttpResponse를 생성하는 로직이 잘 분리되어 있어서 이해하기 쉬웠어요!

3단계때 책임분리를 리팩토링하실거라고 해주셔서 넘 기대가 되네요
간단한 질문 몇 개 남겼으니 확인부탁드려요! 

미션하시느라 고생많으셨습니다 :smile::smile::+1:

2023-09-05 18:41 UTC, hgo641 commented on tomcat/src/test/java/org/apache/coyote/http11/message/ContentTypeTest.java
> +    @DisplayName("Accept Type에 맞는 ContentType을 찾아온다.")
시간이 괜찮으시다면 parametrized 테스트로 해도 좋을 것 같네요!😄

2023-09-05 18:41 UTC, hgo641 commented on tomcat/src/main/java/org/apache/coyote/http11/session/Cookie.java
> +                Collectors.toMap(cookieValue -> cookieValue[0], cookieValue -> cookieValue[1])
```java
final Map<String, String> namesWithValue = Arrays.stream(headerCookieLine.split(COOKIE_DELIMITER))
    .map(cookieWithValue -> cookieWithValue.split(COOKIE_NAME_VALUE_DELIMITER))
    .collect(Collectors.toMap(cookieValue -> cookieValue[0], cookieValue -> cookieValue[1]));
```
collect()부분 한 줄에 있는 게 더 이쁜 것 같은데 어떠신가요?? 아니면 띄우신 이유가 있으신가요?

2023-09-05 18:41 UTC, hgo641 commented on tomcat/src/main/java/org/apache/coyote/http11/session/Cookie.java
> +                Collectors.toMap(cookieValue -> cookieValue[0], cookieValue -> cookieValue[1])
`cookieValue` 이름이 key:value중 value만을 의미하는 것 같아서 조금 헷갈릴수도 있을 것 같아요! (같은 메소드 안에 있는 `namesWithValue` 랑 `cookieWithValue` 때문에 더 헷갈리는 것 같아요.)

`cookiePair` 같은 이름은 어떨까요...?ㅎㅎ 중요한 부분은 아니니 편하게 반영해주세요

2023-09-05 18:41 UTC, hgo641 commented on tomcat/src/main/java/org/apache/coyote/http11/message/ContentType.java
> +    }
`HttpMethod`랑 `HttpProtocol`에서는 findAny()로 찾으셨는데 여기는 findFirst()로 하신 이유가 있나요?

2023-09-06 01:17 UTC, somsom13 commented on tomcat/src/main/java/org/apache/coyote/http11/message/QueryParams.java
> +        final String[] params = queryString.split(PARAMS_DELIMITER);
`mapToQueryParamMap` 을 호출하는 메서드인 `from` 메서드에서 `Optional<String>` 에 대해 `orElse(Collections.emptyMap())` 으로 처리해주고 있기 때문에

Optional이 empty인 상황에 대한 처리도 됩니다!

(`QueryParamsTest` 의 `from_notExist()` 테스트에 해당 경우에 대한 테스트가 있습니다 ㅎㅎ)

2023-09-06 01:19 UTC, somsom13 commented on tomcat/src/main/java/org/apache/coyote/http11/message/ContentType.java
> +    public static ContentType findResponseContentTypeFromRequest(final HttpRequest httpRequest) {
인자가 불변인데 final 키워드가 붙어있지 않은거라면 그저 저의 실수입니다 :) 
이번에 같이 수정하겠습니다 ㅎㅎ

2023-09-06 01:20 UTC, somsom13 commented on tomcat/src/main/java/org/apache/coyote/http11/message/RequestLine.java
> +    public Optional<String> parseFileExtensionFromPath() {
좋습니다~~
다시 보니까 메서드명을 저렇게 지으면 파라미터로 Path를 받아야할 것 처럼 생겼네용

2023-09-06 04:49 UTC, somsom13 commented on tomcat/src/main/java/org/apache/coyote/http11/message/ContentType.java
> +            .orElse(ALL);
Accept 헤더는 현재 받아오고자 하는 데이터가 무엇인지에 따라서 브라우저가 결정해주는 헤더 값이라고 합니다! (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept)
Accpet 헤더에 담긴 콘텐츠 타입으로 클라이언트가 처리할 수 있는 응답 데이터 타입을 제한해두는 것으로 이해하면 된다고 합니다. 
그리고 Accept 헤더가 없는 Request는 "User Agent가 어떠한 미디어 타입의 응답도 받을 수 있다는 의미라고 하네용. ([RFC7231](https://datatracker.ietf.org/doc/html/rfc7231#section-5.3.2))
만약 Request에 담겨있던 Accept Header 중 서버가 반환할 수 있는 타입이 없다면 406 (Not Acceptable)을 반환하거나, 응답할 body가 없는 것 처럼 응답을 보낸다고 합니다!

제가 생각하기로는 Accept 헤더에 담긴 type이 있다면 이에 맞는 Content Type을 보내는 것이 맞을 것 같습니다 ㅎㅎ (처리할 수 없는 타입이라면 애초에 406으로 응답을 보내는 것이 맞을 것 같구요!)

2023-09-06 07:08 UTC, somsom13 commented on tomcat/src/main/java/org/apache/coyote/http11/message/ContentType.java
> +        return findContentTypeFromRequestPath(httpRequest.getRequestLine());
https://github.com/woowacourse/jwp-dashboard-http/pull/352#discussion_r1316721458

위 코멘트랑 연관된 답변일 것 같습니다.

Accpet 헤더가 "이 클라이언트가 처리할 수 있는, 원하는 response 타입을 제한지어서 담는다" 라는 의미를 가지는 만큼, 이를 판단해서 보내주는 것이 맞을 것 같아요!
`주소/index.html` 로 보내는 요청도 브라우저가 요청 경로를 기반으로 Accept헤더를 따로 지정해주기 때문에 Accept 헤더의 우선순위가 더 높지 않을까 싶습니다.

그리고 요청 경로가 반드시 파일 확장자로 끝나지 않는 동적인 요청인 상황에서 따로 Accept헤더가 정해지는 상황도 있을 것 같아요. 이 때는 반드시 Accept 헤더로 응답 type을 판단해야 하지 않을까 싶어요!

2023-09-06 07:14 UTC, somsom13 commented on tomcat/src/main/java/org/apache/coyote/http11/session/Cookie.java
> +package org.apache.coyote.http11.session;
이번 미션에서는 쿠키가 항상 세션이랑 연결되어서 사용되기 때문에 한 패키지 내에 묶어두었습니다. (그리고 그 이후에 패키지 분리를 깜빡하고 하지 않았습니다 😅 😅 ) 

생각해보니 쿠키는 HTTP Message에서 쓰이는 값이니까 HTTP Message를 관리하는 패키지에 두어도 괜찮을 것 같아요! 홍고의 생각은 어떠신가요?

2023-09-06 07:15 UTC, somsom13 commented on tomcat/src/main/java/org/apache/coyote/http11/message/HttpResponse.java
> +    }
멋지네요
아니면 세션을 통해서 쿠키를 설정해준다는 의미이니까 `setCookieBySession` 으로 지어도 될 것 같은데 어떠한가요?

2023-09-06 07:23 UTC, somsom13 commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +            return httpResponse;
어렵네용... 저도 `login` 이라는 메서드는 단순히 동작만 해야 할 것 같은데, `session` 이라는 결과값을 던져주는 것은 
1. 해당 메서드를 사용하는 입장에서 예상치 못한 return값으로 여겨질 수 있을 것 같고
2. 단순히 로그인을 하는 것 말고 세션까지 생성하는 너무 많은 동작을 하는 것이 아닐까? 
라는 생각이 들었어요.

그리고 홍고 말대로 `session`이 단순히 사용자 말고 다른 정보들을 저장할 수도 있는 것이고, Request의 쿠키 헤더에 담긴 값을 통해서 로그인 여부와 상관없이 세션을 꺼내올 수도 있겠네요!

로그인 메서드가 할 수 있는 동작들과 말씀해주신 걸 생각해보면 `User` 객체를 반환하는 것이 가장 좋을 것 같습니다 ㅎㅎ
예리한 답변 감사합니다 💋 😗 😚 😘 🍊

2023-09-06 07:24 UTC, somsom13 commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +                return HttpResponse.ofFile(HttpStatus.CONFLICT, getFilePath("/login.html"), httpRequest);
영광이네요 😊

2023-09-06 07:41 UTC, somsom13 commented on tomcat/src/test/java/org/apache/coyote/http11/message/ContentTypeTest.java
> +    @DisplayName("일치하는 ContentType이 없다면 HTML 타입을 반환한다.")
text/html이면 의도한 데이터 형식으로 응답을 보낼 수는 없을 것 같아요. (ex. JSON 포맷의 데이터인데 html로 화면에 보여지는 응답이 간다.) 
그래도 우선 text/html로 기본 응답 타입을 결정해두면 적어도 "문자열로 라도 데이터를 전달할 수 있겠다" 라는 생각에 저 방식을 선택하긴 했어요! 

> If the header field is present in a request and none of the available representations for the response have a media type that is listed as acceptable, the origin server can either honor the header field by sending a 406 (Not Acceptable) response or disregard the header field by treating the response as if it is not subject to content negotiation.

하지만 공식 문서에 이렇게 명시되어 있는 것을 보았을 때, 서버에서 지원하는 Content Type이 아니라면 차라리 예외를 발생시키고 이 예외에 대해서는 
1. 406
2. 빈 body 응답
을 반환하도록 처리하는 것이 더 나을 것 같기도 하네요.

그리고 html로 응답을 보내버리면 사용자가 보는 화면에 의도치 않은 데이터가 노출되는 문제가 생길 것 같기도 하네용 ㅎㅎ
1번 방식으로 변경해보겠습니다!

2023-09-06 07:42 UTC, somsom13 commented on tomcat/src/test/java/org/apache/coyote/http11/message/ContentTypeTest.java
> +    @DisplayName("Accept Type에 맞는 ContentType을 찾아온다.")
build.gradle에 `@ParameterizedTest` 를 쓸 수 있는 의존성이 없어서 우선은 의존성을 수정하지 않기 위해 전부 분리했었습니다.....^///^

그런데 모두 똑같은 테스트여서 해당 방식으로 변경하는 것이 좋을 것 같습니다. 감사합니다!

2023-09-06 09:15 UTC, somsom13 commented on tomcat/src/main/java/org/apache/coyote/http11/message/HttpHeaders.java
> +        final Map<String, String> headersWithValue = new LinkedHashMap<>();
똑같습니다..^^ 테스트를 실패하는 상황 때문에 LinkedHashMap을 사용했습니다..

그런데 변경하고 생각해보니, LinkedHashMap이 아닌 HashMap을 사용하는 것이 더 좋을 이유가 떠오르지 않는 것 같아요.

성능을 고려해보면 LinkedHashMap과 HashMap의 성능이 큰 차이가 없다고 하고, 오히려 Map에 있는 값을 순회하는 상황에서는 LinkedHashMap이 성능이 조금 더 좋다고 하더라구요!

아니면 HashMap으로 활용하고 테스트 시에 header를 각 라인을 파싱해서 정확히 해당 라인들만 contain 하는지 확인하면 될 것 같기도 하네요!

혹시 홍고는 어떻게 생각하시나요?

2023-09-06 09:21 UTC, somsom13 commented on tomcat/src/main/java/org/apache/coyote/http11/session/Cookie.java
> +                Collectors.toMap(cookieValue -> cookieValue[0], cookieValue -> cookieValue[1])
좋습니다~! 사실 별 의미없이 라인이 너무 길어지는 것 같아서 남겼어용 ㅎㅎ 감사합니다! 😄

2023-09-06 09:22 UTC, somsom13 commented on tomcat/src/main/java/org/apache/coyote/http11/session/Cookie.java
> +                Collectors.toMap(cookieValue -> cookieValue[0], cookieValue -> cookieValue[1])
야무진 이름이라고 생각합니다! 똑같은 의미의 개념이 자꾸 들어가다보니 어떤 이름을 할지 고민됐어요ㅎㅎ

감사합니다 🙇‍♀️

2023-09-06 09:22 UTC, somsom13 commented on tomcat/src/main/java/org/apache/coyote/http11/message/ContentType.java
> +    }
없습니다.. findAny로 통일하는 것이 더 좋을 것 같아요! 👍 👍

2023-09-07 02:43 UTC, somsom13 commented on tomcat/src/main/java/org/apache/coyote/http11/message/HttpResponse.java
> +    }
`setJSessionCookieBySession` 으로 변경했습니당 ^__^

2023-09-07 04:10 UTC, hgo641 commented on tomcat/src/main/java/org/apache/coyote/http11/session/Cookie.java
> +package org.apache.coyote.http11.session;
저도 message 패키지 좋은 것 같아요!!

2023-09-07 04:26 UTC, hgo641 commented on tomcat/src/main/java/org/apache/coyote/http11/message/HttpHeaders.java
> +        final Map<String, String> headersWithValue = new LinkedHashMap<>();
저도 바론의 의견에 동의합니다!ㅎㅎ

헤더의 순서를 유지하고 싶다면 LinkedHashMap을, 아니라면 HashMap을 사용하면 좋을 것 같아요! 바론 말처럼 LinkedHashMap이 값 순회할 때는 성능이 좀 더 좋고 순서 유지가 가능하지만, HashMap보다는 메모리를 더 차지한다는 단점이 있어서 트레이드 오프인 것 같습니다.

저는 헤더의 순서를 유지하진 않아서 그냥 HashMap쓰긴 했는데, 제 리뷰어 포이센세의 말에 의하면 특정 데이터가 앞에 있는 게 좋다고 하시더라고요 ㅎㅎ 리뷰의 선순환~ 순서 지정하고 싶으면 LinkedHashMap이 좋을 것 같아요
> [RFC 7230](https://datatracker.ietf.org/doc/html/rfc7230#section-3.2.2) 에서는 헤더의 순서는 보장할 필요 없으나, message 를 더 빨리 처리할 수 있게 하는 control data는 앞에 놓는 것이 좋은 형태라고 말하고 있네요!

테스트도 동의합니다 ㅎㅎ! 지금 테스트 방식은 HttpHeaders의 순서에 의존하고 있어서 contain으로 검사하는 게 편할 것 같아요!

2023-09-07 04:33 UTC, hgo641 commented on tomcat/src/main/java/org/apache/coyote/http11/message/ContentType.java
> +            .orElse(ALL);
헉 긴 설명 감사합니다! 덕분에 Accept헤더에 대해 잘 이해하게 되었어요ㅎㅎ

Accept헤더에 담긴 type으로 반환해줘야한다는 것 동의합니다!
다만 지금 코드에서는 Accept헤더의 첫 번째 value를 반환해주고 있는 것 같아서, Accept헤더의 첫 번째 value가 항상 현재 반환할 file의 contentType가 일치하는 지 궁금했어요! 

Safari의 경우 image를 요청할 때 Accept 헤더 값이 디폴트로 `image/webp,image/png,image/svg+xml,image/*;q=0.8,video/*;q=0.8,*/*;q=0.5` 이렇게 설정된다는데, 실제 서버가 반환할 이미지의 확장자가 webp가 아니라 png나 jpg일 경우 호환이 잘 되는지가 궁금했어요!
(물론...ㅎㅎ 지금 코드의 경우 webp Content-Type이 없어서 실제 파일의 확장자명에서 추출하는 방식으로 되겠지만...ㅎㅎ)

Accept를 사용할 거면 첫 번째 value를 가져오는 게 아니라 전체 values들 중에서 실제 file의 Content-Type과 일치하는 것을 반환해줘야하는 거 아닌가요?

2023-09-07 04:37 UTC, somsom13 commented on tomcat/src/main/java/org/apache/coyote/http11/message/ContentType.java
> +            .orElse(ALL);
맞습니닼ㅋㅋㅋ 사실은 여러 값들이 들어오면 첫 번째 값들부터 돌면서 서버가 지원할 수 있는 Content Type을 찾아야 합니다.
다만 이번 미션에서는 그럴 상황이 없어서 첫 번째 값으로 처리하도록 설정해두었습니다 ㅎㅎ 추후 확장성을 고려해서 수정하는 방법으로 고려해보겠습니다!

2023-09-07 04:38 UTC, hgo641 approved these changes

2023-09-07 04:39 UTC, merged