[톰캣 구현하기 - 1,  2단계] 그레이(김동욱) 미션 제출합니다.
woowacourse/jwp-dashboard-http pull request #367
Opened 2023-09-04 08:34 UTC by Kim0914

안녕하세요 이리내 !
리뷰 잘 부탁드립니다 ㅎㅎ

우선 큰 구조는 다음과 같습니다.

1. HttpRequest에서 URL 추출
2. URL에 해당하는 핸들러 찾기
3. 핸들러를 이용해 요청 처리 후 HttpResponse 반환

시간이 조금 부족해서 리다이렉트 부분과 테스트를 꼼꼼히 작성하지 못했어요 😅
리뷰 반영할 때 보충해서 추가할게요 ~~

감사합니다 🙇🏻

2023-09-05 06:47 UTC, hectick requested changes
안녕하세요 그레이~
클래스 분리를 적절히 해주신 덕분에 흐름을 따라가면서 코드 리뷰를 수월하게 할 수 있었습니다!

포스트맨도 돌려보고, 궁금한점이나 개선했으면 하는 점 몇자 남겨보았는데요,
그래서 해야할일이 좀 늘었을 수도 있겠습니다만 적절히 셀렉해서 반영해주시면 되겠읍니다~

한번 쭉 보시고 수정할 부분 수정하셔서 pr 요청 주시면 마지할게요!

2023-09-05 06:47 UTC, hectick commented on tomcat/src/main/java/org/apache/handler/FileHandler.java
> +    }
Get 요청이 아니라 Delete 요청이 들어와도 동작하는 이 상황, 괜찮은 것인가요?
<img width="1097" alt="image" src="https://github.com/woowacourse/jwp-dashboard-http/assets/62106852/1926646c-2ef5-4bb0-b4e3-cee7559cfd31">

2023-09-05 06:47 UTC, hectick commented on tomcat/src/main/java/org/apache/handler/LoginHandler.java
> +    }
좋네요👍

2023-09-05 06:47 UTC, hectick commented on tomcat/src/main/java/org/apache/handler/LoginHandler.java
> +            LOG.info("user : {}", user);
오 이렇게 로깅할 수 있었다니
하나 알아갑니다

2023-09-05 06:47 UTC, hectick commented on tomcat/src/main/java/org/apache/request/HttpLine.java
> +    }
애플리케이션을 실행하다보면 line이 null값으로 들어오는 경우도 있어요!
<img width="802" alt="image" src="https://github.com/woowacourse/jwp-dashboard-http/assets/62106852/c91b5917-c42d-478e-8afb-f5ca04d522fb">

2023-09-05 06:47 UTC, hectick commented on tomcat/src/main/java/org/apache/handler/LoginHandler.java
> +        }
Cookie 헤더에 JSESSIONID가 존재하지만 그 값이 SessionManager에는 없는 이상한 값이라면 어떻게 해야할까요
<img width="998" alt="image" src="https://github.com/woowacourse/jwp-dashboard-http/assets/62106852/4efc5ba0-b80d-408c-af11-2f44daac5bbf">

2023-09-05 06:47 UTC, hectick commented on tomcat/src/main/java/org/apache/common/ContentType.java
> +                .filter(contentType -> Objects.equals(contentType.getValue(), value))
getValue()대신 그냥 value를 쓸 수 있는걸요~
```suggestion
                .filter(contentType -> Objects.equals(contentType.value, value))
```

2023-09-05 06:47 UTC, hectick commented on tomcat/src/main/java/org/apache/common/ContentType.java
> +    PERMIT_ALL("*/*");
permit all.. 좋네요 메모..

2023-09-05 06:47 UTC, hectick commented on tomcat/src/main/java/org/apache/common/HttpStatus.java
> +    CONFLICT("409");
CONFLICT는 어떤 상황에 필요한 것인지 궁금해요

2023-09-05 06:47 UTC, hectick commented on tomcat/src/main/java/org/apache/response/HttpResponse.java
> +    }
ContentType 필드를 headers 안에 저장하는데, 따로 필드로 들고있는 이유가 있나요?

2023-09-05 06:47 UTC, hectick commented on tomcat/src/main/java/org/apache/common/Content.java
> +public class Content {
안쓰는 클래스 같아용
무슨 용도였나요?

2023-09-05 07:37 UTC, Kim0914 commented on tomcat/src/main/java/org/apache/handler/LoginHandler.java
> +        }
역시 꼼곰하게 잘 봐주셨네요 ㅎㅎ

session을 가져와서 user를 가져오는 검증까지 추가했습니다 ~

2023-09-05 08:39 UTC, Kim0914 commented on tomcat/src/main/java/org/apache/common/HttpMethod.java
> +                .filter(httpMethod -> Objects.equals(httpMethod.name, value))
null 안정성을 위해서 Objects.equals를 주로 사용합니다.

A.equals(B)에서 A가 상수이거나 null safe 하다면 문제가 되지 않지만, A가 null이면 NullPointerException이 발생할 수 있어서요 !

2023-09-05 08:40 UTC, Kim0914 commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +            HttpRequest httpRequest = HttpRequest.of(bufferedReader);
네(four 아니고 yes)

2023-09-05 12:02 UTC, Kim0914 commented on tomcat/src/main/java/org/apache/handler/FileHandler.java
> +    }
뷰를 요청하는 가능성이 있는 GET, POST 제외하고는 405를 응답하도록 변경해보았습니다 ~

2023-09-05 12:09 UTC, Kim0914 commented on tomcat/src/main/java/org/apache/request/HttpLine.java
> +    }
원인을 찾아봤는데 애플리케이션을 실행하고 첫번째 요청에서 NPE가 발생하더라구요..

Reader에서 첫 줄을 읽으면 null만 존재하는데 어떤 이유인지 아시나요? ㅜ

2023-09-06 05:30 UTC, Kim0914 commented
소중한 피드백 반영했습니다 ㅎㅎ

부족한 테스트도 함께 추가했어요 !

감사합니다 ~~

2023-09-06 07:12 UTC, hectick approved these changes
안녕하세요 그레이~
변경해주신 부분과 테스트 모두 잘 확인했습니다!
추가로 코멘트도 몇개 남겨보았어요!! 다만 아직 해결되지 못한 미스테리가 하나 남아있는데 이건 저도 열심히 찾아보겠습니다🥲
그럼 이만 마지할게용~

2023-09-06 07:12 UTC, hectick commented on tomcat/src/main/java/org/apache/request/HttpLine.java
> +    }
일단 null 처리를 하긴 했지만 저도 아직 정확히 알지는 못합니다...
현재 코드를 돌려보면, 크롬에서 동작할때는 한 요청당 하나의 스레드가 생기지만,
포스트맨에서 요청을 보낼 때는 한 요청에 두개의 스레드가 생기고, 그 중 첫번째 스레드가 null pointer exception이 터지더라구요.
본격적인 요청을 보내기 전에 서버에 일단 아무거나 보내보는걸까요?
혹시 원인을 먼저 알게되면 공유 부탁드립니당..ㅠ

2023-09-06 07:13 UTC, merged