[톰캣 구현하기 1, 2단계] 망고(고재철) 미션 제출합니다.
woowacourse/jwp-dashboard-http pull request #368
Opened 2023-09-04 08:35 UTC by Go-Jaecheol

안녕하세요 루카~~!

1, 2단계까지 구현해봤는데 잘 부탁드립니다🙇‍♂️
3단계가 리팩터링이라고 해서 아직 리팩터링은 진행 안했어요..
그래서 코드가 많이 복잡할 수 있어요.. 하하

다음 단계에서 기가 막히게 리팩터링 해보겠읍니다^^
리뷰 잘 부탁드려요 😎

2023-09-04 16:05 UTC, dooboocookie commented on README.md
> +  - [x] Session 구현하기
요구사항 분석 👍
1, 2단계에서는 기능 단위로 해야할 업무들이 있어서 TDD 같은 것을 하기 힘들었을 것 같아요.
저도 그래서 테스트코드가 하나도 없답니다.

그래서 3단계 리팩토링에선 저도 그렇고 망고도 이제 어떤 처리를 해야되는지 명확하게 알고 있으니까,
대략적으로라도 객체가 어떤게 필요한지 설계를 먼저 해보고 필요한 기능 명세를 뽑아서 TDD로 리팩토링 해나가면 어떨까요?

2023-09-05 05:25 UTC, dooboocookie commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
>              outputStream.flush();
이 부분이 Processor의 process() 의 메서드의 주된 행위를 private 메서드 명과 변수 명으로 잘 표현이 되어있는 것 같아서 매우 잘 읽혔습니다 👍

2023-09-05 05:43 UTC, dooboocookie commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +        return get200ResponseMessage(responseBody, "text/html;");
요청에 따른 핸들링을 잘 해주셨네요!!
분기로 나눠져 있지만 코드가 잘 정리가 되어있어서 매우 잘 이해 됐습니다.👍

근데 몇가지 제안해보고 싶은 부분이 있는데요!
일단, 이 부분에서 하는 작업이 크게 2가지 있을 것 같습니다.
1. 응답의 Content-Type을 결정
2. 요청 패스에 따라 핸들러 매핑

이 메서드의 이름으로 미루어 볼 때 이 메서드의 기능은 `어떤 요청에 대한 핸들러 매핑`이 제일 가까울 것 같은데요.

어떤 자원을 응답해줄 때 Content-Type을 설정해 주는 것 또한 각각의 핸들러에서 이루어 질 수도 있지만,
응답해주려는 정적 파일의 확장자나 요청의 Accept 헤더, 응답을 판단 한다던지 하여 `스프링`말고 `톰캣`에서도 어느정도 지원을 해줄 수 있는 기능이 아닐까 싶습니다.

이 메서드의 경우 `스프링`의 영역에 더 가까운 것 같은데, Response과 같은 톰캣의 영역에 컨텐트 타입을 결정하는 메서드가 있으면 어떨까 싶습니다.
(모든 컨텐트 타입을 다 관리할 수는 없겠지만 .css, .html, .js, ... 이런 정적파일을 조회할 떄는 어떤 응답으로 나갈지에 대해서...)

2023-09-05 06:24 UTC, dooboocookie commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +    }
Request를 파싱할 때 정말 중요한 부분이죠?
이 메서드의 역할은 RequestBody를 -> Map<String, String>으로 파싱을 해주는 역할을 하고있는데요!
반환 값은 확실히 Request Parameters를 반환하고 있는 것 같습니다.
이는 쿼리 스트링(GET)과 바디에 =과 &로 표현된 것(POST)을 둘 다 포함할 수 있을 것 같은데요.

제 생각엔 POST 방식일 때 QueryString을 쓰지 않고 바디에 Request Parameter가 무조건 있을 것이다 라고 기대하기 보단, 요청의 Content-Type을 보고 바디의 내용을 어떤 것으로 파싱하는 과정이 있으면 어떨까 싶습니다!

그래서 제가 제안하고 싶은 것은 두 가지 인데요.

1. Query String으로 오든 application/x-www-form-urlencoded으로 오든, 다 `Map<String, String> requestParameter`로 파싱한다. 
2. POST 메서드일 떄 바디를 보기보단 `Content-Type: application/x-www-form-urlencoded` 일 때 바디를 본다.

이 두 가지를 제안하는 이유는 이 과정은 특정 패스로의 요청이나 특정 메서드의 요청이 있을 때 일어나야되는 일이라기보단, 모든 요청에 대해서 요청 파라미터를 파싱하는 작업을 시도하는 작업이 필요할 것 같습니다!!
(null인 상황도 고려해서요!!)

2023-09-05 06:27 UTC, dooboocookie commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +    }
이런 메서드 하나하나 짜실 때마다 고민 많이 하셨을 것 같아요!! 👍
이런 분기나 setCookie같은 어색한 파리미터는 HttpResponse를 객체를 만드는 3단계 리팩토링에서 많이 개선이 될 수 있을 것 같습니다!!

2023-09-05 06:50 UTC, dooboocookie commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +    }
Files.readString 같은 메서드도 있군요!! 좋은데요?
근데 이 부분 메서드명이 조금 불분명한 것 같습니다.
해당 내용을 살펴보면 uri가 `resource/static 밑에 있는 정적 자원`이라는 가정을 하고, 그 정적자원을 찾아서 스트링으로 변환하는 것인데요.
findResponseBody보단 좀 더 특정상황임을 나타내는 메서드명 어떤신가유?

그리고 어떤 자원을 못 찾는다면, 404 응답을 줄 수 있는 방법을 고려해보는 것은 어떨까요??

2023-09-05 07:06 UTC, dooboocookie commented on tomcat/src/main/java/org/apache/coyote/http11/HttpCookie.java
> +    }
Session을 생성할 떄 특정 쿠키를 만드는 과정이 필요한 것인데,
이것을 Cookie의 역할이라고 보신 이유가 있으실까요??
제 생각에는 특히 랜덤 UUID가 Seesion들을 나타내는 key값이 되므로 이 곳보다는 Processor나 Session관련된 객체에서 이루어 지는것이 자연스러워 보입니다!!
망고의 의견이 궁금해용

2023-09-05 07:16 UTC, dooboocookie commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +            final String uri = requestHeader.get("Request-Line").split(" ")[1];
requestHeader.get("Request-Line") 같은 부분은 변수로 빼놓는 거 어떠신가요?

2023-09-05 07:23 UTC, dooboocookie commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +    }
이 부분에서 좀 보완했으면 좋은 부분이 있는데요.
버그(?)가 발생하는 상황이 있습니다.
현재 브라우저에 JSESSIONID라는 쿠키가 존재하는데, 해당 아이디를 갖는 Session이 없다면, 예외가 발생합니다!!

재현 방법
1. 세션 저장
2. 서버 재시작
3. 세션 필요한 요청

2023-09-05 07:28 UTC, dooboocookie requested changes
안녕하세요 망고!
1, 2단계 미션 요구사항을 벗어나지 않는 상황에서 매우 좋은 가독성을 갖는 코드를 구현해주셨네요!! 실력 대단하신데요??

일단 저는 어떤 요청을 매핑하는 역할 과정보다는
Tomcat이 가져야되는 기능에 대해서 조금 집중해서 보았는데요
1. Request (Header, Body)
2. Response (Header, Body)
3. Session
4. ...

이런 영역을 어떻게 구현하셨는지 살펴보고 리뷰 남겼습니다.

이미 잘 짜신 코드지만, 제 생각을 남겨서 리뷰 남겨 봅니다.
잘 이해안되는 리뷰는 DM 주시면 답변드릴게용!!

2023-09-06 07:57 UTC, Go-Jaecheol commented on README.md
> +  - [x] Session 구현하기
좋아요~~!

2023-09-06 07:59 UTC, Go-Jaecheol commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +            final var bufferedReader = new BufferedReader(inputStreamReader);
앗,, 이 부분은 했다고 생각했는데 안하고 넘어갔네요 🥲
똑같이 try-with-resources로 처리하도록 수정했습니다!

2023-09-06 08:39 UTC, Go-Jaecheol commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
>          try (final var inputStream = connection.getInputStream();
급하게 하다보니 기존에 있던 var 코드는 신경 안쓰고 넘어갔네요.

프로젝트를 할 때 var를 테스트 코드에서만 처음 써봤는데
var를 사용하면 변수명과 그 변수의 역할에 대해 더 집중할 수 있어서 가독성이 좋아진다고 생각합니다.

그래서 생성자와 같이 그냥 코드를 봤을 때도 타입 추론을 할 수 있는 경우에는 var를 사용하도록 정하고 수정했습니다!

2023-09-06 08:57 UTC, Go-Jaecheol commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +            final String uri = requestHeader.get("Request-Line").split(" ")[1];
중복되는 문자열들은 상수로 빼두었습니다!

중복되진 않지만 상수화 되어있지 않는 문자열들도 있는데 이 부분은 리팩토링 하면서 객체 분리되면 마저 정리하겠습니다!!

2023-09-06 10:22 UTC, Go-Jaecheol commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +        return get200ResponseMessage(responseBody, "text/html;");
`handleRequest` 메서드에서 1) path에 따른 핸들러 매핑 기능만 담당하도록 하고, 2) Content-Type을 결정하는 로직은 각 ResponseMessage를 만드는 메서드에서 담당하도록 분리했습니다!

우선은 이렇게 해봤는데 지금 `HttpRequest` 관련 객체를 따로 분리하지 않아서 파라미터로 `path`와 `requestBody`를 각각 따로 넘기는 등 불필요한 작업이 존재합니다.
이 부분은 3단계 리팩토링을 하면서 `HttpRequest` 객체와 `HttpResponse` 객체를 만들면서 해결해보겠습니다!! (TDD도 하면서 한 번에~)

2023-09-06 10:50 UTC, Go-Jaecheol commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +    }
form 방식으로 변경되고 앞으로 Query String으로 요청이 오는 경우는 없을 거라고 단정지어서 생각했네요 🤣

> 1. Query String으로 오든 application/x-www-form-urlencoded으로 오든, 다 Map<String, String> requestParameter로 파싱한다.
> 2. POST 메서드일 떄 바디를 보기보단 Content-Type: application/x-www-form-urlencoded 일 때 바디를 본다.

위 두 피드백 모두 반영했습니다!

2023-09-06 11:34 UTC, Go-Jaecheol commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +    }
클라이언트에서 브라우저에 저장된 쿠키 값을 비워줘야 된다고만 생각했는데
다시 생각해보니 이 상황에 대한 예외 처리를 서버에서 해줘야 되네요!

쿠키에 저장된 JSESSIONID가 서버에 존재하지 않으면 세션을 다시 만들고 재로그인 하도록 수정했습니다.

2023-09-06 16:38 UTC, dooboocookie commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
>          try (final var inputStream = connection.getInputStream();
확실히 user와 같이 타입 추론이 직관적으로 바로 되는 곳에서는 var의 가독성 장점도 큰것 같아요!!
망고의 기준이 명확해져서 코드를 읽기 훨씬 좋아졌습니다!!

2023-09-06 16:56 UTC, dooboocookie commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +    }
잘 반영해주셔서 감사합니다!!
3단계 리팩토링하면서 이러한 요청에 있는 정보들을 파싱해주는 역할을 어디로 가져가면 좋을지 고민해보면 될 것 같습니다!!
코드가 멋있어요!!

2023-09-06 16:56 UTC, dooboocookie commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +    }
명확한 네이밍인것 `같습니다!!```

2023-09-06 17:01 UTC, dooboocookie commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +        return get200ResponseMessage(responseBody, "text/html;");
최대한 1, 2단계의 내용에 집중하면서 리팩토링 욕구를 참으면서 구현한 망고에게 일단 박수를 보냅니다👍
그리고 그렇게 구현하다보니 위 제안으로 코드를 변경하기 쉽지 않을 것 같다는 생각을하긴 했는데
망고 매우 잘 구현해주신것 같습니다!!
말씀하신대로 3단계 Request와 Response 각각에게 책임을 부여해주면 완벽할 것 같습니다!!

2023-09-06 17:04 UTC, dooboocookie commented
망고 피드백 전체적으로 다 잘 적용해주셨네요!!
그리고 어떻게 코드 스멜이 0이죠??
이미 1, 2단계는 충분히 잘 해결하신 것 같으니 3,4 단계로 넘어가볼까요?
가보시죠.

2023-09-06 17:04 UTC, dooboocookie approved these changes

2023-09-06 17:04 UTC, merged