[톰캣 구현하기 - 1, 2단계] 비버(전인표) 미션 제출합니다.
woowacourse/jwp-dashboard-http pull request #377
Opened 2023-09-04 08:42 UTC by ingpyo

2023-09-04 15:40 UTC, youngh0 requested changes
안녕하세요 비버🙇‍♂️ 리뷰 남겼습니다!!

Controller, Service 까지 구현하셔서 놀랐습니다. 열정에 감동 받았습니다 👍
정적 파일 확장자 별 핸들러와 DispatchServlet 구조만 조금 개선되면 좋을 것 같아요!!

코멘트는 전부 반영 안하셔도 됩니다!! 미션하시느라 고생하셨습니다 👆☝️☝️

2023-09-04 15:40 UTC, youngh0 commented on tomcat/src/main/java/nextstep/jwp/UserFilter.java
> +            if (httpStartLine.get("Cookie").contains("JSESSIONID")) {
여기서의 httpStartLine 은 header를 의미하는 것 같은데요. (맞겠죠..?)
Request의 Http version, method, uri 를 담고 있는 HttpStartLine 객체도 있어서 이 코드에서의 httpStartLine 네이밍을 헤더를 의미하도록 변경하면 덜 헷갈릴 것 같아요

2023-09-04 15:40 UTC, youngh0 commented on tomcat/src/main/java/org/apache/coyote/http11/response/HttpStatus.java
> +    NOT(4011,"4011 NOT FOUND");
NOT FOUND 는 404..

2023-09-04 15:40 UTC, youngh0 commented on tomcat/src/main/java/org/apache/coyote/http11/handle/DispatcherServlet.java
> +                    || request.getHttpStartLine().getRequestTarget().getResources().equals("/register") && handleResponse.getHttpStatus().equals(CREATED)) {
HandleResponse의 status가 CREATED인 경우는 "/register" 요청일 때가 유일한 걸로 파악했는데요. 

`resource.equals("/login")` 가 if문에 있어도 && 조건 때문에 "/login"이 resources 인 경우는 무조건 해당 if문을 통과하지 못할 것 같은데 해당 `resource.equals("/login")` 이 조건도 넣어주신 이유가 있나요??

2023-09-04 15:40 UTC, youngh0 commented on tomcat/src/main/java/org/apache/coyote/http11/handle/DispatcherServlet.java
> +            return HttpResponse.of(request.getHttpStartLine().getHttpVersion(), FOUND.getStatusName(), request.getHttpStartLine().getResources() + ".html");
/register 로 접속하면 register.html 파일을 보여주는게 아니라 register.html 로 리다이렉션 할 것 같아요. 

LMS의 2단계 POST로 회원가입 구현하기의 gif 보면 uri는 그대로 /register 로 남아있습니다!

2023-09-04 15:40 UTC, youngh0 commented on tomcat/src/main/java/org/apache/coyote/http11/handle/DispatcherServlet.java
> +            return HttpResponse.of(request.getHttpStartLine().getHttpVersion(), FOUND.getStatusName(), "/login.html");
ditto~

2023-09-04 15:40 UTC, youngh0 commented on tomcat/src/main/java/org/apache/coyote/http11/handle/DispatcherServlet.java
> +        if (handleResponse.getHttpStatus().equals(OK)
이 부분부터 분기가 많아서 코드 파악하기가 조금 어려워서 구조 개선이 필요할 것 같아요..

2023-09-04 15:40 UTC, youngh0 commented on tomcat/src/main/java/org/apache/coyote/http11/response/HttpResponse.java
> +//                "Set-Cookie: " + response.getResponseHeader().get("Set-Cookie") + " \r\n" +
열심히 코딩한 흔적.. 🥲

2023-09-04 15:43 UTC, shb03323 commented on tomcat/src/main/java/org/apache/coyote/http11/handle/DispatcherServlet.java
> +            return HttpResponse.of(request.getHttpStartLine().getHttpVersion(), FOUND.getStatusName(), "/login.html");
me?

2023-09-09 05:34 UTC, youngh0 approved these changes
안녕하세요 비버!
코드 개선을 잘해주셔서 좋았습니다👍
Servlet과 Controller 관련해서 코멘트 남겼는데 확인해주시면 감사하겠습니다 ㅎㅎ

어프루브 하겠습니다!!

2023-09-09 05:34 UTC, youngh0 commented on tomcat/src/main/java/org/apache/catalina/servlet/adapter/HandlerAdapter.java
> +    public static Controller getHandler(HttpRequest request) {
클래스 이름과 메서드 이름은 Handler인데 실제 반환은 Controller 라 Handler or Controller 로 통일하는건 어떨까요?

2023-09-09 05:34 UTC, youngh0 commented on tomcat/src/main/java/org/apache/catalina/servlet/adapter/HandlerAdapter.java
> +        if (requestURI.equals("/login")||requestURI.equals("/register")) {
request uri 가 xx.html 처럼 파일을 요청하는 것이 아닌 /login 같은 경우에 Controller를 통해 처리하는 것 같아요.

그리고 반환된 UserController 에서 다시 doPost(), doGet() 에서도 uri를 통해 분기하고 있는 것으로 파악했습니다.

이 경우 새로운 uri (/ingpyo) 가 추가된다면 getHandler() 메서드의 분기문에 해당 uri에 맞는 controller를 반환하도록 수정해야 할 것 같아요. 

의견 주시면 감사하겠습니다!

2023-09-09 05:34 UTC, youngh0 commented on tomcat/src/main/java/org/apache/catalina/servlet/DefaultServlet.java
> +public class DefaultServlet implements Servlet {
이전 파일 확장자 별 처리 객체가 따로 있던게 이걸로 통합됐군요👍

2023-09-09 05:34 UTC, youngh0 commented on tomcat/src/main/java/nextstep/jwp/controller/UserController.java
> +            if (request.getPath().equals("/login")) {
DispatcherServlet 에 달았던 코멘트와 동일하게 새로운 uri 추가 시 이 부분도 수정이 발생할 것 같아요.

2023-09-09 05:34 UTC, youngh0 commented on tomcat/src/main/java/org/apache/coyote/ResponseEntity.java
> +    public static ResponseEntity forward(HttpStatus statusCode, String path) {
저는 개인적으로 이 메서드 네이밍과 found 네이밍이 바뀌는게 자연스러울 거 같아요.

리다이렉션과 forward 가 궁합이 좋은 것 같다는 생각..? 이건 제 개인적인 생각입니다!

2023-09-09 05:34 UTC, youngh0 commented on tomcat/src/main/java/org/apache/coyote/http11/request/header/HttpHeadersLine.java
> +    public static HttpHeadersLine from(final Map<String, String> httpHeaders) {
확인해주세요~

2023-09-09 05:34 UTC, youngh0 commented on tomcat/src/main/java/org/apache/coyote/ResponseEntity.java
> +    public static ResponseEntity found(final Response response, String location) {
ResponseEntity.found()의 location 파라미터와 ResponseEntity.forward()의 path 파라미터가 모두 동일하게 /index.html 형태로 들어와서 이름 통일해도 좋을 것 같아요!

2023-09-09 05:34 UTC, youngh0 commented on tomcat/src/main/java/org/apache/coyote/http11/request/start/RequestTarget.java
> +    public RequestTarget(final HttpExtension extension, final String path) {
외부에서 사용하지 않어서 private 으로 막으면 좋을 것 같아요!

2023-09-09 05:35 UTC, merged

2023-09-09 07:26 UTC, ingpyo commented on tomcat/src/main/java/org/apache/catalina/servlet/adapter/HandlerAdapter.java
> +    public static Controller getHandler(HttpRequest request) {
그게 더 맞는거같네요!

2023-09-09 07:32 UTC, ingpyo commented on tomcat/src/main/java/org/apache/coyote/ResponseEntity.java
> +    public static ResponseEntity found(final Response response, String location) {
found랑 forward랑 하는 역할 이 다르다고 생각합니다
왜냐하면 found는 리다이렉트 시켜라. forward는 알맞은 html을 찾아서 파일(데이터)를 반환하라 이렇게 생각해서 분리를 했습니다..
레오의 의견은 어떤지 궁금합니다