[톰캣 구현하기 - 1, 2단계] 준팍(박준현) 미션 제출합니다.
woowacourse/jwp-dashboard-http pull request #379
Opened 2023-09-04 08:46 UTC by junpakPark

2023-09-05 07:59 UTC, cpot5620 requested changes
안녕하세요 준팍 !

코드 진짜.. 잘 짜시네요.. 제가 제출한 코드가 부끄러워질 정도였습니다 😢
코드가 읽기 편해서 리뷰하기 수월했던 것 같아요 ! 감사합니다.

현재 단계에서 크게 고쳐야 할 부분은 없는 것 같은데, 미리 말씀해주신 것 처럼 Session 부분이 미구현된 상태라, request changes 하겠습니다.
해당 부분 구현 완료되시면, 바로 approve 하도록 하겠습니다 ! (3단계가 리팩토링이니까요 ~!)

고생 많으셨습니다 !!

2023-09-05 07:59 UTC, cpot5620 commented on tomcat/src/main/java/org/apache/coyote/http11/request/HttpRequestParser.java
> +    }
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 진짜 사소한건데..
메서드 이름과 조건문 수행이 순서가 반대네요 !!

2023-09-05 07:59 UTC, cpot5620 commented on tomcat/src/main/java/org/apache/coyote/http11/request/RequestBody.java
> +    }
현재는 RequestBody가 폼 데이터 형식이기 때문에, 위와 같은 작업을 수행하는 것인가요 ?

만약, 다른 형식에 대해서도 대응해야 한다면 어떤 방법을 사용하실건지 궁금합니다 !

2023-09-05 07:59 UTC, cpot5620 commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +            HandlerMapping handlerMapping = new HandlerMapping();
`HandlerMapping` 객체를 매번 생성할 필요는 없을 것 같은데, 어떻게 생각하시나요 ?

2023-09-05 07:59 UTC, cpot5620 commented on tomcat/src/main/java/org/apache/coyote/http11/response/ResponseEntity.java
> +    }
메서드 명이 조금 어색한 것 같네요 !

2023-09-05 07:59 UTC, cpot5620 commented on tomcat/src/main/java/org/apache/coyote/http11/request/RequestUri.java
> +        }
`Collections.emptyMap()`를 사용하는 것은 어떨까요 ?

QueryString이 처음부터 없는 경우이기 때문에, 불변으로 다루어도 괜찮을 것 같아요 !

2023-09-05 07:59 UTC, cpot5620 commented on tomcat/src/main/java/org/apache/coyote/http11/request/RequestLine.java
> +    }
사용하지 않는 메서드들이 존재하네요 !
추후에 필요할 것으로 판단하셔서 그대로 두신걸까요 !

2023-09-05 07:59 UTC, cpot5620 commented on tomcat/src/main/java/org/apache/coyote/http11/HandlerMapping.java
> +            }
`"/login".equlas(path)`를 사용하면, NPE를 방지할 수 있습니다.

2023-09-05 07:59 UTC, cpot5620 commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +    }
GET 요청에 대해서는 항상 ViewResolver가 동작하는데요 !

이렇게 되면, 1단계 요구사항 중 하나인 **3. Query String 파싱**이 충족되지 않을 것 같아요.

2023-09-05 10:51 UTC, junpakPark commented on tomcat/src/main/java/org/apache/coyote/http11/request/HttpRequestParser.java
> +        }
잘못된 요청이라면 표준 예외 중에선 `IllegalArgumentException`이 적절하겠네요
미쳐 신경쓰지 못했네요 ㅠㅠ 적용완료했습니다!

2023-09-05 10:51 UTC, junpakPark commented on tomcat/src/main/java/org/apache/coyote/http11/request/HttpRequestParser.java
> +    }
적용완료했습니다!

2023-09-05 10:51 UTC, junpakPark commented on tomcat/src/main/java/org/apache/coyote/http11/request/HttpRequestParser.java
> +    }
적용완료했습니다!

2023-09-05 10:53 UTC, junpakPark commented on tomcat/src/main/java/org/apache/coyote/http11/response/ResponseEntity.java
> +    }
`hasSameHttpMethod`로 수정하였습니다.

2023-09-05 10:53 UTC, junpakPark commented on tomcat/src/main/java/org/apache/coyote/http11/request/RequestUri.java
> +        }
적용완료했습니다!

2023-09-05 10:55 UTC, junpakPark commented on tomcat/src/main/java/org/apache/coyote/http11/HandlerMapping.java
> +            }
적용완료했습니다!

2023-09-05 13:20 UTC, junpakPark commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +            HandlerMapping handlerMapping = new HandlerMapping();
상수화 완료했습니다 ㅎㅎ

2023-09-07 05:41 UTC, junpakPark commented on tomcat/src/main/java/org/apache/coyote/http11/request/RequestBody.java
> +    }
네네 일단 폼형식만 대응되게 만들었습니다.
추후에 다른 형식으로 들어오게 된다면 요청 헤더의 Content-Type을 확인하여
분기 처리 하거나 인터페이스 혹은 상속 등으로 구현할 것 같습니다.

2023-09-07 05:42 UTC, junpakPark commented on tomcat/src/main/java/org/apache/coyote/http11/request/RequestLine.java
> +    }
해당 커밋까지는 지금은 쿼리스트링을 사용한 컨트롤러가 없었지만
추후에 쿼리 스트링 값이 들어올 상황이 발생할 수 있을 것으로 판단하여 남겨두었습니다.

2023-09-07 05:43 UTC, junpakPark commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +    }
반영하였습니다.
이번 PR에서는 쿼리 스트링 파싱이 정상적을 동작하는지 확인하기 위해
쿼리 스트링으로도 로그인 혹은 회원가입이 가능하도록 대응해두었습니다.
해당 기능은 다음 단계에선 제거하겠습니다.

2023-09-07 07:35 UTC, junpakPark commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +                final var reader = new BufferedReader(new InputStreamReader(inputStream, StandardCharsets.UTF_8))
쥬니가 말씀하신 의도가 정확합니다 ㅎㅎ

2023-09-07 07:49 UTC, merged