[톰캣 구현하기 - 1, 2단계] 땡칠(박성철) 미션 제출합니다.
woowacourse/jwp-dashboard-http pull request #380
Opened 2023-09-04 08:48 UTC by 0chil

2023-09-04 14:57 UTC, MoonJeWoong requested changes
안녕하세요 땡칠! 히이로입니다. 오랜만이네요~
땡칠의 코드를 리뷰하게 되어 기쁩니다. 잘 부탁드려요! 🙇 

전반적으로 http 요청, 응답 메세지 파싱과 관련된 기능, 핸들러 기능들의 책임 분리를 이미 잘 해두셔서 크게 리뷰할 부분이 없기는 했습니다. 오히려 제가 리뷰하면서 땡칠에게 배웠네요 ㅎㅎ
step3, 4에서 개선할 사항들이라고 여겨지는 부분은 따로 리뷰드리지 않고 땡칠의 의견이 궁금하거나 한 번 확인해주시면 좋을 것 같은 부분들만 리뷰드렸습니다.

혹시 제가 땡칠의 의도를 미처 파악하지 못하고 리뷰드린 부분이 있었거나 더 얘기 나눠보고 싶으신 부분 있으시다면 comment나 DM 부탁드리겠습니다! 아마 확인하시고 리뷰 재요청 주시면 바로 approve 할 수 있을 것 같습니다.

아 추가적으로 sonarcloud에서 발생하는 버그나 다른 이슈들도 함께 확인해보고 해결해보셔도 좋을 것 같아요!

고생하셨습니다~ 👍

2023-09-04 14:57 UTC, MoonJeWoong commented on tomcat/src/main/java/org/apache/coyote/http11/HttpRequest.java
> +                        final String body) {
ㅋㅋㅋ 요런 개행 센스 탐나는데요?! 😄

2023-09-04 14:57 UTC, MoonJeWoong commented on tomcat/src/main/java/org/apache/coyote/http11/HttpRequest.java
> +            BufferedReader reader = new BufferedReader(new InputStreamReader(inputStream));
엇 reader를 try with resource로 여시는 걸 깜빡하신 것 같아요!

2023-09-04 14:57 UTC, MoonJeWoong commented on tomcat/src/main/java/org/apache/coyote/http11/header/Cookies.java
> +        }
요기는 cookie separator가 빠진 것 같아 보입니다!

2023-09-04 14:57 UTC, MoonJeWoong commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +    }
handler mapping 기능 좋네요~! 나중에 HandlerMapper 클래스로 분리해주면 더 깔끔한 책임 분리가 될 수 있을 것 같습니다! 요 부분은 어떻게 할 수 있을까 고민 많이 했는데 많이 배워갑니다 👍

2023-09-06 04:23 UTC, 0chil commented on tomcat/src/test/java/org/apache/coyote/http11/HttpRequestTest.java
> +                .usingRecursiveFieldByFieldElementComparator()
이렇게 eq&hc를 별도로 재정의하지 않은 객체에 활용하기 좋더라구요!

2023-09-06 04:24 UTC, 0chil commented on tomcat/src/main/java/org/apache/coyote/http11/HttpTarget.java
> +    }
저도 긴 고민이 끝에 우선 이렇게 구현해봤는데, 깔끔하게 느껴지신다니 다행이네요.
감사합니다!

2023-09-06 04:32 UTC, 0chil commented on tomcat/src/main/java/org/apache/coyote/http11/header/HttpHeader.java
> +}
히이로가 우려하시는 부분이 '디버깅을 위한 코드가 프로덕션 코드에 포함되었다' 이 맞을까요?
아니라면 말씀해주세요!

리뷰를 반영하면서 잠시 고민해봤는데, 
'디버깅을 위한 객체의 상세정보 제공'도 하나의 기능이며 객체의 변화와 함께 관리되어야 하는 부분이라는 생각이 들었습니다.
그래서 디버깅 때마다 `toString()`을 작성했다 지웠다 하기보단, 그냥 재정의 해두어도 괜찮지 않을까하는 생각도 해보았습니다.

히이로는 이 관점에서는 어떻게 생각하시나요?

2023-09-06 04:40 UTC, 0chil commented on tomcat/src/main/java/org/apache/coyote/http11/header/HttpHeader.java
> +        return this.equals(EMPTY);
`EMPTY`는 null 대신 '값이 없다'를 표현하기 위해 만든 객체였습니다!

`EMPTY`는 static 필드라서 클래스 로드 시점에 딱 한 번만 생성되고 있습니다!
그래서 별도로 EQ&HC를 재정의하지 않아도 충분히 의도한 기능을 수행할 수 있을 것 같아요.

아직은 EQ & HC 가 필요한 곳이 없어서 인스턴스 자체를 비교한다는 의도를 잘 드러내기 위해 다음과 같이 바꿔보았습니다:
```suggestion
        return this == EMPTY;
```

2023-09-06 04:49 UTC, 0chil commented on tomcat/src/main/java/org/apache/coyote/http11/handler/FileHandler.java
> +            return new HttpResponse(body, contentType);
Accept는 다수, Content-Type은 단일이므로 주의해야한다는 말씀이시군요!

서버 입장에서는 Accept 헤더는 참고만 하고, 가능한 Content-Type 중 하나를 고르는 편이 낫겠네요.
가령 지원하지 않는 컨텐츠를 요청했을 때, text/html로 내려준달지 하는 식으로요!

이 부분까진 생각하지 못했는데 꼼꼼한 리뷰 감사합니다!

2023-09-06 04:51 UTC, 0chil commented on tomcat/src/main/java/org/apache/coyote/http11/HttpRequest.java
> +            BufferedReader reader = new BufferedReader(new InputStreamReader(inputStream));
BufferedReader가 닫히면서 [InputStream 까지 함께 닫아버려 소켓이 닫히는 문제](https://stackoverflow.com/questions/484925/does-closing-the-bufferedreader-printwriter-close-the-socket-connection)가 발생했습니다 ㅠㅠ

어떻게 해결해야할지 몰라 우선 이렇게 해두었는데, BufferedReader를 상위에서 관리하는 편이 낫다고 생각됩니다.
반영해서 다시 리뷰요청드리겠습니다!

2023-09-06 04:56 UTC, 0chil commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +    }
감사합니다. 3단계에서 진행해보겠습니다!

관련해 좋은 아이디어가 또 있는데요,
이번에 제 리뷰이가 우르였는데, 우르는 Handler에 Composite 패턴을 활용했더라구요!
개인적으로 우르가 만든 구조가 유연하면서도 중요한 부분이 잘 집약되어 있어 괜찮은 구조라고 생각이 들었습니다.

한번 구경해보시죠!
https://github.com/woowacourse/jwp-dashboard-http/pull/346/files#diff-8e4477636cbfb428f2b9305a4d495a5eeb9fd6635544247332777c4da2efa208

2023-09-07 06:44 UTC, 0chil commented on tomcat/src/main/java/org/apache/coyote/http11/handler/FileHandler.java
> +            return new HttpResponse(body, contentType);
관련해 더 고민해봤는데, RFC 2616에 406 응답을 언급하고 있더라구요.
[406 Not Accepted - MDN](https://developer.mozilla.org/ko/docs/Web/HTTP/Status/406)
하지만 오류를 응답하기보다는, 서버 임의로 컨텐츠 타입을 정해 내려주는 편이 그나마 더 사용자에게 좋을 거라는 판단이 들었어요.
MDN 문서에서도 406은 실제론 잘 쓰이지 않는다고 하네요.

2023-09-08 00:01 UTC, MoonJeWoong commented on tomcat/src/main/java/org/apache/coyote/http11/header/HttpHeader.java
> +        return this.equals(EMPTY);
EMPTY 인스턴스를 싱글톤으로 관리하시는 방향이었군요! 이해했습니다. ㅎㅎ
변경해주신 코드가 동일성을 체크한다는 의미로 다가와서 개인적으로는 더 좋네요! 👍

2023-09-08 00:22 UTC, MoonJeWoong commented on tomcat/src/main/java/org/apache/coyote/http11/handler/FileHandler.java
> +            return new HttpResponse(body, contentType);
말씀해주신 내용에 저도 동의합니다.
지금 당장 미션 내용을 기반으로 구현한다고 하면 저희는 기본적으로 내려주는 타입을 text/html로 지정해둬도 문제는 없을 것 같아요. 컨텐츠 협상에 적용되는 알고리즘 같은 것도 표준적으로 정의된 내용은 없다고 하니 문제 없을 것 같습니다!

2023-09-08 00:52 UTC, MoonJeWoong commented on tomcat/src/main/java/org/apache/coyote/http11/HttpRequest.java
> +            BufferedReader reader = new BufferedReader(new InputStreamReader(inputStream));
스트림에 대한 개념을 잘 모르는 상황에서 리뷰를 달았던 내용이라 새롭게 알게된 내용 참고하시면 좋을 것 같아 추가합니다.

자바에서 스트림은 기반 스트림과 보조 스트림으로 나뉘며 실제로 연결을 유지하고 리소스를 점유하는 것은 기반 스트림, 기반 스트림의 기능, 성능적인 측면을 향상시키기 위해 활용되는 것이 보조 스트림이라고 합니다.

현재 미션 코드에서 기반 스트림은 InputStream, OutputStream이고 이를 인자로 받아서 기능을 수행하는 InputStreamReader나 BufferedReader는 보조 스트림에 해당합니다. 이러한 배경을 생각해보면 Http11Processor 클래스의 process 메서드에서 try-with-resources로 열고 닫는 것은 inputStream과 outputStream만 지정해주고 이를 사용하는 보조 스트림들은 따로 선언해주지 않아도 될 것 같습니다.

앞에서 말씀해주신 문제도 HttpRequest에서 생성한 BufferedReader를 close 하면서 발생한 것이라고 생각이 드는데요, InputStream을 인자로 받아서 BufferedReader를 생성해 사용하고 close를 해주지 않는 방향으로 구현해보시면 해결할 수 있을 것 같습니다. 

혹시 제가 잘못 말씀드린 내용이 있거나 더 얘기 나눠보고 싶으신 부분 있다면 편하게 말씀해주세요!

2023-09-08 00:59 UTC, MoonJeWoong commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +    }
저도 handler 로직 어떻게 처리해줄지 고민이 많았는데 한 번 참고해보겠습니다. ㅎㅎ 리뷰하는데 레퍼런스까지 추천 받다니... 감사합니다! 😄

2023-09-08 01:26 UTC, MoonJeWoong commented on tomcat/src/main/java/org/apache/coyote/http11/header/HttpHeader.java
> +}
요 부분은 제가 생각을 깊게 하지 못하고 리뷰 드린 부분 같습니다.
toString 메서드가 디버깅 용으로 재정의되고 사용되었다면 옳은 방향으로 사용된 것이기에 문제는 없습니다.
말씀해주신 부분처럼 디버깅을 위한 객체의 상세정보 제공을 위한 기능으로 구현하시고 관리할 의도라고 하신다면 유지해주셔도 될 것 같아요. 😃 

하지만 일부 클래스에만 toString이 재정의되는 부분은 전체적인 코드 통일성을 해칠 수도 있고 어떤 기준으로 toString을 재정의하신 것인지 모호해질 수 있는 여지가 존재할 것 같다는 생각도 들었습니다! 해당 부분은 저도 깊게 고민해보지 못한 부분인데 여기에 대한 땡칠의 생각도 들어보고 싶네요~

2023-09-08 03:20 UTC, MoonJeWoong approved these changes
리뷰사항 반영된 것 잘 확인했습니다!
좀 더 같이 고민해보면 좋을 것 같은 부분들도 추가 코멘트 달아봤어요.
구조적인 부분이나 추가적인 리팩토링 이후 단계 진행하면서 같이 진행해보시면 좋을 것 같습니다.

고생하셨습니다 땡칠, 다음 단계에서 뵈어요~ 😄

2023-09-08 03:20 UTC, merged