[톰캣 구현하기 - 1,2단계] 블랙캣(송우석) 미션 제출합니다.
woowacourse/jwp-dashboard-http pull request #391
Opened 2023-09-04 08:59 UTC by Songusika

안녕하세요 제이! 
이번 백엔드 레벨 4 첫번째 미션 1,2 단계 제출합니다!

현재 큰 구조로는 2개의 서블릿이 있습니다.
- 정적 파일만 담당하는 `DefaultServlet`
- Jwp 패키지의 핸들러를 담당하는 `DispatcherServlet`

`ServletMapping` 객체를 통해서 요청에 매핑되는 서블릿을 찾는 구조입니다.

또한 미션에서 요구하는 요청을 담당하는 각 Handler 를 구현하였고
이를 `HandlerMapping` 객체에 담은 후 `DispatcherServlet` 으로 요청이 올 때마다 `HandlerMapping` 에서 지원하는 `Handler` 를 반환 받아서 요청을  처리하고 있는 구조입니다.

매핑이 되지 않은 경우, 서버에서 에러가 발생하는 경우는 각각 404.html, 500.html 로 반환하도록 구현하였습니다.

현재 `Http11ProcessorTest` 테스트가 노란색입니다. 분명 같은 result 로 보이는데 빠르게 문제 찾아서 고치겠습니다.

제이한테 리뷰 받아서 영광이네요!
잘부탁드립니다!

2023-09-04 12:07 UTC, sosow0212 requested changes
코드를 너무 잘 짜신 덕분에 리뷰도 편하게 했습니다!

서블릿을 잘 나눠주시고, 요청또한 Handler로 잘 처리해주셔서 인상 깊었습니다.
구조적으로는 잘해주셔서 크게 고칠 부분이 보이지 않았습니다. 놓치신 컨벤션과 다른 리뷰 몇 가지만 참고해주세요!

저도 블랙캣 코드 보고 정말 많이 배우고 갑니다 :)
바쁘실텐데 미션하시느라 수고 많으셨습니다 🙇🏻‍♂️

2023-09-04 12:07 UTC, sosow0212 commented on tomcat/src/main/java/nextstep/jwp/handler/LoginHandler.java
> +        } catch (UnAuthorizationException | UnRegisteredUserException e) {
쿼리파라미터에서 만약 `account=xxx`가 아닌 `acc=xxx`와 같이 잘못된 값이 들어오면 어떻게 될까요?

2023-09-04 12:07 UTC, sosow0212 commented on tomcat/src/main/java/nextstep/jwp/handler/RegisterHandler.java
> +    private final AuthService authService = new AuthService();
여기도 개행 추가해주세요~

2023-09-04 12:07 UTC, sosow0212 commented on README.md
>  # 톰캣 구현하기
꼼꼼한 기능 구현 목록 작성👍

2023-09-05 13:27 UTC, Songusika commented on tomcat/src/main/java/org/apache/coyote/http/HttpHeader.java
> +                .orElse(null);
처음에는 우리 서버에서 지원하는 헤더만 가져올 수 있도록 생각해서 구현한 부분인데
확실히 null 부분이 우려되네요!
`Optional` 로 반환하도록 그리고 파싱 부분에서는 `ifPresent()` 메서드로 리팩터링 하였습니다.

2023-09-05 13:49 UTC, Songusika commented on README.md
>  # 톰캣 구현하기
🙇‍♂️

2023-09-06 04:24 UTC, Songusika commented on tomcat/src/main/java/org/apache/coyote/http/vo/HttpResponse.java
> +        if(cookie.getSize() != 0){
cookie에 ask 하는 방식으로 했씁니다 ! 👍

2023-09-06 04:31 UTC, Songusika commented on tomcat/src/main/java/nextstep/jwp/handler/LoginHandler.java
> +        } catch (UnAuthorizationException | UnRegisteredUserException e) {
`LoginHandler` 에서는 `account` 와 `password` 라는 바디를 가진 `request` 만 받고 있기 때문에 
`acc` 와 같은 다른 바디값을 요청 시 `Servlet` 을 매핑하는 부분에서 지원하는 `Servlet` 을 찾지 못하고
(LoginHandler 는 Dispatcher Servlet 에 속해 있습니다.) 
`UnSupportedRequestExceptio` 이 발생하여 `Process`  단에서 404를 반환하고 있습니다.

처음 파라미터를 가져오는 부분도 `Optional` 로 처리를 할까했는데 `isSupported()` 메서드를 통해 필요한 바디가 있는 요청 한에서 
받기 때문에 논리적으로는 항상 `not null` 이라고 생각합니다.

그런데 이게 개발자가 한번 더 생각해야 하는 부분이라서
`not null` 임을 보장하더라도 차라리 `Optional` 을 붙일까 생각도 드네요
제이의 생각은 어떠신가요?

2023-09-06 04:32 UTC, Songusika commented on tomcat/src/main/java/nextstep/jwp/exception/AlreadyRegisteredUserException.java
> +        super("이미 가입된 유저입니다.");
추후 리팩터링 예외에 대한 리팩터링이 좀 커질 것 같은데 그 때 적용하겠습니다!

2023-09-06 04:32 UTC, Songusika commented on tomcat/src/test/java/org/apache/coyote/http/vo/CookieTest.java
> +    void 쿠기는_raw_string_형식으로_반환할_수_있다() {
삭제했습니다..! 
부족한 테스트 코드는 다음 단계에서 추가할게요!

2023-09-06 04:32 UTC, Songusika commented on tomcat/src/test/java/nextstep/jwp/handler/HandlerTest.java
> +        assertAll(
assertSoftly() 정말 오랜만에 듣네요 기억에서 잊고 있었어요 🥲
추후 리팩터링 시 적용하겠습니다!

2023-09-06 04:41 UTC, sosow0212 approved these changes
안녕하세요 블랙캣 리뷰 반영을 잘해주셨네요 ㅎㅎ
전체적인 코드 컨벤션도 잘 고쳐주셨고, Optional로 일부 코드는 더 깔끔해졌습니다!

설계를 잘 해주셔서 덕분에 보기 편안한 리뷰를 할 수 있었습니다.
구현하시느라 수고 많으셨습니다 👏

구조적인 부분에 대한 내용과 질문은 다음 미션에서 리뷰 진행하도록 하겠습니다!
3,4단계도 화이팅입니다 🙇🏻‍♂️

2023-09-06 04:41 UTC, sosow0212 commented on tomcat/src/main/java/org/apache/coyote/http/vo/HttpHeaders.java
> +                .collect(Collectors.joining(System.lineSeparator()));
OS에 맞게 개행을 추가해주는 기능을 사용하셨네요 👍

2023-09-06 04:41 UTC, sosow0212 commented on tomcat/src/main/java/org/apache/coyote/http/vo/HttpRequest.java
> +        return rawCookie.map(Cookie::from).orElseGet(Cookie::emptyCookie);
이 부분도 `.orElseGet()` 개행 안 들어갔네요..!
Optional로 코드가 더 깔끔해졌습니다 👍

2023-09-06 04:42 UTC, merged