[톰캣 구현하기 - 1단계] 하마드(이건회) 미션 제출합니다.
woowacourse/jwp-dashboard-http pull request #395
Opened 2023-09-04 20:06 UTC by rawfishthelgh

안녕하세요ㅎㅎ 2단계 구현을 열심히 진행해봤는데, 2-2 요구사항까지밖에 충족하지 못했습니다.
추후 리팩토링 과정에서 재진행해보려고 합니다...늦은 요청 죄송해요!

2023-09-05 17:55 UTC, eunbii0213 commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +        }
기능적인 측면에서 Hello World는 이제 필요하지 않다고 생각해요! test 깨지는 것 때문이라면 하마드의 코드에 맞게 테스트를 수정하고 이 부분을 지우는 건 어떨까요?

2023-09-05 17:56 UTC, eunbii0213 commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +            }
method로 분리해 가독성을 높여 보는 건 어떨까요?

2023-09-05 17:59 UTC, eunbii0213 commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +    }
깔끔해요 👏👏👏 하마드 최고

2023-09-05 18:01 UTC, eunbii0213 commented on tomcat/src/main/java/org/apache/coyote/http11/HttpRequests.java
> +    HELLO("GET", "/", "NONE", "200", "OK", "text/html");
이렇게 enum으로 빼신 이유가 궁금합니다!

2023-09-05 18:03 UTC, eunbii0213 requested changes
안녕하세요 하마드, 주디입니다 🐰 
4단계 첫 미션 진행하시느라 너무 수고 많으셨습니다 👏👏👏
구현을 다 하지못한 것은 리뷰 반영하면서 추가 해주시면 되니 너무 걱정 마세요~ 이례적으로 시간이 촉박하기도 했으니 충분히 이해합니다. 코드를 보니 하마드가 최대한 깔끔하게 코드를 작성하려 노력한 것 같아요. 보는 입장에서 편안했어요. 감사합니다 🙇‍♂️ 

## 기능 구현 요청
- login 에서 "로그인 성공" 로그가 찍히지 않아요! 확인 부탁드립니다~
- register 에서 등록하면 "등록 성공" 로그가 있으면 좋지 않을까요? 
- 2-3, 2-4  구현 부탁드립니다!

## 테스트 보충 요청
- 시간이 남으신다면 테스트 보충도 부탁드립니다! (기능 구현을 우선적으로 하셔도 좋습니다)

2023-09-06 08:26 UTC, rawfishthelgh commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +        }
말씀하신 대로 기능적인 측면을 고려하면, 현재 기본 URl으로 접근했을 때 지정된 페이지가 없으므로 404 응답을 반환하는 것이 나을 수도 있겠다고 판단되네요! 

혹은 인덱스 페이지를 띄우는 방법도 고려할 수 있을 것 같은데, 일단은 지정된 페이지가 없어 404를 응답하도록 변경했습니다.

2023-09-06 08:33 UTC, rawfishthelgh commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +            }
extractUserInfo 메소드로 분리했습니다! 중복 두 개가 사라졌네요 👍

2023-09-06 08:38 UTC, rawfishthelgh commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +        return HttpResponse.of(httpRequests, responseBody);
불필요하게 변수로 분리한 부분이 많았네요! 변수 분리를 줄여 해결했습니다

2023-09-06 08:45 UTC, rawfishthelgh commented on tomcat/src/main/java/org/apache/coyote/http11/HttpRequests.java
> +    HELLO("GET", "/", "NONE", "200", "OK", "text/html");
1. 요청에 해당하는 응답 방식 범위를 한정하고, 해당하는 응답이 없을 시 디폴트 값을 반환하기 위해 ENUM을 도입했습니다! 3단계 요구사항을 적용한다면 핸들러 패턴을 활용하는 것도 좋아보이네요.
2. 롬복 라이브러리는 사실 편의성의 영역이라 판단하고, 지금은 getter만 사용하고 있는 만큼 크게 롬복을 도입할 만큼의 필요성을 느끼지 못했던 것 같네요!

2023-09-07 01:56 UTC, eunbii0213 commented
안녕하세요 하마드🦛~! 주디입니다🐰
리뷰 반영해주신 것 확인했습니다 ㅎㅎ!
1,2단계는 이제 merge 할테니 3,4단계 진행 부탁드립니다! 

그리구 테스트 잘 작성해주셨는데 조금만 더 작성하시면 좋을 것 같아서..! 보충 요청 드립니다! 3,4단계에서 반영 부탁드립니다 ㅎㅎ
- login api에 접속시 session 검사 후  index.html로 redirect (로그인 한 사용자)
- login api에 접속시 session 검사 후 login.html로 redirect (로그인 하지 않은 사용자)
- login 했을 때 올바르지 않은 사용자라면 401로 redirect
- login 했을 때 올바른 사용자라면 index로 redirect
- register할 때 POST로 등록이 되는지
- css, js 읽어오기 테스트

혹시 시간이 모자르다면 3,4단계 기능부터 구현해주시고 후에 여유가 된다면 제가 제안드린 테스트를 추가해주셔도 됩니다! 기능 구현이 먼저라고 생각해요 🤓

가능한 빨리 리뷰해드릴테니 (전 주말에 보내셔도 가능합니당 ㅎㅎ) 편하게 보내주세요~ 궁금한 점은 DM 혹은 코멘트 부탁드립니다! 🔥

2023-09-07 01:57 UTC, merged