[HTTP 서버 구현하기 - 1단계] 멍토(김유기) 미션 제출합니다.
woowacourse/jwp-dashboard-http pull request #40
Opened 2021-08-30 03:48 UTC by daum7766

안녕하세요 조이!
열심히 한다고 했는데 많이 늦었네요!
1단계 요구사항을 만족하는 선에서 마무리를 지었어요.

다른분들은 작은 스프링을 만들었던데... 그건 다음에 도전해볼까 해요

리팩터링때 아래의 내용을 추가하려해요
1. 단위 테스트 추가(몇개가 부족합니다.)
2. 컨트롤러 추가(핸들러에 너무 몰아져 있어서 분리하려해요)
3. 서비스 추가 (userrepository에 로직이 들어가서 리포지토리로 분리하려 해요)
4. 상수 변수화(구현에 집중하다 보니 상수가 너무 많이 들어가있어요)
5. Response 반환 중복 제거(각 상황에 따라서 만들었는데 공통적인 부분을 처리하려 해요)

저는 피드백을 좋아해요!
부담없이 마구마구 질러주세요.

감사합니다.

2021-08-31 10:51 UTC, Joyykim requested changes
안녕하세요 멍토😀 리뷰가 늦어 죄송해요ㅠㅠ
다음 리뷰부턴 정말 빠르게 해드릴게요!!!

크게 복잡한 부분없이 잘 읽히네요ㅎㅎ
어차피 구조는 2단계 리팩토링 미션에서 많이 개선될거라 생각해서 요구사항을 만족하지 못하신 부분에 집중해서 살펴보고 리뷰를 드렸어요. 
테스트코드는 어떤 테스트를 하셨는지 정도만 보고 리뷰를 남기진 않았어요!

2021-08-31 10:51 UTC, Joyykim commented on app/src/main/java/nextstep/jwp/http/RequestHeader.java
> +                return "application/javascript";
`Accept: */*`로 올 때는 모두 `text/html`로 보내주게 되는군요.
`scripts.js`의 `Content-Type`을 보니 `text/html`이에요ㅎㅎ 근데 스크립트 동작은 잘되는것 같네요? 몰까요?
다음 리팩터링 미션에서 개선해주시면 좋을 것 같아요!
<img width="578" alt="스크린샷 2021-08-31 오후 7 21 47" src="https://user-images.githubusercontent.com/56679885/131486209-4d33f5f1-ccc1-4f4f-986a-d71abca67b79.png">

2021-08-31 10:51 UTC, Joyykim commented on app/src/main/java/nextstep/jwp/http/Response.java
> +            "Location: " + request.getParameter("Host") + location
서버 동작을 시켜보니 리다이렉트가 잘 동작하지 않네요. 같은 호스트로 요청하는 거라면 호스트를 제외하고 Path만 넣어주면 되는걸로 알고 있어요.

이 부분은 동작하도록 고쳐주세요!ㅎㅎ

2021-08-31 10:51 UTC, Joyykim commented on app/src/main/java/nextstep/jwp/exception/UnauthorizedException.java
> +public class UnauthorizedException extends RuntimeException {
`로그인에 실패하면 401.html로 리다이렉트한다.`
로그인 실패시 500에러가 나는걸로 확인되네요. 고쳐주세요!

2021-08-31 10:51 UTC, Joyykim commented on app/src/main/java/nextstep/jwp/http/Uri.java
> +    public static Uri valueOf(@Nonnull String pullUri) {
전체 URI를 의미하는 변수 같은데 혹시 `fullUri`인가요??

2021-08-31 10:52 UTC, Joyykim commented on app/src/main/java/nextstep/jwp/RequestHandler.java
> +            final Request request = createdRequest(bufferedReader);
2단계에서 진행해주셔도 돼요ㅎㅎ

2021-08-31 15:13 UTC, daum7766 commented on app/src/main/java/nextstep/jwp/RequestHandler.java
> +            final Request request = createdRequest(bufferedReader);
bufferedReader를 다른 클래스에 넘기는게 싫어서 저렇게 만들게 되었는데 혹시 다른 추천방법이 있으신가요?

2021-08-31 15:13 UTC, daum7766 commented on app/src/main/java/nextstep/jwp/RequestHandler.java
> +            log.debug("Request Error : {}", e.getMessage());
굿굿!
밤새서 만들어서 저런코드가 나왔나보네요 ㅜㅠ
수정하겠습니다.

2021-08-31 15:15 UTC, daum7766 commented on app/src/main/java/nextstep/jwp/http/Response.java
> +            "Location: " + request.getParameter("Host") + location
수정하겠습니다.

2021-08-31 15:21 UTC, daum7766 commented on app/src/main/java/nextstep/jwp/exception/UnauthorizedException.java
> +public class UnauthorizedException extends RuntimeException {
에러처리는 해놓고 에러핸들링을 하지 않았네요!
추가했습니다.

2021-08-31 15:29 UTC, daum7766 commented on app/src/main/java/nextstep/jwp/http/Uri.java
> +    public static Uri valueOf(@Nonnull String pullUri) {
어.. 그렇네요
영알못이라. 하하..

2021-08-31 15:40 UTC, daum7766 commented on app/src/main/java/nextstep/jwp/RequestHandler.java
> +            final Request request = createdRequest(bufferedReader);
해당부분은 좀 더 고민해서 2,3단계때 반영해보겠습니다.

2021-08-31 15:57 UTC, daum7766 commented
안녕하세요 조이!
피드백 잘 받았습니다.
Request 분리빼고 나머지는 반영을 했습니다.
Request 분리는 좀 더 고민 후 다음 제출에 반영하도록 하겠습니다.

2021-09-01 05:08 UTC, Joyykim approved these changes
수고하셨어요! 모두 잘동작하네요ㅎㅎ
2,3단계에서 리팩토링, 구조 개선 화이팅입니다~~
다음 단계에서도 잘부탁드려요!
이만 머지하겠습니다🙏 (우테코에서 이 말을 쓰게 되는군요ㅋㅋ)

2021-09-01 05:08 UTC, Joyykim commented on app/src/main/java/nextstep/jwp/http/Response.java
> +        return message.getBytes(StandardCharsets.UTF_8);
CharSet 파라미터를 전달하지 않아도 UTF-8이 기본인걸로 알고있는데 혹시 명시적으로 적으신 건가요??

2021-09-01 05:08 UTC, merged

2021-09-01 05:10 UTC, daum7766 commented on app/src/main/java/nextstep/jwp/http/Response.java
> +        return message.getBytes(StandardCharsets.UTF_8);
메시지를 보내는데 깨지는 경우가 발생해서 추가해보았습니다.