[톰캣] - 폴로 3,4 단계 미션 제출 합니다.
woowacourse/jwp-dashboard-http pull request #403
Opened 2023-09-07 06:49 UTC by green-kong

미션 3,4단계 진행했습니다.
천천히 리뷰해주셔도 됩니다~

Controller가 servlet의 역할을 하게끔 리팩토링하고,
쓰레드랑, 동시성확장 해봤습니다.

2023-09-11 03:36 UTC, JJ503 requested changes
안녕하세요 폴로!
너무 늦어버린 리뷰입니다... 😅

1, 2 단계 때 이미 너무 잘 구현해 주셨어서 그런지 역시 이번에 수정 사항이 아주 많진 않군요! 👍
이미 제 눈에는 완벽해 보이는지라 간단하게 몇 가지 리뷰만 남겨 보았습니다!

3, 4 단계도 고생 많으셨습니다!

2023-09-11 03:36 UTC, JJ503 commented on tomcat/src/main/java/org/apache/catalina/controller/LoginController.java
> +            return Response.of(request.getHttpVersion(), UNAUTHORIZED, contentType,
엇.. 저는 왜 302로만 리다이렉션이 가능한 줄 알았을까요...?
다시 수정해 봐야겠네요 😭

2023-09-12 07:12 UTC, green-kong commented on tomcat/src/main/java/org/apache/catalina/controller/LoginController.java
> +            return Response.of(request.getHttpVersion(), UNAUTHORIZED, contentType,
엇 이거 리다이렉션 아닌데용....
그냥 로그인 실패하면 401페이지 주는거에요.. 생각해보니 LoginController 쪽에서 302로 리다이렉션 날리는게 맞겠네요... 하핳;;

2023-09-12 07:13 UTC, green-kong commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +            Response responseEntity = getResponse(request);
오 좋은 정보 감사합니다!
제이미덕에 또하나 배워가네요!!

2023-09-12 07:24 UTC, green-kong commented on tomcat/src/main/java/org/apache/catalina/connector/Connector.java
> +    private static final int DEFAULT_MAX_CONNECTION = 10;
작게 잡으면 어떻게 되나 싶어서 이것저것 해보다가 마지막 테스트값이 10이었나보네요....ㅎㅎ
저 값을 몇으로 잡아야 되는지는 고민을 해보진 않았네요 ㅠ
제이미는 어떻게 하셨는지 궁금해요!

2023-09-12 07:25 UTC, green-kong commented on tomcat/src/main/java/org/apache/catalina/controller/RegisterController.java
> +    }
당연히.. 비정상 적인 처리겠죠...?
근데 이번 미션의 취지가 톰캣 구현이지 회원가입 로그인 구현하기가 아니라 도메인에 대한 예외처리는 크게 신경쓰지 않았습니다..!

2023-09-12 07:26 UTC, green-kong commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +
대체 이런건 어떻게 찾아내시는 건가요ㅋㅋㅋㅋㅋㅋ 매의눈 제이미 감사합니다!

2023-09-12 07:28 UTC, green-kong commented on tomcat/src/main/java/org/apache/catalina/controller/HomeController.java
> +        if (httpMethod.equals(GET)) {
부끄럽지만... 제가 HttpMethod를 9개 정의해놔서..
isGet(), isPost() 등등을 만드는게 귀찮아서 이렇게.. 하하핳...
부끄럽네요. 제이미의 의견이 훨씬더 객체지향적이라고 생각합니다..!

2023-09-12 07:30 UTC, green-kong commented on tomcat/src/main/java/org/apache/coyote/http11/request/Request.java
>      }
아 그렇네요!
현재 코드는 request 마다 새로운 sessionManager를 생성하네요..;;
sessionManager는 모든 request에서 공통으로 사용되야 하겠네요!
감사합니다 감사합니다 감사합니다

2023-09-12 07:31 UTC, green-kong commented on study/src/test/java/thread/stage0/ThreadPoolsTest.java
> +        final int expectedPoolSize = Integer.MAX_VALUE;
앗.. ㅋㅋ 맞습니다. 쓰레드 너무 어려워서.. 진짜 말그대로 이것저것 해보다가 남은 잔재네요;;
하핳 열심히 공부한 흔적으로 생각해주세용 ㅋㅋㅋ

2023-09-13 06:32 UTC, JJ503 commented on tomcat/src/main/java/org/apache/catalina/controller/RegisterController.java
> +    }
폴로 의견도 맞네요!
폴로 의견대로 해당 부분은 굳이 적용하지 않아도 괜찮다고 생각하고 넘어가도록 하겠습니다!

2023-09-13 06:33 UTC, JJ503 commented on tomcat/src/main/java/org/apache/catalina/connector/Connector.java
> +    private static final int DEFAULT_MAX_CONNECTION = 10;
사실 저도 저 값을 고민해보려고 했지만 과연 적절한 값이 무언인지 모르겠어 질문드리게 되었습니다...🥲
저는 일단은 고민해 보기에 `최대 ThradPool의 크기는 250`가 있길래 그렇게 설정하긴 했지만 실제로 고민은 아직 하지 못했습니다...ㅎㅎ
저도 좀 더 고민해보도록 하겠습니다!

2023-09-13 06:35 UTC, JJ503 approved these changes
코멘트들 잘 보았습니다!
더 이상 수정 사항은 따로 보이지 않아 이만 머지하도록 하겠습니다.
마지막까지 고생 많으셨습니다 ☺️

2023-09-13 06:35 UTC, merged