[톰캣 구현하기 - 3, 4단계] 준팍(박준현) 미션 제출합니다.
woowacourse/jwp-dashboard-http pull request #407
Opened 2023-09-07 09:11 UTC by junpakPark

2023-09-10 18:33 UTC, cpot5620 requested changes
안녕하세요 준팍 !!

토요일 낮에 리뷰 요청 주셨는데, 리뷰가 늦어졌습니다...
축구하느라 정신이 팔려서 그만.. ⚽ 

코멘트를 모두 반영하실 필요는 없기 때문에, 의견만 남겨주셔도 좋습니다 !
형편 없는(?) 코멘트들이 다수 존재하여, 생각보다 수정할 내용이 없다면 테스트 코드를 작성해보시는 것도 추천드립니다 ㅎㅎ

2023-09-10 18:33 UTC, cpot5620 commented on tomcat/src/main/java/nextstep/jwp/controller/LoginController.java
> +    protected void doGet(HttpRequest httpRequest, HttpResponse httpResponse) {
QueryString으로 로그인 요청하는 것에 대한 처리 로직이 누락 된 것 같아요.

의도하신 걸까요 ?

2023-09-10 18:33 UTC, cpot5620 commented on tomcat/src/main/java/org/apache/coyote/http11/Renderer.java
> +    );
public으로 열어두신 이유가 있나요 ?

상수 추출하다가 실수하신 것 같아요 !

2023-09-10 18:33 UTC, cpot5620 commented on tomcat/src/main/java/org/apache/coyote/http11/Renderer.java
> +    }
404 관련해서 예외 처리를 해두셨길래, 코멘트 남깁니다 !

만약 사용자가 localhost:8080/index... 이라는 입력을 하게 되면 404가 뜨는 것이 자연스러울 것 같은데요 ! (아닐 수도...)
현재는 ResponseBody가 비어있는 상태로 200 OK 가 내려오고 있습니다.

해당 흐름이 의도하신 흐름일까요 ? 아니라면, 404로 처리해보시는 것은 어떨까요 ?

2023-09-10 18:33 UTC, cpot5620 commented on tomcat/src/main/java/org/apache/coyote/http11/Renderer.java
> +        return String.format("%s;charset=utf-8 ", mimeType.getContentType());
attribute를 설정할 때에는 세미콜론 뒤에 공백이 필요하다고 하네요 !

ex) test/html; charset=utf-8

2023-09-10 18:33 UTC, cpot5620 commented on tomcat/src/main/java/org/apache/coyote/http11/session/SessionManager.java
> +public enum SessionManager implements Manager {
SessionManager 클래스를 coyote 패키지 아래에 두신 이유가 있을까요 ?

2023-09-10 18:33 UTC, cpot5620 commented on tomcat/src/main/java/nextstep/jwp/controller/DefaultController.java
> +public class DefaultController implements Controller {
Controller를 구현한 클래스와, AbstractController를 구현한 클래스를 어떤 기준으로 나누셨는지 궁금해요 !

정적 파일을 서빙하는 컨트롤러는 `Controller`를 구현한게 맞나요 ? (뷰 리졸버 느끼이이임?)
(ViewResolver가 삭제된 이력이 있어서 유추해봤습니다 ㅋ.ㅋ.ㅋ)

2023-09-10 18:33 UTC, cpot5620 commented on tomcat/src/main/java/org/apache/coyote/http11/controller/RequestMapping.java
> +        return CONTROLLERS.getOrDefault(path, new NotFoundController());
예외 처리를 하는 방법이 두 가지 정도 있을 것 같은데요.

첫 번째는 준팍이 구현해주신 대로, 각각의 예외 컨트롤러를 만드는 방법이 있을 거고,
두 번째는 커스텀 예외를 만들고, 하나의 예외 핸들러에서 처리해주는 방법이 있을 것 같아요.

개인적인 생각으로는 모든 예외 상황에 항상 정적 파일을 서빙해주기 때문에, 커스텀 예외를 사용하여 하나의 예외 핸들러에서 처리해주는 것이 조금 더 좋을 것 같다는 생각이 드는데요.
위 방법으로 구현하신 이유가 있을까요 ?

2023-09-11 01:22 UTC, junpakPark commented on tomcat/src/main/java/org/apache/coyote/http11/common/MimeType.java
저도 이 부분에 대해 고민을 해봤었습니다.
확실히 구글이나 네이버는 text/javascript를 사용하더라구요.

<img width="1459" alt="스크린샷 2023-09-11 오전 10 17 58" src="https://github.com/woowacourse/jwp-dashboard-http/assets/112045553/d33a7d91-c8f1-42a3-b546-c0fb21551748">

그러나 지원이 종료된 IE를 제외한 5대 브라우저가 모두 application/javascript를 지원하고, IE의 점유율이 0.5% 미만이라는 점에서
표준을 따르는 게 더 유의미하겠다는 판단하에 이와 같이 결정했습니다 ㅎㅎ

2023-09-11 01:35 UTC, junpakPark commented on tomcat/src/main/java/nextstep/jwp/controller/LoginController.java
> +    protected void doGet(HttpRequest httpRequest, HttpResponse httpResponse) {
https://github.com/woowacourse/jwp-dashboard-http/pull/379#discussion_r1318108249

저번 리뷰에서 지우겠다고 말씀드렸었는데... 섭섭하네요...ㅠ

1. 로그인이나 회원 가입 시 정보(특히 비밀번호)가 URL에 그대로 노출된다는 점
2. HTML이 이미 POST를 지원한다는 점

위 두 가지 이유로 인해 해당 로직 삭제했습니다

2023-09-11 01:47 UTC, junpakPark commented on tomcat/src/main/java/nextstep/jwp/controller/DefaultController.java
> +public class DefaultController implements Controller {
1. 일단 제가 Controller와 AbstractController를 나눈 기준은 비즈니스 로직이 필요한지 여부 입니당.
단순히 파일만 서빙하는 경우는 doGet()이나 doPost()를 사용할 필요가 없기 때문에 Controller를 구현했고,
비즈니스 로직이 필요한 경우 (get과 post의 분기가 필요한 경우)에는 AbstractController로 구현했습니다.

2. 정적 파일을 서빙하는 컨트롤러는 `ResourceController`라는 네이밍으로 coyote 패키지 내부에 위치하고 있습니다. 
뷰 리졸버는 Tomcat 미션에 적절하지 않은 네이밍이라고 생각하여 Renderer라는
Renderer라는 네이밍으로 변경하고, 내부에 로직을 더 정리했습니다.

2023-09-11 01:49 UTC, junpakPark commented on tomcat/src/main/java/org/apache/coyote/http11/common/HttpHeaders.java
> +    }
RequestHeaders랑 ResponseHeaders를 HttpHeaders라는 하나의 클래스로 관리하려다가
RequestHeaders 지워주는 거 깜빡했네요 ㅠㅠ
해당 내용 반영했습니다!

2023-09-11 01:50 UTC, junpakPark commented on tomcat/src/main/java/org/apache/coyote/http11/common/HttpCookie.java
> +    }
예리하시군요 ㅎㅎ 디버깅 끝났으니 지워주도록 하겠습니다...

2023-09-11 03:58 UTC, junpakPark commented on tomcat/src/main/java/org/apache/coyote/http11/common/HttpVersion.java
> +    public static HttpVersion from(final String field) {
수정 완료했습니다!

2023-09-11 04:00 UTC, junpakPark commented on tomcat/src/main/java/org/apache/coyote/http11/Renderer.java
> +    );
수정 완료했습니다!

2023-09-11 05:21 UTC, junpakPark commented on tomcat/src/main/java/org/apache/coyote/http11/common/MimeType.java
>      }
MimeType은 필드가 아닌 상수의 이름으로 enum을 반환하므로 기본적으로 지원하는 valueOf를 사용할 수 있었으나,
HttpVersion의 경우는 상수의 이름이 아닌 필드값이 일치하는 경우에 enum을 반환하기 때문에 valueOf를 사용할 수 없었습니다!

```
public enum HttpVersion {
    HTTP_1_0("HTTP/1.0"),
    HTTP_1_1("HTTP/1.1");

    private final String version;
    
    ...

}

```
-> version이 일치하는 경우 해당 Enum을 반환함.


```
public enum MimeType {

    HTML("text/html"),
    CSS("text/css"),
    JS("text/javascript"),
    SVG("image/svg+xml"),
    ICO("image/x-icon");

    private final String contentType;

    ...

}
```
-> contentType이 아닌 enum의 이름과 일치하는 경우 해당 Enum을 반환함.

2023-09-11 05:28 UTC, junpakPark commented on tomcat/src/main/java/org/apache/coyote/http11/controller/RequestMapping.java
> +public enum RequestMapping {
[이펙티브 자바 Item.3](https://steady-coding.tistory.com/619)

enum 클래스로 싱글턴을 구현하는 경우, 인스턴스 생성 시 thread safe를 보장하고,
리플렉션 공격에도 안전하며, Serializable 인터페이스를 구현하지 않아도 되기 때문에
사용하였습니다.

2023-09-11 11:30 UTC, junpakPark commented on tomcat/src/main/java/org/apache/coyote/http11/controller/RequestMapping.java
> +    private static final Map<String, Controller> CONTROLLERS = new ConcurrentHashMap<>();
이 부분이 좀 헷갈리는데요 controllers는 static일 때만 최초에 한번 생성된 후 상태가 변화하고
그 이후엔 별도의 메서드를 구현하지 않았기 때문에 불변이라고 볼 수 있지 않나...라는 생각이 들더라구요
근데 또 생각해보면 어쨌든 생성 후에 추가되면서 상태가 변한 건 맞지 않나? 라는 생각도 들고...
일단 controllers는 비상수로 간주하고, INSTANCE는 상수로 간주하였습니다.

2023-09-11 11:32 UTC, junpakPark commented on tomcat/src/main/java/org/apache/coyote/http11/controller/ResourceController.java
> +                .setRedirect(requestLine.getPath());
네이밍이 고민이었는데 path로 수정하는 게 좋겠네요
감사합니다.

2023-09-11 11:34 UTC, junpakPark commented on tomcat/src/main/java/org/apache/coyote/http11/session/SessionManager.java
> +public enum SessionManager implements Manager {
현재 SessionManager를 HttpRequest 내부에 두고 있기에 같은 위치에 두는 게 자연스럽다고 생각했는데
쥬니는 어떻게 하셨나요?

2023-09-11 12:09 UTC, junpakPark commented on tomcat/src/main/java/org/apache/coyote/http11/controller/RequestMapping.java
> +        return CONTROLLERS.getOrDefault(path, new NotFoundController());
해당 부분은 파일이 없을 때 404를 보여주고, 예상치 못한 오류가 터졌을 땐 500을 터뜨리기 위해 이렇게 구성하였는데요,
커스텀 예외를 적용하여 하나의 예외 핸들러에서 처리할 경우엔 해당 오류를 어떤 식으로 분리해야할지 감이 잡히지 않습니다 
혹시 쥬니는 어떤 방식을 상정하고 말씀하신걸까요?

2023-09-11 12:11 UTC, junpakPark commented on tomcat/src/main/java/org/apache/coyote/http11/response/HttpResponse.java
> +    private String redirect;
네이밍이 적절하지 않았던 것 같네요... redirect 네이밍을 path로 바꾸겠습니다..
이런 방식을 사용한 이유는 파일을 controller 외부에서 찾아서 ResponseBody로 만들어주기 위함이었습니다.
controller 구현체를 만드는 개발자는 Tomcat 내부를 모른다고 가정했습니당ㅋㅋ

2023-09-11 12:13 UTC, junpakPark commented on tomcat/src/main/java/org/apache/coyote/http11/controller/AbstractController.java
> +        }
if문 맨 밑에 404를 반환하도록 했습니다!

2023-09-11 12:21 UTC, junpakPark commented
훌륭한 코멘트들만 존재하여, 좀 더 다각도로 생각할 수 있었네요 ㅎㅎ 감사합니다 👍👍👍

2023-09-11 12:40 UTC, cpot5620 commented on tomcat/src/main/java/org/apache/coyote/http11/controller/RequestMapping.java
> +    private static final Map<String, Controller> CONTROLLERS = new ConcurrentHashMap<>();
static final ~~ 으로 컬렉션을 구현하였더라도, 해당 컬력션을 Immutable로 생성한 것이 아니라면, put(or add) 메서드를 통해 값을 변화시킬 수 있기 때문에, 불변이 아니라고 보는 것 같아요 !

2023-09-11 12:40 UTC, cpot5620 commented on tomcat/src/main/java/nextstep/jwp/controller/LoginController.java
> +    protected void doGet(HttpRequest httpRequest, HttpResponse httpResponse) {
Sorry bro...

2023-09-11 12:45 UTC, cpot5620 commented on tomcat/src/main/java/org/apache/coyote/http11/controller/RequestMapping.java
> +        return CONTROLLERS.getOrDefault(path, new NotFoundController());
저는 Http와 관련된 커스텀 예외 (Not Found, Unauthorized 등)을 만들어두고, 해당 예외 내부에 StatusCode를 갖도록 했어요.
그러면, 하나의 예외 핸들러에서 StatusCode를 토대로 상황에 맞는 핸들링이 가능하니까요 !

정답이 있는 부분은 아니고, 저는 이렇게 구현했다~ 자랑하고 싶어서 써봤습니다 히힛

2023-09-11 12:47 UTC, junpakPark commented on tomcat/src/main/java/org/apache/coyote/http11/controller/RequestMapping.java
> +    private static final Map<String, Controller> CONTROLLERS = new ConcurrentHashMap<>();
쏘 스윗...

2023-09-11 12:48 UTC, cpot5620 commented on tomcat/src/main/java/org/apache/coyote/http11/session/SessionManager.java
> +public enum SessionManager implements Manager {
저는 Session은 Http 자체에 조금 더 관련이 있다고 생각해서 coyote 패키지에 두었고, 해당 세션을 관리하는 SessionManager는 어플리케이션 상태(?)를 관리 한다는 느낌이 더 강해서 catalina 패키지에 두었습니당

2023-09-11 12:48 UTC, junpakPark commented on tomcat/src/main/java/org/apache/coyote/http11/controller/RequestMapping.java
> +        return CONTROLLERS.getOrDefault(path, new NotFoundController());
Taste Good...

2023-09-11 12:52 UTC, cpot5620 commented
```
  ________                  .___      __      ___.          __                           __    
 /  _____/  ____   ____   __| _/     |__| ____\_ |__       |__|__ __  ____ ___________  |  | __
/   \  ___ /  _ \ /  _ \ / __ |      |  |/  _ \| __ \      |  |  |  \/    \\____ \__  \ |  |/ /
\    \_\  (  <_> |  <_> ) /_/ |      |  (  <_> ) \_\ \     |  |  |  /   |  \  |_> > __ \|    < 
 \______  /\____/ \____/\____ |  /\__|  |\____/|___  / /\__|  |____/|___|  /   __(____  /__|_ \
        \/                   \/  \______|          \/  \______|          \/|__|       \/     \/
```

2023-09-11 12:52 UTC, merged