[톰캣 구현하기 - 3, 4단계] 테오(최우성) 미션 제출합니다.
woowacourse/jwp-dashboard-http pull request #410
Opened 2023-09-07 14:11 UTC by woosung1223

안녕하세요 토리 반갑습니다~

step3, step4 모두 완료하고 제출합니다!

이왕 만드는김에 Tomcat의 구조를 모방하고 싶어서 이것저것 시도하느라 시간을 다 보낸 것 같습니다 🥲

그리고 이번에는 미션 내용 이외에도 개인적으로 추가한 기능이 있는데요!

찾아보니 Tomcat의 경우 server.xml 파일을 통해 대부분의 설정을 해주더라구요.
현재 저희가 학습하고 있는 내용인 acceptCount, maxThreads, maxConnections 모두 server.xml 파일을 통해 설정이 되는 것 같아요. ([참고](https://tomcat.apache.org/tomcat-9.0-doc/config/index.html))

그래서 비슷하게 server.xml에 설정 값을 입력하면 자동으로 파싱해서 반영하도록 기능을 구현해봤는데, 처음 보시면 난해하실 수도 있을 것 같아 이 부분은 리뷰하시기 전에 미리 설명드립니다!

2023-09-11 14:58 UTC, ezzanzzan requested changes
안녕하세요 테오 !
일단 리뷰가 늦어져서 정말 죄송해요 🥲

1, 2단계 때 이미 구조가 깔끔했다고 생각했는데 거기서 더 깔끔해지다니 .. 
xml 파일로 스레드 설정한 부분도 정말 대단해요 💯

몇 가지 간단한 리뷰 남겼는데 이런 방법도 있더라~ 라는거니 꼭 수정하지 않으셔도 됩니다 !!!
확인 후 리뷰 요청 부탁드려요 ㅎㅎ

이번 미션 테오 코드 보면서 많이 배우고 갑니다.. 👍
내일부터 하는 새로운 미션도 화이팅이에요 !!
좋은 하루 되세요 🌈

2023-09-11 14:58 UTC, ezzanzzan commented on tomcat/src/main/java/nextstep/jwp/servlets/LoginServlet.java
> +        responseForNotLoggedIn(httpRequest, httpResponse);
메서드 네이밍 👍

2023-09-11 14:58 UTC, ezzanzzan commented on tomcat/src/main/java/org/apache/catalina/connector/Connector.java
>      private static final int DEFAULT_ACCEPT_COUNT = 100;
중간중간 불필요한 개행은 제거해도 괜찮을 것 같아요 ˙ᵕ˙

2023-09-11 14:58 UTC, ezzanzzan commented on tomcat/src/main/java/org/apache/catalina/connector/Connector.java
> +    public Connector(ConnectorConfiguration configuration) {
대단해요 .. 👍

2023-09-11 14:58 UTC, ezzanzzan commented on tomcat/src/main/java/org/apache/catalina/connector/Connector.java
> +    private ServerSocket createServerSocket(int port, int acceptCount) {
컨벤션까지 👍

2023-09-11 14:58 UTC, ezzanzzan commented on tomcat/src/main/java/org/apache/catalina/container/Context.java
> +                .orElseGet(StaticResourceServlet::new);
```suggestion
        return mappings.getOrDefault(absolutePath, new StaticResourceServlet());
```

이렇게도 할 수 있을 거 같아요 !!

2023-09-11 14:58 UTC, ezzanzzan commented on tomcat/src/main/java/org/apache/coyote/http11/ContentType.java
>                  .filter(value -> value.name().toLowerCase().equals(resourceExtension))
오 이렇게도 찾을 수 있겠네요 👍

2023-09-11 14:58 UTC, ezzanzzan commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +             final OutputStream outputStream = connection.getOutputStream()) {
요기는 `final`이 붙은 이유가 있을까요 ?!
테오는 어떤 기준으로 `final`을 사용하고 계시나요 ?!

2023-09-11 14:58 UTC, ezzanzzan commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +            LoggingFilter.logUserInfoIfExists(httpRequest);
로그까지 👍 💯

2023-09-11 14:58 UTC, ezzanzzan commented on tomcat/src/main/java/org/apache/coyote/http11/RequestExtractor.java
>      private static RequestBody extractBodyIfExists(BufferedReader reader,
여기 밑에 "Content-Length" 부분 HttpHeaders.CONTENT_LENGTH로 바꿀 수 있을 거 같네요 !

2023-09-11 14:58 UTC, ezzanzzan commented on tomcat/src/main/java/org/apache/coyote/http11/message/request/RequestBody.java
> +                .map(each -> Map.entry(each[0], each[1]))
다른 부분은 다 상수화되어 있는데 이 부분만 안 되어 있어서요 ! 이유가 있을까요 ?!

2023-09-11 14:58 UTC, ezzanzzan commented on tomcat/src/main/java/org/apache/coyote/http11/message/response/HttpResponse.java
> +        return this;
구웃...👍 💯

2023-09-11 15:35 UTC, woosung1223 commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +             final OutputStream outputStream = connection.getOutputStream()) {
원래 파라미터나 변수에 final을 사용하지 않는 편이라 코드 컨벤션 맞춘다고 `final`을 다 제거하긴 했었는데,

 저 부분만 빼먹었던 것 같네요..! 🥲 감사합니다!

2023-09-12 04:10 UTC, woosung1223 commented on tomcat/src/main/java/nextstep/jwp/servlets/IndexServlet.java
> +    }
맞습니다!

각 서블릿마다 공통부분(HTTP Request Method에 따른 분기 로직)이 있는데,
요걸 제가 인지하지 못했었네요 🥲

빠르게 수정하도록 하겠습니다 감사합니다!

2023-09-12 12:31 UTC, woosung1223 commented on tomcat/src/main/java/org/apache/coyote/http11/message/request/RequestBody.java
> +                .map(each -> Map.entry(each[0], each[1]))
요거는 RequestBody가 여러 Content-Type에 대해 재사용될 수 있기를 의도한건데요!

현재는 `application/x-www-form-urlencoded` 의 경우만 Content-Type으로 들어오므로 상관이 없지만..
추후 여러 Content-Type이 들어오는 경우 메소드만 추가하면 되도록 위처럼 구현했는데요!

따라서 상수처리가 애매했던 것 같아요 🥲 공통부분이 아니니 밖으로 빼기가 그렇더라구요.

2023-09-12 14:35 UTC, ezzanzzan commented on tomcat/src/main/java/org/apache/coyote/http11/message/request/RequestBody.java
> +                .map(each -> Map.entry(each[0], each[1]))
오 좋습니다 :) 💯

2023-09-13 06:26 UTC, ezzanzzan approved these changes
안녕하세요 테오 !!

코드 컨벤션까지 잘 지켜주시고 요구사항이 아닌 Filter나 graceful shutdown 까지... 👏
테오 코드 리뷰 하면서 정말 많이 배우고 갑니다 🙇‍♀️

이번 미션은 이만 머지하겠습니다 !!
다음 미션도 화이팅이에요 👍 오늘도 좋은 하루 되세요 🌈

2023-09-13 06:26 UTC, merged