[톰캣 구현하기 - 3, 4단계] 주노(최준호) 미션 제출합니다.
woowacourse/jwp-dashboard-http pull request #416
Opened 2023-09-08 06:53 UTC by Choi-JJunho

안녕하세요 그레이 오늘 점심으로 먹은 닭도리탕이 정말 맛있었습니다.
맛있는 점심을 먹고 기쁜마음으로 코드를 작성해봤습니다.

리뷰 잘부탁드립니다.

감사합니다.

2023-09-10 12:32 UTC, Kim0914 requested changes
반가워요 주노 ㅎㅎ 닭도리탕 꿀맛이었습니다 :)

이번 단계 미션인 리팩토링도 역시 잘 해주셨네요 👏👏
몇 가지 코멘트 남겼으니 확인부탁해요 ~

2023-09-10 12:32 UTC, Kim0914 commented on tomcat/src/main/java/org/apache/coyote/http11/request/RequestMapping.java
> +    private static final String LOGIN_URI = "/login";
`URIPath`라는 상수 객체를 별도로 생성해주셨는데 여기서는 필드로 또 사용하고 있네요 !

2023-09-10 12:32 UTC, Kim0914 commented on tomcat/src/main/java/org/apache/coyote/http11/request/RequestMapping.java
> +    private static final Controller DEFAULT_CONTROLLER = new DefaultController();
URI와 Controller를 key value로 가지는 Map 자료구조를 사용할 수도 있을 것 같아요 ~

2023-09-10 12:32 UTC, Kim0914 commented on tomcat/src/main/java/org/apache/coyote/http11/response/ResponseBody.java
> +public class ResponseBody {
현재 사용하지 않는 클래스네요 !

HttpResponse에 사용하려고 하셨던 것 같은데...!!

2023-09-10 12:32 UTC, Kim0914 commented on tomcat/src/main/java/org/apache/coyote/http11/types/HeaderType.java
> +public enum HeaderType {
ENUM으로 관리 👍

2023-09-10 12:32 UTC, Kim0914 commented on tomcat/src/main/java/org/apache/coyote/http11/types/HttpProtocol.java
> +                .orElseThrow(() -> new IllegalArgumentException("지원하지 않는 HTTP 메소드입니다."));
```suggestion
                .orElseThrow(() -> new IllegalArgumentException("지원하지 않는 HTTP 프로토콜입니다."));
```

2023-09-10 12:32 UTC, Kim0914 commented on tomcat/src/test/java/nextstep/org/apache/coyote/http11/Http11ProcessorTest.java
> +        System.out.println(output);
sout은 삭제해도 되겠네요 !

2023-09-10 12:32 UTC, Kim0914 commented on tomcat/src/main/java/org/apache/coyote/http11/controller/LoginController.java
> +public class LoginController extends AbstractController {
API와 매핑되는 컨트롤러의 패키지 위치도 고민해보시면 좋을 것 같아요 !

현재 크게 nextstep, org 패키지로 나뉘고 nextstep 패키지 하위에는 web관련 jwp 패키지가 존재합니다.
org 패키지에는 톰캣 관련 패키지(coyote, catalina)가 존재합니다.
coyote, catalina 각각이 의미하는 뜻도 있더라구요 !

요청(API)을 처리하고 적절한 응답을 만들어가는 컨트롤러는 어떤 패키지에 있는게 좋을까용?

2023-09-11 02:53 UTC, Choi-JJunho commented on tomcat/src/main/java/org/apache/catalina/connector/Connector.java
> +    private final ThreadPoolExecutor executorService;
앗! 미처 생각 못했던 부분이네요!
인터페이스 타입으로 받도록 수정했습니다 😅

2023-09-11 03:10 UTC, Choi-JJunho commented on tomcat/src/main/java/org/apache/catalina/connector/Connector.java
> +        this.executorService = (ThreadPoolExecutor) Executors.newCachedThreadPool();
maxThreads가 지정되지 않은 상태에서 매 요청마다 스레드를 생성하는 것 보다 스레드가 60초동안 캐싱되는것이 성능상 이점을 가져가지 않을까? 라는 생각에 `newCachedThreadPool()`를 사용했습니다 😅

다음 아티클을 참고해보니 `newCachedThreadPool()`이 적합한 방식은 아니라고 생각이드네요..!!
https://www.baeldung.com/java-executors-cached-fixed-threadpool

- 스레드를 무한정 생성할 수 있다. (이론상 Integer.MAX_VALUE)
- 스레드 생성 및 종료 작업에 대한 오버헤드가 발생할 수 있다.
- 모든 요청에 대해 새로운 스레드를 생성하기 때문에 요청 순서를 보장할 수 없다.

```java
// newCachedThreadPool
public static ExecutorService newCachedThreadPool() {
    return new ThreadPoolExecutor(0, Integer.MAX_VALUE,
                                  60L, TimeUnit.SECONDS,
                                  new SynchronousQueue<Runnable>());
}

// newFixedThreadPool
public static ExecutorService newFixedThreadPool(int nThreads) {
    return new ThreadPoolExecutor(nThreads, nThreads,
                                  0L, TimeUnit.MILLISECONDS,
                                  new LinkedBlockingQueue<Runnable>());
}
```

2023-09-11 04:12 UTC, Choi-JJunho commented on tomcat/src/main/java/org/apache/catalina/connector/Connector.java
> +        this.executorService = (ThreadPoolExecutor) Executors.newFixedThreadPool(maxThreads);
저도 해당 부분에 대해 궁금해서 한번 알아봤습니다.

createServerSocket을 들어가봅시다!
<img width="588" alt="image" src="https://github.com/woowacourse/jwp-dashboard-http/assets/49794401/a8b1e212-540b-4e92-ac08-d8811f2ca2ed">

ServerSocket의 `backlog`가 `acceptCount`에 해당하는 부분입니다.
<img width="609" alt="image" src="https://github.com/woowacourse/jwp-dashboard-http/assets/49794401/886ad017-ed3e-487a-849d-15818c73d010">

bind라는 메소드 내부에서 listen() 메소드를 사용중이군요..
<img width="551" alt="image" src="https://github.com/woowacourse/jwp-dashboard-http/assets/49794401/6fad4352-f1bb-4a07-824d-7c5999369f1e">

java.net.SocketImpl 추상클래스에 다음과 같이 정의되어있습니다.
<img width="645" alt="image" src="https://github.com/woowacourse/jwp-dashboard-http/assets/49794401/d70d11b7-e191-4ce9-96ff-e63d19af9dfc">

> 들어오는 연결 표시(연결 요청)에 대한 최대 큐 길이를 count 인수로 설정합니다. 큐가 꽉 찼을 때 연결 표시가 도착하면 연결이 거부됩니다.

따라서 socket에서 최대 대기인원에 대한 설정을 하고있다고 생각했습니다.

혹시 제가 잘못 이해하고 있는 내용이 있을까요~!?

2023-09-11 04:14 UTC, Choi-JJunho commented on tomcat/src/main/java/org/apache/coyote/http11/controller/AbstractController.java
> +            return;
어라라.. 저게 왜 붙어있을까요..ㅠㅠ
인텔리제이 의존성이 너무 높아 습관적으로 Option + enter를 눌러 생겼던 것 같습니다!
제거하겠습니다~

2023-09-11 04:15 UTC, Choi-JJunho commented on tomcat/src/main/java/org/apache/coyote/http11/controller/AbstractController.java
> +        if (request.getMethod() == HttpMethod.POST) {
향후 PATCH, DELETE와 같은 HttpMethod가 추가됨에 따라 isPatch, isDelete 등과 같은 메소드가 늘어날 것이 우려됩니다.
이는 HttpMethod와 HttpRequest 두 객체간 강한 의존성을 갖게 된다고 생각합니다..!!

그레이의 의견은 어떤가요?

2023-09-11 04:34 UTC, Choi-JJunho commented on tomcat/src/main/java/org/apache/coyote/http11/request/HttpRequest.java
> +        HttpProtocol protocol = requestLine.getProtocol();
RequestLine을 마지막에 도입하다보니 기존 구조를 그대로 놔뒀던 것 같습니다!
RequestLine을 가지는것도 좋아보이네요!

2023-09-11 04:46 UTC, Choi-JJunho commented on tomcat/src/main/java/org/apache/coyote/http11/request/RequestMapping.java
> +    private static final String LOGIN_URI = "/login";
리팩터링 과정에서 누락된것 같습니다!
수정하겠습니다 👍

2023-09-11 07:26 UTC, Choi-JJunho commented on tomcat/src/main/java/org/apache/coyote/http11/controller/LoginController.java
> +public class LoginController extends AbstractController {
RequestMapping을 Mapper로 추상화하여 Tomcat에 주입하도록 구성했습니다.
추가적으로 Controller 구현체들은 jwp 패키지에 구성했습니다.

2023-09-12 04:37 UTC, Kim0914 commented on tomcat/src/main/java/org/apache/catalina/connector/Connector.java
> +        this.executorService = (ThreadPoolExecutor) Executors.newCachedThreadPool();
꼼꼼한 설명까지... 😙
감사합니당

2023-09-12 04:39 UTC, Kim0914 commented on tomcat/src/main/java/org/apache/catalina/connector/Connector.java
> +        this.executorService = (ThreadPoolExecutor) Executors.newFixedThreadPool(maxThreads);
주노가 작성해주신 내용 맞습니다 !!

제가 개인적으로 더 알아본 내용을 요약해보면

소켓 커넥션 연결 수 제한은 애플리케이션에 연결되는 요청(사람) 수를 제한한다.
스레드 대기 큐 제한은 애플리케이션 내에서 해당 스레드의 core 크기만큼 스레드가 모두 사용중인 상태에서, waiting 할 수 있는 스레드 수를 제한한다.

라고 요약해볼 수 있더라구요 !!
(정확하지 않을 수도 있습니다 😭)

2023-09-12 04:41 UTC, Kim0914 commented on tomcat/src/main/java/org/apache/coyote/http11/controller/AbstractController.java
> +        if (request.getMethod() == HttpMethod.POST) {
`httpRequest.isSameMethod(GET)`, `httpRequest.isSameMethod(POST)`, 로 처리하면 메서드 하나로도 해결할 수 있을 것 같네요 ㅎㅎ

저는 HttpRequest가 구성되기 위해서는 HttpMethod는 반드시 필요하다고 생각하고 단방향 의존이기 때문에 사용할 것 같습니다 !

2023-09-12 04:45 UTC, Kim0914 approved these changes
안녕하세요 주노 !

첫 리뷰 때도 크게 수정할 부분은 없는 것 같아서 소소한 짧은 코멘트만 남겼었는데
개선해주신 부분 너무 잘 봤습니다 ㅎㅎ

이제 다음 미션 진행하시죠 !
고생많았습니다 🙂

2023-09-12 04:45 UTC, merged