[톰캣 구현하기 - 3, 4단계] 여우(조승현) 미션 제출합니다.
woowacourse/jwp-dashboard-http pull request #426
Opened 2023-09-09 06:29 UTC by BackFoxx

### 요구사항에 따라 추가한 것
* 요청마다 스레드를 새로 생성하지 않고, 스레드 풀에 있는 스레드를 사용하도록 개선했습니다.
* static 영역에 있는 HashMap의 동시성 위험을 피하기 위해 구현체를 ConcurrentHashMap으로 변경하였습니다.
### 내맴대로 추가한 것
* @RequestMapping 이라는 커스텀 어노테이션을 컨트롤러 클래스 위에 붙이면 프로세서가 알아서 인식합니다.
* 그렇게 찾아낸 컨트롤러에서, @RequestMapping의 uri 필드와 요청 uri가 일치하는 컨트롤러의 service()를 호출합니다.
* 만약 위에서 컨트롤러를 못 찾았다면,  @RequestMapping의 regex 필드와 요청 uri가 매치하는 컨트롤러의 service()를 호출합니다.

언제나 감사합니다 필립 😊

2023-09-10 09:31 UTC, pilyang reviewed
🦊 3-4단계도 역시 엄청 깔끔하게 잘 구현했네요..!!!

🦊코드리뷰 하면서 오히려 많이 배우고 생각해볼 수 있어서 영광이였습니다!!!

코드적인 부분에서 몇가지 궁금한점들 코멘트 남겼고, 지금당장 할 필요는 없을것 같지만 고민해보면 좋을 것 같은 부분들도 의견 남겨두었어요! 

---

지금은 모든 코드가 `coyote`에 있는데, 전체적인 부분으로는 패키지에 대해서도 한번 확인해보면 좋을 것 같아요.

이번 미션 패키지가 `nextstep.jwp`와 `org.apache`의 `catalina`, `coyote`로 나뉘어져 있는데 이 각각의 역할에 대해서도 찾아보고 배치를 해봐도 좋을 것 같아요.

언제든 궁금하거나 나누고싶은 이야기 있음 호출해주세요~

+) 인텔리제이로 리뷰 남겼는데,, 여러줄에 리뷰 남기는게 적용이 잘 안되어있네요ㅠㅜㅜㅜ 죄송합니다ㅠㅜㅜㅜㅜㅜ

2023-09-10 09:33 UTC, pilyang requested changes
실수로 코멘트로 남겼네요,,, request chagne 슬랙 알림용으로 request change로 다시 날려요!! 리뷰 내용들은 이전 코멘트 확인해주세요~

2023-09-10 13:07 UTC, BackFoxx commented on tomcat/src/main/java/org/apache/coyote/http11/request/HttpMethod.java
> +    }
오마이갓 필립 어케 이런 생각을 했어옵???????
지금까지 enum에서 값 찾기는 무조건 스트림만 사용해 왔는데
맵을 사용하니 진짜 훨씬 가독성있고 성능도 빠르겠네요

2023-09-10 13:12 UTC, BackFoxx commented on tomcat/src/main/java/org/apache/coyote/http11/request/HttpPath.java
> +
헙, 원래 html, css, js 별 요청에 따라 별도의 핸들러를 매핑하기 위해 사용했던 메서드들인데 
StaticResourceController에서 정규식을 통해 핸들러 매핑 작업을 통합하면서 필요없어진 메서드들이네요!

2023-09-10 13:12 UTC, BackFoxx commented on tomcat/src/main/java/org/apache/coyote/http11/session/SessionManager.java
> +    private static Map<String, Session> sessions = new ConcurrentHashMap<>();
꽁꺼렁트 짱!!

2023-09-10 13:13 UTC, BackFoxx commented on tomcat/src/main/java/org/apache/coyote/http11/controller/controllermapping/RequestMapping.java
> +}
으항항!!

2023-09-10 13:16 UTC, BackFoxx commented on tomcat/src/main/java/org/apache/coyote/http11/controller/controllermapping/ControllerMatcher.java
> +
IntelliJ에서 메서드 분리 단축키(command + option + M)을 사용하면
'메서드를 실행하기 위해 클래스 변수를 사용하는가?' 여부에 따라
분리한 메서드에 static을 자동으로 붙여주어요!

위 메서드같은 경우에는 findController 작업을 진행하기 위해
파라미터로 넘어온 HttpPath와 file[] 만 있으면 되고, 힙 영역에 등록되는(맞나?) 클래스 변수를 사용하지 않기 때문에
static을 붙여서 메서드를 스태틱 영역에 위치시키고 재활용할 수 있도록 최적화하고 있습니다!

2023-09-10 15:43 UTC, BackFoxx commented on tomcat/src/main/java/org/apache/coyote/http11/controller/StaticResourceController.java
> +        }
짱이에요 필립!! 안그래도 중복이 많아 언젠간 고쳐야지~~ 하면서 방치중이었는데
enum을 사용해 깔끔히 정리했습니당

2023-09-10 15:47 UTC, BackFoxx commented on tomcat/src/main/java/org/apache/coyote/http11/controller/controllermapping/ControllerMatcher.java
> +        }
ㅎ.ㅎ 그러게용 바보짓했조

2023-09-10 16:21 UTC, BackFoxx commented on tomcat/src/main/java/org/apache/coyote/http11/controller/controllermapping/ControllerMatcher.java
> +        }
요청마다 컨트롤러 스캐닝을 해야 한다는 점은 생각해본 적이 없는데
미쳣다 진짜 양재필씨의 혜안.........................
이 피드백을 반영하기 위해 코드를 뚝딱뚝딱 뜯어고쳤더니
코드가 진짜 깔끔해지고 보기 편해졌어요!
요청마다 클래스 스캔을 하지 않으니 성능적인 개선도 많이 됐을 거구요
와 진짜 짱이네요👍🏻🥹

2023-09-11 12:21 UTC, pilyang approved these changes
🦊 이번 미션 고생 많았어요!!!

코멘트 준 부분들 반영된것들이나, 의견 주신 부분들 확인했어요~!!!

내일부터 새로운 미션 진행해야하고, 프로젝트도 있고 하여 이번 미션은 Approve 하고 머지 할께요!!

다만, 같이 의견 나누고싶거나 고민해볼만한 부분들 코멘트에 남겨두었습니다! 확인해보시면 좋을 것 같아요!! 코멘트 댓글로 남기면 메일로 알림이 와서 저도 확인해보겠습니다!!ㅎㅎ (아니면 언제든 편하게 dm주거나 호출해서 이야기 해보아도 좋아요~)

추가로 이전에 RC 리뷰 코멘트 본문에서 남긴 패키지에 대한 고민을 하며, `Session`과 `Controller`들이 어떤 패키지에 있는것이 좋을까에 대한 고민도 해보고 기회가 된다면 같이 이야기 나눠보면 좋을 것 같아요.

고생했고 다음미션도 같이 화이팅 해봐요 😄

2023-09-11 12:21 UTC, pilyang commented on tomcat/src/main/java/org/apache/coyote/http11/controller/StaticResourceController.java
> +        }
Enum을 사용하니 중복이 제거되고 확실히 깔끔해 졌네요!!

지금은 ContentType값들을 다 순회하면서 if를 통해서 매칭이 되는 타입으로 response를 만들어주고 있는데, 이것을 `ContentType.findBySymbol`을 만들고, `ContentType` enum안에서 확장자로 enum값을 맵핑해두는 맵으로 캐싱해두면 매번 반복문을 통해서 확인을 하지 않아도 될 것 같네요!

2023-09-11 12:21 UTC, pilyang commented on tomcat/src/main/java/org/apache/coyote/http11/controller/controllermapping/ControllerMatcher.java
> +
오 생각하지 못했던 부분인데, 확실히 기존에 메소드들은 인스턴스 상태에 영향을 끼치거나 받지 않고, 어차피 private method여서 객체 없이 사용하지도 못하게 되니까 static으로 하여 메모리 사용량을 향상시킬 수 있겠네요..!!

만약에 해당 static method들이 public method였었다면 객체를 생성하지 않고도 사용할 수 있게되어 사용에 좀 더 의문이 들었을 것 같은데,, 여우 덕분에 새로운 방향에 대해서 생각해보게 되었네요..!!

그런데 지금은 `findController`또한 static method가 되었네요..! 혹시 이유가 있을까요..?

2023-09-11 12:22 UTC, merged

2023-09-11 12:28 UTC, kpeel5839 commented on tomcat/src/main/java/org/apache/coyote/http11/request/HttpMethod.java
> +    }
지리네연

2023-09-11 12:31 UTC, kpeel5839 commented on tomcat/src/main/java/org/apache/coyote/http11/controller/controllermapping/ControllerMatcher.java
> +
대박. 새로운 관점이네요

2023-09-11 12:32 UTC, kpeel5839 commented on tomcat/src/main/java/org/apache/coyote/http11/controller/controllermapping/ControllerMatcher.java
> +        }
> 다만 이렇게 되면 클래스들의 리스트와, 클래스 객체 모두 매 요청시마다 생롭게 검색하고 생성하게 될 것 같네요..! 어차피 이부분은 이번 미션 외적인 부분이라 아래 두가지 부분에 대해서 생각만 해봐도 좋을 것 같아요!!

생롭게?

2023-09-11 12:32 UTC, kpeel5839 commented on tomcat/src/main/java/org/apache/coyote/http11/session/SessionManager.java
> +    private static Map<String, Session> sessions = new ConcurrentHashMap<>();
귀요미 여우짱

2023-09-12 06:16 UTC, BackFoxx commented on tomcat/src/main/java/org/apache/coyote/http11/controller/controllermapping/ControllerMatcher.java
> +
무슨 짓이에요 맫뚜 어른들이 얘기하고 있잔아요

2023-09-12 06:16 UTC, BackFoxx commented on tomcat/src/main/java/org/apache/coyote/http11/controller/controllermapping/RequestMapping.java
> +}
개쩔조!!!!!!!!!!!!!!!

2023-09-12 06:16 UTC, BackFoxx commented on tomcat/src/main/java/org/apache/coyote/http11/request/HttpPath.java
> +
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ