[톰캣 구현하기 - 3, 4단계] 라온(문채원) 미션 제출합니다.
woowacourse/jwp-dashboard-http pull request #433
Opened 2023-09-09 13:33 UTC by mcodnjs

2023-09-09 19:29 UTC, mcodnjs commented on tomcat/src/main/java/org/apache/coyote/http11/common/ResourceContentTypeResolver.java
> +    public String getContentType(final HttpHeaders headers, final String resourceName) {
해당 클래스의 메서드는 들어온 요청의 헤더와 확장자를 파싱하여 response의 Content-Type 을 결정하는 메서드입니다!

로직은 아래와 같습니다 ~!
1. Request Header의 Content-Type 의 첫번째 value를 가져온다.
2. 해당 value에 지원하는 MediaType이 있다면 바로 반환한다.
3. 지원하는 MediaType이 없다면, 1번 과정을 Accept 헤더로 동일하게 반복한다.
4. 지원하는 MediaType이 없다면, 요청 리소스의 확장자를 파싱하여 MediaType의 subType과 비교하여 MediaType을 반환한다.
5. 지원하는 MediaType이 없다면, null이 반환되고, HttpException이 발생한다.

아래의 경우를 예시로 들면, 
Content-Type 헤더가 존재하지 않으므로 
Accept 헤더의 첫번째 값인 _`text/html`_을 나타내는 MediaType(_`TEXT_HTML`_)을 찾아 
String(_`text/html`_)으로 반환합니다!

```
GET /index.html HTTP/1.1
Accept: text/html,application/xhtml+xml,application/xml;q=0.9
```

2023-09-10 13:20 UTC, CFalws requested changes
라온 리팩토링 잘해주셔서 수월하게 리뷰 했습니다. 
많이 바쁘실텐데 리뷰 남긴 것 중에 하시고 싶으신 것만 선택적으로 반영하셔도 됩니다. 
그리고 다른 의견 혹은 라온의 원래 의도, 부담없이 댓글 남겨주시면, 확인하도록 하겠습니다 ^_^
고생 많으셨습니다👍

2023-09-10 13:20 UTC, CFalws commented on tomcat/src/main/java/org/apache/catalina/controller/HttpController.java
> +        }
현재는 해당 uri에 HTTP 메서드가 허용되는지 두 군데에서 관리되고 있습니다. 
canHandle과 doGet, doPost override가 그것인데요. 

**요청**
GET /login HTTP/1.1

위와 같은 요청을 처리하는 컨트롤러를 만든다고 가정했을 때,
canHandle이 true를 반환하고 doGet을 override 하지 않으면 doGet 메서드가 아무일도 하지 않게 됩니다.
반대로 canHandle은 false를 반환했는데 doGet이 override 되어 있다면 예외를 던지고 NOT_FOUND를 발생시키게 되는데요.

톰캣 같은 경우에는 doGet 같은 메서드 오버라이드 여부를 통해 처리를 하는 것으로 알고 있습니다. 
이처럼 관리 포인트를 한 가지로 만들 수 있는 방법도 생각해보시면 좋을 거 같습니다. 
(이 리뷰는 그냥 생각해보실만한 포인트라 남겨둔 것이고 그냥 쓰루하셔도 됩니다.)

2023-09-10 13:30 UTC, CFalws commented on tomcat/src/main/java/org/apache/coyote/http11/request/HttpRequestParser.java
> +    private Map<String, String> parseRequestBody(final String contentLengthHeader) throws IOException {
[1, 2 단계 미션](https://github.com/woowacourse/jwp-dashboard-http/pull/376#discussion_r1320628376)에서 자세한 설명 요청 주셔서 여기에 달도록 하겠습니다. 

예를 들어 
POST /uri/example HTTP/1.1
Content-Type: application/json
Content-Length: 14

{"key": "value"}

위와 같은 요청이 들어왔을 때 empty 상태인 Map이 전달되어서 body에 값이 있지만 마치 없는 것처럼 동작하는 버그가 발생할 수 있다는 의미였습니다

2023-09-10 13:40 UTC, CFalws commented on tomcat/src/main/java/org/apache/coyote/http11/request/HttpRequestParser.java
> +            if (requestHeaders.getHeaderValue(CONTENT_LENGTH) != null) {
참고로 [구구의 리뷰](https://github.com/woowacourse/jwp-dashboard-http/pull/440#discussion_r1320675779)인데요
null을 반환하면 이런 문제가 있을 수 있다고 합니다.

2023-09-11 15:47 UTC, mcodnjs reviewed
안녕하세요, 에밀 
정말정말 꼼꼼하고 자세한 리뷰 감사합니다! 덕분에 정말 많이 배웠습니다 .. 
말씀 주신 부분은 모두 커멘트 달고 수정하였는데요, 
추가적으로 리뷰하실 사항 있으시면 언제든지 마음껏 달아주셔도 됩니다 🙇‍♂️
아래 사진은 .. 저 이해하려고 만들었다가 도움이 되실까 해서 커멘트에도 참고합니다 ㅎㅎ

<img width="861" alt="image" src="https://github.com/woowacourse/jwp-dashboard-http/assets/64852591/23fe42ab-1941-48d2-8076-1c53f391c82a">

2023-09-11 15:47 UTC, mcodnjs commented on tomcat/src/main/java/org/apache/coyote/http11/request/HttpRequestParser.java
> +    private Map<String, String> parseRequestBody(final String contentLengthHeader) throws IOException {
아하 ... 완전히 간파해버렸습니다. 제가 Content-Type에 대해 무지했네요 .. 
해당 부분은 현재 미션에서는 말씀 주신 것처럼 `Content-Type: application/x-www-form-urlencoded`로만 요청이 오기에 문제가 없어 보였네요 ..! 다만, 이 부분은 ... 시간 관계상 ..  추후 .. TODO로 남겨놓겠습니다 ㅎㅎ 감사합니다 👍

2023-09-11 15:47 UTC, mcodnjs commented on tomcat/src/main/java/org/apache/coyote/http11/request/HttpRequestParser.java
> +        }
허허 .. 천재신가요 에밀?

2023-09-11 15:47 UTC, mcodnjs commented on tomcat/src/main/java/org/apache/coyote/http11/request/HttpRequestParser.java
> +            if (requestHeaders.getHeaderValue(CONTENT_LENGTH) != null) {
참고 리뷰까지 감사합니다~
Map의 경우 존재하지 않는 key에 대한 null 반환은 자연스럽다고 생각하여 이부분은 그대로 유지했구요
null을 명시적으로 반환하는 로직만 Optional을 반환하도록 변경하였습니다!

2023-09-12 06:20 UTC, CFalws approved these changes
라온 빠르게 리뷰 적용해주셨네요 ~
덕분에 리뷰 하면서 많이 배우고 고민해볼 수 있었습니다. 
이번 미션 고생하셨고 다음 미션도 화이팅입니다^_^

2023-09-12 06:20 UTC, CFalws commented on tomcat/src/main/java/org/apache/catalina/controller/HttpController.java
> +        }
수정하신 방식 좋은데요? 👍

2023-09-12 06:20 UTC, CFalws commented on tomcat/src/main/java/org/apache/coyote/RequestMapping.java
> +import nextstep.jwp.controller.RootController;
현재 패키지 의존이 nextstep -> org.apache.coyote -> nextstep(컨트롤러들) 으로 순환의존이 있는데요 
nextstep 패키지가 서버 개발자의 코드, coyote는 톰캣의 코드라고 가정하면, (구구께서 말씀하신 것처럼) 
톰캣의 코드가 서버 개발자의 코드에 의존하고 있는 상태인데요
해당 부분에 대해 생각해보시는 것도 좋을 것 같습니다😃

2023-09-12 06:24 UTC, merged