[톰캣 구현하기 - 3, 4단계] 레오(치영호) 미션 제출합니다.
woowacourse/jwp-dashboard-http pull request #438
Opened 2023-09-09 14:35 UTC by youngh0

안녕하세요 박스터. 오랜만에 리뷰 요청 드립니다. 1,2 단계 빠르게 머지 해주셨는데 플젝 하느라 미션 제출이 늦었네요..

3,4 단계 적용 말고는 큰 변경 사항은 없었습니다. 미션에 있는 형태대로 하기 위해 Response를 빈 값으로 만드는 작업 정도가 있겠네요.

현재 HttpsResponse 객체를 보면 많은 값을 가지고 있는데 HttpRequest 객체처럼 reponseStatusLine, requestHeader, requestBody 로 객체를 감싸고 이 3개만 의존하도록 수정할 계획입니다. 저 부분 까지 수정하고 제출하면 늦어질 것 같아서 바로 적용하진 못했습니다..

3,4 단계를 적용하면서 아직 Connector, Precessor 흐름에 대해서 감을 못 잡아서 혹시 잘못되거나 의견 주고 싶으신 부분 있으면 편하게 리뷰 남겨주십쇼!! 내일 책 보면서 더 공부해서 보완할 부분 있으면 보완하겠습니다~

3,4 단계도 잘 부탁드립니다 👍

2023-09-09 14:46 UTC, drunkenhw requested changes
안녕하세요 레오 
깔끔하게 수정된 것 확인했습니다.
하나 아쉬운 점을 꼽자면은 apache 패키지와 jwp 패키지가 양방향으로 의존하고 있다는 점이네요
이런 부분은 추상화를 통해 끊어내는 것은 어떨까요?
화이팅 입니다 빵야

2023-09-09 14:46 UTC, drunkenhw commented on tomcat/src/main/java/org/apache/catalina/connector/Connector.java
> +    private static final int DEFAULT_ACCEPT_MAX_THREADS = 50;
max thread를 50으로 하신 이유가 있으신가요?

2023-09-09 14:46 UTC, drunkenhw commented on tomcat/src/main/java/org/apache/coyote/http11/common/SessionManager.java
> +    private static final Map<UUID, Session> SESSIONS = new ConcurrentHashMap<>();
Good

2023-09-09 14:46 UTC, drunkenhw commented on tomcat/src/main/java/org/apache/coyote/http11/handler/Handlers.java
> +        handler.handle(httpRequest, httpResponse);
handle 메서드를 static으로 하신 이유가 있으실까요?

2023-09-09 14:46 UTC, drunkenhw commented on tomcat/src/main/java/org/apache/coyote/http11/handler/LoginHandler.java
> +    }
메서드 분리 Good
LMS에 적혀있는 힌트를 참고해서 구현하는 것도 좋아보여요!
저도 LMS 에서 힌트를 얻어 구현했더니 코드가 좀 더 깔끔해지더라고요

2023-09-09 14:46 UTC, drunkenhw commented on tomcat/src/main/java/org/apache/coyote/http11/handler/RegisterHandler.java
> +        if (httpRequest.getRequestMethod() == RequestMethod.GET) {
httpRequest.isMatchMethod(GET) 이런 식으로 구현해도 좋을 것 같아요~

2023-09-09 14:46 UTC, drunkenhw commented on tomcat/src/main/java/org/apache/coyote/http11/response/HttpResponse.java
> +    private Cookie cookie;
좀 더 비슷한 객체끼리 묶어서 관리하면 http Response 클래스의 역할이 좀 줄고 가독성도 좋아질 것 같아요~!

2023-09-09 14:46 UTC, drunkenhw commented on tomcat/src/main/java/org/apache/coyote/http11/response/HttpResponse.java
> +        this.responseHeaders.put("Content-Length", String.valueOf(fileData.getBytes().length));
이런 부분은 전역적으로 사용되니 상수 클래스에서 관리하는 것 은 어떨까요?

2023-09-09 14:46 UTC, drunkenhw commented on tomcat/src/main/java/org/apache/coyote/http11/response/HttpResponse.java
> +            headers.add("Set-Cookie: JSESSIONID=" + jsessionid + " ");
JESSIONID 라는 상수 위에 선언되어있던데..

2023-09-09 14:46 UTC, drunkenhw requested changes
안녕하세요 레오 
깔끔하게 수정된 것 확인했습니다.
하나 아쉬운 점을 꼽자면은 apache 패키지와 jwp 패키지가 양방향으로 의존하고 있다는 점이네요
이런 부분은 추상화를 통해 끊어내는 것은 어떨까요?
화이팅 입니다 빵야

2023-09-09 15:46 UTC, youngh0 commented on tomcat/src/main/java/org/apache/coyote/http11/handler/Handlers.java
> +        handler.handle(httpRequest, httpResponse);
Handlers는 Handler 들을 가지고 있는 일급컬렉션 느낌입니다.
해당 객체에 추가적인 책임이 생길 거 같지 않아서 handler 메서드 하나만 호출하고 가변적인 상태를 저장하고 있지 않아서 static 으로 구성해 Processor 에서 바로 Handlers.handle 을 호출하도록 했습니다!

2023-09-09 15:50 UTC, youngh0 commented on tomcat/src/main/java/org/apache/coyote/http11/handler/RegisterHandler.java
> +        if (httpRequest.getRequestMethod() == RequestMethod.GET) {
오 그러네여 바로 반영했습니다 good~

2023-09-10 05:11 UTC, drunkenhw commented on tomcat/src/main/java/org/apache/coyote/http11/handler/Handlers.java
> +        handler.handle(httpRequest, httpResponse);
>앞에서 말했다시피 정적 메소드는 객체의 생성주기와 관계가 없다. 이런 점에서 정적메소드는 객체 지향의 메시지 전달(message passing)[1]을 위반한다. 객체 지향에서는, 객체들은 서로 관계를 맺고 메시지를 통해 정보를 교환하고 결과를 반환한다. 정적 메소드를 실행하는 것은 객체에게 행위를 지시하는 것이 아니다. 다른 객체와 관계를 맺고 있지도 않다. 즉, 메시지 전달이 아니라 (절차 지향의) 함수 호출에 불과하다고 할 수 있다.

저는 개인적으로 static 메서드를 지양하나 util class 에서 사용하는 것 정도는 괜찮다고 생각합니다. 
이유는 static으로 선언하면 어느 클래스에서나 해당 메서드를 사용할 수 있다는 점입니다. 스태틱 메서드를 가지고 있으면 객체간의 서로 협력이 아닌 바로 호출한다는 점인 것 같아요
조금 더 객체지향적인 관점으로 static 메서드를 제거해서 미션을 해보시는 것은 어떠신가요?

https://tecoble.techcourse.co.kr/post/2020-07-16-static-method/

2023-09-10 14:31 UTC, youngh0 commented on tomcat/src/main/java/org/apache/coyote/http11/response/HttpResponse.java
> +    private Cookie cookie;
ResponseLine, ResponseHeaders, ResponseBody 로 분리했습니다!

2023-09-10 14:31 UTC, youngh0 commented on tomcat/src/main/java/org/apache/coyote/http11/response/HttpResponse.java
> +        this.responseHeaders.put("Content-Length", String.valueOf(fileData.getBytes().length));
상수화 완료했습니다!

2023-09-10 14:31 UTC, youngh0 commented on tomcat/src/main/java/org/apache/coyote/http11/response/HttpResponse.java
> +            headers.add("Set-Cookie: JSESSIONID=" + jsessionid + " ");
아이고..

2023-09-10 15:59 UTC, youngh0 commented
안녕하세요 박스터! 참고할 레퍼런스도 주시고 감사합니다 ㅎㅎ

박스터 리뷰대로 패키지 양방향을 제거하려고 노력해봤습니다! 

리팩터링 하다보니 coyote 패키지는 http server 역할, catalina 패키지는 servlet container, jwp 패키지는 저희가 흔히 짜는 repo, controller 역할을 하도록 수정했고, 이 과정에서 양방향 참조가 발생하는 부분은 interface 를 통해 끊어 봤습니다. (지금 생각해보니 Container 인터페이스에 addHandler 를 추가해 Tomcat 에서 이를 호출해 Handler 를 등록하는 것도 좋아보이네요 ㅎ..)

이를 통해 catalina, coyote, jwp 간의 순환참조는 끊을 수 있었습니다.
그러나, 여전히 apache, jwp 패키지만 보면 양방향 의존이 있는데요. 이걸 어떻게 끊을 수 있을까요..? 

1. Handler 를 전부 apache 에 놓아도 jwp 의 Application 이 Tomcat 을 인스턴스를 생성하고, LoginHandler 에서는 jwp 의 InMemoryRepo 를 의존하느라 양방향 의존이 생깁니다.
2. Handler 구현체를 jwp 패키지에 위치 시켜도 HttpRequest, HttpResponse 를 의존해야 하기 때문에 apache 패키지를 의존할 수 밖에 없고, 1번과 마찬가지로 jwp의 Application이 Tomcat 을 의존해 양방향 의존이 생기네요..

방법이 안떠오르네요.. 혹시 좋은 아이디어 있으시면 힌트라도 주시면 감사하겠습니다 ㅎ
계속 고민하면 리뷰 요청이 많이 늦어질 것 같아 일단 리뷰 요청 드립니다!

2023-09-10 16:19 UTC, drunkenhw requested changes
안녕하세요 레오 
관련해서 질문주신거에 대해 제 생각을 짧게 남겨봤습니다 
코드가 멋지네요 빵야

2023-09-10 16:19 UTC, drunkenhw commented on tomcat/src/main/java/org/apache/catalina/servletcontainer/HandlerContainer.java
> +            );
저는 이 부분이 패키지 양방향 참조가 되는 부분이라고 생각이 드는데요.
만약 진짜 톰캣이라면 이러한 매핑 정보를 apache 패키지 내에서 설정을 하는 것일까요?
저희도 스프링을 사용하면서 매번 톰캣으로 웹 사이트를 띄우는데 저희는 톰캣 코드를 손 댄적이 없는 것 같아서요
제가 생각했을 때에는 의존성을 없앨 두가지 방법이 있을 것 같아요
1. 톰캣을 생성할 때 해당 Map을 넣어주기
2. 톰캣에 해당 매핑 정보를 넣을 수 있는 메서드 만들기 ex)`tomcat.addContainer("/", new RootHandler())`


둘 중 어떤 코드가 나은 방법인지는 저도 잘 모르겠습니다. 하지만 저는 톰캣 코드를 까보면서 힌트를 얻긴했습니다.
물론 이게 정답은 아니라 흘려들으셔도 좋습니다!

2023-09-10 16:19 UTC, drunkenhw commented on tomcat/src/main/java/nextstep/jwp/handler/LoginHandler.java
> +    }
https://techcourse.woowahan.com/s/tTBHBX6I/ls/6AeH2Iqy
여기서 `3. Controller 인터페이스 추가해보기` 를 적용하시면 hanlder마다 생기는 중복로직이 사리지고 코드가 깔끔해질 것 같은데요
지금 코드도 가독성이 떨어지는 부분은 아니니깐 해당 패턴을 적용해봐도 좋을 것 같다고 추천만 드리겠습니다~

2023-09-10 16:19 UTC, drunkenhw commented on tomcat/src/main/java/org/apache/catalina/connector/Connector.java
> +        var processor = new Http11Processor(connection, new HandlerContainer());
해당 클래스에서 HanlderContainer를 생성하는 이유가 있으신가요? 궁금해서요

2023-09-10 16:19 UTC, drunkenhw commented on tomcat/src/main/java/org/apache/coyote/http11/common/Cookie.java
> +                .forEach(cookieHeader::add);
```suggestion
String cookieHeader = cookies.entrySet()
    .stream()
    .map(entry -> entry.getKey() + COOKIE_VALUE_DELIMITER + entry.getValue())
    .collect(Collectors.joining(COOKIE_DELIMITER));

```
이런 코드는 어떠신가요

2023-09-10 16:19 UTC, drunkenhw commented on tomcat/src/main/java/org/apache/coyote/http11/response/ResponseBody.java
> +    }
```suggestion
    public static ResponseBody empty() {
        return new ResponseBody("");
    }
```
이런 코드가 휴먼 에러를 방지할 것 같은데 정적 팩토리 메서드로 확실하게 네이밍을 해주는 것에 대해 어떻게 생각하시나요

2023-09-10 16:19 UTC, drunkenhw commented on tomcat/src/main/java/org/apache/coyote/http11/response/ResponseHeaderKey.java
> +    JSESSION("JSESSIONID");
good

2023-09-10 16:19 UTC, drunkenhw commented on tomcat/src/main/java/org/apache/coyote/http11/response/ResponseHeaders.java
> +    protected ResponseHeaders() {
protected인 이유가 있을까요?

2023-09-10 16:19 UTC, drunkenhw commented on tomcat/src/main/java/org/apache/coyote/http11/response/ResponseHeaders.java
> +                .forEach(headers::add);
collect joining은 어떠신가요?

2023-09-10 16:25 UTC, youngh0 commented on tomcat/src/main/java/org/apache/catalina/connector/Connector.java
> +    private static final int DEFAULT_ACCEPT_MAX_THREADS = 50;
LMS 를 못봤습니다..

2023-09-11 05:42 UTC, youngh0 commented on tomcat/src/main/java/org/apache/catalina/servletcontainer/HandlerContainer.java
> +            );
박스터 리뷰를 보고 Tomcat 코드를 뜯어봤습니다.

Tomcat 에 addServlet 메서드가 있더라구요. 그래서 제 예상으론 spring 의 @WebServlet 어노테이션을 통해 servlet 을 등록하는게 아닐까 싶습니다. @Controller 어노테이션은 DispatchServlet 에 컨트롤러를 Handler 로 등록하고 이런식으로 동작할 거 같은데 조금 더 공부를 해봐야 할 것 같아요!

좋은 공부거리 주셔서 감사합니다 ㅎㅎ

2023-09-11 05:44 UTC, youngh0 commented on tomcat/src/main/java/nextstep/jwp/handler/LoginHandler.java
> +    }
적용해보려고 했는데 플젝이랑 다른 공부도 하기에는 적용할 시간이 부족할 것 같아서 못했네요.. 

그래도 감사합니다!!

2023-09-11 05:44 UTC, youngh0 commented on tomcat/src/main/java/org/apache/catalina/connector/Connector.java
> +        var processor = new Http11Processor(connection, new HandlerContainer());
이 부분은 당장 컴파일 에러가 발생했는데 Tomcat 구조를 뜯어보면서 수정했습니다!

2023-09-11 05:46 UTC, youngh0 commented on tomcat/src/main/java/org/apache/coyote/http11/common/Cookie.java
> +                .forEach(cookieHeader::add);
좋네요!! 감사합니다!

2023-09-11 05:49 UTC, youngh0 commented on tomcat/src/main/java/org/apache/coyote/http11/response/ResponseHeaders.java
> +    protected ResponseHeaders() {
ResponseHeaders 를 생성하는 책임은 처음 HttpResponse 를 생성할 때 라고 생각했습니다. 이후 header 값을 설정하는 것은 addHeader 로 수행하기 때문에 같은 package 내부에서만 생성할 수 있도록 방어하기 위해서 protected 로 작성했습니다.

2023-09-11 05:50 UTC, youngh0 commented on tomcat/src/main/java/org/apache/coyote/http11/response/ResponseHeaders.java
> +                .forEach(headers::add);
반영했습니다!

2023-09-11 05:55 UTC, youngh0 commented on tomcat/src/main/java/org/apache/coyote/http11/response/ResponseBody.java
> +    }
명확한 네이밍을 주는게 휴먼 에러를 방지할 수 있겠네요!

2023-09-11 06:25 UTC, youngh0 commented
안녕하세요 박스터! 리뷰 덕분에 톰캣 코드도 까보고 너무 좋았습니다!

이번에는 Handler 등록 코드를 박스터 리뷰를 참고해 수정해봤습니다. 톰캣 코드를 보니 현재 제 코드에서의 Handler 가 사실상 Servlet 인 것 같네요.

리뷰 코멘트에도 남겼지만, 저희가 코드를 작성할 때 직접 서블릿을 작성하고 톰캣의 서블릿 컨테이너에 등록하는 코드를 작성한 적이 없던 것 같아요. 
직접 코드를 까보고 든 생각은 spring 의 @WebServlet 어노테이션을 통해 서블릿을 정의하면 내부적으로 tomcat.addServlet 이 호출되면서 컨테이너에 서블릿이 등록되지 않을까 싶네요. 
@Controller 어노테이션은 DispatcherServlet 에 핸들러로 등록해주는 차이가 있을 것 같아요. 아직은 뇌피셜이라 더 확인은 해봐야될 거 같아요.

2023-09-11 06:31 UTC, drunkenhw approved these changes
리뷰 반영하신거 확인했습니다.
훨씬 더 구조가 깔끔하고 멋지네요 역시 레오입니다
다음 미션도 화이팅 입니다. 빵야

2023-09-11 06:31 UTC, drunkenhw commented on tomcat/src/main/java/org/apache/coyote/http11/response/ResponseBody.java
> +        return new ResponseBody("");
생성자를 실수로 잘못 만드신 것 같네요..ㅎ

2023-09-11 06:31 UTC, drunkenhw commented on tomcat/src/main/java/org/apache/coyote/http11/response/ResponseHeaders.java
> +    private ResponseHeaders(Map<String, String> responseHeaders, Cookie cookie) {
이렇게 파라미터로 받으면 field로 받아야하는거 아닌가요............?

2023-09-11 06:31 UTC, drunkenhw commented on tomcat/src/main/java/org/apache/coyote/http11/response/ResponseLine.java
> +    protected static ResponseLine init() {
init 보다는 create가 좋아보이는데 어떠신가요?

2023-09-11 06:32 UTC, merged

2023-09-11 06:33 UTC, youngh0 commented on tomcat/src/main/java/org/apache/coyote/http11/response/ResponseHeaders.java
> +    private ResponseHeaders(Map<String, String> responseHeaders, Cookie cookie) {
어이쿠 그러네요. 급하게 수정하다가 놓쳤네요 ㅎ