[톰캣 구현하기 - 3, 4단계] 달리 미션 제출합니다
woowacourse/jwp-dashboard-http pull request #442
Opened 2023-09-10 02:56 UTC by waterricecake

안녕하세요 아코!
이번 단계에 리펙토링을 통해 전체적으로 바꿔 보았어요.
request가 들어오면
1. filter를 통해 현재 jsession이 존재할 경우 맞는 유저인지 확인하여 리다이렉트를 해주거나 아님 유저가 아닐경우 401에러 페이지를 리다이렉트 해줍니다.
2. 필터에 적용되는 path가 아니라면 handler를 통해 알맞는 path가 있는지 확인하고 없을 경우 404에러를 띄어 주었습니다.

잘부탁드립니다.

2023-09-12 00:26 UTC, seokhwan-an requested changes
안녕하세요! 달리
먼저 3, 4단계도 고생하셨습니다!👏

3, 4단계를 진행하면서 코드의 전체적인 구조와 흐름에서 가독성이 좋아져서 코드 리뷰를 하는데 술술 읽혀서 즐거웠습니다. 

코드 리뷰를 하면서 달리의 의견을 듣고 싶은 부분에 대해서 피드백을 남겼습니다! 한번 확인부탁드립니다!

2023-09-12 00:26 UTC, seokhwan-an commented on tomcat/src/main/java/org/apache/coyote/http11/request/HttpMethod.java
> +    GET("GET"),
여기도 개행 한줄 추가해 주세요!

2023-09-12 00:26 UTC, seokhwan-an commented on tomcat/src/main/java/nextstep/jwp/controller/RegisterController.java
> +
여기 개행이 두줄 입니다!😱

2023-09-12 00:26 UTC, seokhwan-an commented on tomcat/src/main/java/nextstep/jwp/db/InMemorySession.java
>      private static final Map<User, UUID> session = new HashMap<>();
한줄 개행 추가부탁합니다!
혹시 UUID가 키 값이 아니고 User가 키 값인 이유가 있을까요? 저라면 UUID를 키값으로 가지고 저희가 필요한 정보인 User를 값으로 했을 것 같습니다. 이 부분에 대해서 달리의 의견이 궁금합니다!

2023-09-12 00:26 UTC, seokhwan-an commented on tomcat/src/main/java/nextstep/jwp/exception/UnauthorizedException.java
>      public UnauthorizedException(String message) {
여기도 개행 추가 부탁드립니다!

2023-09-12 00:26 UTC, seokhwan-an commented on tomcat/src/main/java/org/apache/coyote/http11/servlet/Servlet.java
여기도 개행이 두줄입니다!😱

2023-09-12 04:37 UTC, waterricecake commented on tomcat/src/main/java/nextstep/jwp/db/InMemorySession.java
>      private static final Map<User, UUID> session = new HashMap<>();
오 아코 말이 맞는 것 같네요! 단순히 user가 key를 가지는 것이라 생각했는데 생각해보니 uuid를 통해 user를 찾는 것이니 이런형식이 맞겠군요.

2023-09-12 09:20 UTC, waterricecake commented on tomcat/src/main/java/org/apache/coyote/http11/handler/HandlerAdapter.java
> +    }
`RequestMapper`는 각 컨트롤러가 담당하는 method와 url을 저장하는 값객체인데 제가 클래스명을 제대로 정하지 않아서 헤깔릴수도 있겠다 생각이 드네요. 정확한 역할은 
1. RequestMapper: path와 method를 통해 equals와 hash를 정의하고 가지고 있음
2. HandlerAdapter: Map<RequestMapper,Controller>로 사용자의 요청과 requestMapper를 매칭하고 해당하는 컨트롤러를 찾아줌

입니다. 때문에 requestMapper의 클래스명을 바꾸는 것이 어떤가 생각합니다.

2023-09-12 09:22 UTC, waterricecake commented on tomcat/src/main/java/org/apache/coyote/http11/filter/DefaultFilter.java
> +    }
doFilter가 아무런 필터를 추가하지 않았을때 npe를 피하기 위해 설정해둔 것인데 이를 initialChain과 lastChain에 초기 생성시 정의하는 것을 잊었네요;;;;;

2023-09-12 09:23 UTC, waterricecake commented on tomcat/src/main/java/org/apache/coyote/http11/filter/FilterChainManager.java
> +    }
doFilter가 아무런 필터를 추가하지 않았을때 npe를 피하기 위해 설정해둔 것인데 이를 initialChain과 lastChain에 초기 생성시 정의하는 것을 잊었네요;;;;;

2023-09-12 09:27 UTC, waterricecake commented on tomcat/src/main/java/nextstep/jwp/config/LoginFilter.java
> +        final var cookie = request.getCookie();
아 원래는 `var`를 안쓸려고 했는데 여기에 추가한 것을 깜빡했네요;;;;
`var`를 안써봐서 확실한 기준이 아직은 없네요;;

2023-09-12 10:36 UTC, waterricecake commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +            filterChainManager.getInitialChain().doFilter(request, response);
[0ff993d](https://github.com/woowacourse/jwp-dashboard-http/pull/442/commits/0ff993d62eb09f71c101943630653459466f1e59)
[0fca1b5](https://github.com/woowacourse/jwp-dashboard-http/pull/442/commits/0fca1b57de3e6d162f524a123b6f184f0ee2c8f9)
적용하면서 handler또한 싱글톤으로 관리하면 좋겠다는 생각이 들어 추가해보았습니다.

2023-09-12 10:36 UTC, waterricecake commented on tomcat/src/main/java/org/apache/coyote/http11/servlet/Servlet.java
[8b12c21](https://github.com/woowacourse/jwp-dashboard-http/pull/442/commits/8b12c2183fa8ca9e52f42d28a3e7e2029fa14180)

2023-09-12 10:36 UTC, waterricecake commented on tomcat/src/main/java/nextstep/jwp/exception/UnauthorizedException.java
>      public UnauthorizedException(String message) {
[8b12c21](https://github.com/woowacourse/jwp-dashboard-http/pull/442/commits/8b12c2183fa8ca9e52f42d28a3e7e2029fa14180)

2023-09-12 10:36 UTC, waterricecake commented on tomcat/src/main/java/nextstep/jwp/controller/RegisterController.java
> +
[8b12c21](https://github.com/woowacourse/jwp-dashboard-http/pull/442/commits/8b12c2183fa8ca9e52f42d28a3e7e2029fa14180)

2023-09-12 10:36 UTC, waterricecake commented on tomcat/src/main/java/org/apache/coyote/http11/request/HttpMethod.java
> +    GET("GET"),
[8b12c21](https://github.com/woowacourse/jwp-dashboard-http/pull/442/commits/8b12c2183fa8ca9e52f42d28a3e7e2029fa14180)

2023-09-12 10:36 UTC, waterricecake commented on tomcat/src/main/java/org/apache/coyote/http11/request/RequestLine.java
> +    private final HttpMethod method;
[8b12c21](https://github.com/woowacourse/jwp-dashboard-http/pull/442/commits/8b12c2183fa8ca9e52f42d28a3e7e2029fa14180)

2023-09-12 10:37 UTC, waterricecake commented on tomcat/src/main/java/org/apache/coyote/http11/controller/AbstractController.java
> +
[8b12c21](https://github.com/woowacourse/jwp-dashboard-http/pull/442/commits/8b12c2183fa8ca9e52f42d28a3e7e2029fa14180)

2023-09-12 10:37 UTC, waterricecake commented on tomcat/src/main/java/org/apache/coyote/http11/handler/HandlerAdapter.java
> +    private final Map<RequestMapper, Controller> controllers = new HashMap<>();
[8b12c21](https://github.com/woowacourse/jwp-dashboard-http/pull/442/commits/8b12c2183fa8ca9e52f42d28a3e7e2029fa14180)

2023-09-12 10:37 UTC, waterricecake commented on tomcat/src/main/java/org/apache/coyote/http11/controller/ViewFunction.java
> +@FunctionalInterface
[ec7ad61](https://github.com/woowacourse/jwp-dashboard-http/pull/442/commits/ec7ad61cdb6aebf38e253844ce2f3fd57c72fd3c)

2023-09-12 10:37 UTC, waterricecake commented on tomcat/src/main/java/org/apache/coyote/http11/controller/RequestFunction.java
> +}
[ec7ad61](https://github.com/woowacourse/jwp-dashboard-http/pull/442/commits/ec7ad61cdb6aebf38e253844ce2f3fd57c72fd3c)

2023-09-12 10:42 UTC, waterricecake commented on tomcat/src/main/java/org/apache/coyote/http11/util/Resource.java
> +    }
[5019ea3](https://github.com/woowacourse/jwp-dashboard-http/pull/442/commits/5019ea3531f48d3096a6573eafddd746e7bd9ab8)

2023-09-13 02:59 UTC, seokhwan-an commented on tomcat/src/main/java/org/apache/coyote/http11/filter/FilterChainManager.java
> +    }
싱글톤을 잘 구현해주셨네요👍
코드 컨벤션은 잘 안 지켜졌네요..😥
``` suggestion
    public static FilterChainManager getInstance() {
        if (instance == null) {
            synchronized (FilterChainManager.class) {
                instance = new FilterChainManager();
            }
        }
        return instance;
    }
```

2023-09-13 02:59 UTC, seokhwan-an commented on tomcat/src/main/java/org/apache/coyote/http11/filter/FilterChainManager.java
> +        initialChain = lastChain = defaultChain;
이 부분은 두줄로 분리하는 것이 가독성이 좋을 것 같습니다!🤔

2023-09-13 02:59 UTC, seokhwan-an commented on tomcat/src/main/java/org/apache/coyote/http11/filter/FilterChainManager.java
> +            initialChain.next = chain;
컨벤션이 지켜지지 않았네요..
```suggestion
        if (initialChain.equals(defaultChain)) {
            initialChain = chain;
            initialChain.next = defaultChain;
            return;
        }
        if (lastChain.equals(defaultChain)) {
            initialChain.next = chain;
```

2023-09-13 02:59 UTC, seokhwan-an commented on tomcat/src/main/java/org/apache/coyote/http11/filter/DefaultFilter.java
> +    }
추가하신 것 확인했습니다!

2023-09-13 03:04 UTC, seokhwan-an commented on tomcat/src/main/java/org/apache/coyote/http11/filter/FilterChainManager.java
> +            }
여기도 코드 컨벤션이 지켜지지 않았네요..

2023-09-13 03:04 UTC, seokhwan-an commented on tomcat/src/main/java/org/apache/coyote/http11/filter/FilterChainManager.java
> +    }
추가하신 것 확인했습니다!

2023-09-13 03:09 UTC, seokhwan-an commented on tomcat/src/main/java/org/apache/coyote/http11/handler/HandlerAdapter.java
> +    }
클래스 명칭을 수정하니 보다 명확하게 이해가 됩니다. 개인적으로 궁금한 부분은 path만이 아닌 method까지 포함해서 controller를 찾는것 인데요. 그 이유는 controller 내부적으로 doPost와 doGet로 나누어져서 처리가 되기 때문에 path로만 controller를 찾는 것도 괜찮지 않을까 생각합니다.

2023-09-13 03:16 UTC, seokhwan-an commented on tomcat/src/main/java/org/apache/coyote/http11/controller/AbstractController.java
> +        doGet(request, response);
여기서 만약에 put이나 delete 요청이 들어오게 되면 어떻게 동작하게 될까요?🤔

2023-09-13 03:36 UTC, seokhwan-an approved these changes
안녕하세요 달리!
제 리뷰를 빠르게 반영해주셨군요!👍 감사합니다!

제가 달리에게 도움이 되는 리뷰어가 되기위해 리뷰를 할 때 최대한 사소한 것도 보다도 달리의 생각을 물어보면서 메타인지를 시켜주는 것을 목표로 했었는데 도움이 되었는지는 모르겠습니다..! 
저도 달리 코드를 보면서 많이 배울 수 있는 시간이었습니다☺️

현재 요구사항에 대해서는 충분히 만족한다고 생각해서 approve merge하겠습니다.
다음 미션도 화이팅입니다!💪

p.s 제가 처음에 미처 발견하지 못한 사항에 대해 리뷰 남겨보았는데 그 부분에 대해 확인해보면 좋을 것 같습니다!

2023-09-13 03:36 UTC, merged

2023-09-13 04:52 UTC, waterricecake commented on tomcat/src/main/java/org/apache/coyote/http11/controller/AbstractController.java
> +        doGet(request, response);
Handler adaptor에 현재 RequestInfo에 put이나 delete 메서드에 해당되는 RequestInfo가 없어 NoSuchApiException 처리가 될것 같네요. 많약 요청에 대한 controller가 필요하다면 AbstractController에 doPut, doDelete 메서드를 추가하여 구현할 것 같습니다.

2023-09-13 04:56 UTC, waterricecake commented on tomcat/src/main/java/org/apache/coyote/http11/filter/FilterChainManager.java
> +            }
😅

2023-09-13 04:56 UTC, waterricecake commented on tomcat/src/main/java/org/apache/coyote/http11/filter/FilterChainManager.java
> +            initialChain.next = chain;
😅

2023-09-13 04:56 UTC, waterricecake commented on tomcat/src/main/java/org/apache/coyote/http11/filter/FilterChainManager.java
> +        initialChain = lastChain = defaultChain;
😅

2023-09-13 04:56 UTC, waterricecake commented on tomcat/src/main/java/org/apache/coyote/http11/filter/FilterChainManager.java
> +    }
😅