[톰캣 구현하기 - 3, 4단계] 쥬니(전정준) 미션 제출합니다.
woowacourse/jwp-dashboard-http pull request #445
Opened 2023-09-10 06:56 UTC by cpot5620

안녕하세요 에단 ~! 3, 4단계 구현하여 리뷰 요청 드립니다 !

1, 2단계에서의 Handler가 Controller로 바뀌었고, 예외처리를 수행했다는 점 외에는 크게 달라진 점이 없는 것 같아요.
(아 ! JSESSIONID가 올바르지 않은 값일 경우에 해당 쿠키를 삭제하도록 응답 헤더를 수정하는 기능을 추가했어요 !)

이번 PR에서는 테스트를 모두 작성하여 요청하고 싶었는데, 제가 곧 축구를 하러 가야해서.. ⚽ (축구 없인 못살아 ~)
새벽에 PR 요청이 이루어질 것 같아, 우선적으로 리뷰 요청 드립니다.

테스트 코드는 리뷰 작성해주신 이후에, 일괄적으로 커밋하도록 하겠습니다 😄

2023-09-11 03:57 UTC, cookienc requested changes
안녕하세요 쥬니! 골 넣으셨나요?⚽️ㅋㅋㅋ
지난번도 워낙 코드가 좋아서 크게 리뷰할건 없었습니다. 특히 쿠키 지우는 로직도 인상적이었습니다.
이번에는 패키지 구조를 살펴봤고, 코드 스멜도 1개 밖에 없으니 지워주는게 좋을것 같아요.
이번에 반영하실 때는 테스트까지 반영해서 올려주세요. 감사합니다.

2023-09-11 03:57 UTC, cookienc commented on tomcat/src/main/java/org/apache/coyote/http11/common/HttpCookies.java
> +            String[] cookieAndAttribute = element.split(ATTRIBUTE_DELIMITER, 2);
오 이거 좋네요! 배워갑니다

2023-09-11 03:57 UTC, cookienc commented on tomcat/src/main/java/org/apache/coyote/http11/common/HttpCookies.java
> +    }
getCookies()가 HttpResponse 내부구현에 종속된다고 느껴지는데 어떻게 생각하시나요?

2023-09-11 03:57 UTC, cookienc commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +    private static final Logger LOGGER = LoggerFactory.getLogger(Http11Processor.class);
여기는 이름이 log가 아니라 Logger네요

2023-09-11 03:57 UTC, cookienc commented on tomcat/src/main/java/nextstep/jwp/exception/ExceptionHandler.java
> +public class ExceptionHandler {
WOW! 👍👍

2023-09-11 03:57 UTC, cookienc commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +            HttpRequest request = HttpRequestParser.parse(br);
parser를 적용하니까 훨씬 깔끔해졌네요👏

2023-09-11 03:57 UTC, cookienc commented on tomcat/src/main/java/org/apache/catalina/RequestMapping.java
> +public class RequestMapping {
controller는 프로그래머가 짠거니까 jwp 패키지에 놓고, 톰캣이 url과 controller를 알아야하니 requestMapping 을 만들어 catalina에 구현한 건 좋습니다! 실제로 코드도 깔끔하구요.
하지만 이 부분은 순환참조 문제가 생기는데요. 어떻게 개선해 볼 수 있을까요?
지금은 톰켓을 만드는게 주이기 때문에 고민만하고 넘어가셔도 좋아요. 다음 미션에서 스프링을 만드니 그 때 적용해보면 좋을 것 같아요. 답지도 첨부해드려요. 
[말랑 답지](https://github.com/woowacourse/jwp-dashboard-http/pull/383#pullrequestreview-1613632692)
cf) 인텔리제이의 dependency matrix 기능을 사용해보면 순환참조를 쉽게 발견할 수 있어요

2023-09-11 03:57 UTC, cookienc commented on tomcat/src/main/java/org/apache/coyote/http11/request/HttpRequestHeaders.java
> +
private 메서드가 맨 아래로 가는 건 어떨까요? 여러 메서드가 공유하는 private의 위치에 대한 쥬니만의 기준이 있나요?

2023-09-11 04:00 UTC, cookienc commented on tomcat/src/main/java/org/apache/coyote/http11/request/HttpRequestHeaders.java
> +
+ Map에 key를 String으로 관리하고 계시던데, HeaderType으로 안하시는 이유가 있을까요?

2023-09-11 11:12 UTC, cpot5620 commented on tomcat/src/main/java/org/apache/coyote/http11/common/HttpUri.java
> +    private static final int QUERY_STRING_NOT_EXIST_INDEX = -1;
오우.. 곰꼼하시네요 ㅎㅎ 감사합니다 

해당 사항 반영했습니다 !

2023-09-11 11:12 UTC, cpot5620 commented on tomcat/src/main/java/org/apache/coyote/http11/common/HttpUri.java
>      private final QueryString queryString;
해당 사항 반영했습니다 222222

2023-09-11 11:13 UTC, cpot5620 commented on tomcat/src/main/java/org/apache/coyote/http11/request/HttpRequestHeaders.java
> +    private final HttpCookies cookies;
해당 사항 반영했습니다 222222

2023-09-11 11:17 UTC, cpot5620 commented on tomcat/src/main/java/org/apache/coyote/http11/response/HttpResponseHeaders.java
> +        return new HttpResponseHeaders(new LinkedHashMap<>());
아마, 테스트 코드가 실패해서 LinkedHashMap을 사용했던 것 같아요.

HashMap은 입력 순서를 보장하지 못하기 때문에, 예상한 문자열과 동일한지(`isEqualTo()`)를 검증할 때, 통과하지 못하더라구요.
사실, `contains()`를 통해서 검증할 수도 있었을 것 같은데 해당 테스트가 뼈대(?) 코드 였기 때문에.. 사용한 것 같습니다.

에단은 테스트가 실패하지 않으셨나요 ? 아니면, 테스트 코드를 수정하셨었나요 ?

2023-09-11 11:26 UTC, cpot5620 commented on tomcat/src/main/java/org/apache/coyote/http11/common/HttpCookies.java
> +    }
정신없이 구현하다보니, 해당 부분을 놓쳤던 것 같아요.
좋은 지적 감사합니다 😄

HttpCookies의 `getCookies()` 에서는 단순히 Map을 반환하도록 하고,
응답을 위한 문자열을 추출하는 로직을 HttpResponse에서 수행하도록 수정하였습니다.

2023-09-11 11:27 UTC, cpot5620 commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +    private static final Logger LOGGER = LoggerFactory.getLogger(Http11Processor.class);
솔직히 말씀해주세요. 혹시 코드리뷰 툴 같은거 사용하시나요 ?

왜 이렇게 꼼꼼하신거죠 ? 🤪

2023-09-11 11:42 UTC, cpot5620 commented on tomcat/src/main/java/org/apache/coyote/http11/request/HttpRequestHeaders.java
> +
> private 메서드가 맨 아래로 가는 건 어떨까요? 여러 메서드가 공유하는 private의 위치에 대한 쥬니만의 기준이 있나요?

코드를 읽을 때에도, 위에서 아래로 읽잖아요 ?
그러다보니, public 메서드에서 사용하고 있는 private 메서드가 그 아래에 호출 순서대로 존재해야한다고 생각했어요 !
사실, 이런 기준을 세우다보니 **여러 메서드가 공유하는 private 메서드**는 어떻게 하는 것이 좋을까 ? 라는 고민이 들긴 했는데요.
가장 먼저 private 메서드를 호출한 메서드 아래에 둔다면, 이미 위에서 확인했다고 가정해도 괜찮지 않을까 ? 라는 생각이 들었어요.

> Map에 key를 String으로 관리하고 계시던데, HeaderType으로 안하시는 이유가 있을까요?

없습니다.. 굳이 뽑자면, 귀찮아서 그랬다..? ㅎㅎ..
왜냐하면, ResponseHeaders에서는 HeaderType으로 사용하고, RequestHeaders에서는 String을 사용하는 것은 통일성이 어긋난다고 생각했어요.
이때, RequestHeaders에는 Host, Keep-Alive 등 엄청 많은 HeaderType이 존재하다보니, 이러한 모든 HeaderType을 정의해주는 것 보다, 문자열로 관리하는게 낫겠다 싶었습니다..

에단은 HeaderType으로 관리해주셨기 때문에 해당 코멘트를 남겨주셨을 거라고 생각이 드는데요.
종류가 다양한 RequestHeader의 경우에는 어떤 식으로 대응하셨나요 ?

**답변 안 해주시면, 코드 훔쳐보러 갑니다 ? 그리고 코멘트 남깁니다 ?**

2023-09-11 12:36 UTC, cpot5620 commented
에단 !! 좋은 코멘트 너무 감사합니다 ㅎㅎ
부족함 많은 코드 리뷰해주시느라 고생 많으셨습니다.

테스트 코드 추가 및 리뷰 반영 완료하였습니다.

각 코멘트에 의견 남겨 놓았는데, 궁금한 점이 조금 있어서 ㅎㅎ 의견 남겨주시면 감사하겠습니다.

2023-09-11 12:44 UTC, kpeel5839 commented on tomcat/src/main/java/org/apache/coyote/http11/request/HttpRequestHeaders.java
> +
사랑스러운 정준씨

2023-09-11 12:44 UTC, kpeel5839 commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +    private static final Logger LOGGER = LoggerFactory.getLogger(Http11Processor.class);
저도 꼼꼼하다고 해주세요

2023-09-11 12:45 UTC, kpeel5839 commented on tomcat/src/main/java/org/apache/coyote/http11/response/HttpResponseHeaders.java
> +        return new HttpResponseHeaders(new LinkedHashMap<>());
저도 정준씨 말 듣고 LinkedHashMap 썼는데!

2023-09-11 23:19 UTC, cookienc commented on tomcat/src/main/java/org/apache/coyote/http11/response/HttpResponseHeaders.java
> +        return new HttpResponseHeaders(new LinkedHashMap<>());
그런 이유 때문에 쓰셨군요! 아마 저는 EnumMap을 써서 오류가 안난거 같아요

2023-09-11 23:52 UTC, cookienc commented on tomcat/src/main/java/org/apache/catalina/RequestMapping.java
> +public class RequestMapping {
> 현재 코드가 순환 참조 문제가 존재한다는 의미보다는, 위와 같은 구조에서 추후에 순환 참조 발생 가능성이 존재한다로 받아들이면 될까요 ?

제가 이해한 쥬니의 말씀은 (A 메서드가 B 메서드 호출) + (B 메서드가 A 메서드 호출) = StackOverFlow 이런 느낌인것 같습니다! 물론 이런 부분이 발생할 수도 있습니다만, 저는 이 부분은 고려하지는 않았습니다.. 제가 요상하게 썻네요. 죄송합니다.
표현을 달리해서 순환참조라는 표현보다는 패키지가 양방향으로 참조되고 있다고 보는게 맞을 것 같습니다.  이번 미션에서 [단방향 : apache <- jwp] / [양방향 : apache <-> jwp] 이 되어있다고 가정해보겠습니다. 만약 tomcat이 아니라 다른 WAS(저도 모름)를 사용한다면 변경범위가 어느쪽이 더 적을까요? 아마 단방향이 훨씬 변경범위가 적을 겁니다. 또한 코드를 처음 보는 읽는 입장해서 여러 패키지를 왔다갔다한다면 좀 더 이해하기가 어려울 수도 있겠죠! 제가 생각했던 문제는 이런게 있었습니다.

> 그러면, RequestMapping은 coyote 패키지만 의존하고 있고, RequestMappingImpl은 apache 패키지를 의존하고 있기 때문에, 순환 참조의 문제를 해결할 수 있는 거죠 !?

맞아요!

> 이 또한, catalina와 coyote 패키지를 각각(?) 알고 있는 것 같다는 생각이 들어서요 ㅎ

쥬니 말씀이 맞습니다. 세세하게 보면 각각 의존하고 있고, 크게 보자면 apache만 의존하고 있는거라고 할 수 있죠!  하지만 그 부분은 패키지를 분리하면서 생기는 거라 관점 차이인 것 같아요. 가장 중요한건 `흐름이 한방향으로 흐르는가?`라고 생각이 드네요. 

> 한 번 확인해 보았는데,,, 이거 지뢰찾기 아닌가요 ? ㅋㅋㅋㅋㅋㅋㅋㅋㅋ

저도 그냥 빨간색이 있나만 확인합니다ㅋㅋㅋㅋ

2023-09-11 23:58 UTC, cookienc commented on tomcat/src/main/java/org/apache/coyote/http11/request/HttpRequestHeaders.java
> +
> 가장 먼저 private 메서드를 호출한 메서드 아래에 둔다면, 이미 위에서 확인했다고 가정해도 괜찮지 않을까 ? 라는 생각이 들었어요

개인적인 취향이지만 저는 private 메서드를 공유하면 맨 마지막으로 공유한 메서드 아래에 두는 편입니다! 코드를 위에서 아래로 읽기도하고 클래스가 길어지면 처음부터 끝까지 모든 메서드를 읽을까 하는 생각이 들어서요. 아마 저였다면 인스턴스 변수를 확인하고 제가 사용하는 public 메서드 아래부터 읽을 것 같습니다. 뭐 cmd + b 쓰면 크게 상관이 없지만요!

> 종류가 다양한 RequestHeader의 경우에는 어떤 식으로 대응하셨나요 ?

저는 개발자 도구 보고 요청이랑 반환할 때 사용하는 header를 다 enum으로 정의했습니다. 노가다 뛰었죠. 저도 일관성 문제 때문에 HttpHeader라는 enum을 만들고 거기에 다 넣어줘서 일괄적으로 header의 key는 enum으로 관리했습니다.

> 답변 안 해주시면, 코드 훔쳐보러 갑니다 ? 그리고 코멘트 남깁니다 ?

답변 드렸습니다^^

2023-09-12 11:22 UTC, cookienc commented
쥬니 이번 미션 고생 많으셨습니다. 부족하지만 제 리뷰가 도움이 되었다면 좋겠습니다! 다음 미션도 화이팅하세요!

2023-09-12 11:22 UTC, merged