[톰캣 구현하기 - 3, 4단계] 푸우(백승준) 미션 제출합니다.
woowacourse/jwp-dashboard-http pull request #446
Opened 2023-09-10 07:47 UTC by BGuga

안녕하세요!!
3, 4 단계 미션 완료하고 제출드립니다 ㅎㅎ
변경점은 다음과 같습니다.
1. HttpResponse 재정의 : 기존의 HttpResponse 를 ResponseEntity 로 변경 후 HttpResponse 는 StatusLine, Body, Header를 갖도록 변경했습니다.
2. AbstractController 정의 : 하나의 RequestPath( ex. /login ) 단위로 요청을 handler 하는 AbstractController 를 정의하고 응답할 수 없는 HttpMethod 가 있다면 405 Method-Not-Allowed 를 반환하도록 변경했습니다.
3. 테스트 추가

리뷰 감사합니다 ㅎㅎ

2023-09-11 07:32 UTC, eunkeeee requested changes
푸우 안녕하세요
저는 리뷰어 깃짱이라고 합니다
깔끔하게 코드 잘 작성하고, 지난번 테스트도 작성해주셨네요! 

제 리뷰를 크게 요약해보면 두가지인데
1. view와 관련된 내용은 toString()에서 만들지 말고, 아예 분리해주세요! toString()은 디버깅용으로 사용하고, 프로덕션용으로는 사용하지 않는걸 추천드림니다
2. Controller 인터페이스 시그니처를 void service(HttpRequest request, HttpResponse response)로 변경해주세요!

그럼 좋은 월요일 되시길

2023-09-11 07:32 UTC, eunkeeee commented on tomcat/src/main/java/org/apache/coyote/http11/controller/AbstractController.java
> +        return ResponseEntity.notAllowed();
구현하기 전에는 기본적으로 다 404 상태코드로 막아놓은 건가요???
좋은 아이디어같네요..!

2023-09-11 07:32 UTC, eunkeeee commented on tomcat/src/main/java/org/apache/coyote/http11/controller/Controller.java
> +    ResponseEntity<? extends Object> handle(HttpRequest httpRequest);
구구 코치가 5기 잡담 채널에 올려놓은 내용 보면, 메서드 시그니처를 마음대로 변경하지 말라고 되어있는데, (저도 아직 이유 추측중이지만) 무튼 바꾸시면 좋을 것 같습니다! 

```java
void service(HttpRequest httpRequest, HttpResponse httpResponse);
```

2023-09-11 07:32 UTC, eunkeeee commented on tomcat/src/main/java/org/apache/coyote/http11/controller/HandlerMapper.java
> +        return HttpResponse.from(responseEntity).toString();
전부 다 객체 안으로 넣어버렸네요! ㅎㅎ 굳굳

2023-09-11 07:32 UTC, eunkeeee commented on tomcat/src/main/java/org/apache/coyote/http11/controller/LoginController.java
>          if (SessionManager.loggedIn(httpRequest)) {
명확한 메서드 분리 굳굳!

2023-09-11 07:32 UTC, eunkeeee commented on tomcat/src/main/java/org/apache/coyote/http11/controller/LoginController.java
>                  .addHeader("Set-Cookie", "JSESSIONID" + "=" + loginSession.get())
이 부분도 메서드로 분리하거나, 필요한 부분은 상수로 분리하는게 더 좋을 것 같아요~

2023-09-11 07:32 UTC, eunkeeee commented on tomcat/src/main/java/org/apache/coyote/http11/controller/LoginController.java
> +        return ResponseEntity.redirect("/401.html");
상수로 빼주세요! ㅎㅎㅎ

2023-09-11 07:32 UTC, eunkeeee commented on tomcat/src/main/java/org/apache/coyote/http11/controller/SignUpController.java
> +public class SignUpController extends AbstractController {
(제안) URI가 register인데, 용어를 Register로 통일하는건 어떤가요?
맘에 안들면 반영 안해두 됩니당

2023-09-11 07:32 UTC, eunkeeee commented on tomcat/src/main/java/org/apache/coyote/http11/request/HttpRequest.java
> +            String s = httpRequestHeaders.getHeaders().get("Content-Length");
이부분도 상수로 빼주거나, Headers 객체 내부로 넣어줘도 좋을 것 같아요

2023-09-11 07:32 UTC, eunkeeee commented on tomcat/src/main/java/org/apache/coyote/http11/response/HttpResponse.java
> +    private final String body;
ResponseBody도 원시값을 포장해버리면 좀더 통일성 있을 것 같아요!

2023-09-11 07:32 UTC, eunkeeee commented on tomcat/src/main/java/org/apache/coyote/http11/response/HttpResponse.java
> +            throw new UnsupportedOperationException("ResponseBody 에 Body 가 들어있는 경우는 아직 만들지 않았습니다.");
body가 없는 상황이 왜 예외상황이라고 생각했는지 궁금합니다!

2023-09-11 07:32 UTC, eunkeeee commented on tomcat/src/main/java/org/apache/coyote/http11/response/HttpResponse.java
> +    }
toString은 물론 http 스펙은 거의 변하지 않을테지만, 도메인 안에 들어있으면 유연성이 떨어질 것 같다고 생각해요! 
해당 로직을 아예 Response를 만드는 다른 클래스로 빼보는ㄴ건 어떨까요?
여기에만 적어두지만 마찬가지로, statusLine, headers가 각각 자신이 보여줄 response를 String으로 만드는건 부적절해 보여요!

2023-09-11 07:32 UTC, eunkeeee commented on tomcat/src/main/java/org/apache/coyote/http11/response/HttpResponseHeaders.java
> +            return "application/json";
위의 provider의 로직을 다 거치고 나서, null이 아니면 해당 타입으로 추론한 이유가 궁금합니다!
그냥 이번 미션에서만 에러를 일으키지 않을 정도의 용도인가요??

2023-09-11 07:32 UTC, eunkeeee commented on tomcat/src/main/java/org/apache/coyote/http11/response/HttpResponseHeaders.java
> +    public Map<String, String> getHeaders() {
필드를 통째로 외부에 노출하기보다는 find(String key) 같은 메서드를 제공해서 좀 더 객체 내용을 숨겼으면 좋겠어요! 이것도 마찬가지로 푸우의 코드 내에서 Map을 사용하는 부분 전반적에 대한 리뷰임니다!

2023-09-11 07:32 UTC, eunkeeee commented on tomcat/src/main/java/org/apache/coyote/http11/response/StatusLine.java
> +        return HTTP_VERSION + " " + httpStatusCode.getStatusCode() + " " + httpStatusCode.name();
ditto

2023-09-11 07:32 UTC, eunkeeee commented on tomcat/src/main/java/org/apache/coyote/http11/session/SessionManager.java
> +    private static final Map<String, Session> SESSIONS = new ConcurrentHashMap<>();
동시성을 처리할 수 있는 컬렉션 굳굳!

2023-09-11 07:32 UTC, eunkeeee commented on tomcat/src/test/java/nextstep/org/apache/coyote/http11/Http11ProcessorTest.java
> +    }
꼼꼼한 테스트 굳굳! 👍

2023-09-11 16:12 UTC, BGuga commented on tomcat/src/main/java/org/apache/catalina/connector/Connector.java
> +            Math.max(DEFAULT_MAX_THREAD, maxThreads),
> 여기서 Math.max를 통해서 설정하는 이유도 좀 궁금하네요 ㅎㅎ

Math.max는... 지금 생각해보면 최대치를 250으로 항상 유지하려고 당시에 넣은 것 같은데 maxThreads 가 250 넘으면 이상으로 생성되는거니 잘못 만들었네요 👍 싱싱미역 상태였나봅니다..

> 최대 쓰레드를 250개로 만드는건 맞지만, core thread 개수를 어떤 기준으로 선정했는지 궁금합니다!

해석을 잘못한 부분이 있었어요 ㅠㅠ Thread 가 부족하면 늘어나는 Thread Pool 을 만들어야 되는데 최대 크기가 250으로 고정된 ThreadPool 을 만들어야겠다 생각했어요!!
Executor.snewFixedThreadPool() 구현체 본다음에 바로 coreSize, maximumPoolSize 를 250으로 만들려 의도였습니다.
하지만 Fixed 가 아니였으니 core와 maximum 은 달라야 겠네요 ㅎㅎ
coreSize를 선정하기 위해 관련[글](https://code-lab1.tistory.com/269) 과 [영상](https://www.youtube.com/watch?v=fJCVnYyf-0Y) 을 찾아본 결과...
투박하게나마 제가 8코어 m1 mac을 사용하는 상황에서
다른 글들의 예시를 보니 **스레드 응답속도/CPU 사용시간** 계산을 50 ~ 99 정도로 예시를 드는 것 같네요
지금 구현한 스펙상 DB connection 가 없기에 응답 속도가 훨씬 대충 2배 빠르다고 치면..
8 * (1 + 30) 248가 예상 최적 thread 개수로 추정되네요
이게 근사값이니까 얼추 맞추기 위해서는 coreSize 를 한 200? maxSize 를 300 정도로 잡으면 되지 않을까해서
coreSize 200, maxSize 300 으로 결정했습니다!

2023-09-13 05:26 UTC, BGuga commented on tomcat/src/main/java/org/apache/coyote/http11/controller/Controller.java
> +    ResponseEntity<? extends Object> handle(HttpRequest httpRequest);
감사합니다 ㅎㅎ 반영했습니다!

2023-09-13 05:49 UTC, BGuga commented on tomcat/src/main/java/org/apache/coyote/http11/controller/LoginController.java
>                  .addHeader("Set-Cookie", "JSESSIONID" + "=" + loginSession.get())
메서드로 정의했습니다 ㅎㅎ 감사링

2023-09-13 05:54 UTC, BGuga commented on tomcat/src/main/java/org/apache/coyote/http11/controller/LoginController.java
> +        return ResponseEntity.redirect("/401.html");
좋습니다 ~!

2023-09-13 05:54 UTC, BGuga commented on tomcat/src/main/java/org/apache/coyote/http11/controller/SignUpController.java
> +public class SignUpController extends AbstractController {
굿굿 좋습니다!!

2023-09-13 06:01 UTC, BGuga commented on tomcat/src/main/java/org/apache/coyote/http11/request/HttpRequest.java
> +            String s = httpRequestHeaders.getHeaders().get("Content-Length");
날카롭네요 ㅎㅎ 감사합니다!!

2023-09-13 06:02 UTC, BGuga commented on tomcat/src/main/java/org/apache/coyote/http11/response/HttpResponse.java
> +    private final String body;
반영했습니다~!

2023-09-13 06:12 UTC, BGuga commented on tomcat/src/main/java/org/apache/coyote/http11/response/HttpResponse.java
> +            throw new UnsupportedOperationException("ResponseBody 에 Body 가 들어있는 경우는 아직 만들지 않았습니다.");
ResponseEntity<PoohDTO> 같이 쓰면 application/json 으로 반환하도록 만들려고 했어요!!
그래서 만약에 ResponseEntity 에 body 가 있을 경우 해당 타입을 추론해서 json 으로 변환해줘야하는데 이건 아직 안 만들었습니다 ㅎㅎ
그래도 스펙상 ResponseEntity<Object> 이고 body 에 값을 넣을 수는 있기 떄문에 혹시나 호출 했을 때 예외를 발생시키도록 임시방편으로 만들어 뒀습니다!

2023-09-13 06:30 UTC, BGuga commented on tomcat/src/main/java/org/apache/coyote/http11/response/HttpResponse.java
> +    }
그렇네요 👍👍👍 HttpResponseConverter 객체를 생성해서 view 로직들을 다 모았습니다 ㅎㅎ

2023-09-13 06:35 UTC, BGuga commented on tomcat/src/main/java/org/apache/coyote/http11/response/HttpResponseHeaders.java
> +            return "application/json";
responseEntity 의 응답이 view 혹은 json 으로 만들려했습니다!!
하지만... responseEntity 에 object 를 넣었을 때 json 응답으로 현재는 보내고 있진 않지만 해당 기능 만들려던 잔재입니다 ㅎㅎ

2023-09-13 06:46 UTC, BGuga commented on tomcat/src/main/java/org/apache/coyote/http11/response/HttpResponseHeaders.java
> +    public Map<String, String> getHeaders() {
view 출력을 위한 getter 사용을 제외한 나머지 getter 로직 모두 제거했습니다 ㅎㅎ

2023-09-13 06:46 UTC, BGuga commented on tomcat/src/main/java/org/apache/coyote/http11/response/HttpResponseHeaders.java
> +        return headerName + ": " + value;
인지용

2023-09-13 06:46 UTC, BGuga commented on tomcat/src/main/java/org/apache/coyote/http11/response/StatusLine.java
> +        return HTTP_VERSION + " " + httpStatusCode.getStatusCode() + " " + httpStatusCode.name();
인지용 2

2023-09-14 01:39 UTC, eunkeeee commented on tomcat/src/main/java/org/apache/catalina/connector/Connector.java
> +            Math.max(DEFAULT_MAX_THREAD, maxThreads),
core thread 선정 관련해서는 상당히 성능으로 딥하게 공부해야 하네요...!
ㅋㅋ해당 내용은 저도 좀 알아보고 나중에 따로 이야기해봐요

나머지는 위의 요구사항을 최대한 고려한 것 같다고 생각이 드네용

2023-09-14 01:46 UTC, eunkeeee requested changes
푸우 리뷰 반영한거 잘 봤습니다〰️
코드가 전반적으로 깔끔하고 역할이 잘 분리된 것 같아서 아주 만족스럽네요

그치만 조금만 더 개선하면 좋을 것 같아서 아쉬워서 한 번 더 Request Changes 보냅니다
ㅎㅎㅎㅎㅎㅎㅎㅎㅎ

빨리 머지나 했으면 좋겠더라도 조금만 더 개선하면 좋을 것 같아요!

2023-09-14 01:46 UTC, eunkeeee commented on tomcat/src/main/java/org/apache/catalina/connector/Connector.java
> +    private static final int CORE_POOL_SIZE = 100;
답변에서 말해준대로 적절히 푸우가 생각해서 만든 값인데 근거도 있어서 좋네요~

2023-09-14 01:46 UTC, eunkeeee commented on tomcat/src/main/java/org/apache/coyote/http11/HttpResponseConverter.java
> +    public static String convert(HttpResponse httpResponse) {
굳굳! view 관련을 모두 처리하는 클래스군요

2023-09-14 01:46 UTC, eunkeeee commented on tomcat/src/main/java/org/apache/coyote/http11/response/HttpResponse.java
> +    private ResponseBody body;
👍

2023-09-14 01:46 UTC, eunkeeee commented on tomcat/src/main/java/org/apache/coyote/http11/request/HttpRequestHeaders.java
>      private final Optional<Cookies> cookies;
cookie도 결국 header 중 하나라고 생각하는데, 왜 특별히 뺐는지 조금 궁금하긴 합니다!

2023-09-14 01:46 UTC, eunkeeee commented on tomcat/src/main/java/org/apache/coyote/http11/request/HttpRequestHeaders.java
>      }
이거역시 find(String key) 이런식으로 바꾸면 좀 더 은닉할 수 있을 것 같아요

2023-09-14 11:42 UTC, BGuga commented on tomcat/src/main/java/org/apache/coyote/http11/request/HttpRequestHeaders.java
>      private final Optional<Cookies> cookies;
1. Cookies 는 Cookie 에 여러 Cookie 값이 **cookie1=value1; cookie2=value2** 와 같은 형태로 넘어오기에 정의했습니다.
2. Cookies 를 정의해주고 나니 HttpRequestHeaders 에서 Cookies 반환할 때 마다 new Cookies() 로직이 생겼습니다.
3. 하나의 Request 에서 어차피 요청한 쿠키의 값은 변하지 않으니 필드로 빼서 중복을 제거했습니다.

Accept, Content-Type 같은 헤더들도 객체로 만들면 좋겠지만 현재는 쿠키만 만들면 충분하겠다 생각해서 나머지는 만들지 않았습니다 👍

2023-09-14 11:50 UTC, BGuga commented on tomcat/src/main/java/org/apache/coyote/http11/request/HttpRequestHeaders.java
>      }
앗 getHeaders 가 왜있지 삭제했습니다 ㅎㅎ
RequestLine 에 있던 getter 사용 로직을 find(String key) 형태로 사용하도록 변경했습니다!!

2023-09-14 11:53 UTC, eunkeeee approved these changes
코드가 깔끔하고 좋아졌네요!
머지할게요🌟

2023-09-14 11:53 UTC, merged