[톰캣 구현하기 3, 4단계] 오도(문민혁) 미션 제출합니다.
woowacourse/jwp-dashboard-http pull request #452
Opened 2023-09-10 11:59 UTC by odo27

안녕하세요 루쿠!
3,4단계 구현해봤습니다~
이번 리뷰도 잘 부탁드립니다 ㅎㅎ

2023-09-13 03:00 UTC, aiaiaiai1 requested changes
안녕하세요 오도~
리펙터링이랑 구현잘해주셨네요!
예외처리에 대해서 꼼꼼하게 신경을 많이 쓰신거 같습니다
간단하게 의견 남겨드렸는데 확인부탁드려요 고생하셨습니다~~

2023-09-13 06:50 UTC, odo27 commented on tomcat/src/main/java/nextstep/jwp/common/ResourceLoader.java
> +    }
너무 좋아요!

2023-09-13 07:02 UTC, odo27 commented on tomcat/src/main/java/nextstep/jwp/service/LoginService.java
> +    }
SessionManager의 메서드를 static으로 변경했어요!

2023-09-13 07:04 UTC, odo27 commented on tomcat/src/main/java/nextstep/jwp/service/LoginService.java
> +    }
너무 좋아요!

2023-09-13 07:09 UTC, odo27 commented on tomcat/src/main/java/nextstep/jwp/presentation/FrontController.java
> +        }
현재 controller.service 메서드에서 발생하는 모든 예외들을 해당 try-catch문에서 잡고 있어서 ControllerException만 받으면 LoginController에서 발생하는 AuthException을 못잡을 것 같아요!

2023-09-13 07:12 UTC, odo27 commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
>          } catch (HttpException e) {
너무 좋아요!

2023-09-13 07:19 UTC, odo27 commented on tomcat/src/main/java/nextstep/jwp/presentation/FrontController.java
> +}
비지니스 로직에서 예외가 발생하더라도 해당 예외 상황을 HttpProcessor까지 내려보내지 않고 싶었습니다. 예외를 처리해주는 기능을 리퀘스트 매핑에서 하는 것이 어색해서 프론트 컨트롤러라는 클래스에 리퀘스트 매핑과 예외 상황 처리라는 2가지 역할을 부여하게 되었습니다. 사실 프론트 컨트롤러라는 이름이 적절한 이름인지는 모르겠습니다 😭

2023-09-13 07:23 UTC, odo27 commented on tomcat/src/main/java/nextstep/jwp/exception/AuthExceptionType.java
> +    ;
완전 동의합니다! FormDataException을 새롭게 만들었습니다 👍

2023-09-14 09:46 UTC, aiaiaiai1 commented
오도 리뷰 반영이랑 답변 확인했습니다~!
리뷰 반영하시느라 고생하셨어요!!
남은 mvc미션도 파이팅입니다!

2023-09-14 09:46 UTC, merged

2023-09-14 09:51 UTC, kpeel5839 commented
루쿠짱 approve 로 작성하시고 merge 해야져어어어엉