[톰캣 구현하기 - 3, 4단계] 저문(유정훈) 미션 제출합니다.
woowacourse/jwp-dashboard-http pull request #459
Opened 2023-09-10 17:01 UTC by jeomxon

안녕하세요 조이, 저문입니다 :)
이전에 남겨주신 리뷰를 통해서 많이 배웠습니다!
지난 리뷰에 대한 답변은 [여기](https://github.com/woowacourse/jwp-dashboard-http/pull/365)에 남겨두었습니다.

이번은 3단계 리팩터링을 진행하는데 꽤나 오랜시간이 걸렸던 것 같아요.
4단계는 아직 공부해야할 내용이 산더미네요..ㅎㅎ

크게 변한건 없지만 Controller가 생기면서 로직이 훨씬 알아보기 편해진 것 같아요.
그만큼 조이가 리뷰하시기 수월했으면 하네요.

리뷰 잘 부탁드립니다🙇🏻‍♂️🙇🏻‍♂️🙇🏻‍♂️

2023-09-11 13:16 UTC, yeonkkk requested changes
안녕하세요 저문! 조이입니다🍀  

이번에도 구현을 정말 잘 해주셨네요..
코드가 너무 깔끔해서 리뷰하기도 너무 편했고, 정말 많이 배웠습니다🙂 
남길 코멘트가 거의 컨벤션 관련된 것 뿐이네요 ㅎㅎ 역시 고수,,👀⭐️

지난 PR과 이번 PR에 모두 코멘트 남겨두었으니, 편하실 때 확인 부탁드려요 ㅎㅎ
고생하셨습니다!

2023-09-11 13:16 UTC, yeonkkk commented on tomcat/src/main/java/org/apache/coyote/http11/controller/LoginController.java
> +package org.apache.coyote.http11.controller;
변경을 요청드리기보다는 의견을 여쭤보고 싶은 부분인데요, 혹시 controller의 위치(패키지)에 대해 고민해보신 부분이 있으실까요?
(그냥 궁금해서 드리는 질문입니다ㅎ)

2023-09-11 13:16 UTC, yeonkkk commented on tomcat/src/main/java/org/apache/coyote/http11/response/HttpResponse.java
> +        this.body = new String(Files.readAllBytes(new File(resource.getFile()).toPath()));
`resource.getFile()` 부분에서 파일이 없을 경우 NPE가 발생할 수 있을 것 같아요!

2023-09-11 13:16 UTC, yeonkkk commented on tomcat/src/main/java/org/apache/coyote/http11/auth/SessionManager.java
>      }
혹시 기본 생성자를 작성해주신 이유가 있을까요?!

2023-09-12 16:28 UTC, jeomxon commented on tomcat/src/main/java/org/apache/coyote/http11/request/HttpRequestLine.java
> +    private final HttpVersion httpVersion;
네 맞아요 그리고 request에서 받고 있기 때문에 언제 쓰일지 모른다고 생각해서 받아서 남겨두었습니다.

2023-09-13 02:33 UTC, jeomxon commented on tomcat/src/main/java/org/apache/coyote/http11/request/QueryString.java
> +    private static final String QUERY_STRING_SEPARATOR = "=";
영어 뜻을 봤을 때 Separator는 조금 더 넓은 범위의 구분자의 뜻을 담고 있습니다.
그리고 그 내부의 세부적인 구분자의 의미는 delimiter가 쓰이는 것 같아요.
상대적인 의미로 사용되는 것 같다고 판단해서 위와 같은 이름으로 지정했습니다.

2023-09-13 02:34 UTC, jeomxon commented on tomcat/src/main/java/org/apache/coyote/http11/request/HttpRequestLine.java
> +    public HttpRequestLine(
변경 중에 인지하지 못해서 수정을 못했네요..!
private으로 변경하겠습니다.

2023-09-13 02:35 UTC, jeomxon commented on tomcat/src/main/java/org/apache/coyote/http11/controller/LoginController.java
> +            }
좋은 것 같아요 분리하겠습니다~

2023-09-13 02:36 UTC, jeomxon commented on tomcat/src/main/java/org/apache/coyote/http11/controller/LoginController.java
> +package org.apache.coyote.http11.controller;
따로 공부해보지 않았는데 어떤 키워드로 학습하면 좋을까요?
어떤 의존관계를 가지고 설계해야할지 감이 잘 안잡히네요

2023-09-13 02:37 UTC, jeomxon commented on tomcat/src/main/java/org/apache/coyote/http11/auth/SessionManager.java
>      }
이유 없습니다. 삭제했습니다.

2023-09-13 02:48 UTC, jeomxon commented on tomcat/src/main/java/org/apache/coyote/http11/request/HttpRequestBody.java
>                  .collect(Collectors.toMap(infos -> infos.get(0), infos -> infos.get(1), (a, b) -> b));
상수화에 대한 리뷰를 많이 남겨주셨는데요
이런 매직넘버에 대한 상수화를 하면서 네이밍을 고민하는데 많은 시간이 소요되는 것 같아요.
제가 생각했을 때 상수의 네이밍에 대한 고민이 많이 되는 경우는 그 상수를 상수화 할 필요가 있나?, 의미를 정확히 부여해서 상수화하는 의미가 있나? 라는 고민이 많이 드는 것 같아요.

조이같은 경우에 KEY_INDEX, VALUE_INDEX라는 네이밍으로 상수화를 해주셨더라구요.
이미 위 라인에서 구분자로 분리됨을 인지할 수 있고, 0, 1로 분리되는 경우 key, value임을 개발자이면 자연스럽게 파악할 수 있다는 생각이 들었어요. 또한 toMap이라는 메서드 내부에 있기도 하구요.
조이는 이런 경우까지 상수화를 해야한다고 생각하시나요? 때로는 메서드 내부에 직접 사용하는 것도 하나의 방법이 될 수 있지 않나요?
조이의 상수화 기준이 궁금합니다. 조이는 모든 숫자, 문자에 대해서 상수화를 적용하시나요?

2023-09-13 02:52 UTC, jeomxon commented on tomcat/src/main/java/org/apache/coyote/http11/response/HttpResponse.java
> +                "",
단순 상수화에 대한 의견은 좋은 것 같아요.
하지만 요구사항이 변경됐을 때 관리하기 좋다는 의미에 대해서는 이해가 잘 되지 않아요.
상수와 요구사항이 연관이 있나요? 헤더에 대한 상수 값들은 표준으로 정해져있기 때문에 변하지 않을 것이라는 생각이 드는데,
조이는 어떤 관저미에서 요구사항과 상수가 연관있다고 말씀해주신 건지 궁금해요!

2023-09-13 03:09 UTC, jeomxon commented on tomcat/src/main/java/org/apache/coyote/http11/response/HttpResponse.java
> +        this.body = new String(Files.readAllBytes(new File(resource.getFile()).toPath()));
그렇네요.
수정했습니다!

2023-09-13 03:29 UTC, jeomxon commented on tomcat/src/main/java/org/apache/coyote/http11/controller/RegisterController.java
> +    }
당연히 막아야하는 부분이라는 생각이 드는데 제가 인지하지 못했네요.
수정하겠습니다!

2023-09-14 04:24 UTC, jeomxon commented on tomcat/src/main/java/org/apache/coyote/http11/controller/RequestMapping.java
> +public class RequestMapping {
사용자가 어떤 행동을 할지 예측할 수 없으니 좋은 것 같아요
반영했습니다!

2023-09-14 05:10 UTC, jeomxon commented on tomcat/src/main/java/org/apache/coyote/http11/response/HttpResponseHeader.java
> +    private final Map<String, String> headers = new HashMap<>();
제거하는 방향으로 변경했습니다!

2023-09-14 05:26 UTC, yeonkkk approved these changes
저문, 조이 입니다!

질문에 답변도 다 해주시고, 리뷰 잘 반영해주신 것도 확인했습니다 ㅎㅎ👍
정말 처음부터 끝까지 코드가 깔끔해서 리뷰하기 너무 너무 편했습니다.
마지막까지 최고네여 ~~ 

저문의 코드를 리뷰할 수 있어서 너무 영광이었어요 ~~✨
이제 approve & merge 하겠습니다.
고생하셨습니다 ~

2023-09-14 05:27 UTC, merged