[HTTP 서버 구현하기 - 1단계] 김김(김기문) 미션 제출합니다.
woowacourse/jwp-dashboard-http pull request #46
Opened 2021-08-30 11:15 UTC by tributetothemoon

안녕하세요 마갸! 

욕심이 나서 이것저것 세세하게 해보려다가 쓸데 없는 곳에 시간을 허비하고,
막바지에는 자코코 테스트 커버리지를 높이려다 허덕였네요 ㅠ 늦은 PR 죄송합니다.

게다가 시간에 맞춘다고 막바지 되어서는 오히려 코드 퀄리티가 많이 떨어졌어요... 두고두고 리팩토링을 해보겠습니다.

여튼 가차없는 피드백 부탁드립니다 :)!

2021-08-30 14:04 UTC, MyaGya requested changes
고생하셨습니다! 정말 열심히 작성한 코드라는 게 느껴졌어요. 빌더 패턴이나 컨트롤러로 분기를 한 부분에서 노력이 묻어나는 게 보였습니다.
코드 리뷰를 더 잘 해드리고 싶지만 코드 리뷰 경험이 많지 않습니다.
그래서 읽으면서 어색하다거나 이상하게 느낀 점을 위주로 몇 가지 코멘트를 남겼습니다.
당연하지만 반드시 반영할 필요는 없어요.
확인해주시고 언제든지 이상한 부분이 있으면 DM 날려주세요

2021-08-30 14:04 UTC, MyaGya commented on app/src/test/java/nextstep/jwp/controller/LoginControllerTest.java
> +    void loginPage() throws IOException {
개인적인 기호지만 해당 메소드들을 테스트 하는 것도 테스트하고자 하는 기능을 `DisplayName` 을 추가해 주는걸 선호합니다

2021-08-31 09:31 UTC, tributetothemoon commented on app/src/main/java/nextstep/jwp/controller/AbstractController.java
> +public class AbstractController implements Controller {
아뇨 완전한 실수입니다...😱...피드백 감사합니다 ㅜ

2021-08-31 09:31 UTC, tributetothemoon commented on app/src/main/java/nextstep/jwp/controller/LoginController.java
> +    public static final String LINE_SEPARATOR = System.getProperty("line.separator");
개행 문자가 통일되지 않으니 테스트에서 계속 실패하더군요 ㅠㅠ
(\r\n과 \n의 차이...)

2021-08-31 10:50 UTC, tributetothemoon commented on app/src/main/java/nextstep/jwp/controller/NotFoundController.java
> +public class NotFoundController implements Controller {
별 다른 이유는 없습니다. 만드는 순서가 NotFound가 먼저였기도 하고, AbstractController를 상속하나 안 하나 상관 없어서 이렇게 했던 것인데, 이 참에 통일성을 위해 상속하는 것으로 바꾸었습니다.

2021-08-31 10:51 UTC, tributetothemoon commented on app/src/main/java/nextstep/jwp/core/HandlerMap.java
> +    private static final Pattern STATIC_FILE_REQUEST_REGEX = Pattern.compile("(.html|.js|.css|.svg)$");
🤭👍👍! 나중에 큰일이 날 뻔 했군요,...!! 감사합니다!! 이스케이프 문자로 '.'을 제대로 인식하게 [수정](https://github.com/tributetothemoon/jwp-dashboard-http/commit/1efd400cea273e627a257d52275660daa00e4ee3)하였습니다!

2021-08-31 10:52 UTC, tributetothemoon commented on app/src/main/java/nextstep/jwp/core/HandlerMap.java
> +    }
뒤에 `.html`이 붙어있기 때문에 `StaticResourceController`에 매핑되어 처리됩니다. :)

2021-08-31 11:01 UTC, tributetothemoon commented on app/src/main/java/nextstep/jwp/db/InMemoryUserRepository.java
> +        // todo 예외 생성
네 처리된 것은 아니나, [다음에 부여할 id값을 static 변수로 가지게 함으로써](https://github.com/tributetothemoon/jwp-dashboard-http/commit/278b56bb755a714a67d0336fbeed8793094e5de1), 예외는 필요 없게 되었습니다!

2021-08-31 13:01 UTC, tributetothemoon commented on app/src/main/java/nextstep/jwp/model/User.java
> +    private long id;
정말 좋은 생각이라고 생각합니다! JPA에 익숙해지다보니, 어느새 엔티티의 어트리뷰트가 final이 아니어도 된다는 생각을 무심결에 해버린듯 합니다. [수정](https://github.com/tributetothemoon/jwp-dashboard-http/commit/19b4857b84635408133eee44c4d5da452c2ef79d)하였습니다. 좋은 의견 감사합니다 마갸 :)

2021-08-31 13:02 UTC, tributetothemoon commented on app/src/main/java/nextstep/jwp/controller/LoginController.java
> +                .contentType("text/html;charset=utf-8")
이유는 없습니다😅;; 이런저런 순서로 만들다보니 놓친 부분이 있는 것 같아요. 감사합니다. [수정](https://github.com/tributetothemoon/jwp-dashboard-http/commit/db9b3d5bd9325cd47602a819a4b4b4fde797c9a0)하였습니다!

2021-08-31 13:11 UTC, tributetothemoon commented on app/src/main/java/nextstep/jwp/controller/RegisterController.java
> +        User save = InMemoryUserRepository.save(user);
서비스 레이어는 이번 미션에서 분리하지 않기로 했습니다! 많은 부분을 적용하고 싶었지만, 요청/응답 헤더 파싱 및 스프링의 HandlerMapping을 비슷하게 재현하기만 해도 제출시간까지 빠듯할 것 같다는 생각이 들었거든요😢.
`/register`의 `POST`요청이 오면 바디를 읽어 회원가입을 시키라는 요구사항이 있었던만큼 `Controller`의 `doPost`로만 회원가입을 제한한다는 말이 선뜻 와닿지 않는데, 혹시 정확한 질문 의도를 다시 여쭈어보아도 괜찮을까요?

2021-08-31 13:39 UTC, tributetothemoon commented on app/src/test/java/nextstep/jwp/RequestHandlerTest.java
> +                "Content-Length: 5564\n" +
중요한 부분 피드백 정말 감사합니다 마갸. 막바지에 자코코 테스트 커버리지를 높이려고 우랴부랴 테스트코드를 하드코딩했는데, 이 때 미처 생각하지 못한 부분이네요. 생각해보면 개행문자부터 시스템별로 다를 수 있다는 것도 있는데 말이에요.
[모든 테스트의 Content-Lenght를 하드코딩하지 않도록 변경](https://github.com/tributetothemoon/jwp-dashboard-http/commit/74562962db4004d143b676bf9fa1b0f5d365169c)해보았어요. 스크린샷 첨부까지 정말 감사합니다!! 👍

2021-08-31 13:50 UTC, tributetothemoon commented on app/src/test/java/nextstep/jwp/controller/LoginControllerTest.java
> +    void loginPage() throws IOException {
😱급히 하다 빼먹은게 많네요...
[수정](https://github.com/tributetothemoon/jwp-dashboard-http/commit/74562962db4004d143b676bf9fa1b0f5d365169c)하였습니다 !

2021-08-31 14:05 UTC, tributetothemoon commented on app/src/main/java/nextstep/jwp/controller/LoginController.java
> +    }
아무래도 Service 로직이 분리되어 있지 않다보니 통신 응답 내용과 로그인 로직이 혼재해서 벌어지는 일 같습니다... 레이어드 아키텍쳐의 필요성을 느끼는 부분입니다.
`Overloading`이란 어떤 함수에 대한 동명 함수 작성을 의도하신 건지 여쭈어봐도 괜찮을까요?

2021-08-31 14:06 UTC, tributetothemoon commented
1차 리뷰 후 피드백을 반영해보았습니다! 다만 몇가지 궁금한 점에 대해서는 질문을 남겨놓았어요. 여유가 되신다면 답변해주시면 감사하겠습니다 :)!

2021-08-31 14:13 UTC, MyaGya commented on app/src/main/java/nextstep/jwp/controller/LoginController.java
> +    }
네 맞아요. 레이어로 분리하지 않은 상태라서 로직이 섞여있는데 계정을 찾는 기능 자체가 반드시 `HttpRequest` 와 `HttpResponse` 가 존재해야 한다는 부분이 어색해 보였거든요. 저는 이런 상황에서 `Overloading` 하여 임시적으로 분리해놓았다가 레이어가 분리되는 시점에서 다시 만드는데 "필요할 때 까지 미루어라" 라는 원칙도 있는만큼 지금 구조에서는 큰 문제되지 않을 거에요

2021-08-31 14:20 UTC, MyaGya commented on app/src/main/java/nextstep/jwp/controller/RegisterController.java
> +        User save = InMemoryUserRepository.save(user);
질문 의도를 먼저 말씀드리자면 로그인 과정에서의 검증과 회원가입 기능 모두 Http 통신을 통해서 작동하고 있어요. 개인적으로는 이런 코드들은 차후 리펙토링을 진행한다 하더라도 관련 테스트코드가 너무 많이 영향을 받아서 귀찮아지는 경우가 생기더라구요. 그래서 저는 리펙토링 전 기능 확인을 우선시한 코드를 만들 때에는 일부러 한 클래스에 코드를 몰아넣는 방식을 자주 사용해요(개인 취향입니다). 그런데 김김의 코드에서 1차적으로 리펙토링을 진행했다는 느낌이 들었어요. `Controller` 로 분기를 한 점이나 `Request`, `Response` 와 같은 객체를 만들었다는 점에서요. 그래서 리뷰를 했을 때에 이미 설계를 끝마친 상태로 보았어요.
그래서 해당 코드를 보니 굳이 `Service` 로 나누지도 않고, 해당 기능도 리펙토링을 통해 이미 정리가 된 것 같은데 `Service` 가 없으니 해당 기능(계정 생성)을 `RegisterController` 에 종속적으로 만들어서 관리하려는 건가? 라는 생각이 들어서 물어봤습니다! 사용하는데 큰 애로사항이 없다면 신경쓰지 않으셔도 괜찮아요!

2021-08-31 14:22 UTC, MyaGya commented on app/src/main/java/nextstep/jwp/core/HandlerMap.java
> +    }
그렇군요! 모든 매핑을 해당 위치에서 처리하는 것 같은데 `index.html` 과 관련된 컨트롤러도 당연히 여기에 있어야 하는게 아닌가? 라는 흐름으로 말씀드렸습니다

2021-08-31 14:28 UTC, MyaGya requested changes
올려주신 수정 사항 잘 보았습니다! 수정이 굉장히 많았을텐데 수정하느라 고생이 많았어요.
모호하게 질문드린 부분이 많아서 죄송하네요. 다음부터는 신경쓸게요
애매했던 답변들은 리펙토링이 끝났다고 달았던 코멘트였어요. 대부분 레이어 분리가 되지 않아서 최종 설계라고 생각하고 드린 질문이니 가볍게 보고 넘어가주시면 될 것 같습니다.
추가적으로 한 가지 코멘트를 더 달았습니다! 확인하시고 다시 리뷰 요청해주시면 될 것 같습니다!

2021-08-31 14:28 UTC, MyaGya commented on app/src/main/java/nextstep/jwp/web/ContentType.java
> +        this.fileExtensionPattern = Pattern.compile("." + fileExtension);
해당 부분도 정규표현식의 예약어로 사용되고 있는 것 같아요!
지금 구조라면 "defaulthtmltest.css" 와 같은 파일이 있어도 모든 문자 + html 과 같이 처리되어서 `findFirst` 가 되는 html파일로 적용될 위험성이 있어 보입니다!

2021-08-31 17:19 UTC, tributetothemoon commented on app/src/main/java/nextstep/jwp/web/ContentType.java
> +        this.fileExtensionPattern = Pattern.compile("." + fileExtension);
으아 자꾸 놓치네요 감사합니다!!!

2021-08-31 17:31 UTC, tributetothemoon commented on app/src/main/java/nextstep/jwp/controller/RegisterController.java
> +        User save = InMemoryUserRepository.save(user);
> 해당 기능(계정 생성)을 RegisterController 에 종속적으로 만들어서 관리하려는 건가?

맞는 말입니다. 서비스 레이어가 나오기 시작한 이유가, `Massive Controller`, 즉 컨트롤러가 너무 비대해지고 하는 역할이 많아져서라고 하죠! 게다가 초창기 스프링의 `Controller` 인터페이스는 서블릿 처럼 `HttpRequest`, `HttpResponse` 2개를 인자로 받는 형태(지금 제가 짠 구조)였기 때문에 요청과 응답을 직접 주무르는 역할까지 해서 더더욱 그랬다고들 하죠.
마갸의 말대로 테스트 문제, 특정 기능이 컨트롤러에 종속적인 문제, HTTP 통신에 깊게 관여하는 문제 등 때문에 지금의 FrontController, 어노테이션 기반 컨트롤러, 서비스 레이어 등의 기능들이 추가된 것 같다는 생각이 듭니다. :)

2021-08-31 21:53 UTC, merged

2021-08-31 21:53 UTC, MyaGya commented
고생하셨습니다! 1단계는 이정도로 마무리해도 될 것 같아요. 미션 진행하느라 수고하셨고 다음 미션도 화이팅입니다!