[톰캣 구현하기 - 3, 4단계] 땡칠(박성철) 미션 제출합니다.
woowacourse/jwp-dashboard-http pull request #471
Opened 2023-09-11 04:17 UTC by 0chil

안녕하세요 히이로! 지난 리뷰에 이어 잘 부탁드립니다

특이사항은 Controller(Handler) 인터페이스를 요구사항에 맞춰 다음과 같은 형태로 변경하게 되었습니다.
```java
public interface Controller {
    void service(HttpRequest request, HttpResponse response) throws Exception;
}
```

2023-09-11 05:04 UTC, 0chil commented on tomcat/src/main/java/org/apache/catalina/connector/Connector.java
>      private static final int SOCKET_TIMEOUT_SECONDS = 10;
정확한지는 잘 모르겠는데 제가 이해한대로 우선 적어보았습니다.
히이로는 `최대 ThradPool의 크기는 250, 모든 Thread가 사용 중인(Busy) 상태이면 100명까지 대기 상태로 만들려면 어떻게 할까?` 
라는 요구사항을 어떻게 반영해야한다고 생각하시나요?

2023-09-11 16:33 UTC, MoonJeWoong requested changes
안녕하세요 땡칠, 히이로입니다! 🙇 

전반적으로 사소하다고 느껴지는 부분들은 피하고 구조적인 리뷰를 드려보려고 노력했습니다. 땡칠께서 달아주신 질문들에도 답을 달아뒀는데 저도 학습자의 입장이다보니 아무래도 답변 내용이 부족할 수도 있을 것 같아요! 그런 부분은 따로 저에게 말씀해주시면 같이 더 고민해볼 수 있도록 해보겠습니다. 😃 

다음에 다시 pr요청 주시면 merge 하도록 하겠습니다. 추가적으로 개선해보고 싶으신 부분들 선택적으로 반영해서 요청해주세요~

2023-09-11 16:33 UTC, MoonJeWoong commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
>                      httpResponse.getBody()
client에게 내려줄 최종 response 형태를 만드는 책임도 HttpResponse 객체에 부여해보시는건 어떨까요?

2023-09-11 16:33 UTC, MoonJeWoong commented on tomcat/src/main/java/org/apache/catalina/connector/Connector.java
>      private static final int SOCKET_TIMEOUT_SECONDS = 10;
네 저도 정확하게 땡칠과 같은 방식으로 이해하고 있습니다. 모든 쓰레드가 사용중일 떄 100개의 connection 요청들을 queueing하기 위해서 acceptCount로 ServerSocket을 생성할 때 OS에 저장되는 connection들에 대한 queue size를 100으로 설정해줍니다. 

ThreadPool 생성 시 corePoolSize와 maximumPoolSize는 250으로 동일하게 설정했으니 시작부터 250개의 쓰레드가 생성되어 동작하면서 요청들을 처리하게 될 것 같습니다. 

혹시 어떤 부분이 궁금하셨던건지 더 자세하게 따로 말씀해주시면 같이 고민해봐도 좋을 것 같습니다!

2023-09-12 00:42 UTC, 0chil commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +            handle(httpRequest, httpResponse);
응답이 동적으로 생성되기까지 수많은 과정 속에서 언제든 응답코드, 헤더, 바디를 수정하기 위함이라는 말씀이시네요!
듣고 단번에 이해가 되었습니다.

이 말을 듣고보니까
함수 반환으로 Response를 사용하는 제 기존 디자인에서는 
handler 호출 스택의 끝에서 response를 만들도록 제한되는 단점이 있네요.

예를 들어 서비스 객체가 있다면, 호출 스택의 끝인 서비스 객체에서 response를 만들어야할 것 같아요.
이런 디자인은 상황에 따라 부적절한 곳에서 응답을 생성하게 될 수도 있겠네요.

결론은 '어디서든 응답 수정을 쉽게 하려는 의도가 담긴 디자인이다'. 네요
좋은 커멘트 감사합니다~!!

2023-09-12 10:08 UTC, 0chil commented on tomcat/src/main/java/org/apache/catalina/connector/Connector.java
>      private static final int SOCKET_TIMEOUT_SECONDS = 10;
답변해주신 내용이 바로 궁금한 부분이었습니다.
Accept Count가 OS가 queueing 할 크기(백로그 크기)를 결정하는 부분이라고 이해했어요!

2023-09-12 10:58 UTC, 0chil commented on tomcat/src/main/java/org/apache/coyote/http11/HttpResponse.java
> +    }
바디가 없을 때에 대한 Content-Length 표준은 없습니다!
Content-Length를 별도로 설정하지 않고
body 길이에 따라 정하려는 의도였는데, `body = ""` 인 경우를 생각하지 못했네요.

이 부분도 반영해보겠습니다!

2023-09-12 10:58 UTC, 0chil commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
>                      httpResponse.getBody()
오 좋은 생각입니다 역시 👍
반영해보겠습니다!

2023-09-12 11:53 UTC, 0chil commented on tomcat/src/main/java/org/apache/coyote/http11/HttpRequest.java
위 커멘트와 이어지는 내용이네요.

EMPTY 객체를 만들어두고 잘 활용하지 못하는 부분이 아쉬우셨군요. 일관적이지 못하다는 관점 충분히 이해가 갑니다!
하지만 `getContentLength()`를 유지하고 싶어요.

<img width="491" alt="image" src="https://github.com/woowacourse/jwp-dashboard-http/assets/39221443/abbd3250-629d-4e43-a61f-1b643d6f5a4d">

이 메서드를 별도로 만든 의도는 `null`에 대한 대응 방법을 캡슐화하기 위해서였어요.
헤더값은 문자열이므로 `Integer.parseInt(header.getValue())`를 사용해주어야 하는데, 
`header.getValue()`는 빈 문자열일수도 있기 때문에, 위 로직처럼 **빈 헤더인지 체크** 후에 사용해야하는 복잡함이 있습니다.

그래서 '자주 사용하는 일반적인 헤더니까 걱정없이 정수 형태의 컨텐츠 길이를 얻자' 라는 의도로 일종의 헬퍼 메서드를 만들었습니다.

사실 로직의 위치만 다를 뿐, 히이로가 제안해주신 내용과 같은 코드인 것 같아요.
그래서 당연하게도 히이로가 제안하신 코드도 당장 동작하는 상황입니다.

하지만 지금 구현한 헬퍼 메서드를 통해 `null`에 대한 처리도 함께 재활용할 수 있다는 장점이 있으므로 `getContentLength()`는 유지하고자 합니다.

2023-09-13 01:11 UTC, 0chil reviewed
안녕하세요 히이로 ✋🏻 좋은 아침입니다
커멘트 남겨주신 내용들 고민해보고 반영했습니다.
큰 변경이 하나 있고, 작은 변경들 몇 개가 있어서 둘을 나눠서 적어보았습니다:

### RequestMapping
다음은 가장 큰 변경사항(RequestMapping) 커밋입니다!
https://github.com/woowacourse/jwp-dashboard-http/pull/471/commits/5092d782ec9352fc9e3061d79b10179b2968c5b2
- Controller 인터페이스에 `supports` 메서드 추가했습니다!
- `RequestMapping` 클래스 만들었습니다. (리뷰 반영)
- `TargetPath` 라는 클래스에 경로 관련 작업들을 위임했습니다.

### 그 외 변경사항
- Response가 응답 생성 (리뷰 반영)
- 바디 길이 0일때, Content-Length 헤더 제외 (리뷰 반영)
- Handler -> Controller로 재명명 (요구사항)

2023-09-13 13:46 UTC, MoonJeWoong commented on tomcat/src/main/java/org/apache/coyote/http11/HttpRequest.java
null 처리 로직의 캡슐화가 주 목적이셨군요! 이해했습니다 ㅎㅎ 👍

2023-09-13 14:19 UTC, MoonJeWoong commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +    ));
뒤쪽에서 RequestMapping 로직을 읽어봤는데요, List로 전달된 controller들을 순서대로 순회하면서 supports 메서드를 수행하는 방식으로 controller를 매핑시켜주는 방식이었던 것 같아요. 여기에서 List 자료구조를 선택하신 이유가 혹시 있으신지 개인적으로 궁금합니다!

2023-09-14 04:18 UTC, 0chil commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +    ));
1. 좋은 생각이네요.! 동적으로 변할 필요가 있을 때 변경해도 괜찮을 것 같아요.
2. 특별한 이유는 없었습니다. 순서 보장도 필요 없으니 Set이 더 적절하겠네요!

꼼꼼한 커멘트 감사합니다! 말씀주신 내용 반영하겠습니다

2023-09-14 04:20 UTC, 0chil commented on tomcat/src/main/java/org/apache/coyote/http11/HttpResponse.java
> +    private final Headers headers2 = new Headers();
ㅎㅎ 꼼꼼한 리뷰 감사드립니다 반영했습니다!

2023-09-14 04:31 UTC, MoonJeWoong approved these changes
마지막 변경사항까지 반영 완료하셔서 merge 하도록 할게요!
미션 진행하시느라 고생 많으셨습니다 ㅎㅎ 다음 미션도 화이팅입니다~ 😄

2023-09-14 04:31 UTC, merged