[톰캣 구현하기 - 3, 4단계] 스플릿(박상현) 미션 제출합니다.
woowacourse/jwp-dashboard-http pull request #472
Opened 2023-09-11 04:18 UTC by splitCoding

후추 저번 리뷰 너무 꼼꼼하고 좋았어요!!!👍

이번엔 저번보다 조금 더 많이 얘기 나눠보면 좋을 것 같아요!!❤️

2023-09-11 07:12 UTC, Combi153 requested changes
안녕하세요 스플릿!

3,4 단계 구현하느라 고생하셨습니다!

요구사항을 명확히 지키고, 객체도 적절히 분리한 깔끔한 코드네요

이번에도 리뷰하면서 많이 배울 수 있었습니다 😃 

시간이 되신다면 한 가지 제안드리고 싶은 것은 패키지를 적절히 분리하는 것입니다!

[wikipedia](https://en.wikipedia.org/wiki/Apache_Tomcat)에 보면 Tomcat의 Components는 Catalina, Coyote, Jasper 세 가지 입니다.
그 중 Catalina 는 servlet container, Coyote는 Connector 라고 소개되어 있네요.

스플릿의 현재 코드는 요구사항에 관한 대부분의 코드가 Coyote 패키지에 있어요. 만약 Catalina에게 servlet container로 책임을 부여한다면, 패키지 구조를 어떻게 바꾸면 좋을지 고민해보시면 좋을 것 같습니다!

물론 저도 Tomcat 구조를 잘 몰라서 고민하는 중입니다 ~ 스플릿은 패키지를 어떤 식으로 구성할지 궁금하네요 😀

2023-09-11 07:12 UTC, Combi153 commented on tomcat/src/main/java/org/apache/coyote/http11/controller/LoginController.java
> +        loginFail(request, response);
지금 만들어둔 controller에서 Login, Register 기능을 수행하고 있어요. 이러한 기능을 AuthService 같은 객체를 만들어 책임을 주면 어떨까요? Controller에서는 응답만 구성해도 될 것 같아요 😃

2023-09-14 07:24 UTC, splitCoding commented on tomcat/src/main/java/nextstep/jwp/db/InMemoryUserRepository.java
>      }
답변에 앞서 리뷰 진짜❤️

저도 synchronized 키워드를 쓰면 저장시 동기적으로 처리되는데 ConcurrentHashMap 이 의미가 없다는 생각에 완전 동의합니다!!

AtomicLong 을 사용하면 멀티쓰레드 환경에서 동기적이지 않게 처리가 가능하다 해서 AtomicLong을 사용하여 처리해 보았습니다!!

test 도 따로 만들어서 같이 커밋했습니다!!😊

2023-09-14 10:08 UTC, splitCoding commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +            totalRead += readBytesCount;
1. 저도 개인적으로 가독성을 위해서 메서드 분리에 대해서 많이 고민했었어요🧐 하지만 개인적으로 BufferedReader 를 한곳에서 절차적으로 사용하게 강제하고 싶어 분리하지 않고 한메서드로 사용하는 방법을 택했습니다. 😊 
( private 메서드 마저도 내부적으로 잘못된 순서로 호출될 수 없게 하고 싶어서 분리하지 않는 것이 좋다고 판단했어요!! )

2. contentLengthValue 가 훨씬 좋네요!!! 수정하겠습니다!!

2023-09-14 10:10 UTC, splitCoding commented on tomcat/src/main/java/org/apache/coyote/http11/controller/LoginController.java
> +                final HttpResponse newResponse =
좋은 것 같아요!! 수정하겠습니다!!👍

2023-09-14 10:17 UTC, splitCoding commented on tomcat/src/main/java/org/apache/coyote/http11/controller/LoginController.java
> +        loginFail(request, response);
객체 지향이 관점에서 AuthService 생성하는 것 매우 좋은 방법이라고 생각합니다!!👍

개인적으로는 이번 미션의 각각의 controller가 서블릿이고 요청에 따른 처리를 하는 서블릿의 생성에 집중해보는 것 같다고 생각해서 이렇게만 진행했던 것 같아요ㅎㅎ

2023-09-14 12:12 UTC, splitCoding commented on tomcat/src/main/java/org/apache/coyote/http11/response/HttpResponse.java
> +    }
후추의 방법도 좋다고 생각합니다!!!!👍

지금 코드가 정적 팩토리 메서드로 어느정도 특정 response에 대한 생성을 만들어 놓아서 똑같은 내용의 코드가 될 것 같아서 우선 이렇게 작성했었습니다!! 🫡

2023-09-14 12:41 UTC, splitCoding commented on tomcat/src/main/java/org/apache/coyote/http11/response/ContentType.java
> +    JAVASCRIPT("text/javascript");
사람이 읽을 수 있는 모든 문자열 파일들은 text/plain 으로 처리할 수 있는데 이때 특정 확장자를 TEXT_PLAIN 에 지정하기에는 어려움이 있을 것 으로 판단했습니다!!

그래서 외부에서 정적 리소스 확장자에 정확히 맵핑된 Content-Type 을 매핑해주는 방법을 택했습니다!!😊

근데 지금보니 미션 요구사항을 넘어서서 ContentType에 대해 고민해본다면 관리하는 곳이 두 곳이 되어 관리의 어려움이 동반 될 것 같네요ㅠㅠ Content-Type을 정할 수 있는 다른 방식의 메서드를 제공하고 Enum 안에서 모두 관리하는 방법이 더 좋아보입니다!!👍

2023-09-14 14:57 UTC, Combi153 approved these changes
스플릿 안녕하세요! 후추입니다 😀 

3,4 단계 미션 구현하시느라 고생하셨어요!

이번 미션에서 요구사항을 모두 지키셨고, 여러 방면에서 충분히 학습하셨다고 판단해요!

이만 머지하겠습니다 고생하셨어요~

남은 레벨4 화이팅 🚀

2023-09-14 14:57 UTC, Combi153 commented on tomcat/src/test/java/nextstep/jwp/db/InMemoryUserRepositoryTest.java
> +        executorService.shutdown();
스플릿은 log를 자유자재로 다룰 줄 아시는 것 같아요 👍 
저는 log에 대해 깊게 생각해본 적이 없는데 배워갑니다 😃

2023-09-14 14:57 UTC, Combi153 commented on tomcat/src/test/java/nextstep/jwp/db/InMemoryUserRepositoryTest.java
> +        // when
콘솔에 ID를 찍어보는 제 테스트보다 훨씬 낫군요! 멋진 테스트에요 💯

2023-09-14 14:57 UTC, Combi153 commented on tomcat/src/main/java/nextstep/jwp/db/InMemoryUserRepository.java
> +    private static AtomicLong RESERVED_ID = new AtomicLong(0);
AtomicLong 란 게 있는 줄 몰랐는데 대단해요!
synchronized 키워드를 붙이는 것보다 훨씬 성능이 좋을 것 같아요.

2023-09-14 14:57 UTC, Combi153 commented on tomcat/src/main/java/org/apache/catalina/ControllerMapper.java
>  import java.util.Map;
ControllerMapper 가 catalina 패키지로 이동함으로써, Servlet container 역할을 적절히 수행하고 있네요 👍

2023-09-14 14:57 UTC, Combi153 commented on tomcat/src/main/java/org/apache/coyote/http11/controller/LoginController.java
> +        loginFail(request, response);
맞습니다! 저도 미션에서 배울 수 있는 것에 집중하는 게 좋다고 생각해요. 특히나 바쁜 레벨4 미션에서는 더 그렇구요. 앞으로도 각 미션에서 뽑아먹을 수 있는 걸 다 뽑아먹자구요!!

2023-09-14 14:57 UTC, Combi153 commented on tomcat/src/main/java/org/apache/coyote/http11/response/ContentType.java
> +    JAVASCRIPT("text/javascript");
> Content-Type을 정할 수 있는 다른 방식의 메서드를 제공하고 Enum 안에서 모두 관리하는 방법

스플릿이 말씀하신 걸 저도 구현해보고 싶었는데 쉽지 않더라구요! 나중에 여유가 있을 때 도전해보면 좋을 것 같아요 ~

2023-09-14 14:57 UTC, Combi153 commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
> +            totalRead += readBytesCount;
오 그런 이유가 있었군요! 무엇인가를 읽는 작업은 반드시 정해진 절차를 지켜야 할텐데, 그럴 때는 스플릿처럼 절차를 강제하는 것도 좋은 것 같습니다. 저도 다음에 해봐야겠어요~

2023-09-14 14:57 UTC, Combi153 commented on tomcat/src/main/java/nextstep/jwp/db/InMemoryUserRepository.java
>      }
AtomicLong 진짜 맛있네요 잘 먹겠습니다 👍

2023-09-14 14:57 UTC, merged