[톰캣 구현하기 - 3, 4단계] 케로(김지현) 미션 제출합니다.
woowacourse/jwp-dashboard-http pull request #480
Opened 2023-09-11 06:52 UTC by jyeost

바론 -- !
늘 꼼꼼한 리뷰 감사합니다람쥐 ◠‿◠  
1,2 단계에서 리팩 빡시게 해서 3단계에 큰 구조적 변화는 없습니다만...
그래도 파일 체인지는 많네유 ㅠㅠ

4단계 스레드 부분은 아직 잘 몰라서...
점차 알아나가면서 개선해가겠습니다....

2023-09-11 10:50 UTC, somsom13 requested changes
안녕하세요 케로! 바론입니다 🙇 🙇‍♀️ 

1, 2 단계 코드도 구조가 워낙 잘 잡혀있었어서 3단계에서 구조적으로 크게 변한점은 없고 코드가 더 깔끔해졌네용! 👍 👍 

몇 가지 질문만 남겨두었습니당 ㅎ.ㅎ
너무 고생하셨습니다~~!! ❤️ 😍

2023-09-11 10:50 UTC, somsom13 commented on tomcat/src/main/java/nextstep/jwp/controller/LoginController.java
> +            return;
로그인에 성공하면 302 헤더와 함께 index.html 로 redirect 하도록 응답을 보내는 것 같아요! 
요 상황에서 `serViewPathAsBody` 를 따로 설정하신 이유가 있나용?.?

2023-09-11 10:50 UTC, somsom13 commented on tomcat/src/main/java/nextstep/jwp/controller/LoginController.java
> +        final Session session = httpRequest.getSession(false);
`getSession(boolean)` 에 들어가는 파라미터가 어떤 의미를 가지는 값인지 알 수 있을까요?.?

2023-09-11 10:50 UTC, somsom13 commented on tomcat/src/main/java/nextstep/jwp/controller/LoginController.java
> +            return;
59번 라인의 코멘트와 동일합니다!

2023-09-11 10:50 UTC, somsom13 commented on tomcat/src/main/java/nextstep/jwp/controller/RegisterController.java
> +        httpResponse.setRedirect("/index.html");
위의 코멘트와 동일합니다 😄

2023-09-11 10:50 UTC, somsom13 commented on tomcat/src/main/java/org/apache/catalina/connector/Connector.java
> +    private static final int DEFAULT_MAX_THREAD = 30;
이렇게 제한을 두신 이유가 궁금하네용 ㅎㅎ 케로가 코멘트에 말씀해주신 것 처럼 스레드에 대해서 더 공부하시게 된다면... 저도 알려주세용 \(@^0^@)/

2023-09-11 10:50 UTC, somsom13 commented on tomcat/src/main/java/org/apache/coyote/response/HttpResponse.java
> +    private final ResponseStartLine responseStartLine;
TMI) RFC 2616에 따르면 Response Message의 시작 라인은 `StatusLine` 이라고 부른다고 합니당 

요건 수정 요청이 아니라 정말 그냥 TMI입니당 (ﾉ◕ヮ◕)ﾉ*:･ﾟ✧

![image](https://github.com/woowacourse/jwp-dashboard-http/assets/70891072/97cc45b5-7335-4dbc-9458-ae2da3af68cb)

2023-09-11 10:50 UTC, somsom13 commented on tomcat/src/main/java/org/apache/coyote/response/ResponseStartLine.java
> +        this.status = ResponseStatus.OK;
궁금!!! Response Status를 기본적으로 OK로 설정해두신 이유가 궁금해요~~~

2023-09-11 10:50 UTC, somsom13 commented on tomcat/src/main/java/org/apache/front/Proxy.java
> +        this.requestMapping = new RequestMapping();
궁금해서 남기는 질문입니당! Static Mapping과 RequestMapping 필드를 static이 아닌, Proxy 객체 생성 시에 함께 생성하는 이유가 무엇인지 궁금해요~!

1 Proxy - 1 Mapping으로 관리가 되어야 하는건가요?.?

2023-09-11 10:50 UTC, somsom13 commented on tomcat/src/main/java/nextstep/jwp/controller/HelloWorldController.java
>      }
HelloWorldController에 `doPost()` 요청이 들어오면 어떻게 되나요?.?

2023-09-12 06:35 UTC, jyeost commented on tomcat/src/main/java/nextstep/jwp/controller/LoginController.java
> +            return;
헉 그러게요...
필요없이 response에 login.html을 담고 있었네여... 
수정했습니다

2023-09-12 06:53 UTC, jyeost commented on tomcat/src/main/java/nextstep/jwp/controller/LoginController.java
> +        final Session session = httpRequest.getSession(false);
getSession의 메서드 파라미터 명을 수정하여 다시 작성했습니다. 
도 실제 request session에서 처럼 true 일 때 기존 세션이 존재하지 않으면 새로 생성하고, false에서 존재하지 않으면 null을 반환하도록 수정했습니다

2023-09-12 06:54 UTC, jyeost commented on tomcat/src/main/java/org/apache/catalina/connector/Connector.java
> +    private static final int DEFAULT_MAX_THREAD = 30;
일단 로컬에서 돌리고 있기 때문에 많은 스레드를 둘 필요가 없다고 판단해서 처음에 10개를 사용하였는데, ci에서 테스트가 깨져서 스레드 풀 개수 때문일가?? 하고 30까지 수정했던것 입니다....ㅎㅅㅎ 

아직도 잘 모르겠어요 ...ㅠㅠ

2023-09-12 07:01 UTC, jyeost commented on tomcat/src/main/java/nextstep/jwp/controller/HelloWorldController.java
>      }
피알 날리고 궁금해서 해봤는데 NPE 가 발생하더라고여... 
이부분도 처리 처리되도록 수정하였습니다 !

2023-09-12 07:16 UTC, jyeost commented on tomcat/src/main/java/org/apache/front/Proxy.java
> +        this.requestMapping = new RequestMapping();
1 Proxy - 1 Mapping 로 관리되지 않아도 될 것 같아서 처음에는 싱글톤 패턴으로 구현했다가,
리팩하는 과정에서 실수한 것 같습니다... ㅠㅠ

2023-09-12 08:10 UTC, somsom13 commented on tomcat/src/main/java/org/apache/catalina/connector/Connector.java
> +    private static final int DEFAULT_MAX_THREAD = 30;
사실 저도 잘 모르겠어용 ㅋㅋㅋㅋ 근데 지금 미션 상황에서는 케로 말씀대로 많은 accept count와 thread가 필요하지 않을 것 같아요! 
(공부한 내용 공유해달라고 꼬드기는 코멘트 였습니당 ㅎㅋㅎㅎ)

2023-09-12 08:22 UTC, somsom13 approved these changes
안녕하세요 케로~~~ 바론입니다~~~!!!! 
빠른 코멘트 답변과 완벽한 수정,,, 박수갈채 보냅니다 👏 👏 👏 

이번 미션의 요구 사항을 모두 만족하신 것 같아서 merge합니다 💯 👍 

너무 고생하셨습니다~~ 다음 미션도 화이팅이에요!

2023-09-12 08:22 UTC, somsom13 commented on tomcat/src/main/java/nextstep/jwp/controller/HelloWorldController.java
> +
따봉 👍

2023-09-12 08:22 UTC, somsom13 commented on tomcat/src/main/java/org/apache/coyote/request/HttpRequest.java
> +    public Session getSession(final boolean create) {
따따봉 👍

2023-09-12 08:22 UTC, somsom13 commented on tomcat/src/main/java/nextstep/jwp/controller/LoginController.java
> +        final Session session = httpRequest.getSession(true);
케로의  `getSession(true)` 는 다음과 같은 흐름인 것 같은데, 
1. 이미 저장되어 있던 세션이라면 user 를 담은 세션이 반환되고
2. 새롭게 생성된 세션이라면 user를 담고 있지 않는 세션을 반환한다.

`loginPage` 에서 **로그인 여부에 따라 반환할 페이지를 다르게 설정할 때**  `getSession(false)` 를 한 후, `session == null` 여부로 판단하지 않고, 항상 Session이 만들어지고 나서 그 내부의  `Optional<User>` 여부로 판단하도록 구성하신 이유가 궁금해용!!

2023-09-12 08:38 UTC, merged