[톰캣 구현하기 - 3, 4단계] 우르(김현우) 미션 제출합니다.
woowacourse/jwp-dashboard-http pull request #481
Opened 2023-09-11 07:27 UTC by java-saeng

안녕하세요 땡칠 !!!

저번 트러블 슈팅한 문서 공유해주셔서 재밌게 잘 읽었습니다~~

기존 코드와 다르게 많이 리팩터링 되었습니다,,,!!

괜찮으시다면 코드 보면서 이해가 잘 되시는지 궁금해요~~!!
감사합니다.

2023-09-12 08:05 UTC, 0chil requested changes
안녕하세요 우르! 3, 4단계도 잘 구현해주셨습니다!
2단계를 나중에 진행하신게 오히려 좋은 선택이었던 것 같아요 ㅎㅎ

코드 부분은 말씀대로 리팩터링이 많이 되어서 훨씬 읽기가 수월했습니다 👍
책임 분리도 더 명확해져서 설계가 잘 되어있다고 느꼈고 개인적으로 완성도 높다고 생각했습니다.

질문 몇 개 달아두었으니 확인해주시고 더 궁금하신 부분은 DM이나 커멘트 중 편한 방식으로 남겨주세요!
미션 고생많으셨습니다 🫡

2023-09-12 17:24 UTC, java-saeng reviewed
안녕하세요 땡칠 !!

매번 코멘트와 함께 링크 공유해주셔서 감사합니다 :)

땡칠 질문에 대한 답 남겨보았습니다 !!

2023-09-12 17:24 UTC, java-saeng commented on tomcat/src/main/java/org/apache/coyote/handler/HandlerComposite.java
> +        .forEach(it -> it.safeHandle(httpRequest, httpResponse));
와,, 섬세한 리뷰 감사합니다 👍👍👍

바로 수정했습니다 !

2023-09-12 17:32 UTC, java-saeng commented on tomcat/src/main/java/org/apache/coyote/handler/Handler.java
> +  void handle(final HttpRequest httpRequest, final HttpResponse httpResponse) throws IOException;
request에 맞는 controller를 찾기 전에 response에 관한 전처리를 해줘야하는 경우가 있을까? 에 대해서 생각해봤습니다.

대표적인게 `Accept`라고 생각이 드는데, 서버에서 지원하는 Content-Type이 없으면 바로 response `406 Not Acceptable` 를 응답하는 경우도 있지 않을까라는 생각이 들었습니다.

이게 맞는건지는 모르겠지만,, 톰캣이 설계한 이유 중에 아주 사소한 것 중 하나이지 않을까 싶습니다,,

2023-09-12 17:48 UTC, java-saeng commented on tomcat/src/main/java/org/apache/catalina/connector/Connector.java
> +        executor = Executors.newFixedThreadPool(maxThreads);
스레드 풀의 maxThread 의 개수를 250개로 설정하고 acceptCount를 100으로 하면 되지 않을까 싶습니다!!!

땡칠은 어떻게 생각하시나요?

2023-09-13 01:15 UTC, 0chil commented on tomcat/src/main/java/org/apache/catalina/connector/Connector.java
> +        executor = Executors.newFixedThreadPool(maxThreads);
저도 같게 생각했습니다. 
'100개 연결 대기' 부분이 OS가 관리하는 backlog 부분이고, acceptCount로 조절 가능하다고 생각했어요!

2023-09-13 01:19 UTC, 0chil commented on tomcat/src/main/java/org/apache/coyote/handler/Handler.java
> +  void handle(final HttpRequest httpRequest, final HttpResponse httpResponse) throws IOException;
그러게요 ㅎㅎ 컨트롤러에서 정한 응답 외에 오류 응답등이 있을 수 있겠네요
이런 응답 수정을 언제든지, 쉽게 하려고 이렇게 만들지 않았을까 싶어요.
원래 의도는 톰캣을 만든 본인만 알겠죠!

2023-09-13 01:23 UTC, 0chil commented on tomcat/src/main/java/org/apache/coyote/handler/RegisterPageHandler.java
> +    final String bodyData = FileDetector.detect(RENDERING_FILE_NAME);
네 메서드명만 보면 `boolean`이 튀어나올 것 같습니다!

2023-09-13 02:06 UTC, 0chil commented on tomcat/src/main/java/org/apache/coyote/request/HttpRequest.java
>    }
1. 그런 경험이 있으셨군여 ㅎㅎ 저도 접속만 해도 세션이 생기는 서비스들을 본 적 있는 것 같아요 (많이 본 것 같습니다)
세션이 무조건 생성되는 기능이 어색하지는 않지만, 그 기능의 사용 여부를 선택할 수 없다는 점이 아쉽다는 의미였어요.
웹 서버라는 범용적인 코드를 만드는 입장에선 사용자에게 조금 더 선택권을 줘야 좋지 않을까요?

2. 사용자의 편의라는게 코드 사용자의 편의를 말씀하시는 거라면 잘 이해했습니다.

우르 의견 충분히 이해가 되었습니다~ 답변 감사해요 ㅎㅎ

2023-09-13 02:26 UTC, 0chil approved these changes
안녕하세요 우르~
새벽에 리뷰 반영해주셨네요! 퇴근 후에도 열공하시는 모습 너무 멋있습니다.

리뷰하면서 우르덕에 새로운 생각들을 많이 얻고 학습도 하게 되었네요.
- Optional 사용이 꺼려졌는데 그래도 가독성에서 차이가 크다는 점
- Composite 패턴 활용
- canHandle() 메서드를 활용해 Controller 객체에 자율성을 부여하는 아이디어
- HTTP 표준 스펙
등등...

앞으로도 많이 배워가겠습니다 ㅎㅎ 미션 진행하시느라 고생 많으셨어요!

2023-09-13 02:26 UTC, merged