[톰캣 구현하기 3 & 4단계] 홍고(홍여진) 미션 제출합니다
woowacourse/jwp-dashboard-http pull request #483
Opened 2023-09-11 07:41 UTC by hgo641

안녕하세요, 포이!
부족한 코드지만 잘 부탁드립니다ㅠㅠ

변경된 부분은 크게 두 가지 있습니다...
* HandlerMapper내부의 메소드들을 Cotroller인터페이스의 구현체로 변경
* 파일을 읽는 StaticFile 클래스 생성

2023-09-12 05:11 UTC, poi1649 requested changes
홍고 안녕하세요! 전체적으로 패키지 분리를 열심히 해주신게 굉장히 눈에 띄네요! 특히 HandlerMapper 가 ServletContainer 처럼 활용되도록 설정하여 의존을 끊어주신 부분이 인상깊었습니다! 

새로운 미션도 진행되고 할 일이 엄청 많으실 것 같아 머지를 할까 고민했는데요.. 특정 부분에서 의도하신대로 작동하지 않는 코드일 수 있을 것 같아 한 번은 리퀘스트 체인지 남깁니다! 혹시 제가 홍고의 의도를 잘못이해한거라면 수정하지 않으시고 커멘트로 내용만 공유해주시면 감사하겠습니다! 오늘도 좋은 하루 보내세요!

2023-09-12 05:11 UTC, poi1649 commented on tomcat/src/main/java/org/apache/coyote/http11/SessionManager.java
> +    private static final Map<String, Session> SESSIONS = new ConcurrentHashMap<>();
https://google.github.io/styleguide/javaguide.html#s5.2.4-constant-names

저도 구구의 리뷰에서 발견한건데 구글 스타일 컨벤션에서 deeply Immutable 해야만 상수라고 설명하고 있네요. 조금 생각해보셔도 좋아보입니다!

2023-09-13 03:20 UTC, hgo641 commented on tomcat/src/main/java/org/apache/coyote/http11/message/StaticFile.java
> +        } catch (final NullPointerException e) {
classLoader.getResource()에서 리소스가 존재하지 않으면 url이 Null로 할당됩니다!
 Null.getFile()이 되면서 NPE가 발생하더라고요. 

`return new String(Files.readAllBytes(new File(url.getFile()).toPath()));` 에서 catch를 하고 있어 로직을 파악하기 힘들 것 같네요! url이 null이면 new File까지 가지 않고 바로 예외를 반환하게 변경하겠습니다. 감사합니다!!

2023-09-13 06:17 UTC, hgo641 commented on tomcat/src/main/java/nextstep/jwp/controller/LoginController.java
> +        if (request.getSessionValue(USER) != Optional.empty()) {
`request.getSessionValue(USER).isEmpty()` 너무 좋아요~~~ 다른 Optional들도 동일하게 수정했습니다!

2023-09-13 09:02 UTC, hgo641 commented on tomcat/src/main/java/nextstep/jwp/controller/RootController.java
> +        response.setBy(createdResponse);
기존에 유효한 정보(status, body)들을 받아 Response를 생성해주는 로직이 존재했는데, 3단계 요구사항에서 `doGet(final Request request, final Response response)` 메소드가 생기면서 Response를 무조건 디폴트값으로 초기화하게 되었습니다.
기존에 생성한 `유효한 정보(status, body)들을 받아 Response를 생성해주는 로직`을 그대로 재활용하기 위해 `setBy()`를 생성했습니다...ㅎㅎ 

물론 사용하지 않을 복사용 Response 객체가 생기긴 하지만...ㅎㅎ 이 정도는 괜찮지 않을까 했어요...ㅎㅎ
혹시 마음에 걸리는 부분이 있으신가요?

2023-09-13 10:59 UTC, hgo641 commented on tomcat/src/main/java/org/apache/catalina/connector/Connector.java
>      }
헉 그렇네요! 스레드 고수 포이 감사합니다!!
new ThreadPoolExecutor를 사용해서 queue의 사이즈를 100으로 지정해주었습니다!

2023-09-13 11:33 UTC, poi1649 commented on tomcat/src/main/java/nextstep/jwp/controller/RootController.java
> +        response.setBy(createdResponse);
저도 큰 차이는 없다고 생각하는데 혹시 제가 생각못한 장단점이 있을까해서 여쭤봤습니다! 🫡

일반적인 서블릿 프로그래밍과 약간의 차이가 있다면 공통 헤더를 처리해주는 filter들을 따로 두어 doFilter 메서드로 리스폰스에 필요한 것들을 계속해서 set해주는 과정으로 가져가는 것 정도 같네요!

2023-09-13 11:44 UTC, poi1649 commented on tomcat/src/main/java/org/apache/catalina/connector/Connector.java
>      }
오 queue 를 사용하셨군요. 구구는 Executors 안의 메서드를 사용해서 만들어보라고 하셨지만 저도 이 방법이 제일 속편한 것 같아요ㅋㅋㅋㅋ.. ....

그런데 사실 현재 구조라면 socket의 accept-count 수 만큼 백로그에서 추가로 더 대기하게 됩니다. 스레드 작업큐 100개 + 백로그 100개 총 200개의 커넥션이 대기하게 되겠네요. 
이처럼 두가지 영역을 함께 사용하면 의도한 숫자보다 대기하는 커넥션이 많이 생기기도 하고, 관리도 번거로워질 수 있어요! 
스레드 작업큐에 있는 것들은 큐에서 지정된 시간보다 오래 대기하면 time out이 발생합니다. 
반대로 백로그에서 대기하는 커넥션은 3-way-handshake 연결 과정중 마지막 과정인 서버의 ack를 기다리는데 이 과정에서는 일정 시간 응답이 오지 않으면 재요청을 보내게 됩니다.(이는 일반적인 tcp의 특징입니다. )
두 가지를 전부 핸들링 해주는건 조금 번거로울 수도 있어보여요

일반적인 웹 프로그래밍에서 대기큐를 지정하는 경우가 많은지는 잘 모르겠지만, 찾아보시면 도움이 되실 것 같네요!

2023-09-13 11:53 UTC, poi1649 commented on tomcat/src/main/java/org/apache/catalina/connector/Connector.java
> +            executorService.shutdown();
👍👍 쓰레드는 신경쓸게 참 많은 것 같아요 ㅋㅋㅋㅋ

2023-09-13 11:59 UTC, poi1649 commented on tomcat/src/main/java/org/apache/coyote/http11/message/StaticFile.java
> +        } catch (final NullPointerException e) {
앗 위 classLoader에서 먼저 null 을 반환하는군요 혼란을 드려 죄송합니다 ㅋㅋㅋㅋㅋ...🙇‍♂️
그치만 수정하신 로직이 더 좋아보이네요!

2023-09-13 12:09 UTC, poi1649 approved these changes
홍고 안녕하세요! 이것저것 바쁘실텐데 고생많으셨습니다. 🫡
이번 미션은 이만 머지해도 괜찮을 것 같아요! 
정말 마지막으로 조금의 커멘트를 남겼는데 시간나실때 편하게 확인해주시면 감사하겠습니다! 
다음 미션도 화이팅입니다!!

2023-09-13 12:10 UTC, merged