Step4
woowacourse/jwp-dashboard-http pull request #485
Opened 2023-09-11 07:45 UTC by chaewon121

2023-09-11 15:02 UTC, thdwoqor approved these changes
안녕하세요 채채 
3,4 단계 고생많으셨습니다 🙂

확인하니 요구사항이 빠진부분이 있어서 이부분만 고쳐주시면 머지하겠습니다!

시간 날때 coyote, catalina가 어떤의미로 사용되고 어떤 부분까지 처리해야할지 고민해보면 좋을것같아요

2023-09-11 15:07 UTC, thdwoqor requested changes
안녕하세요 채채
3,4 단계 고생많으셨습니다 🙂

확인하니 요구사항이 빠진부분이 있어서 이부분만 고쳐주시면 머지하겠습니다!

시간 날때 coyote, catalina가 어떤의미로 사용되고 어떤 부분까지 처리해야할지 고민해보면 좋을것같아요

2023-09-14 08:07 UTC, chaewon121 commented on tomcat/src/main/java/org/apache/catalina/session/HttpSession.java
> +        values.put(name, value);
생성자를 새로 생성할때마다 새로운 UUID를 주고 그외의 상황에서는 id를 바꾸거나 생성하지 않도록 하기 위해서 생성자에서 진행을 하였습니다! 만들어둔 매서드를 사용하는것이 좋겠네요..!

2023-09-14 08:29 UTC, chaewon121 commented on tomcat/src/main/java/org/apache/coyote/http11/response/LoginGetController.java
> +public class LoginGetController implements Controller {
저는 컨트롤러의 구현체는 확실하게 응답을 처리하는 클래스이기 때문에 coyote 패키지에 있는것이 좋겠다는 생각이 듭니다. controller 인터페이스는 컨테인의 기능이나 코요테를 돕기위한 객체라기보다 유연한 응답처리를 위해 구현된 것이라고 생각이 들어서 catalina보다coyote패키지에 함께 두었습니다..! 저희가 현재 구현하는 응답은 mvc 패턴에서의 view 라기 보단 http응답이라고 생각이 되어 그 응답을 만드는 controller를 jwp밑에 두게 되면 jwp 패키지와 cotyte 패키지가 서로 의존하는 경우가 발생하여 coyote 패키지에 두는것이 낫다고 판단하였습니다!

2023-09-14 15:04 UTC, chaewon121 commented on tomcat/src/main/java/org/apache/coyote/http11/response/HttpResponse.java
>      public void addJSessionId(final String JSessionId) {
이 부분에 대해서 고민해보고 의존성분리를 해보았습니다..! RequestMappingHandler 를 카탈리나로 옮기고 session 검증을 request에서 할 수 있도록 코드를 수정하였습니다..!

2023-09-14 15:12 UTC, thdwoqor approved these changes
안녕하세요 채채
3,4 단계 미션 구현하시느라 고생하셨어요 👍
머지하겠습니다

2023-09-14 15:12 UTC, merged