[톰캣 구현하기 3, 4단계] 연어(황재현) 미션 제출합니다.
woowacourse/jwp-dashboard-http pull request #490
Opened 2023-09-11 08:28 UTC by nuyh99

반갑습니다 폴로!!!!

작업 사항
- 컨트롤러 추가 (기존의 Request -> Response 파싱 책임을 Controller에게 맡겼습니다)
- `new Thread()` -> 스레드풀 사용하도록 변경

# 잘 부탁드립니다🙏

2023-09-12 06:02 UTC, green-kong requested changes
안녕하세요 연어!
맞은편에 앉아서 글로 인사를 하려니 어색하네요.
짜여진 코드는 전반적으로 깔끔해서 잘 읽히는 코드였습니다!
다만 기대했던게 있어서인지, 예외처리부분은 아쉬움이 조금 남네요..ㅠ

몇가지 코멘트 남겨두었는데 코멘트에 답글만 남겨주셔도 됩니다. 
굳이 코드를 수정하실 필요는 없을 것 같아요!(원하신다면 말리진 않겠습니다!)

코멘트에 답글 남겨주시고 다시 리뷰요청 보내주세요!
수고하셨습니다.

2023-09-13 14:02 UTC, nuyh99 commented on tomcat/src/main/java/nextstep/jwp/controller/Controller.java
> +}
패키지 구조가 너무 헷갈려서요ㅠㅠ
코드 레벨 좀 뜯어보면서 정리해볼게요.

![](https://github.com/woowacourse/jwp-dashboard-http/assets/93072571/35b016c8-aa77-4c19-bf09-9bef185f1085)
Java 진영에서는 위의 Servlet을 포함하는 Java EE(Jakarta EE) 스펙을 제공합니다.
그리고 톰캣은 그 스펙을 구현하는 역할을 하구요!

![](https://github.com/woowacourse/jwp-dashboard-http/assets/93072571/40aa5c33-f983-4ad4-ba2a-d75205ffcd13)
Tomcat의 coyote 패키지에서는 Coyote 기반의 서블릿 컨테이너를 위한 인터페이스로 `Adaptor`를 제공하네요!

그리고 Tomcat의 catalina 패키지에서는 위의 `Adaptor`를 구현한 `CoyoteAdaptor`가 있네요.
얘의 역할은 Coyote Processor라고 합니다.

결국 처리는 
catalina.CoyoteAdaptor -> catalina.Connector(coyote.Http11Nio 사용) -> Service(catalina.StandardService) -> Container(catalina.StandardEngine) -> Pipeline(catalina.StandardPipeline)
여기서 Pipeline에 적용된 여러 Valve 들의 `invoke`를 거쳐서 가공을 합니다.

![](https://github.com/woowacourse/jwp-dashboard-http/assets/93072571/38f6593c-d7cd-4446-9e5a-f9b1e41b7037)
이런 식으로 Valve 파이프라인이 진행되는 것 같네요.

그리고 Container, Host, Context 객체들로 적절한 Servlet을 찾아서 service()를 호출합니다.

### 정리해보면,
1. 톰캣의 Coyote는 프로토콜 관련 컴포넌트입니다. 디폴트는 HTTP 1.1 이구요.
2. 톰캣의 Catalina는 톰캣 컨테이너입니다. 톰캣의 핵심이라고 봐도 무방할 것 같습니다.
3. 유저의 요청이 HTTP를 통해 들어오기 때문에 Coyote 컴포넌트를 통해 받습니다. 그리고 CoyoteAdaptor를 통해 Catalina, 즉 톰캣 컨테이너로 가져와서 적절한 서블릿을 찾아서 수행합니다.

### 지금 과제의 구조로 보자면,
Connector로 들어온 요청이 ThreadPool 중 한 스레드에 바인딩되어 Http11Processor에게 위임합니다.
그리고 해당 프로세서가 알맞은 컨트롤러(서블릿)을 찾아서 service()를 호출합니다.
확실히 몇 가지 단계가 빠졌지만 매우 비슷한 구조인 것 같네요.

결론은...!
`Controller`, `AbstractController`는 Catalina에 해당하고 servlet 패키지에 있으면 적당할 것 같습니다. (실제 톰캣의 패키지는 servlets 입니다)
그리고 각 서블릿들은 말씀하신대로 webapp에 해당하는 jwp 패키지에 있는 게 좋을 것 같네요!

2023-09-13 15:34 UTC, nuyh99 commented on tomcat/src/main/java/nextstep/jwp/controller/AbstractController.java
> +    }
오...존재만 알았습니다!

AbstractController의 필드에서 List로 서블릿이 허용하는 메서드 목록을 생성자로 받아서 저장하고,
UnSupported 대신 해당 405를 리턴하면 될 것 같네요.
그리고 Get의 경우만 404로 처리하면 될 것 같아요.

까지만 생각해보고 지금은 잘못된 url, method 조합은 전부 404로 처리했습니다!!

2023-09-13 15:39 UTC, nuyh99 commented on tomcat/src/main/java/org/apache/coyote/http11/request/header/Cookies.java
>          return new Cookies(result);
좋습니다!

2023-09-13 15:41 UTC, nuyh99 commented on tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java
>          }
ㅋㅋㅋㅋㅋㅋㅋㅋㅋ한 번에 처리했었습니다만...
좁은 범위로 처리했습니다!

2023-09-13 15:45 UTC, nuyh99 commented on tomcat/src/main/java/org/apache/coyote/http11/request/header/HeaderKey.java
> +    SET_COOKIE("Set-Cookie");
현재 Enum으로 관리되고 있는 HeaderKey를 그냥 Class로 변경하고 Adaptor 패턴을 쓰면 될 것 같아요!

```java
public class CustomHeaderKey extends HeaderKey {

    public CustomHeaderKey(final String key) {
        super(key);
    }
}
```
이런 식으로 커스텀용 어댑터를 만들어줄 수 있을 것 같습니다.
다만 이 부분도 생각만 해보고 아직은 확장시키지 않았습니다!

2023-09-13 15:52 UTC, nuyh99 commented on tomcat/src/main/java/org/apache/coyote/http11/request/header/RequestLine.java
> +    }
`Http11Processor`에서 처리하기 때문에 현재는 무조건 HTTP 1.1만 가능합니다.
만약 HTTP 2, 3 등의 다른 프로토콜이 쓰인다면 Request 구조부터 달라져서요...!
문자열 형식의 패킷이 Framing되어 바이너리 형태로 존재하는 등 새로 다 만들어야 할 것 같아요.

이에 대해서 추상화하려면 톰캣처럼 프로토콜, 커넥터 등을 전부 추상화하고 구현해야 할 것 같습니다ㅠㅠ
현재의 비즈니스에서는 지금의 상태가 좋다고 생각해요!

2023-09-13 15:53 UTC, nuyh99 commented
가감 없는 꼼꼼한 채찍 감사합니다...!
저녁을 톰캣과 함께 불태웠네요ㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2023-09-14 02:22 UTC, green-kong commented on tomcat/src/main/java/nextstep/jwp/controller/Controller.java
> +}
와우...!
진짜 호기심에 물어본건데 이렇게 까지 깊이 공부를 해보셨네요..!
대단합니다 연어!
덕분에 저도 톰캣의 구조에 대해 조금 더 알게되었네요!!

2023-09-14 02:24 UTC, green-kong commented on tomcat/src/main/java/org/apache/coyote/http11/request/header/HeaderKey.java
> +    SET_COOKIE("Set-Cookie");
오 이렇게 바꿀수도 있겠네요!
좋은 의견 감사합니다!

2023-09-14 03:18 UTC, green-kong approved these changes
크으 역시 맛집이네요! 잘먹고 갑니다!!
리뷰 반영도 가능한 부분에서 많이 해주셨고,
학습도 충분히 하신것 같아 merge 하도록 하겠습니다.
다음 미션도 화이팅하세요!

2023-09-14 03:18 UTC, merged