HTTP 서버 구현하기 - 2, 3단계] 나봄(윤보민) 미션 제출합니다.
woowacourse/jwp-dashboard-http pull request #57
Opened 2021-08-31 11:56 UTC by qhals321

안녕하세요 조앤!! 두 번째 피알입니당!!!!
이번에 신경 쓴 부분은 세션 쿠키와 mvc 관련 전체적인 리팩토링이었어요!
세션과 쿠키는 MethodArgument로도 바로 받아올 수 있게끔 만들었습니다!!

세션 키에 trim 을 안줘서 한참... 헤맸네요ㅠ
세션 관련 테스트도 인수 테스트 형식으로 작성했습니다!

mvc에서 패키지 구조는
- argument : 컨트롤러 메서드 전달인자 관련
- exceptionresolver : 전체적인 에러 핸들링 전략
- handler : 기본적인 컨트롤러 (컨트롤러어댑터)
- mapping : 핸들러 찾는 패키지
- view : 뷰 핸들링 패키지

이렇게 분리해놨습니다!

항상 꼼꼼한 리뷰 너무나 감사해요!!

2021-09-01 14:49 UTC, seovalue commented on README.md
>  - 라인, 헤더, 바디 구분해서 구현
꼼꼼한 README 👍

2021-09-01 14:50 UTC, seovalue commented on app/src/main/java/nextstep/jwp/RequestHandler.java
> +    private HttpSessions httpSessions;
여기도 final 붙이는게 좋을 것 같아요! 👍

2021-09-01 14:52 UTC, seovalue commented on app/src/main/java/nextstep/jwp/webserver/request/DefaultHttpRequest.java
> +    private HttpCookie httpCookie;
RequestLine부터 HttpCookie까지 final로 선언하면 좋을 것 같아요~~ final충..

2021-09-01 14:53 UTC, seovalue commented on app/src/main/java/nextstep/jwp/webserver/response/DefaultHttpResponse.java
> +    private OutputStream outputStream;
OutputStream이 여기로 들어가다니!! 신기하네용

2021-09-01 14:55 UTC, seovalue commented on app/src/main/java/nextstep/jwp/webserver/response/DefaultHttpResponse.java
> +    public void flush() {
flush를 HttpResponse에 적용하시다니... 천재시죠? 아 맞다 천재였지

2021-09-01 15:00 UTC, seovalue commented on app/src/main/java/nextstep/jwp/JwpApplication.java
> +
실행했을 때 중간중간 뜨는 IllegalStateException은 favicon 요청일까요오?

2021-09-01 15:03 UTC, seovalue commented on app/src/main/java/nextstep/jwp/app/ui/LoginController.java
> +    public String unauthorizedPage() {
그냥 궁금해서 남기는 코멘트인데요! 지금은 login에서만 401이 쓰이지만 (일어나지 않을) 미래에는 전역적으로 사용될 수도 있을 것 같은데, 에러 페이지는 따로 분리해서 관리할 수 있지 않을까요? 물론 이번 요구사항에는 전혀 없는거라 그냥 생각나서 달아봅니다!

2021-09-01 15:06 UTC, seovalue commented on app/src/main/java/nextstep/jwp/webserver/request/DefaultHttpRequest.java
> +        return sessionUtil.getSession(sessionId);
👍

2021-09-01 15:12 UTC, seovalue commented on app/src/main/java/nextstep/jwp/mvc/exceptionresolver/NotFoundExceptionResolver.java
> +public class NotFoundExceptionResolver extends AbstractExceptionResolver{
궁금해서 다는 건데요오! Controller의 page에서 String 페이지로 예외를 응답하는 것과 이렇게 Resolver를 사용하는 예외는 어떤 차이로 구분하신건지 궁금해요!!!!!!!! 😵

2021-09-01 15:13 UTC, seovalue commented on app/src/main/java/nextstep/jwp/mvc/handler/MethodHandler.java
> +    ;
외로운 땀을 발견햇읍니다

2021-09-01 15:14 UTC, seovalue commented on app/src/main/java/nextstep/jwp/mvc/handler/RestControllerHandler.java
> +        return null;
RestController는 DispatcherServlet의 ha.handle에서 null을 리턴하던데....... 이걸 여기서도 보다니 진짜 갓입니다 나봄

2021-09-01 15:23 UTC, seovalue requested changes
안녕하세요 나봄! 또다시 조앤입니다 ㅎ히히힣

이번엔 진짜 스프링을 만들어오셨네요!! 코드 보면서 정말 많이 배웠습니다 🙏🏻

미션에서 주어진 요구사항은 전부 다 구현되어있고, 테스트 및 서버 돌려봤을 때도 잘 작동하는 거 확인했어요. 그래서 바로 이만 머지🙏🏻해도 되지만 좀 더 깔끔한 상태로 머지되면 좋잖아요 ?! ㅎㅎㅎㅎ

그래서, SonarQube에서 이야기하는 CodeSmell들과 테스트 커버리지를 80% 이상으로 맞추어봐도 좋을 것 같아요! 그리고 처음 우테코를 시작하면서 항상 지켜왔던 depth와 같은 것들도 한번 지켜보는 건 어떨까요? 수정해나가는 과정에서 또다른 인사이트를 얻으실 수도 🤔 

하지만 필수는 아니기 때문에 원하시는 만큼 한 뒤 다시 리뷰요청 보내주시면 될 것 같아요 😋

리뷰는 (진짜) 궁금한 점 몇가지 남겨보았는데, 나봄의 의견 남겨주시면 좋을 것 같아요! 

첫 리뷰인데, 멋진 코드 리뷰할 수 있게 해주셔서 감사해요 👍 수고많으셨어요!

2021-09-01 23:59 UTC, qhals321 commented on app/src/main/java/nextstep/jwp/mvc/exceptionresolver/NotFoundExceptionResolver.java
> +public class NotFoundExceptionResolver extends AbstractExceptionResolver{
DispatcherServlet 에서 흐름을 진행하는 중 Exception을 만나면 Exception을 가지고 ExceptionResolver를 실행하게 됩니당!!
AbstractExceptionResolver가 실질적으로 resolve 하는 애이고 필요한 데이터는 상속받은 클래스에게 입력을 하도록 유도했습니다! (템플릿 메서드 패턴?)

2021-09-02 00:00 UTC, qhals321 commented on app/src/main/java/nextstep/jwp/mvc/handler/MethodHandler.java
> +    ;
오.... 땀이 언제 저기까지 침투했지....

2021-09-02 00:01 UTC, qhals321 commented on app/src/main/java/nextstep/jwp/mvc/handler/RestControllerHandler.java
> +        return null;
앗... 이 부분은 나중에 RestController 부분도 만들어봐야지 하고 그냥 아무 생각 없이 null 을 리턴해버렸네유... 헤헤

2021-09-02 00:10 UTC, qhals321 commented on app/src/main/java/nextstep/jwp/app/ui/LoginController.java
> +    public String unauthorizedPage() {
넵! 그래서 현재는 redirect:/unauthorized 로 401을 처리하고 있습니당!!
슬슬 만들고 싶은 부분은 ControllerAdvice를 흉내내어 throw new UnauthorizedException(); 만 해두 외부에서 감싸줄 전역 컨트롤러를 만들어보고싶슴돠ㅠㅠ!!

2021-09-02 00:11 UTC, qhals321 commented on app/src/main/java/nextstep/jwp/JwpApplication.java
> +
엇.... 이것저것 해봤는데 IllegatStateException이 안터지던데ㅠ 어떻게 터지는 걸까유ㅠㅠㅠ

2021-09-02 00:11 UTC, qhals321 commented on app/src/main/java/nextstep/jwp/webserver/request/DefaultHttpRequest.java
> +    private HttpCookie httpCookie;
흑흑 final 붙이는 습관을 꼭꼭 들여야겠어요ㅠ

2021-09-02 00:12 UTC, qhals321 commented on app/src/main/java/nextstep/jwp/RequestHandler.java
> +    private HttpSessions httpSessions;
넵 알겠슴돠!!

2021-09-02 00:40 UTC, qhals321 commented
후 하 후 하 
소나큐브가.. 안쓰는 메서드도 전부 테스트로 잡아버려서.. ㅠㅠ
그냥 편의상 이 기능도 제공해줬음 좋겠다 라는 기능들을 다 테스트 대상으로 잡아버렸네요!!
몇 개 삭제하고 css 관련 테스트까지 작성해주니 80프로 드디어 찍었네요!!
조앤이 말해준 리뷰 모두 적용했어요~!!
꼼꼼한 리뷰, 칭찬 너무 고마워요ㅠㅠㅠ

2021-09-02 03:43 UTC, seovalue commented
오호! 커밋 단위로 변경사항을 확인할 수 있어서 좋았어요!

테스트 커버리지도 80%를 넘기셨군요!!!! ㅎㅎ
정말 고생많으셨습니다~ 코드가 깔끔해서 더 이상 변경요청할 것은 전혀! 없는 것 같아요 🐯
ControllerAdvice까지 구현될 프레임워크 나봄 기대할게요! 👍👍

레벨4 첫 미션 고생하셨어요! 이만 머지하겠습니돠 🙏🏻

2021-09-02 03:43 UTC, merged