[HTTP 서버 구현하기 - 2, 3단계] 마크(김병화) 미션 제출합니다.
woowacourse/jwp-dashboard-http pull request #66
Opened 2021-09-01 10:42 UTC by binghe819

### 안녕하세요 배럴~~

1단계때 리팩토링 부분은 구현하여서, 이번 단계에선 쿠키와 세션을 적용해보았어요!

Request에서 `getSession()`을 통해 해당 요청에 대한 세션을 가지고 올 수 있게 하였습니다!

또한, Response에 `addCookie()`를 통해 쿠키를 설정해줄 수 있게 하였습니다.

<br>

이를 통해 요구사항에 있는 `/login`에 접속했을 때 세션을 통해 로그인 상태면 `index.html`로 리다이렉트하도록 해두었습니다!

<br>

> 사실 리팩토링과 테스트하고 싶은 부분이 많지만ㅠ 다른 할 일로 인해 모두 못한 점이 아쉽네요.. 피드백 받고 리팩토링해보겠습니다ㅎㅎ

<br>

### 잘 부탁드려요~~ 편하게 DM 주세요!

2021-09-02 12:54 UTC, knae11 requested changes
마크~ 2,3 단계도 빠르게 제출해주셨네요! :) 

기존에 다양하게 사용할 수 있도록 해두어서 빠르고 큰 변화없이 적용하신 것 같아요 👍 👍 👍 

쿠키를 사용하는 세션은 애플리케이션에서 정상동작하는 것을 확인했습니다 😄 
하지만 깨지는 테스트가 있네요ㅠㅠ 수정 부탁드릴게요! 😀
![image](https://user-images.githubusercontent.com/66905013/131841023-5f6ad906-aba2-4696-837d-fdbaea87e896.png)

더불어 사용하지 않는 전반적으로 한번 확인해 보시는 것도 좋을 것 같아요 :)
몇가지 의견 남겨보았습니다.ㅎㅎㅎ

2021-09-02 12:54 UTC, knae11 commented on app/src/main/java/nextstep/project/presentation/LoginController.java
> +//            User user = (User) session.getAttribute("user");
사용하지 않는 주석은 삭제해 주세요 :)

2021-09-02 12:54 UTC, knae11 commented on app/src/main/java/nextstep/jwp/http/session/HttpSessions.java
> +    static void remove(String id) {
나중을 위해서 만들어 두신 것 같은데 사용하지 않는 메소드는 삭제하는 것도 좋을 것 같아요! :)

2021-09-02 12:54 UTC, knae11 commented on app/src/main/java/nextstep/jwp/http/session/HttpSession.java
> +        attributes.putIfAbsent(name, value);
오! putIfAbsent 새롭게 배워갑니다:) 존재하는 key 로 들어왔을 때, 덮어씌워지지 않는군요!!ㅎㅎㅎ

2021-09-02 12:54 UTC, knae11 commented on app/src/main/java/nextstep/jwp/http/message/HttpCookies.java
> +    private List<HttpCookie> cookies;
오~ 각각의 쿠기들을 리스드로 관리하시는 군요:) 👍

2021-09-02 12:54 UTC, knae11 commented on app/src/main/java/nextstep/jwp/http/message/HttpCookie.java
> +    }
오,, 생성과 파싱을 같이 관리하는 군요! 👍

2021-09-02 12:54 UTC, knae11 commented on app/src/main/java/nextstep/jwp/http/message/HttpCookie.java
> +    public void setValue(String value) {
사용하지 않는 setter는 지워주세요 🙏 이번에 코드를 보면서 지난 코드들도 보니 사용되지 않는 메소드들이 조금 남아있는 것 같아서 확인해 보시면 좋을 것 같아요! :)

2021-09-02 12:54 UTC, knae11 commented on app/src/main/java/nextstep/jwp/http/message/HttpCookies.java
> +    }
여기서 예외 없을 경우 예외를 던지지 않고 parser 에 가서 처리하는 이유가 있는지 궁금하네요 :)
계속 optional 값을 가지고 위로 위로 올라가고 있는 것 같아요. 있을지 없을지 모르는 값들을 계속 optional 로 가지고 다니는 이유가 조금 궁금합니다. 계속 null 일 가능성이 있는 객체를 끊지 않고 가지고 다니면 헷갈리게 될 것 같아서요. 계속해서 null인지 아닌지 확인하는 로직이 들어갈 것 같아서 질문드리는 내용입니다.ㅎㅎㅎ

2021-09-02 12:54 UTC, knae11 commented on app/src/main/java/nextstep/jwp/http/parser/HttpParser.java
> +                );
오 이런 문법도 있군요 :)

2021-09-02 12:54 UTC, knae11 commented on app/src/main/java/nextstep/jwp/http/session/HttpSession.java
> +}
삭제하지 않으셔도 되는데 사용되지 않는건 삭제해도 좋을 것 같다는 의견입니다.ㅎㅎㅎ

2021-09-03 05:21 UTC, binghe819 commented on app/src/main/java/nextstep/jwp/http/session/HttpSessions.java
> +    static void remove(String id) {
습관적으로 추가 메서드를 만들면 삭제 메서드를 만드네요ㅠㅠ 디테일한 부분들 더 신경쓰도록 할게요! 피드백 고마워요ㅎㅎ 👍

2021-09-03 05:24 UTC, binghe819 commented on app/src/main/java/nextstep/jwp/http/message/HttpCookie.java
> +    public void setValue(String value) {
꼼꼼한 피드백 고마워요ㅎㅎ

2021-09-03 06:24 UTC, binghe819 commented on app/src/main/java/nextstep/jwp/http/message/HttpCookies.java
> +    }
우선 `Optional`을 사용한 이유는 쿼리 메서드를 실행하면 빈 값(empty)가 반환될 수 있다는 것을 클라이언트(메서드를 사용하는 객체측)에게 알려주기 위함이었습니다!

그래야 해당 메서드를 사용하는 클라이언트에게 쿼리 메서드의 반환 값에 따른 분기를 나누는 역할을 부여할 수 있을 거 같아서요ㅎㅎ

> 저는 습관적으로 쿼리 메서드엔 가능한 `Optional`을 사용하려고 지향합니다!

실제로 Header에서 `Cookie`라는 이름의 헤더에 `JSESSIONID`가 존재할 때와 존재하지 않을 때의 분기를 `Session`에게 부여해주기 위함으로 사용했습니다.  

하지만 배럴 말대로 계속해서 null인지 확인하는 로직이 들어갈 것 같기도하네요ㅠ 이 부분에 있어서 고민을 조금 더 해봐야겠군요ㅠ

우선은 Optional을 잘 활용하여 `HttpParser`부분을 리팩토링해보았어요!

```java
@Override
public Optional<HttpSession> getSession() {
    return cookies.findByName(SESSION_ID)
        .map(cookie -> HttpSessions.getSession(cookie.getValue()));
}
```

2021-09-03 06:27 UTC, binghe819 commented on app/src/main/java/nextstep/jwp/http/parser/HttpParser.java
> +                );
자바9부터 추가된 기능인데 잘 활용하면 좋은 것 같아요!! 👍

2021-09-03 06:41 UTC, binghe819 commented
배럴 패드백 감사합니다 :) 👍 

1단계때 로그인 관련해서 Query String으로 로그인되는지 확인하는 테스트 코드가 2, 3단계되면서 POST Body 형식으로 바뀌면서 테스트가 깨졌네요ㅠㅠ

자세히 테스트 확인을 안하구 PR을 날렸네요ㅠ 죄송해요!

배럴 피드백에 대한 제 의견도 남겨두었습니다 :) 

> 피드백 다시 한번 고마워요ㅎㅎ

2021-09-05 12:58 UTC, knae11 commented on app/src/main/java/nextstep/jwp/http/message/HttpCookies.java
> +    }
저도 이부분 피드백을 남길 땐, 뭔가 Optional 대신 처리할 방법이 있을 거라고 생각했는데... 제것도 리팩토링 하면서 보니 Optional 로 처리하는게 더 좋은 방법인 것 같기도 해요! 저도 잘 모르고 남긴 피드백 같네요ㅠㅠ 죄송하네요ㅠㅠ 리팩토링 👍 👍

2021-09-05 13:03 UTC, knae11 approved these changes
마크의 코드를 보면서 많이 배웠어요! 👍 👍 
다음 미션도 화이팅 입니다~~~~ 😄

2021-09-05 13:03 UTC, merged