[HTTP 서버 구현하기 - 2, 3단계] 루트(김준근) 미션 제출합니다.
woowacourse/jwp-dashboard-http pull request #68
Opened 2021-09-01 12:43 UTC by Junroot

안녕하세요 찰리! 2,3 단계 제출합니다!
어느 정도 리팩토링이 되어있어서 금방 끝낼줄 알았는데, `Controller` 인터페이스를 완전 새로 고친다고 생각보다 오래 걸렸네요 ㅠㅠ
이번에 세션, 쿠키 구현을 위해서 `HandlerInterceptor` 라는 개념을 도입해봤어요! `IntercpetorResolver`가 `nextstep.jwp.interceptor` 패키지에 존재하는 모든 인터셉터를 스캔해서 관리하도록 구현해봤습니다!

이번 미션도 잘 부탁드릴게요~

2021-09-01 16:25 UTC, Gomding requested changes
루트 2,3단계 빠르게 구현하셨군요!!
코드가 엄청 깔끔한데 이렇게 빠르게 구현했다니 놀랍습니다 😮😮😮😮

배울점이 너무 많아서 코드 읽는 내내 즐거웠습니다 :)
특히 Interceptor 를 구현한점이 인상깊었어요 👍👍 

몇가지 코멘트를 남겼는데 확인 부탁드려요!!
2,3단계 구현하느라 고생하셨습니다 👏 
코멘트에 추가 설명이 필요하거나 의견을 나눠보고 싶다면 언제든 DM 주세요!!

2021-09-01 16:25 UTC, Gomding commented on app/src/main/java/nextstep/jwp/controller/AbstractController.java
> +    }
코드를 보면서 약간 어색했던 부분인데 관점의 차이라고 생각해서 지금부터는 개인적인 의견으로 보시면 됩니다!
Controller 에서 response를 생성하는 부분에 상당부분 관여하는 메소드라고 생각해서
HttpResponse 안에 해당 메소드가 있으면 어땠을까 생각했어요!!
그렇게 한다면 FILE_RESOLVER도 HttpResponse가 가지게 되겠네요

```java
response.respondByFile(final String filePath)
```

루트의 의견이 궁금합니다 😃

2021-09-02 02:09 UTC, Junroot commented on app/src/main/java/nextstep/jwp/infrastructure/http/reader/HttpRequestReader.java
> +            lines.add(line.trim());
빈 문자열 자주 사용되니 상수화 좋아보이네요!

2021-09-02 02:29 UTC, Junroot commented on app/src/main/java/nextstep/jwp/infrastructure/http/interceptor/AbstractInterceptor.java
> +}
헉 그런 방법이!! 👍

2021-09-02 02:42 UTC, Junroot commented on app/src/main/java/nextstep/jwp/controller/AbstractController.java
> +    }
저도 파일 읽기에 관해서 고민이 됐었어요!
`HttpResponse`안에 `responseByFile()` 이 있다면, 컨트롤러 뿐만 아니라 다른 핸들러에서도 사용이 가능하기 때문에 중복 코드를 더 줄일 수 있어서 찰리가 말한 방법도 고민했었습니다.
하지만 제가 내린 결론은 '`HttpResponse`는 단순히 Http 응답을 나타내기 위한 객체기 때문에, 파일을 읽는 과정은 `HttpResponse` 밖에서 하는게 맞다'였습니다. 혹시 다른 의견이 있다면 추가적으로 이야기하셔도 좋을 것 같아요!

2021-09-02 16:21 UTC, Gomding commented on app/src/main/java/nextstep/jwp/WebServer.java
> +    private static final WebApplicationContext CONTEXT = new WebApplicationContext(HANDLER_MAPPING, INTERCEPTOR_RESOLVER);
너무 좋은데요? DI 쪽을 완전 생각 안하고 있었네요..
인사이트를 넓혀주셔서 감사합니다 루트

2021-09-02 16:23 UTC, Gomding commented on app/src/main/java/nextstep/jwp/controller/AbstractController.java
> +    }
오 ```HttpResponse는 단순히 Http 응답을 나타내기 위한 객체기 때문에``` 이 말이 엄청 공감이 되네요.
👍 👍 👍

2021-09-02 18:32 UTC, Gomding approved these changes
루트 2,3 단계 구현하느라 고생하셨습니다!

DM보고 바로 확인했어야했는데 너무 늦게 확인했네요 🙇 🙇 🙇 

피드백 드릴 부분을 많이 찾지 못해서 몇가지 코멘트만 추가로 남기고 이번 미션은 머지하겠습니다!!

루트가 만든 HTTP 서버를 보면서 많이 배웠고 커밋에 루트의 고민들을 보면서 즐거웠습니다!!
요즘 컨디션이 바닥으로 가고있는데 루트의 열정을 보면서 저도 살아나고 있답니다 😄 정말 감사드립니다. 
다음 미션도 화이팅입니다 🔥 🔥 🔥 🔥 🔥

2021-09-02 18:32 UTC, Gomding commented on app/src/main/java/nextstep/jwp/infrastructure/http/request/Cookie.java
> +    }
이건 추가적인 의견이라 현재는 반영 안하셔도 됩니다! 지금 상태에는 현재의 구현이 더 좋은 효율을 가진다고 생각해요 😄 

나중에는 쿠키 자체에 유효시간 HttpOnly 등의 추가 설정을 하려면 Cookie 라는 별개의 객체가 필요하다고 생각해요!
Cookie 라는 객체가 String key, String value 를 들고있고
Cookies 라는 일급 컬렉션으로 가지고 있는 형태가 될 수 있겠네요 😃

2021-09-02 18:32 UTC, merged