[HTTP 서버 구현하기 - 2, 3단계] 아마찌(신지혜) 미션 제출합니다.
woowacourse/jwp-dashboard-http pull request #69
Opened 2021-09-01 13:21 UTC by NewWisdom

안녕하세요 포모 ~ 
마지막으로 남겨주신 피드백 반영을 포함해 2, 3단계 진행 후 PR 제출합니다!!
2단계 리팩토링은 어느정도 진행된 상태에서 조금 더 리팩토링을 해보았습니다 ㅎㅎ 
쿠키와 세션에 대해 공부하면서 재밌게 구현할 수 있었습니다!!!
부족한 부분 있으면 편하게 말씀해주세요 !!! 
리뷰 너무너무 감사합니다 🙇‍♂️
잘부탁드려용 삶성성 포모 화이팅 🔥

2021-09-02 16:28 UTC, bosl95 reviewed
아마지! 포모입니당!!!! 🔥🔥
스케쥴이 빡빡한 걸로 알고 있는데 그와중에 미션하시느라 수고 많으셨다고 우선적으로 말씀해드리고 싶네요 👏👏👏👏👏
일단 전반적으로 코드가 깔끔해서 읽기가 너무 편했어요~! 많이 배워갑니당 ㅎㅎ
이번 2,3단계는 시간을 넉넉하게 잡은 대신 저번보다 더 꼼꼼하게 보려고 해선지 구구절절 뭐가 많네요 😅 아마찌에게 도움이 많이 되었으면 좋겠는데 말이죵..  😳
아마찌 코드를 보면서 드는 궁금한 점 몇자 적어보았구요, 소소한 피드백 드렸으니 보시고 괜찮으시면 반영해주시거나 쓰루 하셔도 좋아요~!!!
"악바리로 폭풍 성장하는 개발자" 아.마.찌 💪 미션 마지막까지 화이팅팅티잉🔥🔥

2021-09-02 16:28 UTC, bosl95 commented on app/src/test/java/nextstep/jwp/FrontControllerTest.java
> +        assertThat(socket.output()).contains(expectedContains);
깃허브상에는 표시가 없는데, import 정리가 필요해보이네요!

2021-09-02 16:28 UTC, bosl95 commented on app/src/test/java/nextstep/jwp/controller/DefaultControllerTest.java
>                  new String(Files.readAllBytes(new File(resource.getFile()).toPath()));
`getFile()`을 requiredNonNull로 지정하거나 assert를 적용해달라구 뜨네유~! (중복!!!)

2021-09-02 16:28 UTC, bosl95 commented on app/src/test/java/nextstep/jwp/controller/LoginControllerTest.java
>                  requestBody);
여기서 아마찌가 의도하는 게 세션id가 있는 상태로 로그인을 시도하는 게 맞나용?? 
지금 저희 미션상에서는 세션 id가 있으면 로그인 페이지 접근이 안되는 걸로 알고 있는데 혹시 제가 잘못 이해한걸까요????

2021-09-02 16:28 UTC, bosl95 commented on app/src/test/java/nextstep/jwp/http/request/HttpRequestTest.java
>          );
`assertAll()`!!!! 좋네요!!! 🚀🚀

2021-09-02 16:28 UTC, bosl95 commented on app/src/test/java/nextstep/jwp/http/session/HttpSessionTest.java
> +    @Test
오호!! 무효화까지! 
꼼꼼한 테스트에 깔끔한 코드 완벽!

2021-09-02 16:31 UTC, bosl95 commented on app/src/main/java/nextstep/jwp/controller/LoginController.java
> +        assert (loginController != null) : "생성된 객체가 없습니다.";
아 그리고 하나 더 궁금한점!
assert 키워드를 많이 사용하셨는데, 이게 아마 소나린트에서 제공하는 부분이었을 거 같아요! requiredNonNull도 있는데, assert 키워드를 사용하신 이유가 있나요? 저한테는 저 키워드가 익숙치가 않아서요! 어떤 의도로 사용하신걸까요!?

2021-09-02 16:35 UTC, bosl95 requested changes
엇 request로 요청 보내는 거 깜박해따

2021-09-03 00:05 UTC, NewWisdom commented on app/src/main/java/nextstep/jwp/RequestMapping.java
> +    private static final Map<String, Controller> controllerMap = new HashMap<>();
오옷 맞아요!!! 꼼꼼한 피드백 감삼다 ㅎㅎ

2021-09-03 00:29 UTC, NewWisdom commented on app/src/main/java/nextstep/jwp/RequestMapping.java
> +    }
오호 !!! 그러네요!
말씀대로 `RegisterController.createInstance(UserService.getUserService())` 하나로 써도 로직에는 문제가 없어요!! 
말씀을 듣고 생각해보았는데 현재 로직에서는 LoginController.getInstance()를 한 번만 호출하지만, 만약 이곳 저곳에서 getInstance를 호출해야한다면 매번 service 객체를 같이 넣어줘야하는 번거로움이 생긴다.? 이겠네요!!
음 그런데 사실 여기서는 LoginController 생성과 이를 호출하는 로직이 딱 한번뿐이니 메서드를 하나로 줄이는게 나을까유~??
사실 [이 글](https://licktwice.tistory.com/62)을 참고했었습니다 ㅎㅎ

2021-09-03 00:36 UTC, NewWisdom commented on app/src/main/java/nextstep/jwp/db/InMemoryUserRepository.java
>          database.put(user.getAccount(), user);
아앗 이 부분은 예외 처리를 해줬는데 기존에 존재하는 회원이어서 가입이 안되면 어떻게 처리할까 하다가
다시 register.html 로 리다이렉트를 시켜놔서 그렇슴다 ㅎㅎㅎ
가입 자체는 막아놨는데 사용자한테는 어떻게 알려주어야할지 고민이네유 흠

2021-09-03 00:37 UTC, NewWisdom commented on app/src/main/java/nextstep/jwp/http/request/RequestHeaders.java
>              return 0;
넵넵 !!! ㅎㅎㅎ
[이 문서](https://www.ibm.com/docs/ko/ibm-mq/9.0?topic=ssfksj-9-0-0-com-ibm-mq-ref-dev-doc-q110660--htm)를 보고 없는 경우는 0으로 처리해주었어용!!

2021-09-03 00:41 UTC, NewWisdom commented on app/src/main/java/nextstep/jwp/db/InMemoryUserRepository.java
>          database.put(user.getAccount(), user);
아앗 존재하는 account일 경우 회원 가입은 안될거에용!!
이 부분은 예외 처리를 해줬는데 기존에 존재하는 회원이어서 가입이 안되면 어떻게 처리할까 하다가
다시 register.html 로 리다이렉트를 시켜놔서 그렇슴다 ㅎㅎㅎ
가입 자체는 막아놨는데 사용자한테는 어떻게 알려주어야할지 고민이네유 흠
포모가 발견한 부분이 이게 맞겠쥬 ?? 👀

2021-09-03 04:37 UTC, NewWisdom commented on app/src/main/java/nextstep/jwp/controller/LoginController.java
> +            response.responseRedirect(HTTP + request.getHeader("Host") + "/401.html");
그러네요!! 
커스텀 예외를 만드는게 더 명확할 것 같습니다 ! 반영반영~

2021-09-03 04:49 UTC, NewWisdom commented on app/src/main/java/nextstep/jwp/db/InMemoryUserRepository.java
오오 좋네요!!! 반영반영 좋은 키워드 감삼다

2021-09-03 04:51 UTC, NewWisdom commented on app/src/main/java/nextstep/jwp/http/request/RequestBody.java
>              }
오옷 감삼다 ㅎㅎㅎ 
음 개인적으로 여기서 인덱스를 상수로 빼는 것보다 냅두는게 가독성이 좋다고 느껴져서 유지해봐두 될까용 ㅎㅎㅎㅎ

2021-09-03 04:54 UTC, NewWisdom commented on app/src/main/java/nextstep/jwp/http/request/RequestLine.java
>              } else {
오옷 생성자 쪽이고 밑에 protocol 초기화도 있어서 일단은 요렇게 가볼게여!! ㄹㅎㅎ

2021-09-03 04:54 UTC, NewWisdom commented on app/src/main/java/nextstep/jwp/http/response/ResponseHeaders.java
>      private final Map<String, String> headers = new LinkedHashMap<>();
테스트 코드를 짜다보니 응답 헤더 순서가 달라서 틀린 경우도 있더라구요!!
헤더 순서를 유지하기 위해 사용했슴다!! ㅎㅎ

2021-09-03 04:55 UTC, NewWisdom commented on app/src/main/java/nextstep/jwp/http/session/HttpCookie.java
> +    }
여기도 순서를 보장하기 위해 썼는데 생각해보니 쿠키는 보장할  필요가 없네용 ㅎㅎㅎㅎㅎ

2021-09-03 04:56 UTC, NewWisdom commented on app/src/test/java/nextstep/jwp/FrontControllerTest.java
> +        assertThat(socket.output()).contains(expectedContains);
오오 예리 감사합니다아아

2021-09-03 05:01 UTC, NewWisdom commented on app/src/test/java/nextstep/jwp/controller/LoginControllerTest.java
>                  requestBody);
아앗 테스트 짜는데 쿠키가 없을 시 로그인 페이지로 가는걸 의도하는 테스트인데
응답에 set cookie 부분이 랜덤으로 날아와서 응답을 작성하는게 안되더라구요 ㅎㅎㅎ
저 세션 아이디는 유효하지 않은 값으로 바꿔야겠네요!!

2021-09-03 05:03 UTC, NewWisdom commented on app/src/main/java/nextstep/jwp/controller/LoginController.java
> +        assert (loginController != null) : "생성된 객체가 없습니다.";
https://stackoverflow.com/questions/60712593/should-you-assert-not-null-with-the-assert-statement-in-production-code
인텔리가 제안해주는대로 그냥 썼었는데 포모말 듣고 찾아보니까 이렇다고 하네요!!
올 덕분에 하나 알아갑니다~!
변경변경! ㅎㅎ

2021-09-03 08:36 UTC, NewWisdom commented on app/src/test/java/nextstep/jwp/controller/LoginControllerTest.java
>                  requestBody);
아아 응답에 set cookie 때문에 무조건적으로 저 cookie를 설정해줬는데
의미를 좀 더 분명하게 해야겠네요!!!
감사함다!! ㅎㅎ

2021-09-03 08:46 UTC, NewWisdom commented
안녕하세요 포모~!!! 
주신 리뷰들 참고해 수정해보았습니다 :)
덕분에 새로운 키워드들도 알아갈 수 있었습니다 짱짱짱 🙇‍♂️
시간나실 때 천천히 리뷰 해주십쇼!!!!
리뷰에 시간내주셔서 정말 무한 감사 👏👏👏
화이팅임다~

2021-09-03 12:16 UTC, bosl95 commented on app/src/main/java/nextstep/jwp/db/InMemoryUserRepository.java
>          database.put(user.getAccount(), user);
얼레 제가 테스트를 다른 코드로 진행했었나봐요 🤣 지금은 잘 되네용~

2021-09-03 12:33 UTC, bosl95 commented
빠르게 피드백 적용해주셨네요!
고생 많으셨슴다 아마찌!!!!!! 👏👏👏👏
다음 미션도 화이팅입니당 🚀🚀

2021-09-03 12:33 UTC, merged