[HTTP 서버 구현하기 - 1단계] 검프(김태정) 미션 제출합니다.
woowacourse/jwp-dashboard-http pull request #7
Opened 2021-08-27 16:36 UTC by Livenow14

안녕하세요 **에드**! 😁
최대한 테스트 코드를 먼저 작성하고, 기능구현을 했어요. 
또한, 이후 리팩토링 수업, 단계가 있어서, 1단계 요구사항 까지만 완료했어요.

첫 크루 피드백이라 떨리네요..! 잘부탁드립니다

2021-08-28 04:13 UTC, sjpark-dev requested changes
안녕하세요 검프! 🙂
리뷰어 에드입니다!

코드의 가독성이 너무 좋았어요. 👍👍👍
좋은 변수명과 실용적인 메소드 분리를 정말 잘 활용하셨어요.

지금 RequestHandler에 집중된 로직을 검프가 어떻게 리팩토링할지 너무 기대되네요! 😆

몇가지 피드백을 남겼지만 꼭 바꿨으면 하는 부분은 없어서
생각만 해보시고 피드백 반영 여부는 검프의 판단에 맡기겠습니다. 👍

2021-08-28 04:13 UTC, sjpark-dev commented on app/src/test/java/nextstep/jwp/RequestHandlerTest.java
> +        return Stream.of(
사용하지 않는 메소드네요!

2021-08-28 04:13 UTC, sjpark-dev commented on app/src/test/java/nextstep/jwp/RequestHandlerTest.java
> +        return String.join("\r\n",
이것도 사용하고 있지 않네요!

2021-08-28 04:30 UTC, Livenow14 commented on app/src/main/java/nextstep/jwp/RequestHandler.java
> +    private static final String STATIC_PATH = "static";
직접 작성하지 않은 코드에 대해 신경을 쓰지못했네요..! 좋은 피드백 감사합니다 ㅎㅎ

2021-08-28 04:31 UTC, Livenow14 commented on app/src/main/java/nextstep/jwp/db/InMemoryUserRepository.java
>  }
로깅을 적절히 활용하면 서비스 동작 파악이 쉬워지는거 같아요!!

2021-08-28 04:43 UTC, Livenow14 commented on app/src/main/java/nextstep/jwp/db/InMemoryUserRepository.java
수정 완료했습니다! 
3f58a82

2021-08-28 04:44 UTC, Livenow14 commented on app/src/test/java/nextstep/jwp/RequestHandlerTest.java
> +        return String.join("\r\n",
수정 완료했습니다!
3f58a823f58a82

2021-08-28 04:45 UTC, Livenow14 commented on app/src/test/java/nextstep/jwp/RequestHandlerTest.java
> +        return Stream.of(
Post_요청에_대해_응답한다의 MethodSource로 활용되고 있어요. (테스트 명과 메소드 명이 일치하면 value옵션이 default로 들어가요 ) 
이부분은 수정하지 않을게요 😊

2021-08-28 05:14 UTC, Livenow14 commented on app/src/main/java/nextstep/jwp/RequestHandler.java
확인해보니 css 반환로직이 잘못되어있었네요..! 좋은 피드백 고마워요 ㅎㅎ 

3f58a82

2021-08-28 05:16 UTC, Livenow14 commented on app/src/main/java/nextstep/jwp/RequestHandler.java
> +                        writeOutputStream(outputStream, http302Response("/index.html"));
저도 고민을 많이 한 부분인데요 😁
현재는 쓰이지 않지만, Login시 해당 유저의 정보를 반환하는게 조금 더 자연스럽다 생각했어요..! (향후 로그인 처리시 쓰일거라 예상했어요)
이부분은 수정하지 않을꼐요! ㅎㅎ

2021-08-28 05:17 UTC, Livenow14 commented on app/src/main/java/nextstep/jwp/RequestHandler.java
> +            final String[] header = line.split(HEADER_DELIMITER);
좋은 피드백 감사해요 ㅎㅎ line.isEmpty로 처리했습니다..!

2021-08-28 05:29 UTC, Livenow14 commented on app/src/main/java/nextstep/jwp/RequestHandler.java
> +            targetUri = targetUri.concat(".html");
.js 파일 등을 처리하려 했는데, 로직을 보니 애매하게 작성한거 같더라고요..! 로직 수정 후 어색한 부분을 제거했어요..! 
refactor: 정정 파일 반환 로직 수정

2021-08-28 06:08 UTC, Livenow14 commented on app/src/main/java/nextstep/jwp/RequestHandler.java
> +        InMemoryUserRepository.save(user);
아직 데이터베이스를 추가하지 않은 상태로 아이디 값을 표시할 것이 없다고 판단돼요. 
Static 변수를 말고 인스턴스 변수를 사용할 수 잇찌만,
지금 요구사항에서는 메모리 DB를 사용하기에 생명주기를 시스템과 같이 하는 Static 변수가 더 어울린다 생각해요! 좋은 피드백 감사합니다.

2021-08-28 06:22 UTC, Livenow14 commented
안녕하세요 에드!! 두번째 PR이네요 ㅎㅎㅎ 
피드백에서 많은 것을 배울 수 있었어요!(전반적으로 수정 하니 가독성이 좀더 좋아졌어요..! )
최대한 1단계 기능 구현사항 내에서 리팩터링 할 수 있는지만 고려해서인지 아직 부족한 부분이 많아요 😂
좋은 피드백 고마워요!! 이번 피드백도 잘 부탁드려요 🙇🏻‍♂️

2021-08-28 08:05 UTC, sjpark-dev requested changes
검프! 피드백 반영하시느라 수고하셨습니다.

검증 로직이 한층 강화되었네요. 👍

리팩토링하면서 수정한 몇가지 코드에 대해서 피드백을 남겼습니다.

2021-08-28 08:54 UTC, Livenow14 commented on app/src/test/java/nextstep/jwp/RequestHandlerTest.java
> +        //given
흠.. 테스트가 실패하면 SonarQube가 동작하지 않아서 build가 안될텐데요..ㅠㅠ 
현재 SonarQube build가 되어있는 상황과 제 로컬환경에서 정상 작동됨을 확인 했기에, 이부분은 넘어갈게요

2021-08-28 09:05 UTC, Livenow14 commented on app/src/main/java/nextstep/jwp/model/User.java
>          this.id = id;
아직 빌드업 단계라 
현재는 public으로 두고, 이후에 사용되지 않음이 확인되면, private으로 변경할 예정이었어요.

혹시 제가 놓치고 있는 "기본생성자를 private으로 변경해야 하는 이유"가 있는지 궁금해요!! 🙇🏻‍♂️

2021-08-28 09:36 UTC, Livenow14 commented on app/src/main/java/nextstep/jwp/RequestHandler.java
> +
javascript를 반환하게 수정했어요 :)

2021-08-28 09:38 UTC, sjpark-dev commented on app/src/test/java/nextstep/jwp/RequestHandlerTest.java
> +        //given
OS간 개행 문자 차이 때문에 테스트가 실패했었네요. 😅

저는 윈도우를 써서 개행문자가 \r\n이 적용되고, 
소나 서버와 검프가 로컬로 돌릴 때는 \n가 적용되었나보네요.

저도 IDE 세팅을 \n으로 바꾸니 테스트가 모두 통과합니다. 👍
혼란을 드려 죄송합니다. 🙇🏻‍♂️

2021-08-28 09:47 UTC, sjpark-dev commented on app/src/main/java/nextstep/jwp/model/User.java
>          this.id = id;
특별한 이유는 없었습니다. 😆
클래스 내부에서만 사용되어야 하는 생성자가 외부에서 사용되면, 
의도하지 않은 결과를 초래할 수 있어서,
닫으면 좋을 것 같다는 피드백을 드렸습니다. 😆

검프가 말씀하신 것 처럼 아직 빌드업 단계이니 그대로 두는게 좋을 것 같네요. 👍

2021-08-29 04:46 UTC, Livenow14 commented
안녕하세요 에드!! 이번 리팩토링에서는 중복코드를 최대한 제거했어요 :) 
다음단계의 추상화 단계가 계속 눈에 밟혔지만.. 최대한 이번 단계에서 할수있는 최적화에 집중했어요(빨리 다 뜯어 고치고 싶네요..ㅎㅎ)!! 

주로 한 부분은, 404 페이지의 이미지 요청, 각 요청별 reponse Header 변경, 중복코드 제거입니다.

이번에도  잘부탁드려요🙇🏻‍♂️

2021-08-29 06:20 UTC, sjpark-dev approved these changes
안녕하세요 검프! 🙂

enum을 활용해서 중복 코드를 많이 제거하셨네요.
코드가 훨씬 간결해졌습니다.

이번 PR는 이만 머지하겠습니다.
수고하셨습니다. 👍

2021-08-29 06:20 UTC, sjpark-dev commented on app/src/test/java/nextstep/jwp/RequestHandlerTest.java
> +    private String toHttpCssResponse() {
expectResponseBody를 받아서 동적으로 값을 생성하는 것도 괜찮을 것 같네요. 😉

2021-08-29 07:50 UTC, merged

2021-08-29 13:39 UTC, Livenow14 commented on app/src/test/java/nextstep/jwp/RequestHandlerTest.java
> +    private String toHttpCssResponse() {
이부분은 다음 단계를 진행하며 반영하도록할게요!! 감사합니다😊